CDCgov/NEDSS-Modernization

apps/modernization-api/src/main/java/gov/cdc/nbs/patient/search/PatientSearchCriteriaQueryResolver.java

Bug fixed
* [CNFT1-2584](https://cdc-nbs.atlassian.net/browse/CNFT1-2584)
[CNFT1-2584]: https://cdc-nbs.atlassian.net/browse/CNFT1-2584?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT1 2584 matching address

---

testing/regression/cypress/step_definitions/hl7/generate-elr.steps.js
testing/regression/cypress/step_definitions/hl7/generate-mark-reviewed.steps.js
testing/regression/cypress/step_definitions/question-library/createNewQuestion.steps.js
testing/regression/cypress/step_definitions/question-library/pagination.steps.js
testing/regression/cypress/step_definitions/question-library/sort.steps.js

Changed to exclude from bundle.

Regressions features path imports  remove @ syntax for bundle reasons

---

apps/modernization-api/src/test/java/gov/cdc/nbs/event/search/investigation/association/AssociatedWithTupleMapperTest.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/contact/ContactNamedByPatientResolverTest.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/morbidity/PatientMorbidityResolverTest.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/morbidity/PatientMorbidityRowAccumulatorTest.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/address/PatientAddressResolverTest.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/administrative/PatientAdministrativeResolverTest.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/birth/PatientProfileBirthSteps.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/ethnicity/PatientEthnicityTupleMapperTest.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/identification/PatientIdentificationResolverTest.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/investigation/PatientInvestigationResolverTest.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/names/PatientNameResolverTest.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/phone/PatientPhoneResolverTest.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/race/PatientRaceAccumulatorTest.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/race/PatientRaceResolverTest.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/race/PatientRaceTupleMapperTest.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/vaccination/PatientVaccinationResolverTest.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/treatment/PatientTreatmentByPatientResolverTest.java
apps/modernization-api/src/test/java/gov/cdc/nbs/support/PermissionMother.java
libs/database-entities/src/test/java/gov/cdc/nbs/entity/odse/PersonTest.java

Fixes sonar maintainability warnings found [here](https://sonarcloud.io/project/issues?impactSoftwareQualities=MAINTAINABILITY&resolved=false&id=CDCgov_NEDSS-Modernization)

Fix code maintainability warnings

---

apps/modernization-ui/src/apps/search/patient/PatientCriteria/Id.spec.tsx
apps/modernization-ui/src/apps/search/patient/PatientCriteria/Id.tsx
apps/modernization-ui/src/apps/search/patient/PatientCriteria/PatientCriteria.tsx
apps/modernization-ui/src/apps/search/patient/PatientCriteria/id.module.scss

Adding the Id form field to Patient search form.
* [CNFT1-2434](https://cdc-nbs.atlassian.net/browse/CNFT1-2434)
[CNFT1-2434]: https://cdc-nbs.atlassian.net/browse/CNFT1-2434?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT1-2434 Patient search: Id

---

apps/modernization-ui/src/apps/search/layout/result/SearchResults.tsx
apps/modernization-ui/src/design-system/Pagination/Pagination.spec.tsx
apps/modernization-ui/src/design-system/Pagination/Pagination.tsx
apps/modernization-ui/src/design-system/Pagination/pagination.module.scss

New Pagination component!
[CNFT1-2443](https://cdc-nbs.atlassian.net/browse/CNFT1-2443)
[CNFT1-2443]: https://cdc-nbs.atlassian.net/browse/CNFT1-2443?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT1-2443 Pagination feature

---

apps/modernization-api/src/main/java/gov/cdc/nbs/event/search/investigation/InvestigationSearchResultResolver.java
apps/modernization-api/src/main/java/gov/cdc/nbs/event/search/labreport/LabReportSearchResultResolver.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/search/PatientSearchResultResolver.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/search/SearchGraphQLPageableMapper.java
apps/modernization-api/src/main/resources/application.yml
apps/modernization-api/src/test/resources/application-test.yml

Increases the max search results to allow at most 100.
* [CNFT1-2726](https://cdc-nbs.atlassian.net/browse/CNFT1-2726)
[CNFT1-2726]: https://cdc-nbs.atlassian.net/browse/CNFT1-2726?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-2726] increases max results for search APIs

---

apps/modernization-ui/src/apps/page-builder/page/management/preview/PreviewPage.tsx
apps/modernization-ui/src/components/button/nav/NavLinkButton.tsx
testing/regression/cypress/e2e/features/advanced-condition-search/addCondition.feature
testing/regression/cypress/e2e/features/advanced-condition-search/createNewCondition.feature
testing/regression/cypress/e2e/features/advanced-condition-search/pagination.feature
testing/regression/cypress/e2e/features/advanced-condition-search/rowSelection.feature
testing/regression/cypress/e2e/features/advanced-condition-search/searchAndFilter.feature
testing/regression/cypress/e2e/features/advanced-condition-search/sorting.feature
testing/regression/cypress/e2e/features/business-rules/businessRules.feature
testing/regression/cypress/e2e/pages/business-rules/businessRules.page.js
testing/regression/cypress/step_definitions/business-rules/businessRules.steps.js

Added automated end to end tests for below manual tests
[CNFT2-1856](https://cdc-nbs.atlassian.net/browse/CNFT2-1856)
[CNFT2-1860](https://cdc-nbs.atlassian.net/browse/CNFT2-1860)
[CNFT2-1856]: https://cdc-nbs.atlassian.net/browse/CNFT2-1856?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CNFT2-1860]: https://cdc-nbs.atlassian.net/browse/CNFT2-1860?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNT-43] E2E Business Rules Library

---

libs/database-entities/src/main/java/gov/cdc/nbs/entity/odse/Person.java

Ensures that the Person `last_chg_time` is updated when race is changed
* [CNFT1-2519](https://cdc-nbs.atlassian.net/browse/CNFT1-2519)
[CNFT1-2519]: https://cdc-nbs.atlassian.net/browse/CNFT1-2519?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-2519] Ensures that person last change time is updated for race

---

apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/RuleSearchBar.tsx
testing/regression/cypress/e2e/features/business-rules/businessRules.feature
testing/regression/cypress/e2e/pages/business-rules/businessRules.page.js
testing/regression/cypress/step_definitions/business-rules/businessRules.steps.js

Added automated end to end tests for below manual tests.
[CNFT2-1910](https://cdc-nbs.atlassian.net/browse/CNFT2-1910)
[CNFT2-2017](https://cdc-nbs.atlassian.net/browse/CNFT2-2017)
[CNFT2-1910]: https://cdc-nbs.atlassian.net/browse/CNFT2-1910?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CNFT2-2017]: https://cdc-nbs.atlassian.net/browse/CNFT2-2017?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNT-43] - E2E - Business Rules Library 

---

apps/modernization-api/src/test/java/gov/cdc/nbs/patient/contact/PatientNamedByContactResolverTest.java

Fixes a code maintainability warning issued by sonar cloud.

Maintainability pt 2

---

apps/modernization-ui/src/apps/search/patient/PatientCriteria/PatientCriteria.tsx
apps/modernization-ui/src/apps/search/patient/PatientCriteria/RaceEthnicity.spec.tsx
apps/modernization-ui/src/apps/search/patient/PatientCriteria/RaceEthnicity.tsx
apps/modernization-ui/src/apps/search/patient/PatientCriteria/race-ethnicity.module.scss

Adding the Race/Ethnicity fields to Patient search.
* [CNFT1-2435](https://cdc-nbs.atlassian.net/browse/CNFT1-2435)
[CNFT1-2435]: https://cdc-nbs.atlassian.net/browse/CNFT1-2435?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT1-2435 Patient search: Race/Ethnicity

---

apps/modernization-ui/src/apps/search/patient/PatientCriteria/Id.spec.tsx
apps/modernization-ui/src/apps/search/patient/PatientCriteria/Id.tsx

Patient search Id field needs to display when Identification Type is selected.
* [CNFT1-2434](https://cdc-nbs.atlassian.net/browse/CNFT1-2434)
[CNFT1-2434]: https://cdc-nbs.atlassian.net/browse/CNFT1-2434?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT1-2434 Patient search: Id field

---

apps/modernization-ui/src/apps/search/patient/transformer.spec.ts
apps/modernization-ui/src/apps/search/patient/transformer.ts

Adding DOB into the transformer function for patient search passing DOB in the response
* [CNFT1-2740](https://cdc-nbs.atlassian.net/browse/CNFT1-2740)
[CNFT1-2740]: https://cdc-nbs.atlassian.net/browse/CNFT1-2740?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

adding DOB in the transformer now getting passing in response data

---

testing/regression/cypress/e2e/features/address.feature
testing/regression/cypress/e2e/features/contact.feature
testing/regression/cypress/e2e/features/lab-report-criteria.feature
testing/regression/cypress/e2e/pages/search.page.js
testing/regression/cypress/e2e/pages/searchEvent.page.js
testing/regression/cypress/step_definitions/advance.search.steps.js
testing/regression/cypress/step_definitions/search.steps.js
testing/regression/cypress/step_definitions/searchEvent.steps.js

New format for new Table UI design. Fix failing E2E tests format for UI improvement. 

New format for new Table UI design

---

apps/modernization-ui/src/apps/search/patient/PatientSearch.tsx

Enabling Add new patient / Add new lab report buttons in PatientSearch
* [CNFT1-2799](https://cdc-nbs.atlassian.net/browse/CNFT1-2799)
[CNFT1-2799]: https://cdc-nbs.atlassian.net/browse/CNFT1-2799?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT1-2799 Add new patient/lab report buttons

---

apps/modernization-ui/src/apps/search/NoInputBanner.tsx
apps/modernization-ui/src/apps/search/NoResultsBanner.tsx
apps/modernization-ui/src/apps/search/investigation/InvestigationSearch.tsx
apps/modernization-ui/src/apps/search/laboratory-report/LaboratoryReportSearch.tsx
apps/modernization-ui/src/apps/search/layout/SearchLayout.spec.tsx
apps/modernization-ui/src/apps/search/patient/PatientSearch.tsx

Bug fixes for the no results, and no input given messages in all searches
* [CNFT1-2795](https://cdc-nbs.atlassian.net/browse/CNFT1-2795)
[CNFT1-2795]: https://cdc-nbs.atlassian.net/browse/CNFT1-2795?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

banner fixes

---

apps/modernization-ui/src/apps/search/NoInputBanner.tsx
apps/modernization-ui/src/apps/search/NoResultsBanner.tsx
apps/modernization-ui/src/apps/search/investigation/InvestigationSearch.tsx
apps/modernization-ui/src/apps/search/laboratory-report/LaboratoryReportSearch.tsx
apps/modernization-ui/src/apps/search/layout/SearchLayout.spec.tsx
apps/modernization-ui/src/apps/search/patient/PatientSearch.tsx
apps/modernization-ui/src/apps/search/useSearch.ts

Bug fix for no results found banners to update the number of results in the header

Bug fix no results banner

---

apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/Add/AddBusinessRules.tsx
apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/BusinessRulesLibraryTable.tsx
apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/Edit/EditBusinessRules.tsx
apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/Form/BusinessRulesForm.tsx
apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/SourceQuestion/SourceQuestion.tsx
apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/TargetQuestion/TargetQuestion.tsx
apps/modernization-ui/src/confirmation/ConfirmationModal.tsx
testing/regression/cypress/e2e/features/business-rules/businessRules.feature
testing/regression/cypress/e2e/pages/business-rules/businessRules.page.js
testing/regression/cypress/step_definitions/business-rules/businessRules.steps.js

Added automated e2e for business rules test case number [CNFT2-1995](https://cdc-nbs.atlassian.net/browse/CNFT2-1995)
[CNFT2-1995]: https://cdc-nbs.atlassian.net/browse/CNFT2-1995?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNT-43 Business Rules Library CNFT2-1995

---

testing/regression/cypress/e2e/features/business-rules/businessRules.feature
testing/regression/cypress/step_definitions/business-rules/businessRules.steps.js

Added automated e2e test case for business rules test case number [CNFT2-2007](https://cdc-nbs.atlassian.net/browse/CNFT2-2007)
[CNFT2-2007]: https://cdc-nbs.atlassian.net/browse/CNFT2-2007?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNT-43] - Business Rules Library CNFT2-2007

---

testing/regression/cypress/e2e/features/business-rules/businessRules.feature
testing/regression/cypress/step_definitions/business-rules/businessRules.steps.js

Added automated e2e test case for business rules test case number [CNFT2-2008](https://cdc-nbs.atlassian.net/browse/CNFT2-2008)
[CNFT2-2008]: https://cdc-nbs.atlassian.net/browse/CNFT2-2008?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNT-43] - Business Rules Library CNFT2-2008

---

apps/modernization-ui/src/apps/search/useSearchResultDisplay.tsx
apps/modernization-ui/src/design-system/table/DataTable.tsx

adding table as default view in toggle button and no data component in table view for when there is no data
* [CNFT1-2789](https://cdc-nbs.atlassian.net/browse/CNFT1-2789)
* [CNFT1-2790](https://cdc-nbs.atlassian.net/browse/CNFT1-2790)
[CNFT1-2789]: https://cdc-nbs.atlassian.net/browse/CNFT1-2789?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CNFT1-2790]: https://cdc-nbs.atlassian.net/browse/CNFT1-2790?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

adding table as default and no data component in table

---

apps/modernization-ui/src/apps/search/investigation/investigationTermsResolver.spec.ts
apps/modernization-ui/src/apps/search/investigation/investigationTermsResolver.ts
apps/modernization-ui/src/apps/search/laboratory-report/laboratoryReportTermsResolver.spec.ts
apps/modernization-ui/src/apps/search/laboratory-report/laboratoryReportTermsResolver.ts
apps/modernization-ui/src/apps/search/patient/patientTermsResolver.spec.ts
apps/modernization-ui/src/apps/search/patient/patientTermsResovler.ts

Patient Search - Basic Information - Chips are not displaying the complete field name
Lab Report Search - Basic Information - Chips are not displaying the complete field name
Investigation Search - Basic Information - Chips are not displaying the complete field name
* [CNFT1-2805](https://cdc-nbs.atlassian.net/browse/CNFT1-2805)
[CNFT1-2805]: https://cdc-nbs.atlassian.net/browse/CNFT1-2805?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Chips name fixes

---

testing/regression/cypress/e2e/features/business-rules/businessRules.feature
testing/regression/cypress/step_definitions/business-rules/businessRules.steps.js

Added automated e2e test case for business rules test case number [CNFT2-2013](https://cdc-nbs.atlassian.net/browse/CNFT2-2013)
[CNFT2-2013]: https://cdc-nbs.atlassian.net/browse/CNFT2-2013?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNT-43] - Business Rules Library CNFT2-2013

---

testing/regression/cypress/e2e/features/business-rules/businessRules.feature
testing/regression/cypress/step_definitions/business-rules/businessRules.steps.js

Added automated e2e test case for business rules test case number [CNFT2-2030](https://cdc-nbs.atlassian.net/browse/CNFT2-2030)
[CNFT2-2030]: https://cdc-nbs.atlassian.net/browse/CNFT2-2030?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNT-43] - Business Rules Library CNFT2-2030

---

apps/modernization-api/src/main/java/gov/cdc/nbs/patient/search/PatientSearchCriteriaQueryResolver.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/search/PatientSearchCriteriaSortResolver.java
apps/modernization-api/src/main/resources/graphql/shared.graphqls
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/PatientMother.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/PatientSteps.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/search/PatientSearchSortingSteps.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/search/PatientSearchVerificationSteps.java
apps/modernization-api/src/test/java/gov/cdc/nbs/search/SortCriteriaSteps.java
apps/modernization-api/src/test/resources/features/patient/search/PatientSearch.sorting.feature
apps/modernization-ui/src/generated/graphql/schema.ts
apps/modernization-ui/src/generated/schema.graphqls

Work in progress...
* [CNFT1-2555](https://cdc-nbs.atlassian.net/browse/CNFT1-2555)
[CNFT1-2555]: https://cdc-nbs.atlassian.net/browse/CNFT1-2555?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT1-2555 API: Patient sorting for every field

---

testing/regression/cypress/e2e/features/preview-page/previewPage.feature
testing/regression/cypress/e2e/pages/preview-page/previewPage.page.js
testing/regression/cypress/step_definitions/preview-page/previewPage.steps.js

Added end to end test case for preview and publish [CNFT2-1980](https://cdc-nbs.atlassian.net/browse/CNFT2-1980)
[CNFT2-1980]: https://cdc-nbs.atlassian.net/browse/CNFT2-1980?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNT-45] - E2E - Preview and publish 

---

testing/regression/cypress/e2e/features/preview-page/previewPage.feature
testing/regression/cypress/e2e/pages/preview-page/previewPage.page.js
testing/regression/cypress/step_definitions/preview-page/previewPage.steps.js

Added end to end test case for preview and publish with published status [CNFT2-1971](https://cdc-nbs.atlassian.net/browse/CNFT2-1971)
[CNFT2-1971]: https://cdc-nbs.atlassian.net/browse/CNFT2-1971?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNT-45] -E2E - Preview and publish with published status

---

testing/regression/cypress/e2e/features/preview-page/previewPage.feature
testing/regression/cypress/step_definitions/preview-page/previewPage.steps.js

Added end to end test case for preview and publish page has published with draft status [CNFT2-1972](https://cdc-nbs.atlassian.net/browse/CNFT2-1972)
[CNFT2-1972]: https://cdc-nbs.atlassian.net/browse/CNFT2-1972?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNT-45] - Preview and publish page - published with draft status 

---

apps/modernization-ui/src/apps/search/layout/navigation/SearchNavigation.tsx
apps/modernization-ui/src/apps/search/layout/result/header/terms/SearchTerms.tsx
apps/modernization-ui/src/apps/search/layout/result/header/terms/search-terms.module.scss
apps/modernization-ui/src/apps/search/layout/result/list/search-result-list.module.scss
apps/modernization-ui/src/apps/search/layout/result/search-results.module.scss

Couple bugs focused on the list view, and the chips in search
* [CNFT1-2827](https://cdc-nbs.atlassian.net/browse/CNFT1-2827)
* [CNFT1-2825](https://cdc-nbs.atlassian.net/browse/CNFT1-2825)
[CNFT1-2827]: https://cdc-nbs.atlassian.net/browse/CNFT1-2827?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CNFT1-2825]: https://cdc-nbs.atlassian.net/browse/CNFT1-2825?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

couple bugs fixed

---

cdc-sandbox/keycloak/imports/nbs-users.json
cdc-sandbox/keycloak/theme/nbs/login/banner/banner.html
cdc-sandbox/keycloak/theme/nbs/login/resources/css/styles.css

Removes the page title copied from the USWDS Banner Example HTML and makes the NBS login theme the default in the local container.

[FIX] Fixes login theme title and sets default login theme

---

testing/regression/cypress/e2e/features/preview-page/previewPage.feature
testing/regression/cypress/step_definitions/preview-page/previewPage.steps.js

Added end to end test case for preview and publish page has Page Info Details [CNFT2-1976](https://cdc-nbs.atlassian.net/browse/CNFT2-1976)
[CNFT2-1976]: https://cdc-nbs.atlassian.net/browse/CNFT2-1976?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNT-45] - E2E - Preview and publish - Page Info Details

---

testing/regression/cypress/e2e/features/preview-page/previewPage.feature
testing/regression/cypress/step_definitions/preview-page/previewPage.steps.js

Added end to end test case for preview and publish page has page history [CNFT2-1977](https://cdc-nbs.atlassian.net/browse/CNFT2-1977)
[CNFT2-1977]: https://cdc-nbs.atlassian.net/browse/CNFT2-1977?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNT-45] - E2E - Preview and publish - Page History

---

testing/regression/cypress/e2e/features/preview-page/previewPage.feature
testing/regression/cypress/step_definitions/preview-page/previewPage.steps.js

Added end to end test case for publishing a newly created page [CNFT2-2297](https://cdc-nbs.atlassian.net/browse/CNFT2-2297)
[CNFT2-2297]: https://cdc-nbs.atlassian.net/browse/CNFT2-2297?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNT-45] - E2E - Preview and publish CNFT2-2297

---

apps/modernization-ui/src/apps/search/layout/result/search-results.module.scss
apps/modernization-ui/src/apps/search/patient/result/table/PatientSearchResultTable.tsx
apps/modernization-ui/src/apps/search/useSearch.ts

Couple bugs with styling and sort
* [CNFT1-2847](https://cdc-nbs.atlassian.net/browse/CNFT1-2847)
* [CNFT1-2842](https://cdc-nbs.atlassian.net/browse/CNFT1-2842)
* [CNFT1-2849](https://cdc-nbs.atlassian.net/browse/CNFT1-2849)
[CNFT1-2847]: https://cdc-nbs.atlassian.net/browse/CNFT1-2847?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CNFT1-2842]: https://cdc-nbs.atlassian.net/browse/CNFT1-2842?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CNFT1-2849]: https://cdc-nbs.atlassian.net/browse/CNFT1-2849?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

both bugs fixed, and ready for testing

---

apps/modernization-ui/src/apps/search/layout/result/header/options/toggleView/ToggleView.tsx

Ensure selected view (table/list) toggle button has CircleCheck icon.
* [CNFT1-2792](https://cdc-nbs.atlassian.net/browse/CNFT1-2792)
[CNFT1-2792]: https://cdc-nbs.atlassian.net/browse/CNFT1-2792?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNT1-2792 Toggle view check icon

---

testing/regression/cypress/e2e/pages/advanced-condition-search/createNewCondition.page.js
testing/regression/cypress/e2e/pages/edit-page/addEditSearchDeleteQuestion.page.js
testing/regression/cypress/e2e/pages/edit-page/addSection.page.js
testing/regression/cypress/e2e/pages/edit-page/deleteSection.page.js
testing/regression/cypress/e2e/pages/edit-page/grouping/groupAndUngroupQuestions.page.js
testing/regression/cypress/e2e/pages/edit-page/manageSection.page.js
testing/regression/cypress/e2e/pages/edit-page/subsection/manageSubsection.page.js
testing/regression/cypress/e2e/pages/question-library/createNewQuestion.page.js
testing/regression/cypress/e2e/pages/question-library/sort.page.js

[CNT-45] - Report Failure Fix

---

apps/modernization-ui/src/apps/search/investigation/GeneralSearchFields.tsx
apps/modernization-ui/src/apps/search/investigation/InvestigationSearch.tsx
apps/modernization-ui/src/apps/search/laboratory-report/GeneralFields.tsx
apps/modernization-ui/src/apps/search/laboratory-report/LaboratoryReportSearch.tsx
apps/modernization-ui/src/apps/search/patient/PatientSearch.tsx
apps/modernization-ui/src/apps/search/useSearch.spec.tsx
apps/modernization-ui/src/apps/search/useSearch.ts

Enabling 'Clear all' button in Patient Search, Investigation Search, Lab report search.
* [CNFT1-2806](https://cdc-nbs.atlassian.net/browse/CNFT1-2806)
[CNFT1-2806]: https://cdc-nbs.atlassian.net/browse/CNFT1-2806?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT1-2806 Clear all

---

apps/modernization-ui/src/apps/search/layout/result/search-results.module.scss
apps/modernization-ui/src/apps/search/layout/search-layout.module.scss
apps/modernization-ui/src/apps/search/patient/result/table/PatientSearchResultTable.tsx
apps/modernization-ui/src/apps/search/useSearch.ts

Small bug fix for the collapse button

Collapse button bug fix

---

apps/modernization-api/src/main/java/gov/cdc/nbs/event/search/investigation/InvestigationSearchCriteriaSortResolver.java
apps/modernization-api/src/main/java/gov/cdc/nbs/event/search/labreport/LabReportSearchCriteriaSortResolver.java
apps/modernization-api/src/main/resources/search/investigation/investigation.index.json
apps/modernization-api/src/main/resources/search/lab-report/lab-report.index.json
apps/modernization-api/src/test/java/gov/cdc/nbs/event/search/investigation/InvestigationSearchResultVerificationSteps.java
apps/modernization-api/src/test/java/gov/cdc/nbs/event/search/labreport/LabReportSearchVerificationSteps.java
apps/modernization-api/src/test/resources/features/search/investigation/InvestigationSearch.sorting.feature
apps/modernization-api/src/test/resources/features/search/lab-report/LabReportSearch.sorting.feature

Updates to indexing for first name to be sortable. (investigation.index.json, lab-report.index.json)
* [CNFT1-2729](https://cdc-nbs.atlassian.net/browse/CNFT1-2729)
* [CNFT1-2730](https://cdc-nbs.atlassian.net/browse/CNFT1-2730)
[CNFT1-2729]: https://cdc-nbs.atlassian.net/browse/CNFT1-2729?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CNFT1-2730]: https://cdc-nbs.atlassian.net/browse/CNFT1-2730?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT1-2729 CNFT1-2729 API: Sort for Investigation/Lab Report Table View

---

apps/modernization-ui/src/apps/search/layout/SearchLayout.tsx
apps/modernization-ui/src/apps/search/patient/PatientCriteria/Address.tsx
apps/modernization-ui/src/apps/search/patient/PatientSearch.tsx

Adds an input mask to zip code to prevent invalid values.  Also adds the ability to disable search if the form is not valid.  
* [CNFT1-2741](https://cdc-nbs.atlassian.net/browse/CNFT1-2741)
[CNFT1-2741]: https://cdc-nbs.atlassian.net/browse/CNFT1-2741?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-2741] only valid zips

---

apps/modernization-ui/src/apps/search/event/components/InvestigationSearch/InvestigationGeneralFields.spec.tsx
apps/modernization-ui/src/apps/search/event/components/InvestigationSearch/InvestigationGeneralFields.tsx
apps/modernization-ui/src/apps/search/event/components/LabReportSearch/LabReportGeneralFields.spec.tsx
apps/modernization-ui/src/apps/search/event/components/LabReportSearch/LabReportGeneralFields.tsx
apps/modernization-ui/src/apps/search/laboratory-report/GeneralFields.spec.tsx
apps/modernization-ui/src/apps/search/laboratory-report/GeneralFields.tsx

Uppercase "ID".
* [CNFT1-2793](https://cdc-nbs.atlassian.net/browse/CNFT1-2793)
[CNFT1-2793]: https://cdc-nbs.atlassian.net/browse/CNFT1-2793?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT1-2793 Uppercase ID

---

apps/modernization-ui/src/apps/search/patient/PatientCriteria/RaceEthnicity.tsx
libs/options-api/src/main/java/gov/cdc/nbs/option/concept/JDBCConceptOptionFinder.java

Changes the race list to `P_RACE_CAT` and ensures that it's alphabetical.
* [CNFT1-2781](https://cdc-nbs.atlassian.net/browse/CNFT1-2781)
[CNFT1-2781]: https://cdc-nbs.atlassian.net/browse/CNFT1-2781?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-2781] Ensures that race list is in alphabetical order

---

apps/modernization-ui/src/apps/search/layout/result/header/options/table/ColumnPreferencesPanel.tsx
apps/modernization-ui/src/apps/search/layout/result/header/options/table/column-preference-panel.module.scss

Fixing column reorder drop bug
* [CNFT1-2857](https://cdc-nbs.atlassian.net/browse/CNFT1-2857)
[CNFT1-2857]: https://cdc-nbs.atlassian.net/browse/CNFT1-2857?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT1-2857 Fix column drop

---

testing/regression/cypress/e2e/pages/create-page/createNewPage.page.js
testing/regression/cypress/e2e/pages/edit-page/grouping/groupAndUngroupQuestions.page.js
testing/regression/cypress/e2e/pages/preview-page/previewPage.page.js

Fixed report failure for Page builder end to end test cases.

[CNT-45] - E2E Report Failure Fixes

---

apps/modernization-ui/src/design-system/checkbox/CheckboxGroup.spec.tsx
apps/modernization-ui/src/design-system/checkbox/CheckboxGroup.tsx

adding fixes to checkbox clear all issue in lab report
* [CNFT1-2859](https://cdc-nbs.atlassian.net/browse/CNFT1-2859)
[CNFT1-2859]: https://cdc-nbs.atlassian.net/browse/CNFT1-2859?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

adding fixes to checkbox clear all issue in lab report

---

testing/regression/cypress/e2e/pages/advanced-condition-search/createNewCondition.page.js

Fixed report failures for Page Builder

[CNT-45] - E2E Report Failure Fix

---

testing/regression/cypress/e2e/pages/advanced-condition-search/createNewCondition.page.js
testing/regression/cypress/e2e/pages/preview-page/previewPage.page.js

Fixed report failures for Page Builder
* [CNT-51](https://cdc-nbs.atlassian.net/browse/CNT-51)
[CNT-51]: https://cdc-nbs.atlassian.net/browse/CNT-51?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNT-51] - E2E Report Failure Fix

---

apps/modernization-ui/src/apps/patient/add/PatientAddRouting.tsx
apps/modernization-ui/src/apps/patient/add/extended/AddPatientExtended.tsx

Adds the route and placeholder page for extended new patient data.
* [Jira Ticket](https://cdc-nbs.atlassian.net/jira/software/c/projects/CNFT1/boards/112?assignee=712020%3A591f5469-427d-49e9-87dc-8b4df72a02b4&selectedIssue=CNFT1-2754)

Adds page for new patient extended

---

apps/modernization-ui/src/components/Entry/entry-wrapper.module.scss
apps/modernization-ui/src/components/selection/multi/MultiSelectInput.scss
apps/modernization-ui/src/design-system/checkbox/Checkbox.spec.tsx
apps/modernization-ui/src/design-system/checkbox/Checkbox.tsx
apps/modernization-ui/src/design-system/checkbox/CheckboxGroup.tsx
apps/modernization-ui/src/design-system/checkbox/checkbox.module.scss
apps/modernization-ui/src/design-system/checkbox/checkboxGroup.module.scss
apps/modernization-ui/src/design-system/select/multi/CheckboxOption.tsx
apps/modernization-ui/src/design-system/select/multi/checkbox-option.module.scss
apps/modernization-ui/src/styles/_components.scss

Adjusts the sizing of the compact variants of `MultiSelect` and `Checkbox`.
- Compact `MultiSelect` components now match the [Design System](https://www.figma.com/design/1291QgFj7tdDFqdSmxT26O/NBS-Design-System?node-id=1602-15376&t=s8QVGDkM95VdYyhL-0)
- Compact `Checkbox` components now match the [Design System](https://www.figma.com/design/1291QgFj7tdDFqdSmxT26O/NBS-Design-System?node-id=4667-14663&t=s8QVGDkM95VdYyhL-0)
* [CNFT1-2865](https://cdc-nbs.atlassian.net/browse/CNFT1-2865)
[CNFT1-2865]: https://cdc-nbs.atlassian.net/browse/CNFT1-2865?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-2865] Adjustments to compact components

---

apps/modernization-ui/src/apps/search/laboratory-report/GeneralFields.spec.tsx
apps/modernization-ui/src/apps/search/laboratory-report/GeneralFields.tsx
apps/modernization-ui/src/apps/search/laboratory-report/labReportFormTypes.ts
apps/modernization-ui/src/apps/search/laboratory-report/laboratoryReportTermsResolver.spec.ts
apps/modernization-ui/src/apps/search/laboratory-report/laboratoryReportTermsResolver.ts

Refactoring the input fields, and changing the input fields.
* [CNFT1-2484](https://cdc-nbs.atlassian.net/browse/CNFT1-2484)
* [CNFT1-2485](https://cdc-nbs.atlassian.net/browse/CNFT1-2485)
* [CNFT1-2486](https://cdc-nbs.atlassian.net/browse/CNFT1-2486)
[CNFT1-2484]: https://cdc-nbs.atlassian.net/browse/CNFT1-2484?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CNFT1-2485]: https://cdc-nbs.atlassian.net/browse/CNFT1-2485?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CNFT1-2486]: https://cdc-nbs.atlassian.net/browse/CNFT1-2486?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

lab report api integration

---

apps/modernization-ui/src/apps/patient/add/AddPatient.tsx
apps/modernization-ui/src/success/SuccessModal.spec.tsx
apps/modernization-ui/src/success/SuccessModal.tsx
apps/modernization-ui/src/success/successModal.module.scss

Updating the success modal to accept a broader range of content in the description field and footer.
Updated the Add new patient success alert to include links to Add lab report and Add investigation.
The links, similar to those in the Patient events tables, point to URL that don't exist yet.
* [CNFT1-2332](https://cdc-nbs.atlassian.net/browse/CNFT1-2332)
[CNFT1-2332]: https://cdc-nbs.atlassian.net/browse/CNFT1-2332?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT1-2332 Update success modal

---

apps/modernization-ui/src/apps/search/investigation/InvestigationSearch.tsx
apps/modernization-ui/src/apps/search/laboratory-report/LaboratoryReportSearch.tsx
apps/modernization-ui/src/apps/search/patient/PatientSearch.tsx

Quick fix for home page search
* [CNFT1-2813](https://cdc-nbs.atlassian.net/browse/CNFT1-2813)
[CNFT1-2813]: https://cdc-nbs.atlassian.net/browse/CNFT1-2813?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-2813] Home Page Search fix

---

.github/workflows/sonar.yaml

Updates the sonar workflow to use Java 21

[DevOps] Sonar check uses java 21

---

testing/regression/cypress/e2e/pages/create-page/createNewPage.page.js
testing/regression/cypress/e2e/pages/create-page/pageElements.page.js
testing/regression/cypress/e2e/pages/edit-page/grouping/groupAndUngroupQuestions.page.js
testing/regression/cypress/e2e/pages/preview-page/previewPage.page.js

Fixed end to end report failure fixes
* [CNT-51](https://cdc-nbs.atlassian.net/browse/CNT-51)
[CNT-51]: https://cdc-nbs.atlassian.net/browse/CNT-51?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNT-51] - E2E Report failure fixes

---

apps/modernization-ui/src/apps/search/patient/result/table/PatientSearchResultTable.tsx
apps/modernization-ui/src/design-system/table/preferences/useColumnPreferences.tsx

On the patient search results table, the legal name is wrapped in a Link to the unique patient profile page.
* [Jira Ticket](https://cdc-nbs.atlassian.net/jira/software/c/projects/CNFT1/boards/112?assignee=712020%3A591f5469-427d-49e9-87dc-8b4df72a02b4&selectedIssue=CNFT1-2884)

Link to profile page on patient results table

---

libs/authorization/src/main/java/gov/cdc/nbs/authorization/permission/scope/JDBCPermissionScopeFinder.java

Cherry-picks [sql int overflow fix](https://github.com/CDCgov/NEDSS-Modernization/pull/1663) into  into release.

Prevents int overflow when creating program-jurisdiciton oid (#1663)

---

apps/modernization-ui/src/apps/search/layout/result/header/options/table/ColumnPreferencesPanel.tsx
apps/modernization-ui/src/apps/search/layout/result/header/options/table/column-preference-panel.module.scss

Moves handles to right to match new designs.

Moves handles to right

---

apps/modernization-api/src/main/java/gov/cdc/nbs/patient/profile/redirect/incoming/ModernizedPatientProfileRedirect.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/profile/redirect/incoming/ModernizedPatientProfileRedirectResolver.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/profile/redirect/incoming/PatientProfileReturningRedirector.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/redirect/incoming/PatientProfileIncomingRedirectionSteps.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/redirect/incoming/PatientProfileIncomingSteps.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/redirect/incoming/PatientProfileReturningRedirectionSteps.java
apps/modernization-api/src/test/resources/features/patient/profile/PatientProfileReturningRedirect.feature
apps/modernization-ui/src/apps/patient/profile/vaccination/PatientVaccinationTable.tsx
apps/modernization-ui/src/classic/ClassicModalLink.tsx
apps/modernization-ui/src/classic/useRedirect.ts
apps/nbs-gateway/src/main/java/gov/cdc/nbs/gateway/patient/profile/PatientProfileEventReturnRouteLocatorConfiguration.java
apps/nbs-gateway/src/main/java/gov/cdc/nbs/gateway/patient/profile/PatientProfileService.java
apps/nbs-gateway/src/main/java/gov/cdc/nbs/gateway/patient/profile/PatientProfileSummaryReturnRouteLocatorConfiguration.java

Ensures that the vaccination pop-up only opens once.
* [CNFT1-2803](https://cdc-nbs.atlassian.net/browse/CNFT1-2803)
[CNFT1-2803]: https://cdc-nbs.atlassian.net/browse/CNFT1-2803?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-2803] View vaccination

---

apps/modernization-ui/src/apps/patient/add/AddPatient.tsx
apps/modernization-ui/src/apps/search/layout/result/header/terms/SearchTerms.tsx
apps/modernization-ui/src/design-system/chips/Chip.spec.tsx
apps/modernization-ui/src/design-system/chips/Chip.tsx
apps/modernization-ui/src/design-system/chips/chip.module.scss

Adding new Chips component replacing outdated styes form previous chips flow
* [CNFT1-2879](https://cdc-nbs.atlassian.net/browse/CNFT1-2879)
[CNFT1-2879]: https://cdc-nbs.atlassian.net/browse/CNFT1-2879?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CNFT1-2321]: https://cdc-nbs.atlassian.net/browse/CNFT1-2321?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

adding chips new chips component

---

apps/modernization-ui/src/apps/patient/add/AddPatient.tsx

Removing missing data modal in add patient
* [CNFT1-2321](https://cdc-nbs.atlassian.net/browse/CNFT1-2321)
[CNFT1-2321]: https://cdc-nbs.atlassian.net/browse/CNFT1-2321?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

removing missing data modal in add patient

---

apps/modernization-ui/src/apps/search/useSearch.ts
apps/modernization-ui/src/apps/search/useSearchResultDisplay.tsx

removing checkbox selections and searching bug fix
* [CNFT1-2887](https://cdc-nbs.atlassian.net/browse/CNFT1-2887)
[CNFT1-2887]: https://cdc-nbs.atlassian.net/browse/CNFT1-2887?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

adding reset call to no input variable

---

.github/workflows/Regression-tests.yaml

Resolves an oopsie made in the regression test workflow. Secrets do not need to be defined in that spot.

Regression test workflow fix

---

apps/modernization-api/src/main/java/gov/cdc/nbs/patient/profile/NewPatient.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/profile/PatientCreateController.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/profile/address/PatientAddress.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/profile/address/change/PatientAddressChangeService.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/profile/names/change/PatientNameChangeService.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/PatientCreateSteps.java
apps/modernization-api/src/test/resources/features/patient/profile/PatientProfileCreate.feature

Build on https://github.com/CDCgov/NEDSS-Modernization/pull/1660 and expand the requestbody to include names and addresses.  Use the existing service to add names and addresses once the patient is created.
note: still working on last feature tests
* [CNFT1-2768](https://cdc-nbs.atlassian.net/browse/CNFT1-2768)
* [CNFT1-2767](https://cdc-nbs.atlassian.net/browse/CNFT1-2767)
```curl --cookie "nbs_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnb3YuY2RjLm5icyIsImlhdCI6MTcyMzUwOTIxMSwiZXhwIjoxNzIzNTExMDExLCJzdWIiOiJzdGF0ZSJ9.nHpyI-9pw6P1VAUSZZaxCwWJjIKbmeCN9yb6HSg1RKk; Max-Age=1800;nbs_user=state;" -X POST -d '{"comment":"a comment", "names":[{"first":"jane", "last":"doe"}], "addresses":[{"address1":"1 way"}]}' -H "Content-Type: application/json" …
```

CNFT1-2767 CNFT1-2768 API: Extended patient data entry for names/addresses

---

apps/modernization-ui/src/apps/patient/add/AddPatient.tsx

Advanced search - Add new patient - Add patient - Routed to Patient search when clicking Add lab report or Add investigation from Success modal fix using classic button
* [CNFT1-2909](https://cdc-nbs.atlassian.net/browse/CNFT1-2909)
[CNFT1-2909]: https://cdc-nbs.atlassian.net/browse/CNFT1-2909?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

adding classic button with url path for lab report and investigation

---

apps/modernization-ui/src/apps/search/layout/result/header/options/table/search-results-table-options.module.scss
apps/modernization-ui/src/components/button/Button.module.scss
apps/modernization-ui/src/components/button/Button.tsx

fixing spacing issue on table view vs list view icons 
* [CNFT1-2902](https://cdc-nbs.atlassian.net/browse/CNFT1-2902)
[CNFT1-2902]: https://cdc-nbs.atlassian.net/browse/CNFT1-2902?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

adding margin 0 on the button element table results

---

apps/modernization-ui/src/apps/patient/add/AddPatient.tsx

Fixing a bug in add lab report and add investigation 
* [CNFT1-2909](https://cdc-nbs.atlassian.net/browse/CNFT1-2909)
[CNFT1-2909]: https://cdc-nbs.atlassian.net/browse/CNFT1-2909?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Cnft1 2909 id fix add patient

---

apps/modernization-ui/src/apps/landing/About/About.spec.tsx
apps/modernization-ui/src/apps/landing/About/About.tsx

Alters the content of the About tab on the NBS7 Landing page.
- Updated NBS Central link
- Updated Feedback section to include link to email address for feedback
* [CNFT1-2931](https://cdc-nbs.atlassian.net/browse/CNFT1-2931)
[CNFT1-2931]: https://cdc-nbs.atlassian.net/browse/CNFT1-2931?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-2931] landing page About section content

---

testing/regression/cypress/e2e/features/profile.feature
testing/regression/cypress/step_definitions/advance.search.steps.js

Fixes for search and patient profile. 
* [CNT-22](https://cdc-nbs.atlassian.net/browse/CNT-22)
[CNT-22]: https://cdc-nbs.atlassian.net/browse/CNT-22?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fixes to search, profile summary, and profile

---

apps/modernization-ui/src/apps/search/layout/result/header/options/toggleView/toggle-view.module.scss
apps/modernization-ui/src/components/button/Button.module.scss

Add Hover state to the segmented buttons, (list and table) for when the buttons are selected to reflect proper hover state and when there non active to also render proper hover state
* [CNFT1-2938](https://cdc-nbs.atlassian.net/browse/CNFT1-2938)
[CNFT1-2938]: https://cdc-nbs.atlassian.net/browse/CNFT1-2938?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Cnft1 2938 hover state segmented buttons

---

apps/modernization-ui/src/apps/search/layout/result/header/options/list/SearchResultsListOptions.tsx
apps/modernization-ui/src/apps/search/patient/PatientCriteria/BasicInformation.tsx
apps/modernization-ui/src/components/ButtonActionMenu/ButtonActionMenu.tsx
apps/modernization-ui/src/components/ButtonActionMenu/buttonActionMenu.module.scss
apps/modernization-ui/src/design-system/checkbox/CheckboxGroup.tsx
apps/modernization-ui/src/design-system/checkbox/checkboxGroup.module.scss

space between the status text and the checkboxes in patient search, tooltip icon button
* [CNFT1-2927](https://cdc-nbs.atlassian.net/browse/CNFT1-2927)
[CNFT1-2927]: https://cdc-nbs.atlassian.net/browse/CNFT1-2927?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

adding search ui fixes

---

apps/modernization-ui/src/apps/search/patient/PatientCriteria/Contact.tsx

Phone number was not being cleared visibly when the clear all button was clicked.
* [CNFT1-2897](https://cdc-nbs.atlassian.net/browse/CNFT1-2897)
[CNFT1-2897]: https://cdc-nbs.atlassian.net/browse/CNFT1-2897?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

cnft1-2897 phone number bug

---

testing/regression/cypress/e2e/features/nbs-classic/home.feature
testing/regression/cypress/e2e/pages/login.page.js
testing/regression/cypress/e2e/pages/nbs-classic/home.page.js
testing/regression/cypress/step_definitions/login.steps.js
testing/regression/cypress/step_definitions/nbs-classic/home.steps.js

Added e2e for classic NBS patient search

[CNT-57] - Classic NBS Search Page Patient Search

---

testing/regression/cypress/e2e/features/nbs-classic/home.feature
testing/regression/cypress/step_definitions/nbs-classic/home.steps.js

Added e2e test for add new lab report. [CNQAT-121](https://cdc-nbs.atlassian.net/browse/CNQAT-121)
[CNQAT-121]: https://cdc-nbs.atlassian.net/browse/CNQAT-121?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNT-57] - CNQAT-121 Classic NBS Search Page Add new lab report

---

testing/regression/cypress/e2e/features/nbs-classic/home.feature
testing/regression/cypress/step_definitions/nbs-classic/home.steps.js

Added end to end test case for My Queue [CNQAT-126](https://cdc-nbs.atlassian.net/browse/CNQAT-126)
[CNQAT-126]: https://cdc-nbs.atlassian.net/browse/CNQAT-126?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNT-57] - CNQAT-126 - Classic NBS My Queue

---

testing/regression/cypress/e2e/features/nbs-classic/home.feature
testing/regression/cypress/step_definitions/nbs-classic/home.steps.js

Added end to end test case for merge patients [CNQAT-127](https://cdc-nbs.atlassian.net/browse/CNQAT-127)
[CNQAT-127]: https://cdc-nbs.atlassian.net/browse/CNQAT-127?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNT-57] - CNQAT-127 - Classic NBS - Merge Patients

---

testing/regression/cypress/e2e/features/nbs-classic/home.feature
testing/regression/cypress/step_definitions/nbs-classic/home.steps.js

Added end to end test case page for reports [CNQAT-128](https://cdc-nbs.atlassian.net/browse/CNQAT-128)
[CNQAT-128]: https://cdc-nbs.atlassian.net/browse/CNQAT-128?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNT-57] - CNQAT-128 - Home page Reports

---

testing/regression/cypress/e2e/pages/edit-page/grouping/groupAndUngroupQuestions.page.js
testing/regression/cypress/e2e/pages/nbs-classic/home.page.js

Fixed report failure for end to end test scripts

[CNT-57] - Fix failed e2e

---

apps/modernization-ui/src/apps/search/layout/result/header/options/toggleView/toggle-view.module.scss

Removing hover state on toggle view active button in patient search following discussions with the designers
* [CNFT1-2938](https://cdc-nbs.atlassian.net/browse/CNFT1-2938)
[CNFT1-2938]: https://cdc-nbs.atlassian.net/browse/CNFT1-2938?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

removing a hover state background-color and border-color

---

apps/modernization-api/src/main/java/gov/cdc/nbs/event/search/investigation/SearchableInvestigation.java
apps/modernization-api/src/main/java/gov/cdc/nbs/event/search/investigation/indexing/SearchableInvestigationFinder.java
apps/modernization-api/src/main/java/gov/cdc/nbs/event/search/investigation/indexing/SearchableInvestigationResolver.java
apps/modernization-api/src/main/java/gov/cdc/nbs/event/search/investigation/indexing/SearchableInvestigationRowMapper.java
apps/modernization-api/src/main/resources/graphql/investigation-search.graphqls
apps/modernization-api/src/test/java/gov/cdc/nbs/event/search/investigation/InvestigationSearchRequester.java
apps/modernization-api/src/test/java/gov/cdc/nbs/event/search/investigation/InvestigationSearchResultConverterTest.java
apps/modernization-api/src/test/java/gov/cdc/nbs/event/search/investigation/indexing/SearchableInvestigationRowMapperTest.java
apps/modernization-api/src/test/resources/features/search/investigation/InvestigationSearch.sorting.feature
apps/modernization-ui/src/generated/gql/queries/findInvestigationsByFilter.gql
apps/modernization-ui/src/generated/graphql/schema.ts
apps/modernization-ui/src/generated/schema.graphqls

Finish up investigator (added to nifi)
Followup to: https://github.com/CDCgov/NEDSS-Modernization/pull/1731
* [CNFT1-2928](https://cdc-nbs.atlassian.net/browse/CNFT1-2928)
[CNFT1-2928]: https://cdc-nbs.atlassian.net/browse/CNFT1-2928?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT1-2928 Advanced search - Investigations - Sorting - Part2

---

apps/modernization-ui/src/apps/search/layout/result/header/options/list/SearchResultsListOptions.tsx
apps/modernization-ui/src/components/ButtonActionMenu/ButtonActionMenu.tsx
apps/modernization-ui/src/styles/_tooltip.scss

2 Bugs fixed:
1. Tooltip for gear icon
2. Tooltip for Add new button not necessary
* [CNFT1-2954](https://cdc-nbs.atlassian.net/browse/CNFT1-2954)
* [CNFT1-2985](https://cdc-nbs.atlassian.net/browse/CNFT1-2985)
[CNFT1-2954]: https://cdc-nbs.atlassian.net/browse/CNFT1-2954?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CNFT1-2985]: https://cdc-nbs.atlassian.net/browse/CNFT1-2985?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Tooltip bug fixed

---

apps/modernization-ui/src/apps/dedup-config/PatientMatchConfig.module.scss
apps/modernization-ui/src/apps/dedup-config/PatientMatchConfiguration.tsx
apps/modernization-ui/src/apps/dedup-config/PatientMatchRouting.tsx
apps/modernization-ui/src/apps/dedup-config/index.ts
apps/modernization-ui/src/routes/AppRoutes.tsx

Setup dedup routing and initial page

---

testing/regression/package-lock.json
testing/regression/package.json

Update badeball npm version

---

testing/regression/cypress/e2e/pages/nbs-classic/home.page.js
testing/regression/cypress/e2e/pages/preview-page/previewPage.page.js

Fix failed end to end test cases

[CNT-57] - Fix failed e2e test cases

---

apps/modernization-ui/src/apps/search/laboratory-report/CriteriaFields.tsx
apps/modernization-ui/src/design-system/autocomplete/single/Autocomplete.tsx
apps/modernization-ui/src/options/autocompete/ResultedTestsAutocomplete.tsx
apps/modernization-ui/src/suggestion/Suggestions.scss

UI autocomplete dropdown for resulted test complete, with showing the code and the name of the test
* [CNFT1-2944](https://cdc-nbs.atlassian.net/browse/CNFT1-2944)
[CNFT1-2944]: https://cdc-nbs.atlassian.net/browse/CNFT1-2944?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Cnft1 2944 resulted test codes

---

apps/modernization-ui/src/apps/search/layout/result/header/options/list/SearchResultsListOptions.tsx
apps/modernization-ui/src/apps/search/layout/result/header/options/list/search-results-list-options.module.scss

Sort by list - selected option has to be highlighted with a checkmark using our own icon component instead of USWDS 
* [CNFT1-2957](https://cdc-nbs.atlassian.net/browse/CNFT1-2957)
[CNFT1-2957]: https://cdc-nbs.atlassian.net/browse/CNFT1-2957?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

adding checkmark on selected option sortby dropdown and refactored

---

apps/modernization-ui/src/options/autocompete/ResultedTestsAutocomplete.tsx

Passing down sizing prop to autoComplete
* [CNFT1-2946](https://cdc-nbs.atlassian.net/browse/CNFT1-2946)
[CNFT1-2946]: https://cdc-nbs.atlassian.net/browse/CNFT1-2946?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

passing down size prop

---

apps/modernization-ui/src/apps/dedup-config/MatchConfiguration/MatchConfiguration.module.scss
apps/modernization-ui/src/apps/dedup-config/MatchConfiguration/MatchConfiguration.tsx
apps/modernization-ui/src/apps/dedup-config/MatchConfiguration/PassConfiguration/PassConfiguration.tsx
apps/modernization-ui/src/apps/dedup-config/MatchConfiguration/PassConfiguration/PassConfigurationListItem.module.scss
apps/modernization-ui/src/apps/dedup-config/MatchConfiguration/PassConfiguration/PassConfigurationListItem.tsx

Adds a mock configuration list with the ability to add and select different configs

adds mock configuration list and functionality

---

db/tools/bulk_patient_import.rb

A quick and dirty script to load patient information in bulk from a csv file.  It takes the original csv and prepends person_uids to them and then creates all the associated csvs for each table (entity, person, person_name, entity_id, person_race, entity_locator_participation, tele_locator,   postal_locator) and subsequently bcps them into the db.  This should be the fastest possible way to get patient data in in bulk (without extra hacks like relaxing indexes etc.).  inputs are the csv file.  The db credentials and starting ids for person_uid and locator_uid are hardcoded
Run with:
`ruby bulk_patient_import.rb [csv-to-import]  [db-host]  [db-username]  [db-password]`
* [CNFT1-2893](https://cdc-nbs.atlassian.net/browse/CNFT1-2893)
```
ruby bulk_patient_import.rb demo_patient_records.csv …
```

CNFT1-2893 Bulk patient import script

---

apps/modernization-ui/src/components/Accordion/accordion.module.scss
apps/modernization-ui/src/design-system/collapsible-panel/collapsible-panel.module.scss

Fixes the width of the search criteria on all browsers, not just Safari.
* [CNFT1-3036](https://cdc-nbs.atlassian.net/browse/CNFT1-3036)
[CNFT1-3036]: https://cdc-nbs.atlassian.net/browse/CNFT1-3036?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-3036] Search criteria width

---

.gitignore
apps/modernization-ui/src/apps/search/layout/result/SearchResults.tsx
apps/modernization-ui/src/components/Table/RangeToggle/RangeToggle.tsx
apps/modernization-ui/src/components/Table/RangeToggle/range-toggle.module.scss
apps/modernization-ui/src/design-system/Pagination/Pagination.spec.tsx
apps/modernization-ui/src/design-system/Pagination/Pagination.tsx
apps/modernization-ui/src/design-system/Pagination/index.ts
apps/modernization-ui/src/design-system/Pagination/pagination.module.scss

Ensures that the pagination controls have a top border in the search results.
List view:
Table view:
Also adds tests for the `Pagination` component
* [CNFT1-2958](https://cdc-nbs.atlassian.net/browse/CNFT1-2958)
[CNFT1-2958]: https://cdc-nbs.atlassian.net/browse/CNFT1-2958?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-2958] Search result border

---

apps/modernization-ui/src/apps/search/layout/result/header/options/list/SearchResultsListOptions.tsx
apps/modernization-ui/src/apps/search/layout/result/header/options/table/SearchResultsTableOptions.tsx
apps/modernization-ui/src/components/NoData/NoData.scss
apps/modernization-ui/src/design-system/sorting/preferences/SortingPreferencesPanel.tsx
apps/modernization-ui/src/styles/_tooltip.scss

Updates the List sorting menu title and tool tip to "Sort list by" to match the designs.

List sorting

---

apps/modernization-api/src/main/java/gov/cdc/nbs/event/search/labreport/LabReportSearchResult.java
apps/modernization-api/src/main/java/gov/cdc/nbs/event/search/labreport/LabTestSummaryFinder.java
apps/modernization-api/src/main/resources/graphql/lab-report-search.graphqls
apps/modernization-ui/src/apps/search/event/components/LabReportSearch/LabReportResults.spec.tsx
apps/modernization-ui/src/apps/search/laboratory-report/result/ResultedTestDisplay.spec.tsx
apps/modernization-ui/src/apps/search/laboratory-report/result/ResultedTestDisplay.tsx
apps/modernization-ui/src/apps/search/laboratory-report/result/laboratoryReportResult.spec.tsx
apps/modernization-ui/src/apps/search/laboratory-report/result/laboratoryReportResult.tsx
apps/modernization-ui/src/apps/search/laboratory-report/result/list/LaboratoryReportSearchResultListItem.spec.tsx
apps/modernization-ui/src/apps/search/laboratory-report/result/resulted-test.module.scss
apps/modernization-ui/src/apps/search/laboratory-report/result/table/LaboratoryReportSearchResultsTable.spec.tsx
apps/modernization-ui/src/generated/gql/queries/findLabReportsByFilter.gql
apps/modernization-ui/src/generated/graphql/schema.ts
apps/modernization-ui/src/generated/schema.graphqls

Display resulted tests in description block of Lab report search results.
* [CNFT1-2942](https://cdc-nbs.atlassian.net/browse/CNFT1-2942)
[CNFT1-2942]: https://cdc-nbs.atlassian.net/browse/CNFT1-2942?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Display resulted tests on lab report search results

---

apps/modernization-api/src/main/java/gov/cdc/nbs/event/search/labreport/ElasticsearchLabReportSearchResolver.java
apps/modernization-api/src/main/java/gov/cdc/nbs/event/search/labreport/LabReportSearchResultResolver.java
apps/modernization-api/src/main/resources/graphql/lab-report-search.graphqls
apps/modernization-api/src/test/java/gov/cdc/nbs/event/search/investigation/InvestigationSearchResultVerificationSteps.java
apps/modernization-ui/src/apps/dedup-config/DataElementsConfiguration/DataElementsConfiguration.tsx
apps/modernization-ui/src/apps/dedup-config/DataElementsConfiguration/DataElementsTable.tsx
apps/modernization-ui/src/apps/dedup-config/const/init.ts
apps/modernization-ui/src/apps/dedup-config/context/DataElementsContext.tsx
apps/modernization-ui/src/generated/schema.graphqls

Store data elements locally

---

apps/modernization-ui/src/apps/dedup-config/DataElementsConfiguration/DataElementsTable.tsx
apps/modernization-ui/src/apps/dedup-config/PatientMatchConfiguration/BlockingCriteria/AddBlockingCriteria.tsx
apps/modernization-ui/src/apps/dedup-config/PatientMatchConfiguration/BlockingCriteria/BlockingCriteriaRow.tsx
apps/modernization-ui/src/apps/dedup-config/PatientMatchConfiguration/PatientMatchConfigurationPage/PatientMatchConfigurationPage.tsx
apps/modernization-ui/src/apps/dedup-config/const/init.ts
apps/modernization-ui/src/apps/dedup-config/context/DataElementsContext.tsx
apps/modernization-ui/src/apps/dedup-config/context/PatientMatchContext.tsx
apps/modernization-ui/src/apps/dedup-config/types/index.ts

Move types

---

apps/modernization-ui/src/apps/dedup-config/PatientMatchConfiguration/BlockingCriteria/BlockingCriteria.tsx
apps/modernization-ui/src/apps/dedup-config/PatientMatchConfiguration/PatientMatchConfigurationPage/PatientMatchConfigurationPage.tsx
apps/modernization-ui/src/apps/dedup-config/PatientMatchConfiguration/PatientMatchConfigurationPage/PatientMatchForm.tsx

Configure pass config fetch

---

apps/modernization-ui/src/design-system/collapsible-panel/collapsible-panel.module.scss

Collapse button is now in front of the scroll bar
* [CNFT1-3071](https://cdc-nbs.atlassian.net/browse/CNFT1-3071)
[CNFT1-3071]: https://cdc-nbs.atlassian.net/browse/CNFT1-3071?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Collapse button

---

apps/modernization-ui/src/apps/dedup-config/PatientMatchConfiguration/PatientMatchConfigurationPage/PatientMatchConfigurationPage.tsx

Config load bug

---

apps/modernization-ui/src/apps/dedup-config/PatientMatchConfiguration/BlockingCriteria/AddBlockingCriteria.tsx
apps/modernization-ui/src/apps/dedup-config/PatientMatchConfiguration/MatchingBounds/MatchingBounds.tsx
apps/modernization-ui/src/apps/dedup-config/PatientMatchConfiguration/MatchingBounds/ProgressBar.tsx
apps/modernization-ui/src/apps/dedup-config/PatientMatchConfiguration/MatchingBounds/progress-bar.module.scss
apps/modernization-ui/src/apps/dedup-config/PatientMatchConfiguration/MatchingCriteria/AddMatchingCriteria.tsx
apps/modernization-ui/src/apps/dedup-config/PatientMatchConfiguration/MatchingCriteria/MatchingCriteriaSection.tsx
apps/modernization-ui/src/apps/dedup-config/PatientMatchConfiguration/PatientMatchConfigurationPage/patient-match-configuration-page.module.scss
apps/modernization-ui/src/apps/dedup-config/PatientMatchConfiguration/PatientMatchConfigurationPage/patient-match-form.module.scss
apps/modernization-ui/src/apps/dedup-config/context/DedupeContext.tsx
apps/modernization-ui/src/apps/dedup-config/context/PatientMatchContext.tsx

Matching Bounds section with Progress bar
* [CNFT2-2773](https://cdc-nbs.atlassian.net/browse/CNFT2-2773)
[CNFT2-2773]: https://cdc-nbs.atlassian.net/browse/CNFT2-2773?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT2-2773 Matching Bounds section

---

apps/modernization-ui/src/apps/patient/profile/mortality/MortalityEntryFields.tsx

Fixes conditional hook call error when selecting state of death in mortality form.
* [CNFT1-3076](https://cdc-nbs.atlassian.net/browse/CNFT1-3076)
[CNFT1-3076]: https://cdc-nbs.atlassian.net/browse/CNFT1-3076?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix more hooks than during previous render

---

apps/modernization-ui/src/apps/dedup-config/PatientMatchConfiguration/BlockingCriteria/AddBlockingCriteria.tsx
apps/modernization-ui/src/apps/dedup-config/PatientMatchConfiguration/BlockingCriteria/BlockingCriteria.tsx
apps/modernization-ui/src/apps/dedup-config/PatientMatchConfiguration/BlockingCriteria/add-blocking-criteria.module.scss
apps/modernization-ui/src/apps/dedup-config/PatientMatchConfiguration/BlockingCriteria/blocking-criteria-row.module.scss
apps/modernization-ui/src/apps/dedup-config/PatientMatchConfiguration/MatchingBounds/MatchingBounds.tsx
apps/modernization-ui/src/apps/dedup-config/PatientMatchConfiguration/MatchingBounds/ProgressBar.tsx
apps/modernization-ui/src/apps/dedup-config/PatientMatchConfiguration/MatchingCriteria/AddMatchingCriteria.tsx
apps/modernization-ui/src/apps/dedup-config/PatientMatchConfiguration/MatchingCriteria/MatchingCriteriaSection.tsx
apps/modernization-ui/src/apps/dedup-config/PatientMatchConfiguration/MatchingCriteria/add-matching-criteria.module.scss
apps/modernization-ui/src/apps/dedup-config/PatientMatchConfiguration/PatientMatchConfigurationPage/patient-match-configuration-page.module.scss
apps/modernization-ui/src/apps/dedup-config/PatientMatchConfiguration/PatientMatchConfigurationPage/patient-match-form.module.scss
apps/modernization-ui/src/apps/dedup-config/const/init.ts
apps/modernization-ui/src/apps/dedup-config/context/PatientMatchContext.tsx
apps/modernization-ui/src/apps/dedup-config/types/index.ts
apps/modernization-ui/src/components/ModalComponent/ModalComponent.scss

Adding category headers to data element modals.
Added category to DataElement objects.
Adjusted general modal styling
* [CNFT2-2774](https://cdc-nbs.atlassian.net/browse/CNFT2-2774)
[CNFT2-2774]: https://cdc-nbs.atlassian.net/browse/CNFT2-2774?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT2-2774 Modal category headers

---

apps/modernization-ui/src/apps/dedup-config/PatientMatchConfiguration/MatchingBounds/MatchingBounds.tsx
apps/modernization-ui/src/apps/dedup-config/PatientMatchConfiguration/MatchingBounds/progress-bar.module.scss
apps/modernization-ui/src/apps/dedup-config/PatientMatchConfiguration/PatientMatchConfigurationPage/PatientMatchConfigurationPage.tsx
apps/modernization-ui/src/apps/dedup-config/PatientMatchConfiguration/PatientMatchConfigurationPage/PatientMatchForm.tsx
apps/modernization-ui/src/apps/dedup-config/types/index.ts

Now lowerBound and upperBound are in the form submission
* [CNFT2-2777](https://cdc-nbs.atlassian.net/browse/CNFT2-2777)
[CNFT2-2777]: https://cdc-nbs.atlassian.net/browse/CNFT2-2777?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT2-2777 Fix lowerBound and upperBound

---

apps/modernization-ui/src/apps/dedup-config/PatientMatchConfiguration/PatientMatchConfigurationPage/PatientMatchConfigurationPage.tsx
apps/modernization-ui/src/apps/dedup-config/PatientMatchConfiguration/PatientMatchConfigurationPage/PatientMatchForm.tsx

Also addresses bug related to overwriting configs array on save.

Generate pass configuration name based on blocking criteria

---

apps/modernization-ui/src/apps/dedup-config/PatientMatchConfiguration/PassConfiguration/PassConfigurationListItem.module.scss
apps/modernization-ui/src/apps/dedup-config/PatientMatchConfiguration/PatientMatchConfigurationPage/PatientMatchConfigurationPage.tsx

Cleanup config list

---

apps/modernization-ui/src/apps/search/laboratory-report/GeneralFields.tsx

Corrects the case for the `Event ID` label in Laboratory Report search.
👀

[FIX] Corrects case on event id label

---

apps/modernization-ui/src/apps/dedup-config/PatientMatchConfiguration/BlockingCriteria/BlockingCriteriaRow.tsx
apps/modernization-ui/src/apps/dedup-config/PatientMatchConfiguration/BlockingCriteria/BlockingCriteriaSection.tsx
apps/modernization-ui/src/apps/dedup-config/PatientMatchConfiguration/MatchingCriteria/MatchingCriteriaRow.tsx
apps/modernization-ui/src/apps/dedup-config/PatientMatchConfiguration/MatchingCriteria/MatchingCriteriaSection.tsx
apps/modernization-ui/src/apps/dedup-config/PatientMatchConfiguration/PatientMatchConfigurationPage/PatientMatchConfigurationPage.tsx
apps/modernization-ui/src/apps/dedup-config/PatientMatchConfiguration/PatientMatchConfigurationPage/PatientMatchForm.tsx

Fixes save/fetch/hydration for criteria methods and upper/lower bounds

---

apps/modernization-ui/src/apps/dedup-config/PatientMatchConfiguration/PatientMatchConfigurationPage/PatientMatchConfigurationPage.tsx
apps/modernization-ui/src/apps/dedup-config/PatientMatchConfiguration/PatientMatchConfigurationPage/PatientMatchForm.tsx

Fix onfig selection bugs/add cancel handling/ add new config rails

---

apps/modernization-ui/src/apps/dedup-config/PatientMatchConfiguration/PatientMatchConfigurationPage/PatientMatchConfigurationPage.tsx
apps/modernization-ui/src/apps/dedup-config/PatientMatchConfiguration/PatientMatchConfigurationPage/patient-match-configuration-page.module.scss

adjust styling for the add configuration button when disabled

---

testing/regression/cypress/e2e/features/nbs-classic/manageQuestions.feature
testing/regression/cypress/e2e/pages/nbs-classic/manageQuestions.page.js
testing/regression/cypress/step_definitions/nbs-classic/manageQuestions.steps.js

Added end to end test case on classic for adding new local question.
* [CNT-64](https://cdc-nbs.atlassian.net/browse/CNT-64)
[CNT-64]: https://cdc-nbs.atlassian.net/browse/CNT-64?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNT-64] - 1032 - Classic - Question Library -  Add New Local

---

apps/modernization-ui/src/apps/dedup-config/DataElementsConfiguration/DataElementsConfiguration.tsx
apps/modernization-ui/src/apps/dedup-config/DataElementsConfiguration/data-elements-configuration.module.scss
apps/modernization-ui/src/apps/dedup-config/PatientMatchConfiguration/MatchingBounds/ProgressBar.tsx
apps/modernization-ui/src/apps/dedup-config/PatientMatchConfiguration/PassConfiguration/PassConfigurationListItem.module.scss
apps/modernization-ui/src/apps/dedup-config/PatientMatchConfiguration/PatientMatchConfigurationPage/PatientMatchConfigurationPage.tsx
apps/modernization-ui/src/apps/dedup-config/PatientMatchConfiguration/PatientMatchConfigurationPage/patient-match-configuration-page.module.scss

styling tweaks

---

apps/modernization-ui/src/apps/dedup-config/context/DataElementsContext.spec.tsx
apps/modernization-ui/src/apps/dedup-config/context/DedupeContext.spec.tsx
apps/modernization-ui/src/apps/dedup-config/context/PatientMatchContext.spec.tsx
apps/modernization-ui/src/apps/dedup-config/types/index.ts

context tests

---

apps/modernization-api/src/main/java/gov/cdc/nbs/patient/profile/create/NewPatient.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/profile/create/PatientCreateController.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/profile/create/PatientCreationService.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/profile/ethnicity/EthnicityDemographic.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/profile/ethnicity/EthnicityPatientCommandMapper.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/profile/ethnicity/PatientEthnicityChangeService.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/PatientCreateSteps.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/create/PatientCreateEntrySteps.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/ethnicity/EthnicityDemographicSupportConfiguration.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/ethnicity/EthnicityEntrySteps.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/ethnicity/PatientProfileCreateEthnicitySteps.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/ethnicity/PatientProfileEthnicityRequester.java
apps/modernization-api/src/test/java/gov/cdc/nbs/support/concept/EthnicitySteps.java
apps/modernization-api/src/test/resources/features/patient/profile/create/ExtendedPatientCreation.ethnicity.feature

Work in progres...
* [CNFT1-2776](https://cdc-nbs.atlassian.net/browse/CNFT1-2776)
[CNFT1-2776]: https://cdc-nbs.atlassian.net/browse/CNFT1-2776?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT1-2776 API: Create Extended patient data entry form for Ethnicity

---

testing/regression/cypress/e2e/features/nbs-classic/manageQuestions.feature

Added end to end test case on classic for adding new PHIN question. 
* [CNT-65](https://cdc-nbs.atlassian.net/browse/CNT-65)
[CNT-65]: https://cdc-nbs.atlassian.net/browse/CNT-65?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNT-65] - 1033 Question Library -  Add New PHIN E2E Test

---

testing/regression/cypress/e2e/features/nbs-classic/manageQuestions.feature

Added end to end test case on classic for editing question.
* [CNT-66](https://cdc-nbs.atlassian.net/browse/CNT-66)
[CNT-66]: https://cdc-nbs.atlassian.net/browse/CNT-66?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNT-66] - 1034 Question Library -  Edit Question

---

apps/modernization-ui/src/apps/search/laboratory-report/labReportFormTypes.ts

…n Collection”
Update “Date of Specification” in Event date type to:
”Date of Specimen Collection”
one line change in apps/modernization-ui/src/apps/search/laboratory-report/labReportFormTypes.ts
* [Jira Ticket](https://cdc-nbs.atlassian.net/browse/CNFT1-3229)

Update “Date of Specification” in Event date type to ”Date of Specimen Collection”

---

testing/regression/cypress/e2e/features/add-patient.feature
testing/regression/cypress/e2e/pages/add-patient.page.js
testing/regression/cypress/e2e/pages/search.page.js
testing/regression/cypress/e2e/pages/searchEvent.page.js

Fixes Add Patient due to new features added to patient profile and search fails due to new UI features.
* [CNT-68](https://cdc-nbs.atlassian.net/browse/CNT-68)
[CNT-68]: https://cdc-nbs.atlassian.net/browse/CNT-68?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNT-68 add patient uses main element and  list fix for search

---

apps/modernization-ui/src/apps/patient/profile/summary/PatientProfileSummary.tsx
apps/modernization-ui/src/apps/search/basic/BasicPatient.spec.tsx
apps/modernization-ui/src/apps/search/investigation/result/list/InvestigationSearchResultListItem.spec.tsx
apps/modernization-ui/src/apps/search/investigation/result/list/InvestigationSearchResultListItem.tsx
apps/modernization-ui/src/apps/search/investigation/result/table/InvestigationSearchResultsTable.spec.tsx
apps/modernization-ui/src/apps/search/investigation/result/table/InvestigationSearchResultsTable.tsx
apps/modernization-ui/src/apps/search/laboratory-report/result/list/LaboratoryReportSearchResultListItem.spec.tsx
apps/modernization-ui/src/apps/search/laboratory-report/result/list/LaboratoryReportSearchResultListItem.tsx
apps/modernization-ui/src/apps/search/laboratory-report/result/table/LaboratoryReportSearchResultsTable.spec.tsx
apps/modernization-ui/src/apps/search/laboratory-report/result/table/LaboratoryReportSearchResultsTable.tsx
apps/modernization-ui/src/apps/search/patient/PatientCriteria/BasicInformation.tsx
apps/modernization-ui/src/apps/search/patient/result/list/PatientSearchResultListItem.tsx
apps/modernization-ui/src/apps/search/patient/result/table/PatientSearchResultTable.tsx
apps/modernization-ui/src/options/gender/options.spec.ts
apps/modernization-ui/src/options/gender/options.ts

* [CNFT1-3177](https://cdc-nbs.atlassian.net/browse/CNFT1-3177)
[CNFT1-3177]: https://cdc-nbs.atlassian.net/browse/CNFT1-3177?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT1-3177: Sex Other rename to Unknown

---

apps/modernization-api/postman/NBS Local Docker.postman_environment.json
apps/modernization-api/postman/NBS Local.postman_environment.json
apps/modernization-api/postman/NDESS-Modernization-API.postman_collection.json

Updates to the postman collection that includes the new patient add extended API `/nbs/api/profile`.

Postman collection updates

---

testing/regression/cypress/e2e/features/nbs-classic/manageConditions.feature
testing/regression/cypress/e2e/pages/nbs-classic/manageConditions.page.js
testing/regression/cypress/step_definitions/nbs-classic/manageConditions.steps.js

Added end to end test case on classic for add new condition.
* [CNT-67](https://cdc-nbs.atlassian.net/browse/CNT-67)
[CNT-67]: https://cdc-nbs.atlassian.net/browse/CNT-67?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNT-67] - 1035 - Condition Library - Add New Condition

---

testing/regression/cypress/e2e/pages/edit-page/manageSection.page.js

Fixed end to end test failure for modernization NBS Page Builder
* [CNT-67](https://cdc-nbs.atlassian.net/browse/CNT-67)
[CNT-67]: https://cdc-nbs.atlassian.net/browse/CNT-67?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNT-67] - E2E test failure fix

---

testing/regression/cypress/e2e/features/nbs-classic/manageConditions.feature

Added end to end test case on classic for edit condition library.
* [CNT-69](https://cdc-nbs.atlassian.net/browse/CNT-69)
[CNT-69]: https://cdc-nbs.atlassian.net/browse/CNT-69?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNT-69] - 1036 - Edit Condition Library

---

apps/modernization-api/src/main/java/gov/cdc/nbs/event/search/EventFilter.java
apps/modernization-api/src/main/java/gov/cdc/nbs/event/search/InvestigationFilter.java
apps/modernization-api/src/main/java/gov/cdc/nbs/event/search/LabReportFilter.java
apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/entity/CodeSetGroupMetadatum.java
apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/entity/WaNndMetadatum.java
apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/entity/WaTemplate.java
apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/entity/WaUiMetadata.java
apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/filter/Filter.java
apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/filter/ValueFilter.java
apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/component/ContentNode.java
apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/component/LayoutNode.java
libs/authentication/src/main/java/gov/cdc/nbs/authentication/entity/AuthUser.java
libs/authentication/src/main/java/gov/cdc/nbs/authentication/entity/AuthUserRole.java
libs/database-entities/src/main/java/gov/cdc/nbs/entity/odse/Act.java
libs/database-entities/src/main/java/gov/cdc/nbs/entity/odse/EntityId.java
libs/database-entities/src/main/java/gov/cdc/nbs/entity/odse/EntityLocatorParticipation.java
libs/database-entities/src/main/java/gov/cdc/nbs/entity/odse/PersonName.java
libs/database-entities/src/main/java/gov/cdc/nbs/entity/odse/PersonRace.java
libs/database-entities/src/main/java/gov/cdc/nbs/patient/demographic/PatientRaceDemographic.java

Addresses new sonar rule [javaarchitecture:S7027](https://sonarcloud.io/organizations/cdcgov/rules?open=javaarchitecture%3AS7027&rule_key=javaarchitecture%3AS7027)

[sonar] addresses new sonar rule javaarchitecture:S7027

---

apps/modernization-api/src/main/java/gov/cdc/nbs/codes/PrimaryOccupationValueSetFinder.java

Filter list of primary occupations to only the top-level, how it exists in NBS 6.
* [Jira Ticket](https://cdc-nbs.atlassian.net/browse/CNFT1-3363)

CNFT1-3363: Add Patient Extended: Filter to only top-level primary occupations

---

cdc-sandbox/dedupe-configuration/Dockerfile
cdc-sandbox/dedupe-configuration/config_schema.sql
cdc-sandbox/dedupe-configuration/docker-compose.yml

This merge would add the scripts and a docker-compose file for configuration database.
* [Jira Ticket](url): https://cdc-nbs.atlassian.net/browse/CND-120?atlOrigin=eyJpIjoiODA1MGVmOWM3OWRkNDkxNGE1ODhlYTk0YjdjOTBhMTgiLCJwIjoiaiJ9

CND-120 Add scripts for config db

---

testing/regression/cypress/e2e/features/nbs-classic/home.feature
testing/regression/cypress/e2e/features/nbs-classic/manageConditions.feature
testing/regression/cypress/e2e/features/nbs-classic/manageQuestions.feature
testing/regression/cypress/e2e/features/nbs-classic/manageTemplates.feature

Added end to end test for NBS classic filter library results on template library.
* [CNT-71](https://cdc-nbs.atlassian.net/browse/CNT-71)
[CNT-71]: https://cdc-nbs.atlassian.net/browse/CNT-71?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNT-71] - 1038 - Template Library Filter Library results page

---

apps/modernization-ui/src/apps/patient/add/extended/inputs/race/categoryValidator.spec.ts
apps/modernization-ui/src/apps/patient/add/extended/inputs/race/categoryValidator.ts

https://cdc-nbs.atlassian.net/browse/CNFT1-3362

Fix typo in categoryValidator

---

apps/modernization-ui/src/apps/patient/add/addressFields/AddressFields.tsx

Fixes a call to a possibly `undefined` value that was preventing navigation to "Add new patient"

[FIX] States are optional

---

apps/modernization-ui/src/apps/search/patient/result/table/PatientSearchResultTable.tsx

* [CNFT1-3279](https://cdc-nbs.atlassian.net/browse/CNFT1-3279)
[CNFT1-3279]: https://cdc-nbs.atlassian.net/browse/CNFT1-3279?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Legal name, and other names hidden

---

testing/regression/cypress/e2e/features/nbs-classic/manageTemplates.feature

Added end to end test for NBS classic template rule - view rule
* [CNT-72](https://cdc-nbs.atlassian.net/browse/CNT-72)
[CNT-72]: https://cdc-nbs.atlassian.net/browse/CNT-72?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNT-72] - 1039 - Template Rules View Rule

---

testing/regression/cypress/e2e/features/nbs-classic/home.feature
testing/regression/cypress/e2e/pages/nbs-classic/home.page.js
testing/regression/cypress/step_definitions/nbs-classic/home.steps.js

REPORTS (WIDGET) - RUN REPORT
* [CNT-76](https://cdc-nbs.atlassian.net/browse/CNT-76)
[CNT-76]: https://cdc-nbs.atlassian.net/browse/CNT-76?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNT-76 Run widget report

---

apps/modernization-ui/src/apps/patient/add/extended/asExtendedNewPatientEntry.ts

Bug has been fixed:
* [CNFT1-3404](https://cdc-nbs.atlassian.net/browse/CNFT1-3404)
[CNFT1-3404]: https://cdc-nbs.atlassian.net/browse/CNFT1-3404?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Extension input was not being populated

---

apps/modernization-ui/src/apps/patient/add/Race/RaceFields.tsx
apps/modernization-ui/src/apps/patient/add/contactFields/ContactFields.tsx
apps/modernization-ui/src/apps/patient/add/ethnicityFields/EthnicityFields.tsx

Fixing Home phone, Race , and Ethnicity fields adding default values and Checked properties to transfer data back from extended to basic
* [CNFT1-2998](https://cdc-nbs.atlassian.net/browse/CNFT1-2998)
[CNFT1-2998]: https://cdc-nbs.atlassian.net/browse/CNFT1-2998?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-2998]fixing fields Home-phone, Race, and Ethnicity

---

apps/modernization-ui/src/design-system/input/numeric/NumericInput.spec.tsx
apps/modernization-ui/src/design-system/input/numeric/NumericInput.tsx

Adds more strict handling of input for the `NumericInput` component.
* [CNFT1-3372](https://cdc-nbs.atlassian.net/browse/CNFT1-3372)
[CNFT1-3372]: https://cdc-nbs.atlassian.net/browse/CNFT1-3372?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-3372] More restrictions on the NumericInput component

---

testing/regression/cypress/e2e/features/nbs-classic/manageValueSets.feature
testing/regression/cypress/e2e/pages/nbs-classic/manageValueSets.page.js
testing/regression/cypress/step_definitions/nbs-classic/manageValueSets.steps.js

Added end to end test for add new local Valueset.
* [CNT-86](https://cdc-nbs.atlassian.net/browse/CNT-86)
[CNT-86]: https://cdc-nbs.atlassian.net/browse/CNT-86?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNT-86] - 1040 - Valueset Library - Add new local

---

apps/modernization-api/src/main/java/gov/cdc/nbs/patient/search/phone/PatientSearchResultDetailedPhoneFinder.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/search/phone/PatientSearchResultDetailedPhoneResolver.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/search/phone/PatientSearchResultPhone.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/search/phone/PatientSearchResultPhoneMapper.java
apps/modernization-api/src/main/resources/graphql/patient-search.graphqls
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/PatientMother.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/phone/PatientProfilePhoneSteps.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/search/PatientSearchRequester.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/search/PatientSearchVerificationSteps.java
apps/modernization-api/src/test/java/gov/cdc/nbs/support/concept/phones/PhoneSteps.java
apps/modernization-api/src/test/resources/features/patient/search/PatientSearch.feature
apps/modernization-ui/src/apps/search/patient/result/patientSearchResult.spec.tsx
apps/modernization-ui/src/generated/gql/queries/findPatientsByFilter.gql
apps/modernization-ui/src/generated/graphql/schema.ts
apps/modernization-ui/src/generated/schema.graphqls

Changes the Patient search response to return the description of phone types and uses instead of returning the code value.
A search request of 
```graphql
query patients($filter: PersonFilter!, $page: SortablePage) {
findPatientsByFilter(filter: $filter, page: $page) {
content {
shortId
phones
detailedPhones {
type
use
number
}
}
total
}
}
```
With the variables
```json
{
"filter" :{
"recordStatus": ["ACTIVE"],
"gender": "F",
"phoneNumber": "444"
}
}
```
Will result in the response
```json
{
"data": {
"findPatientsByFilter": {
"content": [
{
"shortId": 77001,
"phones": [
"404-515-1516",
"505-444-9344"
],
"detailedPhones": [
{
"type": "Cellular Phone",
"use": "Mobile Contact",
"number": "404-515-1516"
},
{
"type": "Phone",
"use": "Home",
"number": "505-444-9344"
}
]
},
{
"shortId": 100043, …
```

[CNFT1-3283] phone type descriptors

---

testing/regression/cypress/e2e/features/nbs-classic/manageValueSets.feature

Added end to end test for adding new PHIN valueset.
* [CNT-87](https://cdc-nbs.atlassian.net/browse/CNT-87)
[CNT-87]: https://cdc-nbs.atlassian.net/browse/CNT-87?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNT-87] - 1041 - Valueset Library - Add new PHIN

---

apps/modernization-ui/src/design-system/richTooltip/RichTooltip.spec.tsx

Quick addition to work done in https://cdc-nbs.atlassian.net/browse/CNFT1-3308 to test out the new RichTooltip component.
https://cdc-nbs.atlassian.net/browse/CNFT1-3424

Write behavioral unit tests for the new RichTooltip component

---

testing/regression/cypress/e2e/features/nbs-classic/manageValueSets.feature

Added end to end test for filter navigate result pages on valueset library.
* [CNT-88](https://cdc-nbs.atlassian.net/browse/CNT-88)
[CNT-88]: https://cdc-nbs.atlassian.net/browse/CNT-88?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNT-88] - 1042 - Valueset Library - Filter navigate result pages

---

apps/modernization-ui/src/design-system/chips/chip.module.scss

Patient Search Results screen - chips has match the design style in Figma
Chips icon has to be 16X16, including the margin around it
Label text has to be Sentence case
padding and font size updates
* [CNFT1-3418](https://cdc-nbs.atlassian.net/browse/CNFT1-3418)
[CNFT1-3418]: https://cdc-nbs.atlassian.net/browse/CNFT1-3418?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-3418]: adding chips style updates

---

apps/modernization-ui/src/apps/search/patient/patientTermsResolver.spec.ts
apps/modernization-ui/src/apps/search/patient/patientTermsResovler.ts
apps/modernization-ui/src/design-system/chips/Chip.tsx
apps/modernization-ui/src/design-system/chips/chip.module.scss

Update chips on Patient Search Results screen to ensure they match the sentence case requirement for its values stored in patientTermsResolver
* [CNFT1-3418](https://cdc-nbs.atlassian.net/browse/CNFT1-3418)
[CNFT1-3418]: https://cdc-nbs.atlassian.net/browse/CNFT1-3418?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-3418]: updating terms resolver and tests

---

apps/modernization-ui/src/apps/search/patient/patientTermsResolver.spec.ts
apps/modernization-ui/src/apps/search/patient/patientTermsResovler.ts
apps/modernization-ui/src/design-system/chips/chip.module.scss

Fixing fields to use caps for the chips on patient search
* [CNFT1-3418](https://cdc-nbs.atlassian.net/browse/CNFT1-3418)
[CNFT1-3418]: https://cdc-nbs.atlassian.net/browse/CNFT1-3418?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-3418]: caps for chips fields

---

testing/regression/cypress/e2e/features/nbs-classic/manageValueSets.feature

Added end to end test for expand and collapse sub sections on valueset library
* [CNT-89](https://cdc-nbs.atlassian.net/browse/CNT-89)
[CNT-89]: https://cdc-nbs.atlassian.net/browse/CNT-89?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNT-89] - 1043 - Valueset Library - Expand and collapse subsections

---

apps/modernization-ui/src/apps/search/patient/result/table/PatientSearchResultTable.tsx

Removes the other names column and makes sure that the Patient Names column is selected and first by default.
* [Jira Ticket](https://cdc-nbs.atlassian.net/browse/CNFT1-3414)

Cnft1 3414 patient search search results table is not appearing as per the design

---

testing/regression/cypress/e2e/features/nbs-classic/manageValueSets.feature

Fixed typo
* [CNT-90](https://cdc-nbs.atlassian.net/browse/CNT-90)
[CNT-90]: https://cdc-nbs.atlassian.net/browse/CNT-90?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNT-90] - 1044 Valueset Library - Fixed typo

---

apps/modernization-api/src/main/java/gov/cdc/nbs/patient/search/PatientSearchCriteriaSortResolver.java
apps/modernization-api/src/main/java/gov/cdc/nbs/search/SearchSorting.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/search/PatientSearchVerificationSteps.java
apps/modernization-api/src/test/java/gov/cdc/nbs/support/concept/names/NameSteps.java
apps/modernization-api/src/test/resources/features/patient/search/PatientSearch.name.sorting.feature
apps/modernization-api/src/test/resources/features/patient/search/PatientSearch.sorting.feature

Sorting for legal name now configured so it rollbacks on other fields to sort if some fields are the same.
* [CNFT1-3276](https://cdc-nbs.atlassian.net/browse/CNFT1-3276)
[CNFT1-3276]: https://cdc-nbs.atlassian.net/browse/CNFT1-3276?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Cnft1 3276 sorting patient name

---

apps/modernization-ui/src/design-system/Pagination/Pagination.spec.tsx
apps/modernization-ui/src/design-system/Pagination/Pagination.tsx
apps/modernization-ui/src/design-system/Pagination/pagination.module.scss

apps/modernization-ui/src/design-system/Pagination/Pagination.tsx:
```<div className={total > 0 ? styles.pagination : styles.hidden}>```
apps/modernization-ui/src/design-system/Pagination/pagination.module.scss:
```.hidden {
display: none;
}```
https://cdc-nbs.atlassian.net/browse/CNFT1-3428

There must be at least one result to show the pagination component. Otherwise the pagination is hidden.

---

apps/modernization-api/src/main/java/gov/cdc/nbs/patient/search/PatientSearchCriteriaSortResolver.java
apps/modernization-api/src/main/java/gov/cdc/nbs/search/SearchSorting.java
apps/modernization-ui/src/apps/search/patient/result/table/PatientSearchResultTable.tsx

UI connected to API for the sorting of patient name
* [CNFT1-3275](https://cdc-nbs.atlassian.net/browse/CNFT1-3275)
[CNFT1-3275]: https://cdc-nbs.atlassian.net/browse/CNFT1-3275?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UI patient name sorting

---

apps/modernization-api/src/main/java/gov/cdc/nbs/patient/search/PatientDemographicQueryResolver.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/search/PatientFilter.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/search/PatientLocationQueryResolver.java
apps/modernization-api/src/main/resources/graphql/patient-search.graphqls
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/PatientSteps.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/search/PatientSearchCriteriaSteps.java
apps/modernization-api/src/test/resources/features/patient/search/PatientSearch.street-operator.feature
apps/modernization-ui/src/generated/graphql/schema.ts
apps/modernization-ui/src/generated/schema.graphqls

* [CNFT1-3401](https://cdc-nbs.atlassian.net/browse/CNFT1-3401)
[CNFT1-3401]: https://cdc-nbs.atlassian.net/browse/CNFT1-3401?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT1-3401 API: Update API to handle Operators for Street address

---

testing/regression/cypress/e2e/features/nbs-classic/viewInvestigation.feature
testing/regression/cypress/e2e/pages/nbs-classic/openInvestigation.page.js
testing/regression/cypress/step_definitions/nbs-classic/openInvestigation.steps.js

Verify Open Investigations page links to a  View Investigation page
* [CNT-82](https://cdc-nbs.atlassian.net/browse/CNT-82)
[CNT-82]: https://cdc-nbs.atlassian.net/browse/CNT-82?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNT-82 Verify Classic Open Investigation

---

apps/modernization-api/src/main/java/gov/cdc/nbs/patient/search/PatientFilter.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/search/PatientLocationQueryResolver.java
apps/modernization-api/src/main/resources/graphql/patient-search.graphqls
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/search/PatientSearchCriteriaSteps.java
apps/modernization-api/src/test/resources/features/patient/search/PatientSearch.city-operator.feature
apps/modernization-api/src/test/resources/features/patient/search/PatientSearch.street-operator.feature
apps/modernization-ui/src/generated/graphql/schema.ts
apps/modernization-ui/src/generated/schema.graphqls

* [CNFT1-3400](https://cdc-nbs.atlassian.net/browse/CNFT1-3400)
[CNFT1-3400]: https://cdc-nbs.atlassian.net/browse/CNFT1-3400?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT1-3400 API: Update API to handle Operators for City

---

testing/regression/cypress/e2e/features/nbs-classic/manageValueSets.feature

Added end to end test for valueset search - make inactive
* [CNT-96](https://cdc-nbs.atlassian.net/browse/CNT-96)
[CNT-96]: https://cdc-nbs.atlassian.net/browse/CNT-96?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNT-96] - 1045 - Valueset search - make inactive

---

testing/regression/cypress/e2e/features/nbs-classic/editInvestigation.feature
testing/regression/cypress/e2e/pages/nbs-classic/editInvestigation.page.js
testing/regression/cypress/step_definitions/nbs-classic/editInvestigation.steps.js

Added end to end test for Edit Investigation for classic NBS
* [CNT-80](https://cdc-nbs.atlassian.net/browse/CNT-83)
[CNT-80]: https://cdc-nbs.atlassian.net/browse/CNT-80?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNT-80] - E2E - View investigation - Edit

---

testing/regression/cypress/e2e/features/nbs-classic/managePages.feature
testing/regression/cypress/e2e/pages/nbs-classic/managePages.page.js
testing/regression/cypress/step_definitions/nbs-classic/managePages.steps.js

Added end to end test for add new investigation on classic NBS.
* [CNT-97](https://cdc-nbs.atlassian.net/browse/CNT-97)
[CNT-97]: https://cdc-nbs.atlassian.net/browse/CNT-97?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNT-97] - E2E - Manage Pages - Add New Investigation

---

apps/modernization-ui/src/apps/search/patient/PatientCriteria/BasicInformation.tsx
apps/modernization-ui/src/apps/search/patient/add/asNewPatientEntry.spec.ts
apps/modernization-ui/src/apps/search/patient/add/asNewPatientEntry.ts
apps/modernization-ui/src/apps/search/patient/criteria.ts
apps/modernization-ui/src/apps/search/patient/patientTermsResolver.spec.ts
apps/modernization-ui/src/apps/search/patient/patientTermsResovler.ts
apps/modernization-ui/src/apps/search/patient/transformer.spec.ts
apps/modernization-ui/src/apps/search/patient/transformer.ts

Implement the first name as operator select/input combo.
* [Jira Ticket](https://cdc-nbs.atlassian.net/browse/CNFT1-3314)

CNFT1-3314: Implement operator select for first name

---

testing/regression/cypress/e2e/features/events.feature
testing/regression/cypress/step_definitions/nbs-classic/vaccination.steps.js

Create and delete a vaccination
* [CNT-93](https://cdc-nbs.atlassian.net/browse/CNT-93) [CNT-94](https://cdc-nbs.atlassian.net/browse/CNT-94) 
[CNT-93]: https://cdc-nbs.atlassian.net/browse/CNT-93?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CNT-94]: https://cdc-nbs.atlassian.net/browse/CNT-94?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNT-93 CNT-94 add and delete VACCINATION

---

apps/modernization-ui/src/apps/search/patient/criteria.ts
apps/modernization-ui/src/apps/search/patient/patientTermsResolver.spec.ts
apps/modernization-ui/src/apps/search/patient/patientTermsResovler.ts
apps/modernization-ui/src/apps/search/patient/transformer.spec.ts
apps/modernization-ui/src/apps/search/patient/transformer.ts

API integration and the Chips have been completed
* [CNFT1-3445](https://cdc-nbs.atlassian.net/browse/CNFT1-3445)
* [CNFT1-3346](https://cdc-nbs.atlassian.net/browse/CNFT1-3346)
[CNFT1-3445]: https://cdc-nbs.atlassian.net/browse/CNFT1-3445?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CNFT1-3346]: https://cdc-nbs.atlassian.net/browse/CNFT1-3346?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Cnft1 3445 event id UI

---

testing/regression/cypress/e2e/features/nbs-classic/managePages.feature

Added end to end test case for add new contact record on manage pages.
* [CNT-99](https://cdc-nbs.atlassian.net/browse/CNT-99)
[CNT-99]: https://cdc-nbs.atlassian.net/browse/CNT-99?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNT-99] - 1048 - Manage Pages - Add New Contact Record

---

testing/regression/cypress/e2e/features/nbs-classic/managePages.feature

Added end to end test case for page details on manage pages.
* [CNT-100](https://cdc-nbs.atlassian.net/browse/CNT-100)
[CNT-100]: https://cdc-nbs.atlassian.net/browse/CNT-100?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNT-100] - 1049 - Manage Pages - Page Details

---

apps/modernization-api/src/main/java/gov/cdc/nbs/patient/search/PatientSearchCriteriaFilterResolver.java
apps/modernization-api/src/test/resources/features/patient/search/PatientSearch.born-on.feature

* [CNFT1-3548](https://cdc-nbs.atlassian.net/browse/CNFT1-3548)
[CNFT1-3548]: https://cdc-nbs.atlassian.net/browse/CNFT1-3548?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fixed bug where no born on date in db causes search api error

---

apps/modernization-ui/src/apps/search/patient/result/patientSearchResult.tsx
apps/modernization-ui/src/apps/search/patient/result/table/PatientSearchResultTable.tsx

- create displayPatientAge function in apps/modernization-ui/src/apps/search/patient/result/patientSearchResult.tsx
- uses previously utilized internalizeDate function as well as adding a line break and the displayAgeAsOfToday value to match figma design
- renames Date of Birth column to 'DOB/Age' to match figma design 
https://cdc-nbs.atlassian.net/browse/CNFT1-3018

Cnft1 3018 UI update search results table view to display details of page age

---

apps/modernization-ui/src/apps/patient/add/extended/inputs/race/RaceRepeatingBlock.tsx
apps/modernization-ui/src/apps/patient/data/race/RaceEntryFields.spec.tsx
apps/modernization-ui/src/apps/patient/data/race/RaceEntryFields.tsx

As a user, I want Detailed race data reset, every time Race value changes.
* [CNFT1-3453](https://cdc-nbs.atlassian.net/browse/CNFT1-3453)
[CNFT1-3453]: https://cdc-nbs.atlassian.net/browse/CNFT1-3453?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Detailed Race Bug

---

testing/regression/cypress/e2e/features/nbs-classic/home.feature
testing/regression/cypress/e2e/pages/nbs-classic/home.page.js

Fixed end to end failed report test cases.
* [CNT-100](https://cdc-nbs.atlassian.net/browse/CNT-100)
[CNT-100]: https://cdc-nbs.atlassian.net/browse/CNT-100?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNT-100] - Fix Report Failures

---

apps/modernization-ui/src/design-system/date/criteria/DateCriteriaEntry.spec.tsx
apps/modernization-ui/src/design-system/date/criteria/DateCriteriaEntry.tsx
apps/modernization-ui/src/design-system/date/criteria/DateEntryCriteria.tsx
apps/modernization-ui/src/design-system/date/criteria/date-range/DateRangeEntry.spec.tsx
apps/modernization-ui/src/design-system/date/criteria/date-range/DateRangeEntry.tsx
apps/modernization-ui/src/design-system/date/criteria/date-range/date-range-entry.module.scss
apps/modernization-ui/src/design-system/date/criteria/exact-date/ExactDateEntry.tsx
apps/modernization-ui/src/design-system/date/criteria/useDateBetweenCriteria.tsx
apps/modernization-ui/src/design-system/date/criteria/validateDateCriteria.ts
apps/modernization-ui/src/design-system/date/picker/DatePicker.tsx
apps/modernization-ui/src/design-system/date/validateDateRange.ts

Date Range Entry Component for the date criteria between search
* [CNFT1-3433](https://cdc-nbs.atlassian.net/browse/CNFT1-3433)
[CNFT1-3433]: https://cdc-nbs.atlassian.net/browse/CNFT1-3433?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Cnft1 3433 date range between search

---

testing/regression/cypress/e2e/features/nbs-classic/managePages.feature
testing/regression/cypress/e2e/pages/nbs-classic/managePages.page.js
testing/regression/cypress/e2e/pages/nbs-classic/manageValueSets.page.js
testing/regression/cypress/step_definitions/nbs-classic/managePages.steps.js

Added end to end test for View Tab on Classic NBS
* [CNT-104](https://cdc-nbs.atlassian.net/browse/CNT-104)
[CNT-104]: https://cdc-nbs.atlassian.net/browse/CNT-104?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNT-104] - 1055 - View Tab e2e

---

testing/regression/cypress/e2e/features/nbs-classic/managePages.feature

Added end to end test for Clone Page on Classic NBS
* [CNT-105](https://cdc-nbs.atlassian.net/browse/CNT-105)
[CNT-105]: https://cdc-nbs.atlassian.net/browse/CNT-105?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNT-105] - 1056 - Clone Page E2E

---

apps/modernization-api/src/main/java/gov/cdc/nbs/patient/search/PatientDemographicQueryResolver.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/search/PatientSearchCriteriaSteps.java
apps/modernization-api/src/test/resources/features/patient/search/PatientSearch.feature

Switch to terms query
* [CNFT1-3556](https://cdc-nbs.atlassian.net/browse/CNFT1-3556)
[CNFT1-3556]: https://cdc-nbs.atlassian.net/browse/CNFT1-3556?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT1-3556 API: Update Patient ID API to accept multiple values with delimiter comma, space and semicolon

---

apps/modernization-ui/src/apps/patient/add/addressFields/AddressFields.tsx

utilize the AddPatientExtendedForm address zip code validations in the normal New patient (not extended) creation form.
* [Jira Ticket](https://cdc-nbs.atlassian.net/browse/CNFT1-3563)

bring /add/addressFields/AddressFields.tsx in line with /data/address/AddressEntryFields.tsx validations

---

apps/modernization-ui/src/apps/patient/add/AddPatient.tsx

Save button enter key submissions removed, by changing the type of button from submit to button
* [CNFT1-3332](https://cdc-nbs.atlassian.net/browse/CNFT1-3332)
[CNFT1-3332]: https://cdc-nbs.atlassian.net/browse/CNFT1-3332?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Save button, enter key submission removed

---

apps/modernization-api/src/main/java/gov/cdc/nbs/patient/search/PatientDemographicQueryResolver.java

Moved the `applyLocalIds()` call outside the loop. This is inline with the Elasticsearch query for query/terms.
* [Jira Ticket](https://cdc-nbs.atlassian.net/browse/CNFT1-3578)

CNFT1-3578: Fix patient ID search returns all patients

---

apps/modernization-ui/src/apps/patient/add/addressFields/AddressFields.tsx
apps/modernization-ui/src/apps/patient/data/address/AddressEntryFields.spec.tsx
apps/modernization-ui/src/apps/patient/data/address/AddressEntryFields.tsx
apps/modernization-ui/src/apps/patient/profile/addresses/AddressEntryFields.tsx
apps/modernization-ui/src/apps/search/patient/PatientCriteria/Address.tsx

Change Please enter a valid ZIP code (XXXXX) using only numeric characters (0-9). to Please enter a valid ZIP code (XXXXX or XXXXX-XXXX ) using only numeric characters (0-9).

Cnft1 3563 UI new patient address zip add character limit

---

apps/modernization-ui/src/apps/patient/add/contactFields/ContactFields.tsx

Add button taken out as well as the placeholder
* [CNFT1-3561](https://cdc-nbs.atlassian.net/browse/CNFT1-3561)
[CNFT1-3561]: https://cdc-nbs.atlassian.net/browse/CNFT1-3561?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

phone changes completed

---

apps/modernization-ui/src/apps/patient/add/AddPatient.tsx
apps/modernization-ui/src/apps/patient/add/PatientAddRouting.tsx

Cancel button has been added 
* [CNFT1-3393](https://cdc-nbs.atlassian.net/browse/CNFT1-3393)
[CNFT1-3393]: https://cdc-nbs.atlassian.net/browse/CNFT1-3393?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

cancel button added

---

apps/modernization-ui/src/design-system/input/numeric/Numeric.tsx
apps/modernization-ui/src/design-system/input/numeric/useNumeric.spec.ts
apps/modernization-ui/src/design-system/input/numeric/useNumeric.ts

Clear all fix using reducer in Numeric.tsx to fix clearing input from exact date component.
* [CNFT1-3582](https://cdc-nbs.atlassian.net/browse/CNFT1-3582)
[CNFT1-3582]: https://cdc-nbs.atlassian.net/browse/CNFT1-3582?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-3582-clear-all-exact-date-input-fix]

---

apps/modernization-api/src/main/java/gov/cdc/nbs/codes/CodedValues.java
apps/modernization-api/src/main/java/gov/cdc/nbs/codes/GeneralCodedValueResolver.java

Format as "GED" but continue formatting other strings using standardized format.
* [Jira Ticket](https://cdc-nbs.atlassian.net/browse/CNFT1-3534)

CNFT1-3534: Special string handling for education values

---

apps/modernization-ui/src/apps/patient/add/contactFields/ContactFields.tsx

Added back in the email input field
* [CNFT1-3561](https://cdc-nbs.atlassian.net/browse/CNFT1-3561)
[CNFT1-3561]: https://cdc-nbs.atlassian.net/browse/CNFT1-3561?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Phone basic section bug

---

apps/modernization-ui/src/apps/patient/data/sexAndBirth/SexAndBirthEntryFields.tsx

adding rule for 20 char max for additional gender in sex and birth section within patient extended form add-
* [CNFT1-3531](https://cdc-nbs.atlassian.net/browse/CNFT1-3531)
[CNFT1-3531]: https://cdc-nbs.atlassian.net/browse/CNFT1-3531?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-3531-additional-gender-char-limit-rule]: adding rule for 20 char max for additional gender

---

apps/modernization-ui/src/design-system/date/criteria/exact-date/ExactDateEntry.tsx

adding check for undefined values handleChange function
* [CNFT1-3582](https://cdc-nbs.atlassian.net/browse/CNFT1-3582)
[CNFT1-3582]: https://cdc-nbs.atlassian.net/browse/CNFT1-3582?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-3582-clear-all-0-input-fix] 

---

apps/modernization-ui/src/apps/patient/add/extended/inputs/race/RaceRepeatingBlock.tsx
apps/modernization-ui/src/options/race/useRaceCategoryOptions.ts

adding multi race value to race repeating block
* [CNFT1-3441](https://cdc-nbs.atlassian.net/browse/CNFT1-3441)
[CNFT1-3441]: https://cdc-nbs.atlassian.net/browse/CNFT1-3441?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-3441-adding-multi-race-value-extended-race]

---

apps/modernization-ui/src/apps/patient/add/contactFields/ContactFields.tsx
apps/modernization-ui/src/apps/patient/data/phoneEmail/PhoneEmailEntryFields.tsx

User should be allowed to enter any value within 20 characters. Short form and extended form. 
* [Jira Ticket](https://cdc-nbs.atlassian.net/jira/software/c/projects/CNFT1/boards/112?selectedIssue=CNFT1-3524)

Cnft1 3524 UI new patient extended phone email extension character limit

---

libs/options-api/src/main/java/gov/cdc/nbs/option/counties/autocomplete/CountyOptionAutocompleteController.java
libs/options-api/src/main/java/gov/cdc/nbs/option/counties/autocomplete/CountyOptionResolver.java
libs/options-api/src/main/java/gov/cdc/nbs/option/jdbc/autocomplete/SQLBasedOptionResolver.java
libs/options-api/src/test/java/gov/cdc/nbs/option/AutocompleteRequester.java
libs/options-api/src/test/java/gov/cdc/nbs/option/county/CountyMother.java
libs/options-api/src/test/java/gov/cdc/nbs/option/county/CountyOptionSteps.java
libs/options-api/src/test/java/gov/cdc/nbs/option/county/CountyStateParameterResolver.java
libs/options-api/src/test/java/gov/cdc/nbs/option/county/autocomplete/CountyAutocompleteSteps.java
libs/options-api/src/test/resources/features/counties/CountiesOptions.feature

Endpoint:
`/nbs/api/options/counties/{state}/search`
Params:
`criteria`
`limit`
* [CNFT1-3498](https://cdc-nbs.atlassian.net/browse/CNFT1-3498)
[CNFT1-3498]: https://cdc-nbs.atlassian.net/browse/CNFT1-3498?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT1-3498 API: Create Type ahead function for County

---

apps/modernization-ui/src/apps/patient/add/otherInfoFields/OtherInfoFields.tsx
apps/modernization-ui/src/components/Entry/vertical-entry-wrapper.module.scss
apps/modernization-ui/src/design-system/input/operator/OperatorInput.tsx
apps/modernization-ui/src/design-system/input/operator/operator.module.scss

Minor fixes to other information section. Current age already fixed in a prior PR. Fix text and styling.
* [Jira Ticket](https://cdc-nbs.atlassian.net/browse/CNFT1-3305)

CNFT1-3305: Fix operator select styling and text issues

---

apps/modernization-ui/.eslintrc.json
apps/modernization-ui/src/apps/patient/add/AddPatient.spec.tsx
apps/modernization-ui/src/apps/patient/add/AddPatient.tsx
apps/modernization-ui/src/apps/patient/add/PatientAddRouting.tsx
apps/modernization-ui/src/apps/patient/add/extended/AddPatientExtended.spec.tsx
apps/modernization-ui/src/apps/patient/add/useBasicExtendedTransition/useBasicExtendedTransition.tsx
apps/modernization-ui/src/apps/patient/add/usePreFilled.ts
apps/modernization-ui/src/apps/search/patient/PatientCriteria/useSearchFromAddPatient.tsx
apps/modernization-ui/src/apps/search/patient/PatientSearchActions.tsx
apps/modernization-ui/src/apps/search/patient/add/useAddPatientFromSearch.ts
apps/modernization-ui/src/apps/search/patient/add/useSearchFromAddPatient.spec.tsx
apps/modernization-ui/src/apps/search/patient/add/useSearchFromAddPatient.tsx
apps/modernization-ui/src/apps/search/patient/result/none/NoPatientResults.tsx
apps/modernization-ui/src/apps/search/useSearchCriteria.ts
apps/modernization-ui/src/apps/search/useSearchCriteriaEncrypted.tsx

Cancel button now navigates back saving the search results when they click add patient
* [CNFT1-3580](https://cdc-nbs.atlassian.net/browse/CNFT1-3580)
[CNFT1-3580]: https://cdc-nbs.atlassian.net/browse/CNFT1-3580?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Cnft1 3580 bug cancel button

---

testing/regression/cypress/e2e/features/nbs-classic/managePages.feature
testing/regression/cypress/e2e/pages/nbs-classic/home.page.js
testing/regression/cypress/e2e/pages/nbs-classic/managePages.page.js
testing/regression/cypress/step_definitions/nbs-classic/managePages.steps.js

Added end to end test for add / import elements on page builder classic pages.
* [CNT-115](https://cdc-nbs.atlassian.net/browse/CNT-115)
[CNT-115]: https://cdc-nbs.atlassian.net/browse/CNT-115?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNT-115] - 1063 - Add import element E2E

---

cdc-sandbox/nbs6-win-container/Dockerfile
cdc-sandbox/nbs6-win-container/README.md
cdc-sandbox/nbs6-win-container/entrypoint.ps1
cdc-sandbox/nbs6-win-container/task-scheduler.ps1
cdc-sandbox/nbs6-win-container/tasks.csv

Adding the ability to schedule additional NBS6 tasks via csv. Tasks are all enabled by default but may be disabled through an environment variable.

Sgz nbs6 updates

---

apps/nbs-gateway/build.gradle
apps/question-bank/build.gradle
apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/pagerules/PageRuleCreator.java
apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/condition/create/CreateConditionSteps.java
apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/condition/read/ReadConditionSteps.java
apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/page/DeleteQuestionFromPageSteps.java
apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/page/content/question/UpdatePageCodedQuestionSteps.java
apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/page/content/question/UpdatePageCodedQuestionValuesetSteps.java
apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/page/content/question/UpdatePageDateQuestionSteps.java
apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/page/content/question/UpdatePageNumericQuestionSteps.java
apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/page/content/question/UpdatePageTextQuestionSteps.java
apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/page/content/reorder/ReorderSteps.java
apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/page/content/section/CreateSectionSteps.java
apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/page/content/section/DeleteSectionSteps.java
apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/page/content/section/UpdateSectionSteps.java
apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/page/content/subsection/CreateSubsectionSteps.java
apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/page/content/subsection/DeleteSubsectionSteps.java
apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/page/content/subsection/UnGroupSubsectionSteps.java
apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/page/content/subsection/UpdateSubsectionSteps.java
apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/page/content/tab/UpdateTabSteps.java
apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/page/state/PageStateChangeSteps.java
apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/programarea/ProgramAreaFinderSteps.java
apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/question/DisplayControlOptionsSteps.java
apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/question/QuestionSearchSteps.java
apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/question/SetQuestionStatusSteps.java
apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/question/UpdateQuestionSteps.java
apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/question/ValidateQuestionSteps.java
apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/support/QuestionMother.java
apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/support/UserMother.java
gradle/libs.versions.toml

Resolves the bugs and code smells that were reported from test classes based on rule changes that went into effect on 12/4.

Resolves SonarQube issues from 12/4

---

apps/modernization-ui/src/apps/patient/add/basic/AddPatientBasicForm.tsx
apps/modernization-ui/src/apps/patient/add/extended/AddPatientExtendedForm.spec.tsx
apps/modernization-ui/src/apps/patient/data/administrative/AdministrativeEntryFields.spec.tsx
apps/modernization-ui/src/apps/patient/data/administrative/AdministrativeEntryFields.tsx

* [CNFT1-3303](https://cdc-nbs.atlassian.net/browse/CNFT1-3303)
[CNFT1-3303]: https://cdc-nbs.atlassian.net/browse/CNFT1-3303?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

cnft1-3303-general-information-basic

---

apps/modernization-ui/src/apps/patient/add/basic/AddPatientBasicForm.tsx
apps/modernization-ui/src/apps/patient/add/basic/identification/BasicIdentificationFields.spec.tsx
apps/modernization-ui/src/apps/patient/add/basic/identification/BasicIdentificationFields.tsx
apps/modernization-ui/src/apps/patient/add/basic/identification/BasicIdentificationRepeatingBlock.spec.tsx
apps/modernization-ui/src/apps/patient/add/basic/identification/BasicIdentificationRepeatingBlock.tsx
apps/modernization-ui/src/apps/patient/add/basic/identification/BasicIdentificationView.spec.tsx
apps/modernization-ui/src/apps/patient/add/basic/identification/BasicIdentificationView.tsx
apps/modernization-ui/src/apps/patient/add/basic/identification/index.ts

Added the component for the Identification section for the new basic add patient form.
* [Jira Ticket](https://cdc-nbs.atlassian.net/browse/CNFT1-3392)

CNFT1-3392: Identification section for basic patient form

---

libs/options-api/src/main/java/gov/cdc/nbs/option/states/autocomplete/StateOptionAutocompleteController.java
libs/options-api/src/main/java/gov/cdc/nbs/option/states/autocomplete/StateOptionResolver.java
libs/options-api/src/test/java/gov/cdc/nbs/option/county/CountyStateParameterResolver.java
libs/options-api/src/test/java/gov/cdc/nbs/option/state/autocomplete/StateAutocompleteSteps.java
libs/options-api/src/test/resources/features/states/StatesOptions.feature

Endpoint:
`/nbs/api/options/states/search`
Params:
`criteria`
`limit`
* [CNFT1-3497](https://cdc-nbs.atlassian.net/browse/CNFT1-3497)
[CNFT1-3497]: https://cdc-nbs.atlassian.net/browse/CNFT1-3497?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

3497 - API: Create Type ahead function for State

---

apps/modernization-ui/src/apps/patient/add/basic/AddPatientBasicForm.tsx
apps/modernization-ui/src/apps/patient/add/basic/sections.ts

* [CNFT1-3303](https://cdc-nbs.atlassian.net/browse/CNFT1-3303)
[CNFT1-3303]: https://cdc-nbs.atlassian.net/browse/CNFT1-3303?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

general information section name is changed

---

apps/modernization-ui/src/apps/patient/add/NewPatientEntry.ts
apps/modernization-ui/src/apps/patient/add/otherInfoFields/OtherInfoFields.tsx

Adds Date validation to "Date of birth" in "New patient".
* [CNFT1-3396](https://cdc-nbs.atlassian.net/browse/CNFT1-3396)
[CNFT1-3396]: https://cdc-nbs.atlassian.net/browse/CNFT1-3396?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-3396] adds validation to Date of birth

---

apps/modernization-ui/src/apps/patient/add/otherInfoFields/OtherInfoFields.tsx
apps/modernization-ui/src/apps/patient/data/general/GeneralInformationEntryFields.tsx

Update character limit to 16 for State HIV case ID in New patient- Extended and Patient profile.
* [Jira Ticket](https://cdc-nbs.atlassian.net/browse/CNFT1-3535)

Cnft1 3535 UI new patient extended general patient information state hiv case id character limit

---

libs/options-api/src/main/java/gov/cdc/nbs/option/countries/autocomplete/CountryOptionAutocompleteController.java
libs/options-api/src/main/java/gov/cdc/nbs/option/countries/autocomplete/CountryOptionResolver.java
libs/options-api/src/test/java/gov/cdc/nbs/option/country/autocomplete/CountryAutocompleteSteps.java
libs/options-api/src/test/resources/features/countries/CountryOptions.feature

Endpoint:
`/nbs/api/options/countries/search`
Params:
`criteria`
`limit`
* [CNFT1-3375](https://cdc-nbs.atlassian.net/browse/CNFT1-3375)
[CNFT1-3375]: https://cdc-nbs.atlassian.net/browse/CNFT1-3375?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT1-3375 API: Create Type ahead function for Country

---

apps/modernization-ui/src/apps/patient/add/basic/sections.ts

Fix the right side bar for personal details section.
* [Jira Ticket](https://cdc-nbs.atlassian.net/browse/CNFT1-3305)

CNFT1-3305: Fix basic form section name and href for personal details

---

apps/modernization-ui/src/apps/patient/add/basic/AddPatientBasicForm.tsx
apps/modernization-ui/src/apps/patient/add/basic/sections.ts

Fixing name issue with Ethnicity and race to Ethnicity & race
* [CNFT1-3321](https://cdc-nbs.atlassian.net/browse/CNFT1-3321)
[CNFT1-3321]: https://cdc-nbs.atlassian.net/browse/CNFT1-3321?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-3321]-ethnicity-race-name-fix

---

apps/modernization-ui/src/apps/patient/add/PatientAddRouting.tsx
apps/modernization-ui/src/apps/patient/add/basic/AddPatientBasic.tsx
apps/modernization-ui/src/apps/patient/add/basic/name/NameEntryFields.tsx
apps/modernization-ui/src/apps/patient/add/basic/personalDetails/BasicPersonalDetailsFields.tsx
apps/modernization-ui/src/apps/patient/add/basic/phoneEmail/BasicPhoneEmailFields.tsx
apps/modernization-ui/src/apps/patient/add/basic/raceEthnicity/BasicEthnicityRaceFields.tsx

Save button integration for the new /patient/add form which correctly adds the patient transferring the data and displaying the success modal
* [CNFT1-3588](https://cdc-nbs.atlassian.net/browse/CNFT1-3588)
[CNFT1-3588]: https://cdc-nbs.atlassian.net/browse/CNFT1-3588?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Cnft1 3588 save button integration

---

apps/modernization-ui/src/apps/search/patient/result/table/PatientSearchResultTable.tsx
apps/modernization-ui/src/apps/search/patient/result/table/patient-search-result-table.module.scss

Make links bold in patient results table.
* [Jira Ticket](https://cdc-nbs.atlassian.net/browse/CNFT1-3607)

CNFT1-3607: Add style for links in patient search table

---

apps/modernization-ui/src/apps/patient/add/DataEntryMenu.spec.tsx
apps/modernization-ui/src/apps/patient/add/DataEntryMenu.tsx

Data entry menu name updates for extended and add patient forms
* [CNFT1-3619](https://cdc-nbs.atlassian.net/browse/CNFT1-3619)
[CNFT1-3619]: https://cdc-nbs.atlassian.net/browse/CNFT1-3619?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

renaming data entry menu labels

---

apps/modernization-ui/src/address/suggestion/AddressSuggestionInput.tsx
apps/modernization-ui/src/apps/patient/add/basic/AddPatientBasic.tsx
apps/modernization-ui/src/apps/patient/add/basic/AddPatientBasicForm.tsx
apps/modernization-ui/src/apps/patient/add/basic/address/BasicAddressFields.spec.tsx
apps/modernization-ui/src/apps/patient/add/basic/address/BasicAddressFields.tsx
apps/modernization-ui/src/apps/patient/add/basic/entry.ts
apps/modernization-ui/src/apps/patient/add/basic/personalDetails/BasicPersonalDetailsFields.tsx
apps/modernization-ui/src/apps/patient/add/basic/phoneEmail/BasicPhoneEmailFields.tsx

Address section completed, with default value for country
* [CNFT1-3388](https://cdc-nbs.atlassian.net/browse/CNFT1-3388)
[CNFT1-3388]: https://cdc-nbs.atlassian.net/browse/CNFT1-3388?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Address section basic

---

apps/modernization-ui/src/apps/search/patient/add/useAddPatientFromSearch.ts

Routing to patient/add when user clicks on add patient 
* [CNFT1-3490](https://cdc-nbs.atlassian.net/browse/CNFT1-3490)
[CNFT1-3490]: https://cdc-nbs.atlassian.net/browse/CNFT1-3490?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-3490]: routing to patient/add

---

apps/modernization-ui/src/apps/patient/add/basic/AddPatientBasicForm.tsx
apps/modernization-ui/src/apps/patient/add/basic/sections.ts
apps/modernization-ui/src/apps/patient/add/layout/add-layout.module.scss

adding min width for right side menu to fix wrapping of text and fixing ids nav section
Result:
Fixed Address section click issue and labels wrapping of text to match design
Design: 
* [CNFT1-3600](https://cdc-nbs.atlassian.net/browse/CNFT1-3600)
[CNFT1-3600]: https://cdc-nbs.atlassian.net/browse/CNFT1-3600?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

 [CNFT1-3600]adding min width for right side menu to fix wrapping of text and fixing ids navsection

---

cdc-sandbox/nbs6-win-container/Dockerfile

Adding sqlcmd to nbs6 container

add sqlcmd

---

testing/regression/cypress/e2e/features/nbs-classic/organization.feature
testing/regression/cypress/e2e/features/nbs-classic/patient.feature
testing/regression/cypress/e2e/pages/nbs-classic/organization.page.js
testing/regression/cypress/e2e/pages/nbs-classic/patient.page.js
testing/regression/cypress/step_definitions/nbs-classic/organization.steps.js
testing/regression/cypress/step_definitions/nbs-classic/patient.steps.js

Added end to end tests for search patient, edit patient and find organization on Dedupe
* [CNT-116](https://cdc-nbs.atlassian.net/browse/CNT-116)
* [CNT-117](https://cdc-nbs.atlassian.net/browse/CNT-117)
* [CNT-118](https://cdc-nbs.atlassian.net/browse/CNT-118)
[CNT-116]: https://cdc-nbs.atlassian.net/browse/CNT-116?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CNT-117]: https://cdc-nbs.atlassian.net/browse/CNT-117?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CNT-118]: https://cdc-nbs.atlassian.net/browse/CNT-118?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNT-116] [CNT-117] [CNT-118] - E2E - Dedupe - Search Patient,  Edit Patient and Find Organization 

---

testing/regression/cypress/e2e/features/nbs-classic/organization.feature
testing/regression/cypress/e2e/features/nbs-classic/provider.feature
testing/regression/cypress/e2e/pages/nbs-classic/organization.page.js
testing/regression/cypress/e2e/pages/nbs-classic/provider.page.js
testing/regression/cypress/step_definitions/nbs-classic/organization.steps.js
testing/regression/cypress/step_definitions/nbs-classic/provider.steps.js

Added end to end tests for dedupe - Add Organization and Add Provider
* [CNT-119](https://cdc-nbs.atlassian.net/browse/CNT-119)
* [CNT-120](https://cdc-nbs.atlassian.net/browse/CNT-120)
[CNT-119]: https://cdc-nbs.atlassian.net/browse/CNT-119?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CNT-120]: https://cdc-nbs.atlassian.net/browse/CNT-120?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNT-119 CNT-120 Dedupe Add Organization and Add Provider

---

apps/modernization-ui/src/apps/patient/add/DataEntryMenu.spec.tsx
apps/modernization-ui/src/apps/patient/add/DataEntryMenu.tsx

Data entry menu: Letters O and P for Organization and Provider should display in lowercase
* [CNFT1-3654](https://cdc-nbs.atlassian.net/browse/CNFT1-3654)
[CNFT1-3654]: https://cdc-nbs.atlassian.net/browse/CNFT1-3654?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-3654]:renaming data entry menu labels

---

apps/modernization-ui/src/apps/patient/add/basic/AddPatientBasic.tsx
apps/modernization-ui/src/apps/patient/add/basic/asNewExtendedPatientEntry.spec.ts
apps/modernization-ui/src/apps/patient/add/basic/asNewExtendedPatientEntry.ts
apps/modernization-ui/src/apps/patient/add/useBasicExtendedTransition/useBasicExtendedTransition.spec.tsx
apps/modernization-ui/src/apps/patient/add/useBasicExtendedTransition/useBasicExtendedTransition.tsx

New transition for the new basic form added in the same hook used in the old basic form.
* [CNFT1-3409](https://cdc-nbs.atlassian.net/browse/CNFT1-3409)
[CNFT1-3409]: https://cdc-nbs.atlassian.net/browse/CNFT1-3409?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Cnft1 3409 extended data

---

apps/modernization-ui/src/apps/patient/add/extended/add-patient-extended.module.scss
apps/modernization-ui/src/design-system/entry/multi-value/RepeatingBlock.module.scss

a) Ensure that a scroll bar is visible to the user when the window is small enough on the new patient form extended to prevent the nav menu from being cut off.
b) Ensure that the scroll bar is not shown on table entries for the repeating block since all fields in the table are set to wrap.
* https://cdc-nbs.atlassian.net/browse/CNFT1-3618
* https://cdc-nbs.atlassian.net/browse/CNFT1-3615

Cnft1 3618 UI new patient extended no horizontal scroll bar for the form

---

testing/regression/cypress/e2e/features/nbs-classic/place.feature
testing/regression/cypress/e2e/pages/nbs-classic/place.page.js
testing/regression/cypress/step_definitions/nbs-classic/place.steps.js

Search Place 
* [CNT-122](https://cdc-nbs.atlassian.net/browse/CNT-122)
[CNT-122]: https://cdc-nbs.atlassian.net/browse/CNT-122?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNT-122 find place through search

---

apps/modernization-ui/src/design-system/table/DataTableRow.tsx

…tespace
* [Jira Ticket](https://cdc-nbs.atlassian.net/browse/CNFT1-3622)

change the NoData display in DataTableRow to be dashes instead of whitespace

---

apps/modernization-ui/src/apps/patient/data/administrative/AdministrativeEntryFields.spec.tsx
apps/modernization-ui/src/apps/patient/data/administrative/AdministrativeEntryFields.tsx

Rename "General comments" to "Comments" in Administrative section.

CNFT1-3670: Rename General comments to Comments

---

apps/modernization-ui/src/apps/patient/add/extended/AddPatientExtended.tsx

Routing updated for cancel button in extended form to go to the new basic form
* [CNFT1-3669](https://cdc-nbs.atlassian.net/browse/CNFT1-3669)
[CNFT1-3669]: https://cdc-nbs.atlassian.net/browse/CNFT1-3669?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

routing changed to new basic from extended form

---

testing/regression/cypress/e2e/features/nbs-classic/place.feature
testing/regression/cypress/e2e/pages/nbs-classic/home.page.js
testing/regression/cypress/e2e/pages/page-library/searchAndFilter.page.js

Fixed reports failures
* [CNT-120](https://cdc-nbs.atlassian.net/browse/CNT-120)
[CNT-120]: https://cdc-nbs.atlassian.net/browse/CNT-120?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNT-120] - Fix report failure

---

testing/regression/cypress/e2e/pages/add-patient.page.js
testing/regression/cypress/e2e/pages/search.page.js
testing/regression/cypress/e2e/pages/summaryTab.page.js
testing/regression/cypress/step_definitions/search.steps.js

Fixed tests for Profiles, Search, Events, and Patients

Fixed regression tests for patient, search, and profile

---

apps/modernization-api/src/main/java/gov/cdc/nbs/patient/search/PatientDemographicQueryResolver.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/search/PatientFilter.java
apps/modernization-api/src/main/resources/graphql/patient-search.graphqls
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/PatientSteps.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/search/PatientSearchCriteriaSteps.java
apps/modernization-api/src/test/resources/features/patient/search/PatientSearch.born-on.feature
apps/modernization-ui/src/generated/graphql/schema.ts
apps/modernization-ui/src/generated/schema.graphqls

Write a painless script to query the born on date values.  Switch the native format to MM-DD-YYYY. Do a contains search replacing any slash in the query with dash (and dashes come along for free).  If we detect that the filter has dashes or slashes just do that dob/script query search (it can't be an age search).  If it can be an age filter do a `should` on both the script query for dob and a range query on age.
* [CNFT1-3466](https://cdc-nbs.atlassian.net/browse/CNFT1-3466)
[CNFT1-3466]: https://cdc-nbs.atlassian.net/browse/CNFT1-3466?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT1-3466 Search API: Add filters for DOB/ Age

---

cdc-sandbox/nbs6-win-container/Dockerfile
cdc-sandbox/nbs6-win-container/entrypoint.ps1
cdc-sandbox/nbs6-win-container/tasks.csv

Adjusted default scheduled tasks to all be on unless otherwise turned off and excluded null interaction with variable. Added covidetl as a new scheduled task.

adjust scheduled tasks

---

apps/modernization-ui/src/apps/deduplication/match-configuration/model/Matching.ts

Adds `Exact match` option to deduplication config screen.
N/A

Add exact match option

---

testing/regression/cypress/e2e/features/nbs-classic/patient.feature
testing/regression/cypress/e2e/pages/nbs-classic/patient.page.js
testing/regression/cypress/step_definitions/nbs-classic/patient.steps.js

Added end to end test for new patient with valid information as of date scenario.
* [CNT-125](https://cdc-nbs.atlassian.net/browse/CNT-125)
[CNT-125]: https://cdc-nbs.atlassian.net/browse/CNT-125?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNT-125] - E2E - Valid information as of date

---

testing/regression/cypress/e2e/features/basic-info.feature
testing/regression/cypress/e2e/pages/search.page.js
testing/regression/cypress/step_definitions/hl7/generate-elr.steps.js
testing/regression/cypress/step_definitions/hl7/generate-mark-reviewed.steps.js
testing/regression/cypress/step_definitions/hl7/submit-notification.steps.js
testing/regression/cypress/step_definitions/search.steps.js

Fixes for DOB and basic search. Fixes for ELR response body being an array.

Basic Search regression fixes and fixes for ELR backend

---

testing/regression/cypress/e2e/pages/search.page.js
testing/regression/cypress/e2e/pages/searchEvent.page.js

Fixed for changes made in Feature PR https://github.com/CDCgov/NEDSS-Modernization/pull/2177

Fix for change in search Filter Results

---

apps/modernization-ui/src/apps/search/layout/result/header/options/table/SearchResultsTableOptions.tsx
apps/modernization-ui/src/apps/search/layout/result/header/options/table/search-results-table-options.module.scss
apps/modernization-ui/src/design-system/filter/useFilter.tsx

-Fixing color of button when active 
-Fixing x icon close and reset/sort buttons to only clear text in input on click instead of removing the filter
* [CNFT1-3298](https://cdc-nbs.atlassian.net/browse/CNFT1-3298)
[CNFT1-3298]: https://cdc-nbs.atlassian.net/browse/CNFT1-3298?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-3298]fixing issues with the filter button and clear all enhancements

---

testing/regression/cypress/e2e/features/patient-extended-form/patient.feature
testing/regression/cypress/e2e/pages/patient-extended-form/patient.page.js
testing/regression/cypress/step_definitions/patient-extended-form/patient.steps.js

Added end to end test for Comments Text Field Accepts Text Up to 2000 Characters.
* [CNT-127](https://cdc-nbs.atlassian.net/browse/CNT-127)
[CNT-127]: https://cdc-nbs.atlassian.net/browse/CNT-127?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNT-127] - Comments Text Field Accepts Text Up to 2000 Characters

---

testing/regression/cypress/e2e/features/patient-extended-form/patient.feature
testing/regression/cypress/e2e/pages/patient-extended-form/patient.page.js
testing/regression/cypress/step_definitions/patient-extended-form/patient.steps.js

Optional and invalid Comments for New Patient Extended Form
* [CNQAT-511 CNQAT-510](https://cdc-nbs.atlassian.net/browse/CNQAT-510)(https://cdc-nbs.atlassian.net/browse/CNQAT-511)

CNQAT-510 CNQAT-511 Optional and invalid Comments for New Patient Extended Form

---

apps/modernization-api/src/main/java/gov/cdc/nbs/patient/search/PatientDemographicQueryResolver.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/search/PatientFilter.java
apps/modernization-api/src/main/resources/graphql/patient-search.graphqls
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/search/PatientSearchCriteriaSteps.java
apps/modernization-api/src/test/resources/features/patient/search/PatientSearch.feature
apps/modernization-ui/src/generated/graphql/schema.ts
apps/modernization-ui/src/generated/schema.graphqls

Leverage `contains` code in the `TextCriteria` for an elasticsearch filter query
* [CNFT1-3471](https://cdc-nbs.atlassian.net/browse/CNFT1-3471)
[CNFT1-3471]: https://cdc-nbs.atlassian.net/browse/CNFT1-3471?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT1-3469 Search API: Add filters for Phone

---

testing/regression/cypress/e2e/features/patient-extended-form/patient.feature

Added the end to end test for missing address information.
* [CNT-137](https://cdc-nbs.atlassian.net/browse/CNT-137)
[CNT-137]: https://cdc-nbs.atlassian.net/browse/CNT-137?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNT-137] - E2E - Missing Address Information

---

apps/modernization-ui/src/apps/search/patient/PatientCriteria/BasicInformation.tsx

Search criteria label for patient ID has been changed to "Patient ID(s)"
* [CNFT-3782](https://cdc-nbs.atlassian.net/browse/CNFT1-3782)

Patient ID label change

---

cdc-sandbox/nbs6-win-container/README.md
cdc-sandbox/nbs6-win-container/entrypoint.ps1
cdc-sandbox/nbs6-win-container/task-scheduler.ps1

Added the ability to change windows scheduled tasks at runtime by setting an optional environment variables starting with updateScheduledTask_. The following scenarios were tested.
1. 1 scheduled task update named updateScheduledTask_ELRImporter and the value encapsulated in ""
2. 1 scheduled task update named updateScheduledTask_ELRImporter and the value encapsulated in ''
3. 1 scheduled task update named updateScheduledTask_ELRImporter and no docker value encapsulation
4. no scheduled task updates
5. 2 scheduled task named updateScheduledTask_ELRImporter updateScheduledTask_MSGout and no docker value encapsulation

adding ability to modify existing scheduled tasks

---

testing/regression/cypress/e2e/features/patient-extended-form/patient.feature
testing/regression/cypress/e2e/pages/patient-extended-form/patient.page.js
testing/regression/cypress/step_definitions/patient-extended-form/patient.steps.js

Added end to end test for valid dropdown scenarios.
* [CNT-143](https://cdc-nbs.atlassian.net/browse/CNT-143)
[CNT-143]: https://cdc-nbs.atlassian.net/browse/CNT-143?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNT-143] - E2E - Valid Dropdown Scenarios

---

testing/regression/cypress/e2e/features/patient-extended-form/patient.feature
testing/regression/cypress/e2e/pages/patient-extended-form/patient.page.js
testing/regression/cypress/step_definitions/patient-extended-form/patient.steps.js

Added end to end test for missing required dropdown selections.
* [CNT-144](https://cdc-nbs.atlassian.net/browse/CNT-144)
[CNT-144]: https://cdc-nbs.atlassian.net/browse/CNT-144?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNT-144] - E2E - Missing required Dropdown selections

---

testing/regression/cypress/e2e/features/patient-extended-form/patient.feature
testing/regression/cypress/e2e/pages/patient-extended-form/patient.page.js
testing/regression/cypress/step_definitions/patient-extended-form/patient.steps.js

Regression tests for Valid Phone number, Valid ID, and invalid ID for Extended Form
* [CNT-142] [CNT-141] [CNT-140] (https://cdc-nbs.atlassian.net/browse/CNT-140) (https://cdc-nbs.atlassian.net/browse/CNT-141) (https://cdc-nbs.atlassian.net/browse/CNT-142)
[CNT-142]: https://cdc-nbs.atlassian.net/browse/CNT-142?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CNT-141]: https://cdc-nbs.atlassian.net/browse/CNT-141?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CNT-140]: https://cdc-nbs.atlassian.net/browse/CNT-140?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Valid Phone number, valid ID, and invalid ID for Extended Form

---

apps/modernization-ui/src/design-system/field/Field.spec.tsx
apps/modernization-ui/src/design-system/field/Field.tsx
apps/modernization-ui/src/design-system/field/field.module.scss
apps/modernization-ui/src/styles/_components.scss

This will add small, medium and large sizing to all Field components. 
* [Jira Ticket](https://cdc-nbs.atlassian.net/browse/CNFT1-3772)

Cnft1 3772 UI patient search add small size text input component

---

testing/regression/cypress/e2e/features/patient-extended-form/patient.feature
testing/regression/cypress/e2e/pages/patient-extended-form/patient.page.js
testing/regression/cypress/step_definitions/patient-extended-form/patient.steps.js

Added end to end test for adding a Lab Report After Creating a New Patient.
* [CNT-146](https://cdc-nbs.atlassian.net/browse/CNT-146)
[CNT-146]: https://cdc-nbs.atlassian.net/browse/CNT-146?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNT-146] - E2E - Adding a Lab Report After Creating a New Patient

---

apps/modernization-ui/package-lock.json
apps/modernization-ui/src/apps/search/useSearchResults.ts

Any active search filters are now removed when "Clear all" is clicked.  
* [CNFT1-3793](https://cdc-nbs.atlassian.net/browse/CNFT1-3793)
[CNFT1-3793]: https://cdc-nbs.atlassian.net/browse/CNFT1-3793?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-3793] Clear filter when criteria cleared

---

testing/regression/cypress/e2e/features/patient-extended-form/patient.feature

Added end to end test for adding an Investigation After Creating a New Patient
* [CNT-147](https://cdc-nbs.atlassian.net/browse/CNT-147)
[CNT-147]: https://cdc-nbs.atlassian.net/browse/CNT-147?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNT-147] - E2E - Adding an Investigation After Creating a New Patient

---

apps/modernization-ui/src/design-system/date/criteria/DateCriteriaEntry.tsx
apps/modernization-ui/src/design-system/date/criteria/date-range/DateRangeEntry.tsx
apps/modernization-ui/src/design-system/date/picker/DatePicker.tsx
apps/modernization-ui/src/design-system/date/picker/date-picker.module.scss
apps/modernization-ui/src/design-system/field/field.module.scss
apps/modernization-ui/src/styles/_components.scss

These are the values for the select small
and these are the values for the small input
Implement Styles for the small size Date Picker component that matches the [figma]design
([https://www.figma.com/design/lU5zi29qGeVt3cGxoRIU3V/NBS-Design-System-2.0?node-id=4694-16840](https://www.figma.com/design/lU5zi29qGeVt3cGxoRIU3V/NBS-Design-System-2.0?node-id=4694-16840&m=dev)) 
* [CNFT1-3776](https://cdc-nbs.atlassian.net/browse/CNFT1-3776)
[CNFT1-3776]: https://cdc-nbs.atlassian.net/browse/CNFT1-3776?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-3776]: Adding date picker ds updates for sizes

---

testing/regression/cypress/e2e/pages/patient-extended-form/patient-extended.page.js
testing/regression/cypress/e2e/pages/patient-extended-form/patient.page.js

Fixes ENV. Removed duplicate code from merge.

Merge Fixes for Regression

---

testing/regression/cypress/e2e/hl7/elr-generate.feature
testing/regression/cypress/step_definitions/hl7/generate-elr.steps.js

ELR Seeds for major STDs.
* [CNT-148](https://cdc-nbs.atlassian.net/browse/CNT-148)
[CNT-148]: https://cdc-nbs.atlassian.net/browse/CNT-148?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNT-148 seeds and script for 6 cases

---

apps/modernization-ui/src/apps/search/patient/result/table/PatientSearchResultTable.tsx
apps/modernization-ui/src/design-system/table/DataTable.spec.tsx
apps/modernization-ui/src/design-system/table/DataTable.tsx
apps/modernization-ui/src/design-system/table/DataTableRow.tsx
apps/modernization-ui/src/design-system/table/HeightConstrained.tsx

Remove the "View More" button from the patient search results table, but make a flag so repeating block and other tables can include it where needed.
* [Jira Ticket](https://cdc-nbs.atlassian.net/browse/CNFT1-3594)

CNFT1-3594: Patient search results remove view more button

---

testing/regression/cypress/e2e/features/patient-extended-form/patient.feature
testing/regression/cypress/e2e/pages/patient-extended-form/patient.page.js
testing/regression/cypress/step_definitions/patient-extended-form/patient.steps.js

Added end to end test for searching the Patient by last name using "Starts With" dropdown option.
* [CNT-152](https://cdc-nbs.atlassian.net/browse/CNT-152)
[CNT-152]: https://cdc-nbs.atlassian.net/browse/CNT-152?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNT-152] - E2E - Searching for a patient by Last Name using Starts with

---

apps/modernization-api/README.md
apps/nbs-gateway/README.md
documentation/feature-flags/README.md
libs/configuration-api/README.md

Adds documentation on feature flagging in the `modernization-ui` and how to make them configurable through the `configuration-api`

[Documentation] feature flag 

---

apps/modernization-ui/src/apps/search/patient/result/table/PatientSearchResultTable.tsx

For ID Column on Search results: Table view
Enable sortable: true
For Email Column on Search results: Table view
Enable sortable: true
* [CNFT1-3810](https://cdc-nbs.atlassian.net/browse/CNFT1-3810)
* [CNFT1-3812](https://cdc-nbs.atlassian.net/browse/CNFT1-3812)
[CNFT1-3810]: https://cdc-nbs.atlassian.net/browse/CNFT1-3810?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CNFT1-3812]: https://cdc-nbs.atlassian.net/browse/CNFT1-3812?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

adding sortable option for id and email

---

testing/regression/cypress/e2e/features/patient-extended-form/patient.feature
testing/regression/cypress/step_definitions/patient-extended-form/patient.steps.js

Added end to end test for search patient using contains on last name field.
* [CNT-153](https://cdc-nbs.atlassian.net/browse/CNT-153)
[CNT-153]: https://cdc-nbs.atlassian.net/browse/CNT-153?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNT-153] - E2E - Searching for a patient by Last Name using Contains

---

apps/modernization-ui/src/apps/patient/add/basic/AddPatientBasic.tsx

New patient form is available for user, Cancel and Add extended data buttons are functional
Problem 
Currently navigating to extended or clicking the cancel button throws an error so adding these changes fixes that issue
* [CNFT1-3833](https://cdc-nbs.atlassian.net/browse/CNFT1-3833)
[CNFT1-3833]: https://cdc-nbs.atlassian.net/browse/CNFT1-3833?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

adding check to ensure data is passed forward

---

testing/regression/cypress/e2e/features/patient-extended-form/patient.feature
testing/regression/cypress/e2e/pages/patient-extended-form/patient.page.js
testing/regression/cypress/step_definitions/patient-extended-form/patient.steps.js

Regression tests for First Name Modern Search; Sounds like, Starts with, Equal, Not equal, and Contains.
* [CNT-157 CNT-158 CNT-159 CNT-160 CNT-161 ](https://cdc-nbs.atlassian.net/browse/CNT-157 https://cdc-nbs.atlassian.net/browse/CNT-158 https://cdc-nbs.atlassian.net/browse/CNT-159 https://cdc-nbs.atlassian.net/browse/CNT-160 https://cdc-nbs.atlassian.net/browse/CNT-161)

CNT-157, CNT-158, CNT-159, CNT-160, CNT-161

---

testing/regression/cypress/e2e/features/patient-extended-form/patient.feature
testing/regression/cypress/step_definitions/patient-extended-form/patient.steps.js

Added end to end test for searching patient last name using Equal.
* [CNT-154](https://cdc-nbs.atlassian.net/browse/CNT-154)
[CNT-154]: https://cdc-nbs.atlassian.net/browse/CNT-154?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNT-154] - E2E - Searching for a patient by Last Name using Equal

---

apps/modernization-ui/src/design-system/entry/multi-value/RepeatingBlock.module.scss

Added a small amount of padding on the active state to match new figma: 
* [Jira Ticket](https://cdc-nbs.atlassian.net/browse/CNFT1-3794)

CNFT1-3794: UI: New patient- Extended: Update View/ edit/ delete buttons

---

apps/modernization-ui/src/apps/search/patient/result/table/PatientSearchResultTable.tsx

Set sortable: true on phone column.
* [Jira Ticket](https://cdc-nbs.atlassian.net/browse/CNFT1-3815)

CNFT1-3815 UI Enable Sorting for Phone

---

testing/regression/cypress/e2e/features/patient-extended-form/patient.feature

Added end to end test for search patient by last name using not equal.
* [CNT-155](https://cdc-nbs.atlassian.net/browse/CNT-155)
[CNT-155]: https://cdc-nbs.atlassian.net/browse/CNT-155?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNT-155] - E2E - Searching for patient by Last Name using Not Equal

---

cdc-sandbox/nbs6-win-container/README.md
cdc-sandbox/nbs6-win-container/entrypoint.ps1

Update to support passed in db credentials

add db env processing

---

testing/regression/cypress/e2e/features/patient-extended-form/patient.feature

Added end to end test for searching for patient by Last Name using Sounds like
* [CNT-156](https://cdc-nbs.atlassian.net/browse/CNT-156)
[CNT-156]: https://cdc-nbs.atlassian.net/browse/CNT-156?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNT-156] - E2E - Searching for patient by Last Name using Sounds like

---

testing/regression/cypress/e2e/pages/patientSearchPage.page.js

Removed duplicate entry for verifySearchResults method
* [CNT-156](https://cdc-nbs.atlassian.net/browse/CNT-156)
[CNT-156]: https://cdc-nbs.atlassian.net/browse/CNT-156?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNT-156] Remove duplicate entry for verifySearchResults

---

apps/modernization-ui/src/styles/_buttons.scss

Fixed alignment issues 
Repeated block buttons --
Buttons aligned correctly --
No story yet assigned but a bug will be created and I will add it here later.

ensures the “small” styles properly override the base styles

---

apps/modernization-api/src/main/java/gov/cdc/nbs/patient/search/PatientSearchCriteriaSortResolver.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/PatientMother.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/phone/PatientProfilePhoneSteps.java
apps/modernization-api/src/test/resources/features/patient/search/PatientSearch.phone.sorting.feature

* [CNFT1-3707](https://cdc-nbs.atlassian.net/browse/CNFT1-3707)
[CNFT1-3707]: https://cdc-nbs.atlassian.net/browse/CNFT1-3707?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT1-3707 API : Implement sorting logic for Phone

---

apps/modernization-ui/package-lock.json
testing/regression/cypress/step_definitions/patient-extended-form/patient.steps.js
testing/regression/package-lock.json

Fixed build/ report failure for end to end tests.
* [CNT-156](https://cdc-nbs.atlassian.net/browse/CNT-156)
[CNT-156]: https://cdc-nbs.atlassian.net/browse/CNT-156?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNT-156] - E2E - Fix report failure

---

testing/regression/cypress/e2e/features/modern-ui/search.feature
testing/regression/cypress/e2e/pages/nbs-classic/home.page.js
testing/regression/cypress/step_definitions/nbs-classic/home.steps.js

* [CNT-171](https://cdc-nbs.atlassian.net/browse/CNT-171)(https://cdc-nbs.atlassian.net/browse/CNT-169)(https://cdc-nbs.atlassian.net/browse/CNT-170)
[CNT-171]: https://cdc-nbs.atlassian.net/browse/CNT-171?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNT-169, CNT-170, CNT-171

---

apps/modernization-ui/src/design-system/entry/multi-value/RepeatingBlock.tsx
apps/modernization-ui/src/design-system/table/DataTable.tsx

Removing implementation of no data row from data table impacting patient search and only keeping it on the extended form
* [CNFT1-3797](https://cdc-nbs.atlassian.net/browse/CNFT1-3797)
[CNFT1-3797]: https://cdc-nbs.atlassian.net/browse/CNFT1-3797?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT1-3797-nodata-fallback

---

apps/modernization-ui/src/apps/search/patient/PatientSearch.tsx
apps/modernization-ui/src/sorting/useSorting.tsx

First sort option for patient search table fields has to be Ascending
* [CNFT1-3859](https://cdc-nbs.atlassian.net/browse/CNFT1-3859)
[CNFT1-3859]: https://cdc-nbs.atlassian.net/browse/CNFT1-3859?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-3859]: adding sorting direction to ascending by defaultSort

---

cdc-sandbox/nbs6-win-container/entrypoint.ps1

Bug fix on entrypoint task name

updated taskname

---

apps/modernization-ui/src/design-system/table/data-table.module.scss

Removing padding not needed
* [CNFT1-3797](https://cdc-nbs.atlassian.net/browse/CNFT1-3797)
[CNFT1-3797]: https://cdc-nbs.atlassian.net/browse/CNFT1-3797?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT1-3797-removing-padding

---

apps/modernization-ui/src/apps/search/basic/BasicPatient.tsx

UI: Patient search: List View- Sort list by and Table Sort indicators has to be marked, while switching between List and Table views
* [CNFT1-3862](https://cdc-nbs.atlassian.net/browse/CNFT1-3862)
[CNFT1-3862]: https://cdc-nbs.atlassian.net/browse/CNFT1-3862?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT1-3862-sorting-preserved-patientName

---

apps/modernization-ui/src/apps/search/patient/PatientSearch.tsx
apps/modernization-ui/src/apps/search/patient/result/none/NoPatientResults.tsx
apps/modernization-ui/src/design-system/field/Field.tsx
apps/modernization-ui/src/design-system/field/HorizontalField.tsx
apps/modernization-ui/src/design-system/field/VerticalField.tsx
apps/modernization-ui/src/design-system/field/field.module.scss
apps/modernization-ui/src/design-system/input/text/TextInput.tsx
apps/modernization-ui/src/design-system/input/text/TextInputField.tsx
apps/modernization-ui/src/design-system/input/text/text-input.module.scss
apps/modernization-ui/src/design-system/table/Header.tsx
apps/modernization-ui/src/design-system/table/header.module.scss
apps/modernization-ui/src/design-system/table/header/filter/HeaderFilterField.spec.tsx
apps/modernization-ui/src/design-system/table/header/filter/HeaderFilterField.tsx
apps/modernization-ui/src/design-system/table/header/filter/header-filter-field.module.scss

Sizing changed, spacing fixed
* [CNFT1-3866](https://cdc-nbs.atlassian.net/browse/CNFT1-3866)
[CNFT1-3866]: https://cdc-nbs.atlassian.net/browse/CNFT1-3866?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Cnft1 3866 filter component small size

---

apps/modernization-ui/src/apps/patient/add/basic/AddPatientBasicForm.tsx
apps/modernization-ui/src/apps/patient/add/extended/AddPatientExtendedForm.spec.tsx
apps/modernization-ui/src/apps/patient/add/extended/AddPatientExtendedForm.tsx
apps/modernization-ui/src/design-system/entry/multi-value/RepeatingBlock.tsx

Update “*All required fields for adding comments” field help text to “*Required“ in New patient, New patient-Extended forms.
* [CNFT1-3889](https://cdc-nbs.atlassian.net/browse/CNFT1-3889)
[CNFT1-3889]: https://cdc-nbs.atlassian.net/browse/CNFT1-3889?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fixing message on cards in basic and extended

---

apps/modernization-ui/src/components/Accordion/Accordion.tsx
apps/modernization-ui/src/components/Accordion/accordion.module.scss

Padding size changed
Collapse button changes
* [CNFT1-3846](https://cdc-nbs.atlassian.net/browse/CNFT1-3846)
[CNFT1-3846]: https://cdc-nbs.atlassian.net/browse/CNFT1-3846?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT1-3846 accordian header

---

testing/regression/cypress/e2e/features/address.feature
testing/regression/cypress/e2e/features/basic-info.feature
testing/regression/cypress/e2e/features/contact.feature
testing/regression/cypress/step_definitions/search.steps.js

Regression fixes for address, basic-info, and contact.

Regression fixes for address, basic-info, and contact

---

apps/modernization-api/src/main/java/gov/cdc/nbs/patient/search/PatientDemographicQueryResolver.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/search/SearchablePatient.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/search/indexing/SearchablePatientFinder.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/search/indexing/SearchablePatientResolver.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/search/indexing/SearchablePatientRowMapper.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/search/PatientSearchCriteriaSteps.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/search/indexing/SearchablePatientRowMapperTest.java
apps/modernization-api/src/test/resources/features/patient/search/PatientSearch.feature

* [CNFT1-3867](https://cdc-nbs.atlassian.net/browse/CNFT1-3867)
[CNFT1-3867]: https://cdc-nbs.atlassian.net/browse/CNFT1-3867?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT1-3867 API: Patient Search: Patient ID filter- Apply filter and Indexes to Short ID

---

apps/modernization-ui/src/design-system/table/NoDataRow.tsx

Adding period to end of sentence
-->   No data has been added.
* [CNFT1-3918](https://cdc-nbs.atlassian.net/browse/CNFT1-3918)
[CNFT1-3918]: https://cdc-nbs.atlassian.net/browse/CNFT1-3918?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-3918]adding period to end of sentence

---

apps/modernization-ui/src/apps/patient/add/basic/AddPatientBasic.tsx
apps/modernization-ui/src/apps/patient/add/cancelAddPatientPanel/handleNativeCancelAddPanel.ts
apps/modernization-ui/src/apps/patient/add/cancelAddPatientPanel/index.ts
apps/modernization-ui/src/apps/patient/add/extended/AddPatientExtended.tsx

Changes to show the browser's native cancel confirmation message when the customized cancel confirmation message is not available. 
* [Jira Ticket](https://cdc-nbs.atlassian.net/browse/CNFT1-2333)

Cnft1 2333 fixes

---

apps/modernization-ui/src/apps/patient/data/sexAndBirth/SexAndBirthEntryFields.tsx

When entering an invalid DOB format in the Date of birth field, the Current age is calculated when it should not occur.
* [CNFT1-3876](https://cdc-nbs.atlassian.net/browse/CNFT1-3876)
[CNFT1-3876]: https://cdc-nbs.atlassian.net/browse/CNFT1-3876?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-3876]: adding valueView error checks

---

apps/modernization-ui/src/apps/deduplication/data-elements/form/DataElementRow/DataElementRow.tsx

Remove validations for numeric inputs
none

Remove Validations for Numeric Input

---

testing/regression/README.md

Update README File 
* [CNT-177](https://cdc-nbs.atlassian.net/browse/CNT-177)
[CNT-177]: https://cdc-nbs.atlassian.net/browse/CNT-177?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Steps for cypress hidden files

---

cdc-sandbox/nbs6-win-container/Dockerfile
cdc-sandbox/nbs6-win-container/entrypoint.ps1

Recommended wildfly memory configuration
* [CNPT-2122](https://cdc-nbs.atlassian.net/jira/software/c/projects/CNPT/boards/104/backlog?assignee=5dc090d8c424110de525712f&selectedIssue=CNPT-2122)
[CNPT-2122]: https://cdc-nbs.atlassian.net/browse/CNPT-2122?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

nbs6 java opts updates

---

cdc-sandbox/nbs6-win-container/README.md
cdc-sandbox/nbs6-win-container/entrypoint.ps1
cdc-sandbox/nbs6-win-container/tasks.csv

Adds phcrimporter to task scheduler and user parameter it needs to run

add phcr importer

---

apps/modernization-ui/src/design-system/input/text/textarea.module.scss

set max-width: 40rem on textarea
* [Jira Ticket](https://cdc-nbs.atlassian.net/browse/CNFT1-3796)

CNFT1-3796 Text area component update max width 40 rem

---

apps/modernization-ui/src/design-system/date/criteria/DateCriteriaField.tsx
apps/modernization-ui/src/design-system/date/criteria/date-criteria.module.scss
apps/modernization-ui/src/design-system/date/criteria/exact/exact-date-field.module.scss
apps/modernization-ui/src/design-system/date/criteria/range/DateRangeField.tsx
apps/modernization-ui/src/design-system/date/criteria/range/date-range-field.module.scss
apps/modernization-ui/src/design-system/date/picker/date-picker.module.scss
apps/modernization-ui/src/design-system/field/VerticalField.tsx
apps/modernization-ui/src/design-system/field/helper-text.module.scss
apps/modernization-ui/src/design-system/field/inline-message.module.scss
apps/modernization-ui/src/design-system/field/vertical-field.module.scss
apps/modernization-ui/src/styles/_uswds.scss
apps/modernization-ui/src/uswds/types.d.ts

1. Date picker matches figma designs
2. Date picker now has blue highlights when picking to and from dates
3. Error state with the date picker, making sure red bar is not going all the way down
* [CNFT1-3874](https://cdc-nbs.atlassian.net/browse/CNFT1-3874)
* [CNFT1-3871](https://cdc-nbs.atlassian.net/browse/CNFT1-3871)
[CNFT1-3874]: https://cdc-nbs.atlassian.net/browse/CNFT1-3874?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CNFT1-3871]: https://cdc-nbs.atlassian.net/browse/CNFT1-3871?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Cnft1 3874 date picker component and error state fixes

---

apps/nbs-gateway/build.gradle
gradle/libs.versions.toml

🔨 Dependency upgrades for the Spring boot based projects.

version updates

---

apps/nbs-gateway/src/main/java/gov/cdc/nbs/gateway/RouteOrdering.java
apps/nbs-gateway/src/main/java/gov/cdc/nbs/gateway/deduplication/DeduplicationAPIRouteLocatorConfiguration.java
apps/nbs-gateway/src/main/java/gov/cdc/nbs/gateway/deduplication/DeduplicationService.java
apps/nbs-gateway/src/main/java/gov/cdc/nbs/gateway/deduplication/DeduplicationServiceProvider.java
apps/nbs-gateway/src/main/java/gov/cdc/nbs/gateway/modernization/ModernizationAPIRouteLocatorConfiguration.java
apps/nbs-gateway/src/main/resources/application.yml
apps/nbs-gateway/src/test/java/gov/cdc/nbs/gateway/deduplication/DeduplicationAPIRouteLocatorConfigurationDisabledTest.java
apps/nbs-gateway/src/test/java/gov/cdc/nbs/gateway/deduplication/DeduplicationAPIRouteLocatorConfigurationEnabledTest.java

Adds `nbs-gateway` routing for Deduplication api
* [CND-234](https://cdc-nbs.atlassian.net/browse/CND-234)
[CND-234]: https://cdc-nbs.atlassian.net/browse/CND-234?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

deduplication-api routing

---

apps/modernization-ui/src/apps/patient/add/basic/AddPatientBasic.tsx
apps/modernization-ui/src/apps/patient/add/basic/asBasicNewPatientEntry.ts
apps/modernization-ui/src/apps/patient/add/basic/entry.ts

Address fields in the basic patient is now keeping the values when going between extended and basic.
* [CNFT1-3983](https://cdc-nbs.atlassian.net/browse/CNFT1-3983)
[CNFT1-3983]: https://cdc-nbs.atlassian.net/browse/CNFT1-3983?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

cnft1 3983 address bug

---

apps/modernization-api/src/main/java/gov/cdc/nbs/patient/search/phone/PatientSearchResultDetailedPhoneFinder.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/search/phone/PatientSearchResultPhoneMapper.java

Email address type is now being shown in phone number column in patients search results
* [CNFT1-3937](https://cdc-nbs.atlassian.net/browse/CNFT1-3937)
[CNFT1-3937]: https://cdc-nbs.atlassian.net/browse/CNFT1-3937?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

cnft1 3937 phone number type/use

---

apps/modernization-ui/src/apps/deduplication/api/model/Labels.ts
apps/modernization-ui/src/apps/deduplication/api/model/Pass.ts
apps/modernization-ui/src/apps/deduplication/api/useMatchConfiguration.ts
apps/modernization-ui/src/apps/deduplication/configuration/MatchConfigurationLandingPage.tsx
apps/modernization-ui/src/apps/deduplication/configuration/import/importPreview/ImportPreview.spec.tsx
apps/modernization-ui/src/apps/deduplication/configuration/import/importPreview/ImportPreview.tsx
apps/modernization-ui/src/apps/deduplication/configuration/import/importPreview/data-element-table/DataElementsTable.spec.tsx
apps/modernization-ui/src/apps/deduplication/configuration/import/importPreview/data-element-table/DataElementsTable.tsx
apps/modernization-ui/src/apps/deduplication/configuration/import/importPreview/import-preview.module.scss
apps/modernization-ui/src/apps/deduplication/configuration/import/importPreview/pass-configuration-table/PassConfigurationTable.spec.tsx
apps/modernization-ui/src/apps/deduplication/configuration/import/importPreview/pass-configuration-table/PassConfigurationTable.tsx
apps/modernization-ui/src/apps/deduplication/configuration/match-configuration/pass-configuration/pass-form/blocking-criteria/BlockingCriteria.spec.tsx
apps/modernization-ui/src/apps/deduplication/configuration/match-configuration/pass-configuration/pass-form/blocking-criteria/BlockingCriteria.tsx
apps/modernization-ui/src/apps/deduplication/configuration/match-configuration/pass-configuration/pass-form/blocking-criteria/panel/BlockingCriteriaSidePanel.spec.tsx
apps/modernization-ui/src/apps/deduplication/configuration/match-configuration/pass-configuration/pass-form/blocking-criteria/panel/BlockingCriteriaSidePanel.tsx
apps/modernization-ui/src/apps/deduplication/configuration/match-configuration/pass-configuration/pass-form/matching-criteria/MatchingCriteria.tsx
apps/modernization-ui/src/apps/deduplication/configuration/match-configuration/pass-configuration/pass-form/matching-criteria/panel/MatchingCriteriaSidePanel.tsx
apps/modernization-ui/src/apps/deduplication/configuration/match-configuration/pass-configuration/pass-form/side-panel/side-panel.module.scss

1. Adds the preview screen for configuration import.
2. Consolidates label definitions for data elements and matching criteria to ease lookup
* [CND-218](https://cdc-nbs.atlassian.net/browse/CND-218)
[CND-218]: https://cdc-nbs.atlassian.net/browse/CND-218?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Deduplication - Import preview

---

apps/modernization-ui/src/apps/patient/add/PatientCreatedPanel.tsx
apps/modernization-ui/src/classic/ClassicButton.tsx

Includes fixes for  [CNFT1-3985](https://cdc-nbs.atlassian.net/browse/CNFT1-3985) made with #2425 .
[CNFT1-3985]: https://cdc-nbs.atlassian.net/browse/CNFT1-3985?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-3985] corrected urls

---

cdc-sandbox/nbs6-win-container/Dockerfile
cdc-sandbox/nbs6-win-container/entrypoint.ps1

Added parameters to update nndmConfig.properties.

add nndmConfig updates

---

apps/modernization-ui/src/apps/deduplication/configuration/match-configuration/pass-configuration/PassConfiguration.tsx
apps/modernization-ui/src/apps/deduplication/configuration/match-configuration/pass-configuration/pass-form/matching-bounds/MatchingBounds.spec.tsx
apps/modernization-ui/src/apps/deduplication/configuration/match-configuration/pass-configuration/pass-form/matching-bounds/MatchingBounds.tsx
apps/modernization-ui/src/apps/deduplication/configuration/match-configuration/pass-configuration/pass-form/matching-bounds/bound-entry/BoundEntry.tsx
apps/modernization-ui/src/apps/deduplication/configuration/match-configuration/pass-configuration/pass-form/matching-bounds/bound-entry/bound-entry.module.scss

1. Adds validation to Matching bounds
a. Lower bound must be less than total log odds
b. Lower bound must be less than upper bound
c. Upper bound must be greater than or equal to lower bound
d. Upper bound must be less that total log odds
* [CND-258](https://cdc-nbs.atlassian.net/browse/CND-258)
[CND-258]: https://cdc-nbs.atlassian.net/browse/CND-258?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Cnd 258 bound validation

---

apps/modernization-ui/src/design-system/entry/multi-value/RepeatingBlock.spec.tsx
apps/modernization-ui/src/design-system/entry/multi-value/RepeatingBlock.tsx

Remove the "+" icon from the update button. Update unit tests. 

CNFT1-3993: New patient extended repeating block update button

---

apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/entity/WaNndMetadatum.java

Attempts to resolve the last couple of [sonar findings](https://sonarcloud.io/project/issues?issueStatuses=OPEN%2CCONFIRMED&sinceLeakPeriod=true&id=CDCgov_NEDSS-Modernization).

Move suppress to entity level

---

apps/modernization-api/src/main/java/gov/cdc/nbs/patient/search/phone/PatientSearchResultPhoneMapper.java

Now the 4 uses are given short forms.
Mobile Contact” => “Cell”
“Alternate Work Place” => “Work
“Primary Work Place” => “Work”
“Home” => “Home”
* [CNFT1-3996](https://cdc-nbs.atlassian.net/browse/CNFT1-3996)
[CNFT1-3996]: https://cdc-nbs.atlassian.net/browse/CNFT1-3996?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

small change

---

.github/workflows/Build-and-deploy-elasticsearch.yaml
.github/workflows/Build-and-deploy-modernization-api.yaml
.github/workflows/Build-and-deploy-nbs-gateway.yaml
.github/workflows/Build-and-deploy-nbs6-win-container.yaml
.github/workflows/Build-and-deploy-nifi.yaml
.github/workflows/Build-and-deploy-page-builder-api.yaml
.github/workflows/Release-candidate-containers.yml
.github/workflows/Release-container.yaml

Updates token permissions to restore pipeline functionality.

updating token handling

---

cdc-sandbox/nbs6-win-container/entrypoint.ps1

Removes extra lines, that do nothing, and fixes task name disabling.

remove extra characters

---

.github/workflows/Build-and-deploy-modernization-api.yaml
.github/workflows/Build-and-deploy-page-builder-api.yaml

Updates 2 pipeline's token permissions where sonar token is called

add token permissions for sonar call

---

apps/modernization-ui/src/apps/search/patient/PatientSearchActions.tsx

Takes away add new dropdown and ust has add new patient button if user has the correct permissions
* [CNFT1-3925](https://cdc-nbs.atlassian.net/browse/CNFT1-3925)
[CNFT1-3925]: https://cdc-nbs.atlassian.net/browse/CNFT1-3925?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

add new button changed to only have the add new patient button

---

testing/regression/cypress/e2e/pages/login.page.js

Login function fixed by removing the wait.

Removed wait from login function

---

apps/modernization-ui/src/shared/header/NavBar.spec.tsx
apps/modernization-ui/src/shared/header/NavBar.tsx

Fixing the format of the page title to ensure it is always capitalizing the first letter of the title regardless if the url is in lowercase
* [CNFT1-4011](https://cdc-nbs.atlassian.net/browse/CNFT1-4011)
[CNFT1-4011]: https://cdc-nbs.atlassian.net/browse/CNFT1-4011?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-4011]: Adding JS in a const to use to format the page title on the anchor tag for the Navbar component

---

apps/modernization-ui/src/apps/deduplication/data-elements/DataElementConfig.tsx

Updates the data elements form to use form rules to trigger `isValid` and `isDirty`
* [CND-264](https://cdc-nbs.atlassian.net/browse/CND-264)
[CND-264]: https://cdc-nbs.atlassian.net/browse/CND-264?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix save button enable

---

apps/modernization-ui/src/apps/deduplication/patient-merge/landing/MergeLanding.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/landing/merge-landing.module.scss

Rookie mistake

---

apps/modernization-ui/src/design-system/tag/Tag.spec.tsx
apps/modernization-ui/src/design-system/tag/Tag.stories.tsx
apps/modernization-ui/src/design-system/tag/Tag.tsx
apps/modernization-ui/src/design-system/tag/index.ts
apps/modernization-ui/src/design-system/tag/tag.module.scss

[##]() Description
This is a part 1 of two Prs to ensure tags is working as expected within the table card header and table card for patient file. For now this is the tag component and later will add more to it as well as its usage with other components
Tag component based on DS 
https://www.figma.com/design/lU5zi29qGeVt3cGxoRIU3V/NBS-Design-System-2.0?node-id=12350-30631&m=dev
* [CNFT1-4016](https://cdc-nbs.atlassian.net/browse/CNFT1-4016)
[CNFT1-4016]: https://cdc-nbs.atlassian.net/browse/CNFT1-4016?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-4016]: Adding tag base component along with styles and DS variations

---

apps/modernization-ui/src/design-system/card/table/TableCard.tsx
apps/modernization-ui/src/design-system/card/table/TableCardHeader.spec.tsx
apps/modernization-ui/src/design-system/card/table/TableCardHeader.tsx
apps/modernization-ui/src/design-system/card/table/table-card-header.module.scss
apps/modernization-ui/src/design-system/tag/Tag.stories.tsx
apps/modernization-ui/src/design-system/tag/tag.module.scss

Implementing tags within table card header to view tags within the collapsible card when there is a data table present
* [CNFT1-4016](https://cdc-nbs.atlassian.net/browse/CNFT1-4016)
[CNFT1-4016]: https://cdc-nbs.atlassian.net/browse/CNFT1-4016?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-4016]: adding tests for results count and using tags

---

testing/regression/cypress/e2e/features/modern-ui/search-filter.feature

Filter Patient Search Results Using a Partial Patient ID. 
tch. 
* [CNT-174](https://cdc-nbs.atlassian.net/browse/CNT-174)
[CNT-174]: https://cdc-nbs.atlassian.net/browse/CNT-174?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNT-174 Filter Patient Search Results Using a Partial Patient ID Match

---

testing/regression/cypress/e2e/features/basic-info.feature
testing/regression/cypress/e2e/features/events.feature
testing/regression/cypress/e2e/features/patient-profile-summary.feature

Regression fixes for seed DOB and Patient ID

Regression fixes for seed DOB and Patient ID

---

apps/modernization-ui/src/design-system/chips/Chip.spec.tsx
apps/modernization-ui/src/design-system/chips/Chip.tsx
apps/modernization-ui/src/design-system/icon/Icon.spec.tsx
apps/modernization-ui/src/design-system/icon/Icon.tsx
apps/modernization-ui/src/utils/index.ts
apps/modernization-ui/src/utils/triggerOnEnterOrSpace.ts

When user's focus is on Chips, if user presses Enter or space, chips has to be removed and search results are updated.
* [CNFT1-4090](https://cdc-nbs.atlassian.net/browse/CNFT1-4090)
[CNFT1-4090]: https://cdc-nbs.atlassian.net/browse/CNFT1-4090?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Cnft1 4090 chips removal

---

apps/modernization-ui/src/apps/deduplication/configuration/import/ImportConfigurationModal.spec.tsx
apps/modernization-ui/src/apps/deduplication/configuration/import/ImportConfigurationModal.tsx

Shows import error message when valid JSON is uploaded but is not a configuration
🤠

Fixes error message for import config

---

apps/modernization-ui/src/apps/patient/file/PatientFile.tsx
apps/modernization-ui/src/apps/patient/file/PatientFileHeader.tsx
apps/modernization-ui/src/apps/patient/file/PatientFileRouting.tsx
apps/modernization-ui/src/apps/patient/file/patient-file.module.scss
apps/modernization-ui/src/components/TabNavigation/TabNavigation.stories.tsx
apps/modernization-ui/src/components/TabNavigation/TabNavigation.tsx
apps/modernization-ui/src/components/TabNavigation/tabNavigation.module.scss
apps/modernization-ui/src/shared/header/NavBar.tsx

Story for storybook
* [CNFT1-4013](https://cdc-nbs.atlassian.net/browse/CNFT1-4013)
[CNFT1-4013]: https://cdc-nbs.atlassian.net/browse/CNFT1-4013?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Cnft1 4013 tab navigation storybook

---

apps/modernization-ui/src/apps/deduplication/configuration/match-configuration/pass-configuration/pass-list/pass-entry/pass-entry.module.scss

Add cursor: pointer

---

apps/nbs-gateway/build.gradle
gradle/libs.versions.toml

Updates the dependency versions for Spring boot to resolve [CVE-2025-22235](https://nvd.nist.gov/vuln/detail/CVE-2025-22235)

[CVE-2025-22235] Updates spring versions

---

apps/nbs-gateway/build.gradle
gradle/libs.versions.toml

Updates the dependency versions for Spring boot to resolve [CVE-2025-22235](https://nvd.nist.gov/vuln/detail/CVE-2025-22235)

[CVE-2025-22235] Updates spring versions 

---

apps/modernization-ui/src/design-system/hint/Hint.spec.tsx
apps/modernization-ui/src/design-system/hint/Hint.stories.tsx
apps/modernization-ui/src/design-system/hint/Hint.tsx
apps/modernization-ui/src/design-system/hint/hint.module.scss

- Update the `Hint` component to support a custom target, but default will still be info icon
- Additional stories for custom target and positioning
This is required for the new Patient File page.
* [Jira Ticket](https://cdc-nbs.atlassian.net/browse/CNFT1-4135)

CNFT1-4135: Hint component enhancements

---

apps/modernization-ui/src/apps/patient/add/basic/AddPatientBasic.tsx

Skip link add new patient page to be the information as of date field
* [CNFT1-4006](https://cdc-nbs.atlassian.net/browse/CNFT1-4006)
[CNFT1-4006]: https://cdc-nbs.atlassian.net/browse/CNFT1-4006?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-4006]: adding skip link to information as of field in add patient basic

---

apps/modernization-ui/src/apps/deduplication/api/useMatchesRequiringReview.ts
apps/modernization-ui/src/apps/deduplication/patient-merge/landing/MergeLanding.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/landing/matches-requiring-review-table/MatchesRequiringReviewTable.spec.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/landing/matches-requiring-review-table/MatchesRequiringReviewTable.tsx

Allows sorting on the merge requiring review table
* [CND-296](https://cdc-nbs.atlassian.net/browse/CND-296)
[CND-296]: https://cdc-nbs.atlassian.net/browse/CND-296?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Allow sorting of merge table

---

apps/modernization-ui/src/apps/patient/file/summary/patient-file-summary.module.scss

Small spacing change between values and labels from 0.31rem to 0.25rem.
* [CNFT1-4063](https://cdc-nbs.atlassian.net/browse/CNFT1-4063)
[CNFT1-4063]: https://cdc-nbs.atlassian.net/browse/CNFT1-4063?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

small spacing change

---

apps/modernization-ui/src/apps/deduplication/patient-merge/landing/matches-requiring-review-table/MatchesRequiringReviewTable.spec.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/landing/matches-requiring-review-table/MatchesRequiringReviewTable.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/landing/matches-requiring-review-table/matches-requiring-review.module.scss

Fixes a styling issue with merge landing table
Fixes default page size
* [CND-302](https://cdc-nbs.atlassian.net/browse/CND-302)
[CND-302]: https://cdc-nbs.atlassian.net/browse/CND-302?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Set default page size to 20. Fix overflow issue with pagination

---

apps/modernization-ui/src/apps/patient/add/basic/identification/BasicIdentificationRepeatingBlock.spec.tsx
apps/modernization-ui/src/apps/patient/add/basic/personalDetails/BasicPersonalDetailsFields.spec.tsx
apps/modernization-ui/src/apps/patient/add/basic/personalDetails/BasicPersonalDetailsFields.tsx
apps/modernization-ui/src/apps/patient/add/extended/AddPatientExtended.spec.tsx
apps/modernization-ui/src/apps/patient/add/extended/AddPatientExtendedForm.spec.tsx
apps/modernization-ui/src/apps/patient/add/extended/inputs/address/AddressRepeatingBlock.spec.tsx
apps/modernization-ui/src/apps/patient/add/extended/inputs/identification/IdentificationRepeatingBlock.spec.tsx
apps/modernization-ui/src/apps/patient/add/extended/inputs/name/NameEntryView.spec.tsx
apps/modernization-ui/src/apps/patient/add/extended/inputs/name/NameRepeatingBlock.spec.tsx
apps/modernization-ui/src/apps/patient/add/extended/inputs/phone/PhoneEntryView.spec.tsx
apps/modernization-ui/src/apps/patient/data/general/GeneralInformationEntryFields.spec.tsx
apps/modernization-ui/src/apps/patient/data/general/GeneralInformationEntryFields.tsx

Removes imports and unused mocks using code from `apps/patient/profile`.

Preparation for removal apps/patient/profile

---

apps/modernization-ui/src/apps/patient/file/delete/DeleteAction.spec.tsx
apps/modernization-ui/src/apps/patient/file/delete/DeleteAction.tsx

Fix the "has associations" warning message in the tooltip of the Delete button on patient file page.
* [Jira Ticket](https://cdc-nbs.atlassian.net/browse/CNFT1-4154)

CNFT1-4154: Fix patient file delete associations message

---

apps/modernization-ui/src/apps/deduplication/patient-merge/details/MergeDetails.spec.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-review/MergeReview.spec.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-review/MergeReview.tsx

Updates patient merge details page heading to match updated designs.
🤠

Fixes merge details page heading

---

apps/modernization-ui/src/apps/deduplication/patient-merge/details/MergeDetails.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-preview/MergePreview.spec.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-preview/MergePreview.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-preview/merge-preview.module.scss
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-review/MergeReview.spec.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-review/MergeReview.tsx

Develop Shell page for Patient Merge Preview page
Prototype Link: [Figma](https://www.figma.com/proto/Zug6ufzgx1J3uBz7VttQtn/NBS-7.x--%3E-Patient-Merge-1.1?node-id=2260-135064&t=IkhDJhbCGrCw8X3U-1&scaling=min-zoom&content-scaling=fixed&page-id=955%3A72490&starting-point-node-id=2260%3A135064&show-proto-sidebar=1)
https://github.com/user-attachments/assets/d0fd968d-8e71-4501-bc6d-cb14bb6b051f
* [CND-306](https://cdc-nbs.atlassian.net/browse/CND-306?atlOrigin=eyJpIjoiY2U3ODI4Nzk5NWI3NGU1OGIxMmIxZTUyNTg0ZDgyMDYiLCJwIjoiaiJ9)
[CND-306]: https://cdc-nbs.atlassian.net/browse/CND-306?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add Merge Preview Shell

---

apps/modernization-ui/src/apps/search/layout/SearchLayout.tsx
apps/modernization-ui/src/apps/search/layout/search-layout.module.scss

Fixing a prop name that is also used in search layout for a class used for styling
* [CNFT1-4141](https://cdc-nbs.atlassian.net/browse/CNFT1-4141)
[CNFT1-4141]: https://cdc-nbs.atlassian.net/browse/CNFT1-4141?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-4141]: fixing prop names to match their actions purpose

---

apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-preview/dummyData.ts

Adding dummy data for preview page
N/A

Add placeholder dummyData.ts

---

apps/modernization-api/src/test/java/gov/cdc/nbs/event/report/lab/LabReportMother.java
apps/modernization-api/src/test/java/gov/cdc/nbs/event/report/lab/LabReportSteps.java
apps/modernization-api/src/test/java/gov/cdc/nbs/event/report/lab/LabReportingSupportConfiguration.java
apps/modernization-api/src/test/java/gov/cdc/nbs/event/report/lab/test/CodedResultedTestMother.java
apps/modernization-api/src/test/java/gov/cdc/nbs/event/report/lab/test/ResultedTestCleaner.java

Ensures that resulted tests are cleaned up after a scenario has completed.

[Feature Tests] Resulted test clean up

---

apps/modernization-ui/src/apps/deduplication/api/model/PatientData.ts
apps/modernization-ui/src/apps/deduplication/api/useMergeDetails.ts
apps/modernization-ui/src/apps/deduplication/patient-merge/details/MergeDetails.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-review/MergeReview.spec.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-review/MergeReview.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-review/merge-review.module.scss
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-review/model/PatientMergeForm.ts
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-review/patient-form/admin-comments/AdminCommentsSelection.spec.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-review/patient-form/admin-comments/AdminCommentsSelection.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-review/patient-form/admin-comments/admin-comment-selection.module.scss
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-review/patient-form/admin-comments/admin-comment/AdminComment.spec.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-review/patient-form/admin-comments/admin-comment/AdminComment.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-review/patient-form/admin-comments/admin-comment/admin-comment.module.scss
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-review/patient-form/admin-comments/length-constrained/LengthConstrained.spec.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-review/patient-form/admin-comments/length-constrained/LengthConstrained.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-review/patient-form/patient-id/PatientIdSelection.spec.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-review/patient-form/patient-id/PatientIdSelection.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-review/patient-form/patient-id/patient-id-selection.module.scss
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-review/patient-form/shared/group-line/GroupLine.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-review/patient-form/shared/group-line/group-line.module.scss
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-review/patient-form/shared/section-label/SectionLabel.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-review/patient-form/shared/section-label/section-label.module.scss
apps/modernization-ui/src/apps/deduplication/patient-merge/landing/MergeLanding.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/landing/matches-requiring-review-table/MatchesRequiringReviewTable.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/landing/matches-requiring-review-table/matches-requiring-review.module.scss

Adds person Id and administrative comments section to patient merge
1. Patient Id displayed is `person_uid` instead of local Id
2. No default selections are made
https://github.com/CDCgov/NEDSS-DataIngestion/pull/382
* [CND-279](https://cdc-nbs.atlassian.net/browse/CND-279)
[CND-279]: https://cdc-nbs.atlassian.net/browse/CND-279?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Cnd 279 admin comments

---

apps/modernization-ui/src/apps/patient/file/summary/openInvestigations/OpenInvestigationsCard.tsx
apps/modernization-ui/src/design-system/card/table/table-card-header.module.scss

Fixes some problems identified after design review 
UI: Summary: Open Investigations
* [Jira Ticket](https://cdc-nbs.atlassian.net/browse/CNFT1-4073)

Cnft1 4073 design review revisions

---

apps/modernization-api/src/main/java/gov/cdc/nbs/patient/labreport/PatientLabReport.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/labreport/PatientLabReportsController.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/labreport/PatientLabReportsFinder.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/labreport/PatientLabReportsResolver.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/labreport/PatientLabReportsRowMapper.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/labreport/PatientTestResultsFinder.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/labreport/PatientTestResultsRowMapper.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/labreport/PatientLabReportRequester.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/labreport/PatientLabReportsSteps.java
apps/modernization-api/src/test/resources/features/patient/labreport/PatientLabReportsApi.feature
apps/modernization-ui/src/generated/index.ts
apps/modernization-ui/src/generated/models/AssociatedInvestigation.ts
apps/modernization-ui/src/generated/models/FacilityProviders.ts
apps/modernization-ui/src/generated/models/OrderingProvider.ts
apps/modernization-ui/src/generated/models/PatientLabReport.ts
apps/modernization-ui/src/generated/models/TestResult.ts
apps/modernization-ui/src/generated/services/PatientLabReportsService.ts

Find lab reports by patient id, find test results by patient id, collate test results into lab reports based on lab id
* [CNFT1-4128](https://cdc-nbs.atlassian.net/browse/CNFT1-4128)
[CNFT1-4128]: https://cdc-nbs.atlassian.net/browse/CNFT1-4128?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
```
[
{
"eventId": "OBS-19999982TEST",
"receivedDate": "2025-05-23",
"processingDecision": null,
"facilityProviders": {
"reportingFacility": "Northside Hospital",
"orderingProvider": {
"prefix": null,
"first": "Dean",
"last": "Learner",
"suffix": null
},
"sendingFacility": null
},
"collectedDate": "1994-09-04",
"testResults": [
{
"resultedTest": "Acid-Fast Stain",
"codedResult": "abnormal",
"numericResult": null,
"units": null,
"highRange": null, …
```

CNFT1-4128 API: Lab reports: List all the lab reports for the patient file

---

apps/modernization-api/postman/NDESS-Modernization-API.postman_collection.json
apps/modernization-api/src/main/java/gov/cdc/nbs/data/selectable/Selectable.java
apps/modernization-api/src/main/java/gov/cdc/nbs/data/selectable/SelectableRowMapper.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/file/demographics/phone/PatientPhoneDemographic.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/file/demographics/phone/PatientPhoneDemographicController.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/file/demographics/phone/PatientPhoneDemographicFinder.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/file/demographics/phone/PatientPhoneDemographicRowMapper.java
apps/modernization-api/src/test/java/gov/cdc/nbs/WebInteractionSteps.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/demographics/phone/PatientEmailDemographicSteps.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/demographics/phone/PatientPhoneDemographicSteps.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/file/demographics/phone/PatientFilePhoneDemographicRequester.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/file/demographics/phone/PatientFilePhoneDemographicSteps.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/file/demographics/phone/PatientFilePhoneDemographicVerificationSteps.java
apps/modernization-api/src/test/resources/features/patient/file/demographics/phone/PatientFile.phone.feature
apps/modernization-api/src/test/resources/features/patient/file/demographics/phone/PatientFile.phone.permissions.feature
apps/modernization-ui/src/generated/index.ts
apps/modernization-ui/src/generated/models/PatientPhoneDemographic.ts
apps/modernization-ui/src/generated/models/Selectable.ts
apps/modernization-ui/src/generated/services/PatientFileService.ts

Adds the `/nbs/api/patients/{patient}/demographics/phones` endpoint to the `modernization-api`.
- Updates Postman collection
- Adds Feature tests
```cucumber
Feature: Permissions for viewing the phone demographics of a patient
Background:
Given I have a patient
Scenario: I cannot view a Patient's phone demographics without logging in
Given I am not logged in at all
When I view the patient's phone demographics
Then I am not allowed due to insufficient permissions
Scenario: I cannot view a Patient's phone demographics without  permission
Given I am logged into NBS
When I view the patient's phone demographics
Then I am not allowed due to insufficient permissions
```
```cucumber
@patient-file @patient-phone-demographics
Feature: Viewing the phone demographics of a patient
Background:
Given I …
```

[CNFT1-4214] Patient file phone demographics endpoint

---

apps/modernization-ui/src/apps/patient/file/patient-file-header.module.scss
apps/modernization-ui/src/libs/patient/patient-descriptor.module.scss

Patient file Header : Adding responsive header matching the **designs**
Implementation 
* [CNFT1-4155](https://cdc-nbs.atlassian.net/browse/CNFT1-4155)
[CNFT1-4155]: https://cdc-nbs.atlassian.net/browse/CNFT1-4155?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-4155]:adding flex start and increasing gap size

---

apps/modernization-ui/src/apps/deduplication/api/model/MergeCandidate.ts
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-review/MergeReview.spec.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-review/MergeReview.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-review/model/PatientMergeForm.ts
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-review/patient-form/ethnicity/ethnicity/Ethnicity.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-review/patient-form/sex-and-birth/SexAndBirthSelection.spec.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-review/patient-form/sex-and-birth/SexAndBirthSelection.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-review/patient-form/sex-and-birth/sex-and-birth/SexAndBirth.spec.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-review/patient-form/sex-and-birth/sex-and-birth/SexAndBirth.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-review/patient-form/shared/merge-data-display/MergeDataDisplay.tsx

Adds sex and birth section to merge ui
* [CND-331](https://cdc-nbs.atlassian.net/browse/CND-331)
[CND-331]: https://cdc-nbs.atlassian.net/browse/CND-331?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add sex and birth section

---

apps/modernization-ui/src/apps/patient/file/summary/PatientSummaryContent.spec.tsx
apps/modernization-ui/src/apps/patient/file/summary/PatientSummaryContent.tsx

Change the spelling/casing for card title to **Patient summary** (lowercase 's').
Add unit test for patient summary.
* [Jira Ticket](https://cdc-nbs.atlassian.net/browse/CNFT1-4246)

CNFT1-4246: Fix Patient summary title and add unit test

---

apps/modernization-ui/src/apps/deduplication/api/model/MergeCandidate.ts
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-review/MergeReview.spec.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-review/MergeReview.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-review/model/PatientMergeForm.ts
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-review/patient-form/mortality/MortalitySelection.spec.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-review/patient-form/mortality/MortalitySelection.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-review/patient-form/mortality/mortality/Mortality.spec.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-review/patient-form/mortality/mortality/Mortality.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-review/patient-form/sex-and-birth/sex-and-birth/SexAndBirth.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-review/patient-form/shared/merge-data-display/MergeDataDisplay.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-review/patient-form/shared/merge-data-display/merge-data-display.module.scss

1. Adds mortality section to patient merge screen
2. Use labels for field labels
* [CND-332](https://cdc-nbs.atlassian.net/browse/CND-332)
[CND-332]: https://cdc-nbs.atlassian.net/browse/CND-332?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add mortality

---

apps/modernization-ui/src/apps/deduplication/api/model/MergeCandidate.ts
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-review/MergeReview.spec.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-review/MergeReview.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-review/model/PatientMergeForm.ts
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-review/patient-form/general/GeneralSelection.spec.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-review/patient-form/general/GeneralSelection.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-review/patient-form/general/general-info/GeneralInfo.spec.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-review/patient-form/general/general-info/GeneralInfo.tsx

Adds patient general info section to merge review page
* [CND-333](https://cdc-nbs.atlassian.net/browse/CND-333)
[CND-333]: https://cdc-nbs.atlassian.net/browse/CND-333?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Merge - General Info section

---

apps/modernization-ui/src/apps/deduplication/api/model/MergeCandidate.ts
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-review/MergeReview.spec.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-review/MergeReview.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-review/patient-form/address/address-data-table/AddressDataTable.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-review/patient-form/address/address-details/AddressDetails.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-review/patient-form/admin-comments/admin-comment/AdminComment.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-review/patient-form/ethnicity/ethnicity/Ethnicity.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-review/patient-form/general/general-info/GeneralInfo.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-review/patient-form/identification/identification-data-table/IdentificationDataTable.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-review/patient-form/identification/identification-details/IdentificationDetails.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-review/patient-form/investigations/InvestigationDisplay.spec.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-review/patient-form/investigations/InvestigationsDisplay.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-review/patient-form/investigations/investigation/Investigation.spec.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-review/patient-form/investigations/investigation/Investigation.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-review/patient-form/investigations/investigation/investigation.module.scss
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-review/patient-form/mortality/mortality/Mortality.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-review/patient-form/name/name-data-table/NameDataTable.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-review/patient-form/name/name-details/NameDetails.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-review/patient-form/phone-email/phone-email-data-table/PhoneEmailDataTable.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-review/patient-form/phone-email/phone-email-details/PhoneEmailDetails.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-review/patient-form/race/race-data-table/RaceDataTable.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-review/patient-form/race/race-details/RaceDetails.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-review/patient-form/sex-and-birth/sex-and-birth/SexAndBirth.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-review/patient-form/shared/toDateDisplay.ts

1. Adds investigation section to merge screen
* [CND-287](https://cdc-nbs.atlassian.net/browse/CND-287)
[CND-287]: https://cdc-nbs.atlassian.net/browse/CND-287?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add investigation section

---

apps/modernization-ui/src/apps/patient/file/events/investigations/InvestigationsCard.tsx

Adds the "Add Investigation" button to the "Investigations" card on the Events tab of the Patient file.
* [CNFT1-4071](https://cdc-nbs.atlassian.net/browse/CNFT1-4071)
[CNFT1-4071]: https://cdc-nbs.atlassian.net/browse/CNFT1-4071?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-4071] Add Investigation button

---

apps/nbs-gateway/Dockerfile
apps/nbs-gateway/src/main/java/gov/cdc/nbs/gateway/classic/NBS6RouteLocatorConfiguration.java
apps/nbs-gateway/src/main/resources/application.yml
apps/nbs-gateway/src/test/resources/application-remove-cookie-gateway-filter.yml
apps/nbs-gateway/src/test/resources/application-request-parameter-to-cookie-gateway-filter.yml

Moved the NBS6 basic routing to a `RouterFunction` and preemptively updates the remaining configuration based routes to use the property names introduced in version spring cloud gateway version 4.3.0.

[FIX] nbs-gateway

---

apps/modernization-ui/src/apps/deduplication/DeduplicationRouting.tsx
apps/modernization-ui/src/apps/deduplication/api/model/MatchRequiringReview.ts
apps/modernization-ui/src/apps/deduplication/api/model/MergeCandidate.ts
apps/modernization-ui/src/apps/deduplication/api/useMergeDetails.ts
apps/modernization-ui/src/apps/deduplication/patient-merge/details/MergeDetails.spec.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/details/MergeDetails.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-review/MergeReview.spec.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-review/patient-form/patient-id/PatientIdSelection.spec.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-review/patient-form/patient-id/PatientIdSelection.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/landing/MergeLanding.spec.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/landing/matches-requiring-review-table/MatchesRequiringReviewTable.spec.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/landing/matches-requiring-review-table/MatchesRequiringReviewTable.tsx

1. Updates patient Id to display the searchable local Id
2. Updates API to load merge candidate list with `matchId`
* [CND-346](https://cdc-nbs.atlassian.net/browse/CND-346)
[CND-346]: https://cdc-nbs.atlassian.net/browse/CND-346?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Cnd 346 merge local

---

apps/modernization-api/Dockerfile
apps/modernization-ui/src/apps/patient/add/PatientCreatedPanel.tsx
apps/modernization-ui/src/apps/patient/file/events/investigations/InvestigationsCard.tsx
apps/modernization-ui/src/navigation/useNavigationBlock.ts

The "Add investigation" button was being displayed regardless of permissions.
* [CNFT1-4071](https://cdc-nbs.atlassian.net/browse/CNFT1-4071)
[CNFT1-4071]: https://cdc-nbs.atlassian.net/browse/CNFT1-4071?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-4071] Add Investigations permissions

---

apps/modernization-api/src/main/java/gov/cdc/nbs/patient/demographics/address/AddressDemographicPatientCommandMapper.java

When adding a Patient address demographic the census tract and country fields were transposed.

[FIX] Address: census tract and country fields

---

apps/modernization-ui/src/apps/deduplication/api/useRemoveMerge.ts
apps/modernization-ui/src/apps/deduplication/patient-merge/details/MergeDetails.spec.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/details/MergeDetails.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-review/MergeReview.spec.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-review/MergeReview.tsx

Hooks up buttons to remove a single patient from merge and remove all patients from merge
* [CND-274](https://cdc-nbs.atlassian.net/browse/CND-274)
[CND-274]: https://cdc-nbs.atlassian.net/browse/CND-274?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Merge - keep separate

---

apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/page/create/PageCreatorSteps.java

Attempts to resolve 2 new code smells that were detected in the last scan.
[Sonar scan](https://sonarcloud.io/project/issues?issueStatuses=OPEN%2CCONFIRMED&sinceLeakPeriod=true&id=CDCgov_NEDSS-Modernization)

Resolve sonar code smell

---

apps/modernization-ui/src/design-system/checkbox/checkbox.module.scss

Adds `position: relative;` to apps/modernization-ui/src/design-system/checkbox/checkbox.module.scss as noted in the ticket
* [Jira Ticket](https://cdc-nbs.atlassian.net/browse/NIS-54)

Bug fix: NIS-54 Update position relative on checkbox

---

libs/configuration-api/src/main/java/gov/cdc/nbs/configuration/settings/session/Session.java
libs/configuration-api/src/main/java/gov/cdc/nbs/configuration/settings/session/SessionConfiguration.java

Follow up to https://github.com/CDCgov/NEDSS-Modernization/pull/2672

Config api for timeout

---

apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-review/patient-form/shared/merge-data-table/MergeDataTable.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-review/patient-form/shared/merge-data-table/merge-data-table.module.scss

Resolves a styling issue on merge review page
* [CND-354](https://cdc-nbs.atlassian.net/browse/CND-354)
[CND-354]: https://cdc-nbs.atlassian.net/browse/CND-354?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Merge review - Fix styling

---

gradle/cucumber-logging.gradle
gradle/libs.versions.toml

Updates the Spring Boot versions to resolve [CVE-2025-48988](https://avd.aquasec.com/nvd/cve-2025-48988)

[Versions] Spring Boot 3.5.3

---

apps/modernization-ui/src/design-system/card/Card.tsx
apps/modernization-ui/src/design-system/card/card.module.scss

The collapse button that shows when a `Card` component is collapsible was not the correct size.

[FIX] Design System/ Card collapse button

---

apps/modernization-ui/src/design-system/message/Message.stories.tsx
apps/modernization-ui/src/design-system/message/Message.tsx
apps/modernization-ui/src/design-system/message/message.module.scss

Centers the icon that displays in the `Message` component.
* [CNFT1-4242](https://cdc-nbs.atlassian.net/browse/CNFT1-4242)
[CNFT1-4242]: https://cdc-nbs.atlassian.net/browse/CNFT1-4242?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-4242] Message icon centered

---

apps/modernization-ui/src/design-system/modal/Modal.tsx
apps/modernization-ui/src/design-system/modal/modal.module.scss

Adjust the specificity of the `Modal` styles to override USWDS styles where needed.
* [CNFT1-4202](https://cdc-nbs.atlassian.net/browse/CNFT1-4202)
[CNFT1-4202]: https://cdc-nbs.atlassian.net/browse/CNFT1-4202?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-4202] Modal styles

---

apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/page/content/question/PageQuestionDeleterTest.java

Fixes two code smells found in latest scan.

Attempt to fix code smells

---

apps/modernization-ui/src/apps/patient/file/demographics/PatientFileDemographics.tsx
apps/modernization-ui/src/apps/patient/file/demographics/demographics.ts
apps/modernization-ui/src/apps/patient/file/demographics/mortality/PatientFileMortalityCard.tsx
apps/modernization-ui/src/apps/patient/file/demographics/mortality/index.ts
apps/modernization-ui/src/apps/patient/file/demographics/mortality/patientMortality.ts
apps/modernization-ui/src/apps/patient/file/demographics/patient-file-demographics.module.scss
apps/modernization-ui/src/libs/patient/demographics/mortality/edit/MortalityDemographicFields.spec.tsx
apps/modernization-ui/src/libs/patient/demographics/mortality/edit/MortalityDemographicFields.tsx
apps/modernization-ui/src/libs/patient/demographics/mortality/edit/index.ts
apps/modernization-ui/src/libs/patient/demographics/mortality/edit/useMortalityOptions.ts
apps/modernization-ui/src/libs/patient/demographics/mortality/index.ts
apps/modernization-ui/src/libs/patient/demographics/mortality/mortality.ts
apps/modernization-ui/src/libs/patient/demographics/mortality/view/MortalityDemographicCard.tsx
apps/modernization-ui/src/libs/patient/demographics/mortality/view/MortalityDemographicView.spec.tsx
apps/modernization-ui/src/libs/patient/demographics/mortality/view/MortalityDemographicView.tsx
apps/modernization-ui/src/libs/patient/demographics/mortality/view/index.ts

Adds the "Mortality" card to the "Demographics" tab of the Patient file.
* [CNFT1-4234](https://cdc-nbs.atlassian.net/browse/CNFT1-4234)
[CNFT1-4234]: https://cdc-nbs.atlassian.net/browse/CNFT1-4234?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-4234] Patient file: demographics Mortality

---

apps/modernization-ui/src/apps/patient/file/demographics/PatientFileDemographics.tsx
apps/modernization-ui/src/apps/patient/file/demographics/demographics.ts
apps/modernization-ui/src/apps/patient/file/demographics/race/PatientFileRaceCard.tsx
apps/modernization-ui/src/apps/patient/file/demographics/race/patientRace.ts
apps/modernization-ui/src/libs/patient/demographics/race/RaceDemographicCard.tsx
apps/modernization-ui/src/libs/patient/demographics/race/RaceDemographicFields.tsx
apps/modernization-ui/src/libs/patient/demographics/race/RaceDemographicView.spec.tsx
apps/modernization-ui/src/libs/patient/demographics/race/RaceDemographicView.tsx
apps/modernization-ui/src/libs/patient/demographics/race/index.ts
apps/modernization-ui/src/libs/patient/demographics/race/race-demographic-card.module.scss
apps/modernization-ui/src/libs/patient/demographics/race/race.ts
apps/modernization-ui/src/libs/patient/demographics/race/useRaceCodedValues.ts

Race card 
* [CNFT1-4200](https://cdc-nbs.atlassian.net/browse/CNFT1-4200)
[CNFT1-4200]: https://cdc-nbs.atlassian.net/browse/CNFT1-4200?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Cnft1 4200 race card

---

apps/nbs-gateway/README.md
apps/nbs-gateway/src/main/java/gov/cdc/nbs/gateway/system/management/SystemManagementPageRouteLocatorConfiguration.java
apps/nbs-gateway/src/main/resources/application.yml
apps/nbs-gateway/src/test/java/gov/cdc/nbs/gateway/system/management/SystemManagementPageRouteLocatorConfigurationDisabledTest.java
apps/nbs-gateway/src/test/java/gov/cdc/nbs/gateway/system/management/SystemManagementPageRouteLocatorConfigurationEnabledTest.java

The `nbs-gateway` needs to be updated to have a configurable route override for the system management page to redirect to the modernized System management
* [CND-363](https://cdc-nbs.atlassian.net/browse/CND-363?atlOrigin=eyJpIjoiZWEzMDI5NzJlYjlhNDU1ZDk0ZDI3MzQxY2I5YWMwYWYiLCJwIjoiaiJ9)
[CND-363]: https://cdc-nbs.atlassian.net/browse/CND-363?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FeatureFlag: System Management Routing

---

apps/modernization-ui/src/apps/patient/file/demographics/administrative/PatientFileAdministrativeInformationCard.tsx
apps/modernization-ui/src/apps/patient/file/summary/documentRequiringReview/PatientDocumentRequiringReviewCard.tsx
apps/modernization-ui/src/libs/patient/demographics/administrative/AdministrativeInformationCard.spec.tsx
apps/modernization-ui/src/libs/patient/demographics/administrative/AdministrativeInformationCard.tsx

2 titles changes very slightly
* [CNFT1-4309](https://cdc-nbs.atlassian.net/browse/CNFT1-4309)
* [CNFT1-4275](https://cdc-nbs.atlassian.net/browse/CNFT1-4275)
[CNFT1-4309]: https://cdc-nbs.atlassian.net/browse/CNFT1-4309?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CNFT1-4275]: https://cdc-nbs.atlassian.net/browse/CNFT1-4275?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2 bug fixes, fixing titles of cards

---

apps/modernization-ui/src/page/scrollToTop/ScrollToTop.tsx

removing unneeded role of main since group is announced by default as needed without it and it causes axe issues
* [https://cdc-nbs.atlassian.net/browse/CNFT1-4315](https://cdc-nbs.atlassian.net/browse/CNFT1-4315)

removing unneeded role of main since group is anmounced by default as needed without it and it causes axe issues

---

apps/modernization-ui/src/apps/system-management/components/security/SecuritySection.tsx

Bug 🐞: Spelling mistake in system/management permissions for Security Card
N/A

Spelling mistake: Permissions

---

apps/modernization-ui/src/apps/deduplication/api/usePatientMerge.ts
apps/modernization-ui/src/apps/deduplication/patient-merge/details/MergeDetails.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-preview/MergePreview.spec.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-preview/MergePreview.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-review/MergeReview.spec.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-review/MergeReview.tsx

Enables the Merge button
* [CND-275](https://cdc-nbs.atlassian.net/browse/CND-275)
[CND-275]: https://cdc-nbs.atlassian.net/browse/CND-275?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Cnd 275 merge button

---

apps/modernization-ui/src/apps/deduplication/configuration/MatchConfigurationLandingPage.tsx
apps/modernization-ui/src/apps/deduplication/configuration/import/ImportConfigurationModal.spec.tsx
apps/modernization-ui/src/apps/deduplication/configuration/import/ImportConfigurationModal.tsx
apps/modernization-ui/src/apps/deduplication/configuration/import/importModal/import-modal.module.scss
apps/modernization-ui/src/apps/deduplication/configuration/match-configuration/header/PersonMatchHeader.tsx
apps/modernization-ui/src/apps/deduplication/configuration/match-configuration/pass-configuration/pass-form/blocking-criteria/panel/blocking-criteria-panel.module.scss
apps/modernization-ui/src/apps/deduplication/configuration/match-configuration/pass-configuration/pass-form/matching-bounds/MatchingBounds.tsx
apps/modernization-ui/src/apps/deduplication/configuration/match-configuration/pass-configuration/pass-form/matching-bounds/matching-bounds.module.scss
apps/modernization-ui/src/apps/deduplication/configuration/match-configuration/pass-configuration/pass-form/matching-criteria/attribute/MatchingCriteriaAttribute.tsx
apps/modernization-ui/src/apps/deduplication/configuration/match-configuration/pass-configuration/pass-form/matching-criteria/attribute/matching-criteria-attribute.module.scss
apps/modernization-ui/src/apps/deduplication/configuration/match-configuration/pass-configuration/pass-form/matching-criteria/matching-criteria.module.scss
apps/modernization-ui/src/apps/deduplication/configuration/match-configuration/pass-configuration/pass-list/pass-entry/PassEntry.spec.tsx
apps/modernization-ui/src/apps/deduplication/configuration/match-configuration/pass-configuration/pass-list/pass-entry/PassEntry.tsx
apps/modernization-ui/src/apps/deduplication/configuration/match-configuration/pass-configuration/pass-list/pass-entry/pass-entry.module.scss
apps/modernization-ui/src/apps/deduplication/configuration/match-configuration/pass-configuration/pass-list/pass-list.module.scss
apps/modernization-ui/src/design-system/hint/hint.module.scss
apps/modernization-ui/src/shared/header/NavBar.module.scss

Addresses several small styling issues discovered during a design review
* [CND-365](https://cdc-nbs.atlassian.net/browse/CND-365)
Pass configuration list top padding (was 1.5rem, should be 1rem)
Pass configuration list heading should not have a border bottom. border-top should be on list component
Pass list entries should have a bottom border
Pass list edit icon should only show on hover
Edit icon needs tooltip (Edit name)
Threshold info icons are not vertically aligned center
Matching criteria - Label / log odds - needs to be vertically center aligned
Threshold numeric input width needs to be increased to 6rem (was 5.5)
Total logs odds - make this appear vertically center aligned with the input (add padding-top:  1.5rem estimated)
Blocking criteria side panel - gap on both sides should …

Cnd 365 design review pt2

---

apps/modernization-api/src/main/java/gov/cdc/nbs/patient/events/tests/ResultedTestResolver.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/events/tests/ResultedTestRowMapper.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/events/tests/ResultedTestRowMapperTest.java

Now displaying the separator as well for numeric result
* [CNFT1-4332](https://cdc-nbs.atlassian.net/browse/CNFT1-4332)
[CNFT1-4332]: https://cdc-nbs.atlassian.net/browse/CNFT1-4332?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Bug fix for resulted test DRR and Labreport

---

apps/modernization-ui/src/apps/patient/file/events/investigations/PatientFileInvestigationsCard.tsx
apps/modernization-ui/src/apps/patient/file/events/investigations/investigations.module.scss
apps/modernization-ui/src/apps/patient/file/events/reports/laboratory/PatientFileLaboratoryReportsCard.tsx
apps/modernization-ui/src/apps/patient/file/events/reports/laboratory/lab-reports.module.scss
apps/modernization-ui/src/apps/patient/file/summary/documentRequiringReview/PatientDocumentRequiringReviewCard.tsx
apps/modernization-ui/src/apps/patient/file/summary/documentRequiringReview/drr.module.scss
apps/modernization-ui/src/apps/patient/file/summary/openInvestigations/PatientFileOpenInvestigationsCard.tsx
apps/modernization-ui/src/apps/patient/file/summary/openInvestigations/open-investigations.module.scss
apps/modernization-ui/src/apps/search/patient/result/table/patient-search-result-table.module.scss
apps/modernization-ui/src/design-system/table/data-table.module.scss
apps/modernization-ui/src/design-system/table/header/_widths.scss

Applies column widths to the "Documents requiring review", "Open investigations", "Investigations", and "Lab report" tables.
* [CNFT1-4220](https://cdc-nbs.atlassian.net/browse/CNFT1-4220)
* [CNFT1-4221](https://cdc-nbs.atlassian.net/browse/CNFT1-4221)
* [CNFT1-4157](https://cdc-nbs.atlassian.net/browse/CNFT1-4157)
* [CNFT1-4257](https://cdc-nbs.atlassian.net/browse/CNFT1-4257)
[CNFT1-4220]: https://cdc-nbs.atlassian.net/browse/CNFT1-4220?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CNFT1-4221]: https://cdc-nbs.atlassian.net/browse/CNFT1-4221?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CNFT1-4157]: https://cdc-nbs.atlassian.net/browse/CNFT1-4157?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y …

[CNFT1-4220] Patient file column widths

---

apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-preview/components/address/PreviewAddress.spec.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-preview/components/address/PreviewAddress.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-preview/components/identification/PreviewIdentification.spec.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-preview/components/identification/PreviewIdentification.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-preview/components/name/PreviewName.spec.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-preview/components/name/PreviewName.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-preview/components/phone-and-email/PreviewPhoneAndEmail.spec.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-preview/components/phone-and-email/PreviewPhoneAndEmail.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-preview/components/race/PreviewRace.spec.tsx

Fixes some date format issues when sorting. Adds some tests to ensure sort is valid.
* [CND-385](https://cdc-nbs.atlassian.net/browse/CND-385)
[CND-385]: https://cdc-nbs.atlassian.net/browse/CND-385?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Merge preview - sort

---

apps/modernization-api/src/main/java/gov/cdc/nbs/patient/events/tests/ResultedTestResolver.java
apps/modernization-api/src/test/java/gov/cdc/nbs/event/report/lab/test/TextResultedTestMother.java
apps/modernization-ui/src/apps/patient/file/summary/documentRequiringReview/PatientDocumentRequiringReviewCard.tsx

2 Bugs dealt with:
1. Report date added for morbidity reports
2. Text results not displaying
* [CNFT1-4347](https://cdc-nbs.atlassian.net/browse/CNFT1-4347)
* [CNFT1-4348](https://cdc-nbs.atlassian.net/browse/CNFT1-4348)
[CNFT1-4347]: https://cdc-nbs.atlassian.net/browse/CNFT1-4347?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CNFT1-4348]: https://cdc-nbs.atlassian.net/browse/CNFT1-4348?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-4347] DRR Bugs

---

apps/modernization-ui/package-lock.json
apps/modernization-ui/src/apps/deduplication/data-elements/validation/DataElementValidationError.tsx
apps/modernization-ui/src/apps/page-builder/page/management/edit/tabs/ManageTabsTile/ManageTabsTile.tsx
apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/ViewBusinessRule/ViewBusinessRule.tsx
apps/modernization-ui/src/apps/patient/file/PatientFileRouting.tsx
apps/modernization-ui/src/apps/patient/file/renderPatientFile.tsx
apps/modernization-ui/src/libs/events/reports/morbidity/TreatmentList.tsx
apps/modernization-ui/src/libs/guard/Guarded.tsx
apps/modernization-ui/src/libs/guard/GuardedLayout.tsx

Removes the default fallback `RedirectHome` from `Guard` and adds it as the `fallback` of `GuardedLayout`.

[FIX] Guarded default fallback

---

apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-preview/components/shared/preview-card-lined/LinedMergePreviewCard.module.scss

Made a mistake in styling for Preview Screen card

Redo Styling

---

apps/modernization-ui/src/apps/patient/file/events/treatments/patientTreatments.ts

Fixes a bad import that prevents `npm run start` from loading the application.

Fix - bad import

---

apps/modernization-api/src/main/java/gov/cdc/nbs/patient/file/demographics/mortality/PatientMortalityDemographicRowMapper.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/file/demographics/sex_birth/PatientSexBirthDemographicFinder.java

Mortality and Sex & Birth enhancements
* [CNFT1-4334](https://cdc-nbs.atlassian.net/browse/CNFT1-4334)
* [CNFT1-4335](https://cdc-nbs.atlassian.net/browse/CNFT1-4335)
[CNFT1-4334]: https://cdc-nbs.atlassian.net/browse/CNFT1-4334?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CNFT1-4335]: https://cdc-nbs.atlassian.net/browse/CNFT1-4335?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Mortality and Sex & Birth enhancements

---

apps/modernization-ui/src/apps/patient/file/events/reports/morbidity/PatientFileMorbidityReportsCard.tsx
apps/modernization-ui/src/apps/patient/file/summary/documentRequiringReview/PatientDocumentRequiringReviewCard.tsx
apps/modernization-ui/src/libs/classic/ClassicModalContext.tsx
apps/modernization-ui/src/libs/classic/classic-modal.module.scss

Restores the padding to Patient file > Events that was removed due to change with 
* [CNFT1-4048](https://cdc-nbs.atlassian.net/browse/CNFT1-4048)
[CNFT1-4048]: https://cdc-nbs.atlassian.net/browse/CNFT1-4048?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-4048] Fix patient file event padding

---

apps/modernization-ui/src/apps/patient/file/events/treatments/PatientFileTreatmentsCard.tsx
apps/modernization-ui/src/apps/patient/file/events/treatments/treatments.module.scss
apps/modernization-ui/src/apps/patient/file/events/vaccinations/PatientFileVaccinationsCard.tsx
apps/modernization-ui/src/apps/patient/file/events/vaccinations/patient-file-vaccinations.module.scss
apps/modernization-ui/src/apps/patient/file/events/vaccinations/transformer.ts
apps/modernization-ui/src/apps/patient/file/events/vaccinations/vaccinations.ts

2 bug fixes in this PR
1. Administered wording
2. Browser modal for treatments
* [CNFT1-4047](https://cdc-nbs.atlassian.net/browse/CNFT1-4047)
* [CNFT1-4049](https://cdc-nbs.atlassian.net/browse/CNFT1-4049)
[CNFT1-4047]: https://cdc-nbs.atlassian.net/browse/CNFT1-4047?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CNFT1-4049]: https://cdc-nbs.atlassian.net/browse/CNFT1-4049?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Bug fixes treatment vaccination

---

apps/modernization-ui/src/apps/deduplication/api/model/MatchRequiringReview.ts
apps/modernization-ui/src/apps/deduplication/api/usePatientMerge.ts
apps/modernization-ui/src/apps/deduplication/api/useRemoveMerge.ts
apps/modernization-ui/src/apps/deduplication/patient-merge/landing/matches-requiring-review-table/MatchesRequiringReviewTable.spec.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/landing/matches-requiring-review-table/MatchesRequiringReviewTable.tsx

Adjusts the ui model to match some backend adjustments
* [CND-410](https://cdc-nbs.atlassian.net/browse/CND-410)
[CND-410]: https://cdc-nbs.atlassian.net/browse/CND-410?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix type to match adjusted API

---

apps/modernization-api/src/main/java/gov/cdc/nbs/patient/events/tests/ResultedTestRowMapper.java
apps/modernization-ui/src/apps/patient/file/summary/documentRequiringReview/PatientDocumentRequiringReviewCard.tsx

1. Labels added for event date
2. Order for resulted test
* [CNFT1-4355](https://cdc-nbs.atlassian.net/browse/CNFT1-4355)
* [CNFT1-4354](https://cdc-nbs.atlassian.net/browse/CNFT1-4354)
[CNFT1-4355]: https://cdc-nbs.atlassian.net/browse/CNFT1-4355?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CNFT1-4354]: https://cdc-nbs.atlassian.net/browse/CNFT1-4354?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DRR enhancements

---

apps/modernization-ui/src/apps/patient/file/events/reports/morbidity/PatientFileMorbidityReportsCard.tsx

* [CNFT1-4373](https://cdc-nbs.atlassian.net/browse/CNFT1-4373)
[CNFT1-4373]: https://cdc-nbs.atlassian.net/browse/CNFT1-4373?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Morbidity facility/provider labels

---

apps/modernization-ui/src/libs/patient/demographics/administrative/edit/AdministrativeInformationFields.spec.tsx
apps/modernization-ui/src/libs/patient/demographics/administrative/edit/AdministrativeInformationFields.tsx

Administrative comments card for edit
* [CNFT1-4076](https://cdc-nbs.atlassian.net/browse/CNFT1-4076)
[CNFT1-4076]: https://cdc-nbs.atlassian.net/browse/CNFT1-4076?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT1 4121 administrative edit page

---

.github/workflows/sonar.yaml

Updates the sonar scan to pass the updated container tag to the test command.

Update test container to latest

---

apps/modernization-ui/src/apps/patient/file/events/PatientFileEvents.tsx
apps/modernization-ui/src/apps/patient/file/events/contactsNamed/PatientFileContactsNamedCard.tsx
apps/modernization-ui/src/apps/patient/file/events/contactsNamed/patientContacts.ts
apps/modernization-ui/src/apps/patient/file/events/events.ts
apps/modernization-ui/src/apps/patient/file/events/patientsNamed/PatientFilePatientsNamedCard.tsx
apps/modernization-ui/src/apps/patient/file/events/patientsNamed/patientNamed.ts
apps/modernization-ui/src/libs/events/contacts/ContactsCard.tsx
apps/modernization-ui/src/libs/events/contacts/contactsNamed.ts

* [CNFT1-4055](https://cdc-nbs.atlassian.net/browse/CNFT1-4055)
[CNFT1-4055]: https://cdc-nbs.atlassian.net/browse/CNFT1-4055?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT1-4055-patient-named

---

apps/modernization-ui/src/libs/patient/demographics/name/NameDemographicFields.spec.tsx
apps/modernization-ui/src/libs/patient/demographics/name/NameDemographicFields.tsx

* [CNFT1-4364](https://cdc-nbs.atlassian.net/browse/CNFT1-4364)
[CNFT1-4364]: https://cdc-nbs.atlassian.net/browse/CNFT1-4364?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-4364] Patient file Edit: Name

---

apps/modernization-ui/src/apps/patient/file/summary/documentRequiringReview/PatientDocumentRequiringReviewCard.tsx

Dashes fix
* [CNFT1-4355](https://cdc-nbs.atlassian.net/browse/CNFT1-4355)
[CNFT1-4355]: https://cdc-nbs.atlassian.net/browse/CNFT1-4355?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT1-4355 [FIX] - Dashes event date

---

apps/modernization-ui/src/design-system/field/value/value-field.module.scss
apps/modernization-ui/src/libs/patient/demographics/sex-birth/edit/SexBirthDemographicFields.spec.tsx
apps/modernization-ui/src/libs/patient/demographics/sex-birth/edit/SexBirthDemographicFields.tsx

* [CNFT1-4385](https://cdc-nbs.atlassian.net/browse/CNFT1-4385)
[CNFT1-4385]: https://cdc-nbs.atlassian.net/browse/CNFT1-4385?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT1-4385 -> Sex Birth Edit UI

---

apps/modernization-ui/src/design-system/card/collapsible.module.scss
apps/modernization-ui/src/libs/patient/demographics/address/edit/EditAddressDemographicsCard.tsx
apps/modernization-ui/src/libs/patient/demographics/phoneEmail/PhoneEmailDemographicCard.tsx
apps/modernization-ui/src/libs/patient/demographics/phoneEmail/PhoneEmailDemographicRepeatingBlock.tsx
apps/modernization-ui/src/libs/patient/demographics/phoneEmail/edit/EditPhoneEmailDemographicsCard.tsx
apps/modernization-ui/src/libs/patient/demographics/phoneEmail/edit/PhoneEmailDemographicFields.spec.tsx
apps/modernization-ui/src/libs/patient/demographics/phoneEmail/edit/PhoneEmailDemographicFields.tsx
apps/modernization-ui/src/libs/patient/demographics/phoneEmail/edit/usePhoneEmailOptions.ts
apps/modernization-ui/src/libs/patient/demographics/phoneEmail/index.ts
apps/modernization-ui/src/libs/patient/demographics/phoneEmail/phone-email-demographic-card.module.scss
apps/modernization-ui/src/libs/patient/demographics/phoneEmail/phone-email-demographic-repeating-block.module.scss
apps/modernization-ui/src/libs/patient/demographics/phoneEmail/phoneEmails.ts

Ensures that the Phone & email card on Patient file edit has the correct labels and validation
* [CNFT1-4375](https://cdc-nbs.atlassian.net/browse/CNFT1-4375)
[CNFT1-4375]: https://cdc-nbs.atlassian.net/browse/CNFT1-4375?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-4375] Patient file edit > Phone & email

---

apps/modernization-ui/src/libs/patient/demographics/mortality/edit/MortalityDemographicFields.spec.tsx
apps/modernization-ui/src/libs/patient/demographics/mortality/edit/MortalityDemographicFields.tsx
apps/modernization-ui/src/libs/patient/demographics/mortality/mortality.ts
apps/modernization-ui/src/libs/patient/demographics/mortality/view/MortalityDemographicView.spec.tsx

* [CNFT1-4387](https://cdc-nbs.atlassian.net/browse/CNFT1-4387)
[CNFT1-4387]: https://cdc-nbs.atlassian.net/browse/CNFT1-4387?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT1-4387 -> Mortality Edit Card

---

apps/modernization-api/src/main/java/gov/cdc/nbs/patient/file/events/contact/PatientFileContactNamedByPatientFinder.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/file/events/contact/PatientFilePatientNamedByContactFinder.java

* [CNFT1-4408](https://cdc-nbs.atlassian.net/browse/CNFT1-4408)
[CNFT1-4408]: https://cdc-nbs.atlassian.net/browse/CNFT1-4408?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT1-4408 [FIX] First middle last suffix

---

apps/modernization-ui/src/apps/patient/file/events/contacts/ContactsCard.tsx

Card is collapsed if it is empty
* [CNFT1-4054](https://cdc-nbs.atlassian.net/browse/CNFT1-4054)
[CNFT1-4054]: https://cdc-nbs.atlassian.net/browse/CNFT1-4054?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Contact named collapse by deafult on empty card [FIX]

---

apps/modernization-ui/package-lock.json
apps/modernization-ui/package.json
apps/modernization-ui/src/apps/patient/file/edit/PatientFileEdit.tsx
apps/modernization-ui/src/apps/patient/file/edit/evaluated.ts
apps/modernization-ui/src/design-system/entry/navigation-guard/NavigationGuard.tsx
apps/modernization-ui/src/navigation/useFormNavigationBlock.ts
apps/modernization-ui/src/navigation/useNavigationBlock.ts

Makes the Patient file edit "Cancel" functionality a little better.  If there are no changes the "Cancel" will return the user to the previous page (like a back button).  There is an issue blocking the modal from the `NavigationGuard`.
* [CNFT1-4116](https://cdc-nbs.atlassian.net/browse/CNFT1-4116)
[CNFT1-4116]: https://cdc-nbs.atlassian.net/browse/CNFT1-4116?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-4116] Patient edit cancel

---

apps/modernization-ui/src/libs/patient/demographics/ethnicity/edit/EthnicityDemographicFields.tsx

Ethnicity details now only clear when the selected ethnicity is not "Hispanic or Latino".
* [CNFT1-4095](https://cdc-nbs.atlassian.net/browse/CNFT1-4095)
[CNFT1-4095]: https://cdc-nbs.atlassian.net/browse/CNFT1-4095?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-4095] Patient file edit > Ethnicity details clear 

---

apps/modernization-ui/src/design-system/table/header/column-header.module.scss

Ensures that a labeled column header has a visible background and non-visible text.

[FIX] DataTable Actions header

---

apps/modernization-ui/src/apps/patient/file/summary/documentRequiringReview/PatientDocumentRequiringReviewCard.tsx
apps/modernization-ui/src/design-system/tag/Tag.tsx
apps/modernization-ui/src/design-system/tag/tag.module.scss
apps/modernization-ui/src/styles/_colors.scss

* [CNFT1-4417](https://cdc-nbs.atlassian.net/browse/CNFT1-4417)
[CNFT1-4417]: https://cdc-nbs.atlassian.net/browse/CNFT1-4417?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT1 4417 Electronic tag

---

apps/modernization-ui/src/design-system/field/horizontal-field.module.scss
apps/modernization-ui/src/shared/header/NavBar.module.scss

Fixes the label spacing for small horizontal fields.

[FIX] Horizontal field label sizing

---

apps/modernization-ui/src/apps/patient/file/summary/documentRequiringReview/PatientDocumentRequiringReviewCard.tsx
apps/modernization-ui/src/apps/patient/file/summary/documentRequiringReview/drr.module.scss
apps/modernization-ui/src/design-system/tag/Tag.tsx
apps/modernization-ui/src/design-system/tooltip/Tooltip.tsx
apps/modernization-ui/src/design-system/tooltip/tooltip.module.scss

* [CNFT1-4417](https://cdc-nbs.atlassian.net/browse/CNFT1-4417)
[CNFT1-4417]: https://cdc-nbs.atlassian.net/browse/CNFT1-4417?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT1 4417 Electronic indicator tooltip

---

apps/modernization-ui/package-lock.json
apps/modernization-ui/package.json
apps/modernization-ui/src/components/selection/multi/MultiSelectAutocomplete.tsx
apps/modernization-ui/src/components/selection/multi/MultiSelectInput.tsx
apps/modernization-ui/src/design-system/select/multi/MultiSelect.tsx
apps/modernization-ui/src/design-system/select/multi/multi-select.scss

The styles for the `MultiSelect` component were being pull from a separate component, they are now defined with the `design-system/select/multi` folder.

[FIX] Restores the multi-select styles

---

libs/database-entities/src/main/java/gov/cdc/nbs/entity/odse/EntityLocatorParticipation.java
libs/database-entities/src/main/java/gov/cdc/nbs/entity/odse/PostalEntityLocatorParticipation.java
libs/database-entities/src/main/java/gov/cdc/nbs/entity/odse/PostalLocator.java
libs/database-entities/src/main/java/gov/cdc/nbs/entity/odse/TeleEntityLocatorParticipation.java

Ensures that birth and death locations are only updated when needed to prevent the creation of duplicate history records.

[FIX] Locator history for Birth and Death place

---

apps/modernization-ui/package-lock.json
apps/modernization-ui/src/libs/patient/demographics/address/edit/AddressDemographicFields.spec.tsx
apps/modernization-ui/src/libs/patient/demographics/address/edit/AddressDemographicFields.tsx

Ensures that the "Comments" field on the "Address" card in edit mode of the Patient file displays in-line validations when the field is not valid.
* [CNFT1-4078](https://cdc-nbs.atlassian.net/browse/CNFT1-4078)
[CNFT1-4078]: https://cdc-nbs.atlassian.net/browse/CNFT1-4078?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-4078] Address Comments in-line validations

---

.github/workflows/Build-and-deploy-modernization-api.yaml
.github/workflows/Build-and-deploy-nbs-gateway.yaml
.github/workflows/Build-and-deploy-page-builder-api.yaml

Changes "Build and deploy" workflows to trigger when dependencies change.

[FIX] "Build and deploy" workflows trigger on dependency change
