- patient-search/ui/package-lock.json
- patient-search/ui/package.json
- patient-search/ui/src/components/EventSearch/EventSearch.tsx
- patient-search/ui/src/components/EventSearch/EventType.tsx
- patient-search/ui/src/components/EventSearch/SearchCriteria.tsx
- patient-search/ui/src/components/EventSearch/generalSearch.tsx
- patient-search/ui/src/components/FormInputs/CheckBoxControl.tsx
- patient-search/ui/src/components/FormInputs/MultiSelectControl.tsx
- patient-search/ui/src/components/FormInputs/SelectControl.tsx
- patient-search/ui/src/components/FormInputs/SelectInput.tsx
- patient-search/ui/src/pages/advancedSearch/AdvancedSearch.scss
- patient-search/ui/src/pages/advancedSearch/AdvancedSearch.tsx
- patient-search/ui/src/pages/advancedSearch/SearchItems.tsx
- patient-search/ui/src/providers/SearchCriteriaContext.tsx
- patient-search/ui/src/routes/AppRoutes.tsx
- patient-search/ui/src/utils/util.ts
Print and Export 
Error Message 
Fields for Investigation Criteria (pending to add 2) -> Investigator and Investigator Selected
Fields for general search
> Event search UI

- .dockerignore
- .github/workflows/dockerfile-to-ecr.yaml
- apps/modernization-api/Dockerfile
- apps/modernization-api/README.md
- apps/modernization-api/build.gradle
- apps/modernization-api/src/main/resources/application.yml
- apps/modernization-api/src/test/resources/application-test.yml
- docker-compose.yml
* externalizes modernization-api configuration
* reduces footprint of modernization-api container
* ensures that the ui is also built
* ensures that the ui is built when modernization-api container is built
> Modernization-api externalized configuration (#102)

- apps/modernization-api/build.gradle
Modernization-api build now creates one jar
> combines spring build into one jar

- apps/modernization-ui/src/pages/advancedSearch/AdvancedSearch.tsx
We'll need a ticket to make a selected/active state for the Button component.
> CNPT-949 Hide Sortby on selection

- .github/workflows/Build-common-asset-server.yaml
- .github/workflows/Build-elasticsearch.yaml
- .github/workflows/Build-modernization-api.yaml
- .github/workflows/Build-nifi.yaml
- .github/workflows/dockerfile-to-ecr.yaml
The updates contained in this PR do not remove any current build processes. They are to set up our builds to be closer to microservices architecture. 
When reviewing please look at the build related to the modernization-api. Build triggers were left intentionally broad so dev team could adjust if needed.
> Sgz update container build process

- apps/modernization-ui/src/pages/advancedSearch/components/PatientResults.tsx
I think this looks ok and adheres to the tickets requests, but I might be wrong 😬
> CNFT1-1 Fields as headings patient search

- apps/modernization-ui/src/components/FormInputs/Input.tsx
- apps/modernization-ui/src/components/FormInputs/PhoneNumberInput/PhoneNumberInput.spec.tsx
- apps/modernization-ui/src/components/FormInputs/PhoneNumberInput/PhoneNumberInput.tsx
- apps/modernization-ui/src/pages/advancedSearch/components/patientSearch/ContactForm.tsx
- apps/modernization-ui/src/pages/advancedSearch/components/patientSearch/PatientSearch.tsx
- apps/modernization-ui/src/utils/PhoneValidation.ts
This blocks searching with non numerical numbers.
From 1 to 10 digits can be searched, 10 digit with formatting is allowed.
Another ticket will need to be made for international numbers
> CNPT-944 Phone number special characters

- apps/modernization-ui/src/pages/advancedSearch/components/InvestigationResults.tsx
- apps/modernization-ui/src/pages/advancedSearch/components/LabReportResults.tsx
- apps/modernization-ui/src/pages/advancedSearch/components/PatientResults.tsx
- apps/modernization-ui/src/pages/patientProfile/PatientProfile.tsx
> - fixing redirection for patient-profile

- README.md
- docs/Package-By-Feature.md
Adds guidelines to project documentation to suggest packaging by feature
> Adds guildelines to project documentation to suggest packaging by feature

- apps/modernization-ui/src/components/FormInputs/DatePickerInput.tsx
- apps/modernization-ui/src/pages/advancedSearch/AdvancedSearch.scss
- apps/modernization-ui/src/pages/advancedSearch/AdvancedSearch.spec.tsx
- apps/modernization-ui/src/pages/advancedSearch/AdvancedSearch.tsx
- apps/modernization-ui/src/pages/advancedSearch/components/InvestigationResults.tsx
- apps/modernization-ui/src/pages/advancedSearch/components/PatientResults.tsx
- apps/modernization-ui/src/settings.scss
- apps/modernization-ui/src/styles/_typography.scss
- apps/modernization-ui/src/styles/_uswds.scss
Big change is some trussworks styling overrides and other styling tweaks in the /styles/ folder.
Also fixed a DatePicker unit test in this branch.
> CNFT1-362 No results / Add new button

- apps/modernization-api/src/main/java/gov/cdc/nbs/graphql/filter/PatientFilter.java
- apps/modernization-api/src/main/java/gov/cdc/nbs/service/RedirectionService.java
- apps/modernization-api/src/test/java/gov/cdc/nbs/EncryptionSteps.java
- apps/modernization-api/src/test/java/gov/cdc/nbs/PatientSearchSteps.java
- apps/modernization-api/src/test/java/gov/cdc/nbs/PermissionSteps.java
- apps/modernization-api/src/test/java/gov/cdc/nbs/RedirectSteps.java
- apps/modernization-api/src/test/java/gov/cdc/nbs/services/FindMorbidityReportsForPatientTest.java
- apps/modernization-api/src/test/resources/features/Redirect.feature
Fix redirect missing RecordStatus value. Add redirect test to ensure search is successful
> On redirect set RecordStatus

- apps/modernization-ui/src/components/FormInputs/Input.scss
- apps/modernization-ui/src/components/FormInputs/Input.tsx
- apps/modernization-ui/src/components/FormInputs/PhoneNumberInput/PhoneNumberInput.spec.tsx
- apps/modernization-ui/src/components/FormInputs/PhoneNumberInput/PhoneNumberInput.tsx
- apps/modernization-ui/src/pages/advancedSearch/AdvancedSearch.scss
- apps/modernization-ui/src/pages/advancedSearch/AdvancedSearch.tsx
- apps/modernization-ui/src/pages/advancedSearch/components/PatientResults.tsx
- apps/modernization-ui/src/pages/advancedSearch/components/patientSearch/AddressForm.spec.tsx
- apps/modernization-ui/src/pages/advancedSearch/components/patientSearch/AddressForm.tsx
- apps/modernization-ui/src/pages/advancedSearch/components/patientSearch/ContactForm.tsx
- apps/modernization-ui/src/pages/advancedSearch/components/patientSearch/PatientSearch.tsx
- apps/modernization-ui/src/styles/_uswds.scss
- apps/modernization-ui/src/utils/PhoneValidation.ts
- apps/modernization-ui/src/utils/ZipValidation.ts
Most fields can really be anything. DatePicker already implemented so this PR adds validation for:
- phone
- zip
- email
Unit tests
(Would love to merge this before Thomas' demo Monday)
> CNFT1-361 Data entry: Invalid input error

- apps/modernization-ui/src/components/Spinner/Spinner.scss
- apps/modernization-ui/src/components/Spinner/Spinner.tsx
- apps/modernization-ui/src/routes/AppRoutes.tsx
- apps/modernization-ui/src/shared/header/NavBar.tsx
Absurdly simple fix but works:
- * routes lead to Login when not logged in
- * routes lead to AdvancedSearch when logged in
> CNFT1-666 Login page redirect

- apps/modernization-ui/src/components/FormInputs/DatePickerInput.spec.tsx
- apps/modernization-ui/src/components/FormInputs/DatePickerInput.tsx
- apps/modernization-ui/src/pages/advancedSearch/AdvancedSearch.tsx
- apps/modernization-ui/src/pages/advancedSearch/components/eventSearch/EventSearch.tsx
- apps/modernization-ui/src/pages/advancedSearch/components/patientSearch/PatientSearch.tsx
- apps/modernization-ui/src/pages/patientProfile/PatientProfile.tsx
In this PR I have pushed changes related to Cnft1 649, CNFT1-661, CNFT1-314.
Fixed clear all button in Event Search page,
Fixed date picker input not being entered added validation on blur instead of every change
Added print functionality for patient-profile
Fixed failing unit test cases
> Cnft1 649 event search  clear all button takes to patient search v2

- apps/modernization-ui/package.json
- apps/modernization-ui/src/components/FormInputs/MultiSelectControl.scss
- apps/modernization-ui/src/components/FormInputs/MultiSelectControl.tsx
- apps/modernization-ui/src/pages/advancedSearch/AdvancedSearch.tsx
- apps/modernization-ui/src/pages/advancedSearch/components/eventSearch/GeneralSearch.tsx
- apps/modernization-ui/src/pages/advancedSearch/components/eventSearch/LabGeneralSearch.tsx
- apps/modernization-ui/src/pages/advancedSearch/components/eventSearch/SearchCriteria.tsx
This updates the multi-select dropdown with the `react-select` component.
This enables:
- Clear all fields
- No default selection
- better UI
> Cnft1 715 update multi select dropdown component

- CODEOWNERS
Using this: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners as a guide, I created the CODEOWNERS file which should automatically include the team/tech leads in PRs
> Cnft1 769 create code owner code in git for code review process

- apps/modernization-ui/src/mixins/_viewports.scss
- apps/modernization-ui/src/settings.scss
- apps/modernization-ui/src/styles/_uswds.scss
Adding horizontal scroll to table rows--in this case 1024px viewport width.
Added viewport breakpoint mixins.
> CNFT1-768 Horizontal scrollbars Patient Profile

- .github/workflows/sonar.yaml
- apps/modernization-api/build.gradle
- apps/modernization-api/src/test/java/gov/cdc/nbs/containers/database/NbsDatabaseContainer.java
- apps/modernization-api/src/test/java/gov/cdc/nbs/containers/database/NbsTestDatabaseInitializer.java
- apps/modernization-api/src/test/resources/application-test.yml
- cdc-sandbox/test-db/Dockerfile
Removes the Cucumber test filter so they are executed during sonar scan.
> Remove cucumber test filter

- apps/modernization-ui/src/components/Table/SortableTable.tsx
- apps/modernization-ui/src/pages/addPatient/components/SuccessForm/SuccessForm.tsx
- apps/modernization-ui/src/pages/patient/profile/PatientProfile.tsx
- apps/modernization-ui/src/pages/patient/profile/addresses/AddressModal.tsx
- apps/modernization-ui/src/pages/patient/profile/addresses/AddressesTable.tsx
- apps/modernization-ui/src/pages/patient/profile/addresses/DetailsAddressModal.tsx
- apps/modernization-ui/src/pages/patient/profile/administrative/AddCommentModal.tsx
- apps/modernization-ui/src/pages/patient/profile/administrative/AdministrativeTable.tsx
- apps/modernization-ui/src/pages/patient/profile/identification/AddIdentificationModal.tsx
- apps/modernization-ui/src/pages/patient/profile/identification/DetailsIdentificationModal.tsx
- apps/modernization-ui/src/pages/patient/profile/identification/IdentificationsTable.tsx
- apps/modernization-ui/src/pages/patient/profile/identification/useFindPatientProfileIdentifications.ts
- apps/modernization-ui/src/pages/patient/profile/names/AddNameModal.tsx
- apps/modernization-ui/src/pages/patient/profile/names/DetailsNameModal.tsx
- apps/modernization-ui/src/pages/patient/profile/names/NamesTable.tsx
- apps/modernization-ui/src/pages/patient/profile/phoneEmail/AddPhoneEmailModal.tsx
- apps/modernization-ui/src/pages/patient/profile/phoneEmail/PhoneAndEmailTable.tsx
- apps/modernization-ui/src/pages/patient/profile/race/AddRaceModal.tsx
- apps/modernization-ui/src/pages/patient/profile/race/RaceTable.tsx
- apps/modernization-ui/src/pages/patient/profile/sexBirth/SexBirth.tsx
- apps/modernization-ui/src/pages/patient/profile/vaccination/VaccinationTable.tsx
Apply Sorting for identifications table last two fields 
Apply Sorting for Race table last two fields 
Delete button does not work on first click sometimes(bug)
Details in names table does not work for second record (bug)
Sorting style changes for rest of tables in reusable component 
fixing null for fields in address
> Cnft1 783 sorting bugs style pp

- apps/modernization-ui/src/components/FormInputs/PhoneNumberInput/PhoneNumberInput.tsx
- apps/modernization-ui/src/pages/addPatient/AddPatient.tsx
- apps/modernization-ui/src/pages/addPatient/components/contactFields/ContactFields.tsx
- apps/modernization-ui/src/pages/advancedSearch/AdvancedSearch.tsx
- apps/modernization-ui/src/pages/advancedSearch/components/PatientResults.tsx
CNFT1-767- New Patient Creation Function- Updates
CNFT1-746- 508 Issue: Link Does Not Have TAB Access
CNFT1-849- Patient Search Update- "Closest Match"- Default Sort
> Cnft1 767 new patient creation function updates

- apps/modernization-api/src/test/java/gov/cdc/nbs/patient/PatientSearchSteps.java
- apps/modernization-api/src/test/java/gov/cdc/nbs/support/util/ElasticsearchPersonMapper.java
Sonar cloud on the last PR ran clean... https://github.com/CDCgov/NEDSS-Modernization/pull/244
> Fix search by race tests

- apps/modernization-api/src/main/java/gov/cdc/nbs/patient/PatientService.java
- apps/modernization-api/src/test/java/gov/cdc/nbs/patient/PatientSearchSteps.java
- apps/modernization-api/src/test/java/gov/cdc/nbs/support/PersonMother.java
- apps/modernization-api/src/test/resources/features/patient/PatientSearch.feature
**How** Convert Short id to regular patient id (prefix + offsetId + suffix) then use that in the exact matcher.
> CNFT1-846 Patient Search- By Short ID

- README.md
- cdc-sandbox/.gitignore
The "new" restore file contains a subfolder, `restore` and contains `.mdf` and `.ldf` files.  Added hopefully clearer text for the restore instructions as well as a sample command to unzip directly into the proper directory.
> Unzip restore

- .github/workflows/sonar.yaml
- apps/patient-listener/src/test/java/gov/cdc/nbs/patientlistener/request/update/PatientUpdaterTest.java
- apps/question-bank/build.gradle
- apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/question/CreateQuestionResolverTest.java
- build.gradle
- gradle/cucumber-logging.gradle
- libs/database-entities/src/test/java/gov/cdc/nbs/entity/odse/PersonTest.java
1. Point to latest test-db image
2. Fix gradle config to fail build on test failure
> Change test db snapshot

- build.gradle
> Bump version to test quality gate

- libs/database-entities/src/main/java/gov/cdc/nbs/entity/odse/EntityId.java
- libs/database-entities/src/main/java/gov/cdc/nbs/entity/odse/Person.java
- libs/database-entities/src/test/java/gov/cdc/nbs/entity/odse/PersonTest.java
Classic NBS requires that the name sequence starts at 1.
> Patient Create data correction

- apps/geocoding-api/src/main/java/gov/cdc/nbs/geocoding/Application.java
- apps/geocoding-api/src/test/java/gov/cdc/nbs/api/geocoding/RunCucumberTest.java
Adds a main class for the geocoding service to allow build to succeed.
> Add main class for geocoding project

- apps/question-bank/postman/Local.postman_environment.json
- apps/question-bank/postman/Question Bank.postman_collection.json
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/entity/question/DateQuestion.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/question/QuestionController.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/question/QuestionCreator.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/question/command/QuestionCommand.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/question/request/CreateQuestionRequest.java
- apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/entity/question/DateQuestionTest.java
- apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/question/CreateQuestionSteps.java
- apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/support/QuestionRequestMother.java
- apps/question-bank/src/test/resources/features/question/CreateQuestion.feature
Allows creation of `Date` questions
-- JSON of date question created with new API
```json
{
"wa_question_uid": 1028508,
"code_set_group_id": null,
"data_cd": null,
"data_location": "NBS_CASE_ANSWER.ANSWER_TXT",
"question_identifier": "GA13012",
"question_oid": "2.16.840.1.113883.12.78",
"question_oid_system_txt": "Abnormal flags (HL7)",
"question_unit_identifier": null,
"data_type": "DATE",
"data_use_cd": null,
"question_label": "Sample date question label",
"question_tool_tip": "Sample date question tooltip",
"rdb_column_nm": "ADM_DATE_RDB_COLUMN_NAME",
"part_type_cd": null,
"default_value": null,
"version_ctrl_nbr": 1,
"unit_parent_identifier": null,
"question_group_seq_nbr": null,
"future_date_ind_cd": "F",
"legacy_data_location": null,
"repeats_ind_cd": null,
"add_user_id": 10054282, …
```
> create Date question API

- apps/modernization-ui/src/components/Table/HorizontalTable.tsx
- apps/modernization-ui/src/pages/patient/profile/sexBirth/SexBirth.tsx
- apps/modernization-ui/src/pages/patient/profile/sexBirth/SexBirthForm.tsx
- apps/modernization-ui/src/pages/patient/profile/vaccination/index.ts
adding integration for update API for Sex and Birth card in demographics
> Cnft1 1076 update sex birth integration

- apps/modernization-ui/src/components/Table/HorizontalTable.tsx
- apps/modernization-ui/src/pages/patient/profile/generalInfo/GeneralInformationForm.tsx
- apps/modernization-ui/src/pages/patient/profile/generalInfo/GeneralPatient.tsx
api for update is not fully functional but the integration is set from the UI calling the API ,
> General patient info update integration

- apps/modernization-ui/src/apps/page-builder/pages/ManagePages/ManagePagesSorter.ts
- apps/modernization-ui/src/apps/page-builder/pages/ManagePages/ManagePagesTable.tsx
Enabling table sorting for Manage Pages
> CNFT2-554 Manage Pages sort ascending/descending

- apps/modernization-api/src/main/java/gov/cdc/nbs/patient/profile/CountryCodeResolver.java
- apps/modernization-api/src/main/java/gov/cdc/nbs/patient/profile/StateCodeResolver.java
- apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/CountryCodeResolverTest.java
- apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/StateCodeResolverTest.java
- apps/modernization-ui/src/pages/patient/profile/summary/PatientProfileSummary.tsx
Prevents a lookup of Country and State for Patient Search results without a country or state.
> Resolves error from state and country lookups for Patient Search results

- apps/modernization-ui/src/pages/advancedSearch/AdvancedSearch.tsx
- apps/modernization-ui/src/pages/advancedSearch/components/eventSearch/LabGeneralSearch.tsx
- Fixing Issues with selecting date picker
- Fixing issues for handling chipClose, added logic for the handleLabReportChipClose
> Search lab report bug fixes

- apps/modernization-ui/src/pages/addPatient/AddPatient.tsx
- passing cellphone to the API
> - passing cellphone to the API

- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/valueset/ValueSetReader.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/valueset/repository/ValueSetRepository.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/valueset/request/ValueSetSearchRequest.java
- apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/valueset/read/ValueSetReaderTest.java
/page-builder/api/v1/valueset/search now accept search on valueSetTypeCd i.e LOCAL or PHIN
**### Example1:**
**Request:**
````
{
"valueSetTypeCd": "LOCAL"
}
````
**### Example2:
Request:**
```
{
"valueSetTypeCd": "PHIN"
}
```
> CNFT2-707: Update List Value Set Endpoint with Additional Param

- apps/modernization-ui/src/pages/addPatient/AddPatient.tsx
This covers 
"[Demo] Missing data elements on search results page for new patient add"
> fixing the properties of the form to submit data correctly

- apps/modernization-ui/src/pages/patient/profile/names/NameEntryForm.tsx
- apps/modernization-ui/src/pages/patient/profile/phoneEmail/PhoneEmailEntryForm.tsx
- apps/modernization-ui/src/settings.scss
This solves 
https://cdc-nbs.atlassian.net/browse/CNFT1-1116
https://cdc-nbs.atlassian.net/browse/CNFT1-1118
https://cdc-nbs.atlassian.net/browse/CNFT1-982
https://cdc-nbs.atlassian.net/browse/CNFT1-984
> solving bugs and ui errors

- apps/modernization-ui/src/providers/UserContext.spec.tsx
> Add router to spec

- apps/modernization-ui/src/apps/page-builder/components/AddValueset/AddValueset.scss
- apps/modernization-ui/src/apps/page-builder/components/AddValueset/AddValueset.spec.tsx
- apps/modernization-ui/src/apps/page-builder/components/AddValueset/AddValueset.tsx
- apps/modernization-ui/src/index.tsx
- apps/modernization-ui/src/routes/AppRoutes.tsx
- [CNFT2-547] FED - Add Value Sets
- https://cdc-nbs.atlassian.net/browse/CNFT2-547
[CNFT2-547]: https://cdc-nbs.atlassian.net/browse/CNFT2-547?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
>  [CNFT2-547] FED - Add Value Sets

- apps/modernization-ui/src/apps/page-builder/components/AddValueset/AddValueset.spec.tsx
- apps/modernization-ui/src/apps/page-builder/components/AddValueset/AddValueset.tsx
- apps/modernization-ui/src/pages/patient/profile/addresses/AddressesTable.tsx
Removes Zip Code from the Address column as a Zip Code column was added.
Before fix:
After fix:
> BBJ12-33 zip code removal

- apps/modernization-ui/src/pages/advancedSearch/AdvancedSearch.tsx
- apps/modernization-ui/src/pages/advancedSearch/components/patientSearch/AddressForm.tsx
- apps/modernization-ui/src/providers/SearchCriteriaContext.tsx
Switches the States list used by Patient search to the non-pagination list
> BBJ12-27/ Patient Search State List

- apps/modernization-ui/src/components/FormInputs/MultiSelectControl.tsx
- apps/modernization-ui/src/pages/advancedSearch/components/eventSearch/EventSearch.tsx
- apps/modernization-ui/src/pages/advancedSearch/components/eventSearch/LabSearchCriteria.tsx
- apps/modernization-ui/src/pages/advancedSearch/components/eventSearch/SearchCriteria.tsx
- apps/modernization-ui/src/pages/patient/profile/phoneEmail/PhoneEmailEntryForm.tsx
https://cdc-nbs.atlassian.net/browse/BBJ12-29-Notification status drop-down field inoperable
Added style for notification status, if its open then it will open towards the top instead of opening below the viewer point
https://cdc-nbs.atlassian.net/browse/BBJ12-25-Added validation for this field to not allow special characters
> adding scroll to bottom of event search and added validation country code

- apps/modernization-ui/src/pages/patient/profile/PatientProfile.tsx
- apps/modernization-ui/src/pages/patient/profile/investigation/PatientInvestigationsTable.tsx
- apps/modernization-ui/src/pages/patient/profile/labReport/LabReportTable.tsx
- apps/modernization-ui/src/pages/patient/profile/morbidity/MorbidityTable.tsx
- apps/modernization-ui/src/pages/patient/profile/vaccination/PatientProfileVaccinations.tsx
- apps/modernization-ui/src/pages/patient/profile/vaccination/PatientVaccinationContainer.tsx
- apps/modernization-ui/src/pages/patient/profile/vaccination/PatientVaccinationTable.tsx
- apps/modernization-ui/src/pages/patientProfile/Events.tsx
Removes the `Add` button in the Events tab when the Patient is not `ACTIVE`
> BBJ12-43/ removes event add for deleted patient

- apps/modernization-ui/src/apps/page-builder/components/ImportTemplate/ImportTemplate.scss
- apps/modernization-ui/src/apps/page-builder/components/ImportTemplate/ImportTemplate.spec.tsx
- apps/modernization-ui/src/apps/page-builder/components/ImportTemplate/ImportTemplate.tsx
- apps/modernization-ui/src/routes/AppRoutes.tsx
- [CNFT2-628] - Import Template Modal
- https://cdc-nbs.atlassian.net/browse/CNFT2-628
[CNFT2-628]: https://cdc-nbs.atlassian.net/browse/CNFT2-628?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CNFT2-628] - Import Template Modal

- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/question/QuestionFinder.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/question/repository/WaQuestionRepository.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/question/request/FindQuestionRequest.java
- apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/question/QuestionFinderTest.java
- apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/question/QuestionSearchSteps.java
> CNFT2-739: Update Question Search To Include QuestionType

- apps/modernization-ui/src/apps/page-builder/components/AddValueset/AddValueset.spec.tsx
- apps/modernization-ui/src/apps/page-builder/components/AddValueset/AddValueset.tsx
- apps/modernization-ui/src/apps/page-builder/components/ConditionalCase/ConditionalCase.scss
- apps/modernization-ui/src/apps/page-builder/components/ConditionalCase/ConditionalCase.spec.tsx
- apps/modernization-ui/src/apps/page-builder/components/ConditionalCase/ConditionalCase.tsx
- apps/modernization-ui/src/apps/page-builder/components/ValuesetLibrary/SearchBar.tsx
- apps/modernization-ui/src/apps/page-builder/components/ValuesetLibrary/ValuesetLibrary.scss
- apps/modernization-ui/src/apps/page-builder/components/ValuesetLibrary/ValuesetLibrary.tsx
- apps/modernization-ui/src/apps/page-builder/components/ValuesetLibrary/ValuesetLibraryTable.tsx
- apps/modernization-ui/src/apps/page-builder/components/ValuesetLibrary/ValuesetLibraryTableWrapper.tsx
- apps/modernization-ui/src/apps/page-builder/generated/models/Question.ts
- apps/modernization-ui/src/components/ModalComponent/ModalComponent.tsx
- apps/modernization-ui/src/components/Table/Table.tsx
- apps/modernization-ui/src/routes/AppRoutes.tsx
- (CNFT2-720) FED - Link Value Set To Question
- https://cdc-nbs.atlassian.net/browse/CNFT2-720
> (CNFT2-720) FED - Link Value Set To Question

- apps/modernization-ui/src/pages/addPatient/AddPatient.scss
- apps/modernization-ui/src/pages/addPatient/AddPatient.tsx
Update Page Navigation for sections to match USWDS component
Ensure In-Page Navigation is added to New Patient creation with internal scrolls
> fixing scrolling issues for addPatient sidebar

- apps/modernization-ui/src/apps/page-builder/components/QuickConditionLookup/QuickConditionLookup.tsx
- apps/modernization-ui/src/apps/page-builder/pages/AddNewPage/AddNewPage.scss
- apps/modernization-ui/src/apps/page-builder/pages/AddNewPage/AddNewPage.tsx
- apps/modernization-ui/src/apps/page-builder/pages/PageBuilder/PageBuilder.scss
- apps/modernization-ui/src/apps/page-builder/services/programAreaAPI.ts
- apps/modernization-ui/src/apps/page-builder/services/valueSetAPI.ts
- apps/modernization-ui/src/assets/shared.scss
- apps/modernization-ui/src/components/FormInputs/Input.tsx
- apps/modernization-ui/src/components/PredictiveInput/PredictiveInput.tsx
- apps/modernization-ui/src/components/selection/multi/MultiSelectInput.scss
- apps/modernization-ui/src/components/selection/multi/MultiSelectInput.tsx
This is the Add New Page markup.
Just the route with functionality and new select input component forthcoming.
Backend calls en route as well.
> CNFT2-760 Add new page landing markup

- apps/modernization-ui/src/pages/patient/profile/labReport/LabReportTable.tsx
- apps/modernization-ui/src/settings.scss
Making sure the lines break with words instead of in between characters
> fixing the way the lines break for the text within tables

- apps/modernization-ui/src/pages/addPatient/AddPatient.scss
Making sure add Patient scroll is smooth and has "ease-in" transition with the desired speed in compliance with the HCD team
> Add patient ease in scroll effect

- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/valueset/ValueSetReader.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/valueset/response/Concept.java
- apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/valueset/read/ValueSetReaderTest.java
> CNFT2-829: Add Concept Code to Response Body

- apps/modernization-ui/src/apps/page-builder/components/EditPageContent/EditPageContent.scss
- apps/modernization-ui/src/apps/page-builder/components/EditPageContent/EditPageContent.tsx
- apps/modernization-ui/src/apps/page-builder/components/EditPageHeader/EditPageHeader.scss
- apps/modernization-ui/src/apps/page-builder/components/EditPageHeader/EditPageHeader.tsx
- apps/modernization-ui/src/apps/page-builder/components/EditPageSidebar/EditPageSidebar.scss
- apps/modernization-ui/src/apps/page-builder/components/EditPageSidebar/EditPageSidebar.tsx
- apps/modernization-ui/src/apps/page-builder/components/EditPageTabs/EditPageTabs.scss
- apps/modernization-ui/src/apps/page-builder/components/EditPageTabs/EditPageTabs.tsx
- apps/modernization-ui/src/apps/page-builder/components/Navigation/Navigation.tsx
- apps/modernization-ui/src/apps/page-builder/components/PagesBreadcrumb/PagesBreadcrumb.scss
- apps/modernization-ui/src/apps/page-builder/components/PagesBreadcrumb/PagesBreadcrumb.tsx
- apps/modernization-ui/src/apps/page-builder/pages/AddNewPage/AddNewPage.scss
- apps/modernization-ui/src/apps/page-builder/pages/AddNewPage/AddNewPage.tsx
- apps/modernization-ui/src/apps/page-builder/pages/EditPage/EditPage.scss
- apps/modernization-ui/src/apps/page-builder/pages/EditPage/EditPage.tsx
- apps/modernization-ui/src/apps/page-builder/pages/ManagePages/usePageSummaryAPI.ts
- apps/modernization-ui/src/apps/page-builder/pages/PageBuilder/PageBuilder.tsx
- apps/modernization-ui/src/routes/AppRoutes.tsx
> CNFT2-610 Create Edit Page form

- .github/workflows/Build-and-deploy-common-asset-server.yaml
- .github/workflows/Build-and-deploy-elasticsearch.yaml
- .github/workflows/Build-and-deploy-modernization-api.yaml
- .github/workflows/Build-and-deploy-nifi.yaml
- .github/workflows/Build-modernization-test-db.yaml
- .github/workflows/Release-gradle-container.yaml
Removes the `update_helm_chart` and `values_file_with_path` from the workflow files.  These properties were removed the from Build and Release workflow templates with [Workflow PR 9](https://github.com/CDCgov/NEDSS-Workflows/pull/9/files)
> Removes update_helm_chart and values_file_with_path

- apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/address/change/PatientProfileAddressChangeSteps.java
Addresses three Sonar identified code smells in the PatientProfileAddressChange test.
https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&types=CODE_SMELL&id=CDCgov_NEDSS-Modernization&open=AYlqr5ejFLEhzndjfI03
https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&types=CODE_SMELL&id=CDCgov_NEDSS-Modernization&open=AYlqr5ejFLEhzndjfI04
https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&types=CODE_SMELL&id=CDCgov_NEDSS-Modernization&open=AYlqr5ejFLEhzndjfI05
> Addresses Sonar code smells

- apps/modernization-ui/src/apps/page-builder/components/AddValueset/AddValueset.scss
- apps/modernization-ui/src/apps/page-builder/components/AddValueset/AddValueset.tsx
- apps/modernization-ui/src/apps/page-builder/components/Concept/Concept.scss
- apps/modernization-ui/src/apps/page-builder/components/Concept/Concept.tsx
- apps/modernization-ui/src/apps/page-builder/components/Concept/ConceptTable.spec.tsx
- apps/modernization-ui/src/apps/page-builder/components/Concept/ConceptTable.tsx
- apps/modernization-ui/src/apps/page-builder/components/Concept/SearchBar.tsx
- apps/modernization-ui/src/apps/page-builder/components/Concept/useConceptAPI.ts
- apps/modernization-ui/src/apps/page-builder/components/ImportTemplate/ImportTemplate.tsx
- apps/modernization-ui/src/apps/page-builder/context/ConceptContext.tsx
- apps/modernization-ui/src/apps/page-builder/context/PageBuilderContext.tsx
- apps/modernization-ui/src/apps/page-builder/context/QuestionsContext.tsx
- apps/modernization-ui/src/apps/page-builder/context/ValueSetContext.tsx
- apps/modernization-ui/src/apps/page-builder/generated/services/ValueSetControllerService.ts
- apps/modernization-ui/src/apps/page-builder/pages/QuestionLibrary/QuestionLibrary.scss
- apps/modernization-ui/src/apps/page-builder/pages/QuestionLibrary/QuestionLibrary.tsx
- apps/modernization-ui/src/apps/page-builder/pages/QuestionLibrary/QuestionLibraryTable.tsx
- apps/modernization-ui/src/apps/page-builder/pages/QuestionLibrary/SearchBar.tsx
- apps/modernization-ui/src/apps/page-builder/pages/ValuesetLibrary/SearchBar.tsx
- apps/modernization-ui/src/apps/page-builder/pages/ValuesetLibrary/ValuesetLibrary.scss
- apps/modernization-ui/src/apps/page-builder/pages/ValuesetLibrary/ValuesetLibrary.tsx
- apps/modernization-ui/src/apps/page-builder/pages/ValuesetLibrary/ValuesetLibraryTable.tsx
- apps/modernization-ui/src/apps/page-builder/pages/ValuesetLibrary/ValuesetTabs.scss
- apps/modernization-ui/src/apps/page-builder/pages/ValuesetLibrary/useValuesetAPI.ts
- apps/modernization-ui/src/components/ModalComponent/ModalComponent.tsx
- apps/modernization-ui/src/pages/advancedSearch/components/eventSearch/EventType.tsx
[cnft1-751] - Add value set - Create new button on every search result
[cnft2-752] - Create Value set - Concept tab
https://cdc-nbs.atlassian.net/browse/CNFT2-751
https://cdc-nbs.atlassian.net/browse/CNFT2-752
> [cnft2-752] - concepts tab

- .github/workflows/Build-and-deploy-modernization-api.yaml
- .github/workflows/sonar.yaml
this fix allows for passing secrets required by the sonar.yaml workflow
> fix secret reference

- apps/modernization-ui/src/pages/advancedSearch/AdvancedSearch.tsx
- apps/modernization-ui/src/pages/advancedSearch/components/PatientResults.tsx
- apps/modernization-ui/src/pages/advancedSearch/components/patientSearch/PatientSearch.tsx
[CNFT1-1452](https://cdc-nbs.atlassian.net/browse/CNFT1-1452) and [CNFT1-1451](https://cdc-nbs.atlassian.net/browse/CNFT1-1451)
1. Adds `Patient Id` field to the Patient Search form.
2. Displays short Id instead of localId on patient result card
3. Allows users to search by either short or long Id 
[CNFT1-1452]: https://cdc-nbs.atlassian.net/browse/CNFT1-1452?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CNFT1-1451]: https://cdc-nbs.atlassian.net/browse/CNFT1-1451?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CNFT1-1452 patient id search

- apps/modernization-ui/src/apps/page-builder/components/EditPageContent/EditPageContent.tsx
- apps/modernization-ui/src/apps/page-builder/components/EditPageHeader/EditPageHeader.tsx
- apps/modernization-ui/src/apps/page-builder/components/EditPageTabs/EditPageTabs.scss
- apps/modernization-ui/src/apps/page-builder/generated/models/PageDetails.ts
- apps/modernization-ui/src/apps/page-builder/generated/services/PageControllerService.ts
- apps/modernization-ui/src/apps/page-builder/pages/EditPage/EditPage.tsx
- apps/modernization-ui/src/apps/page-builder/services/pagesAPI.ts
Here we incorporate the fetchPageDetails API call into Edit Page.
> CNFT2-843 Author Integrate fetch page details API

- apps/modernization-ui/src/apps/page-builder/pages/ManagePages/ManagePagesTable.spec.tsx
- apps/modernization-ui/src/apps/page-builder/pages/ManagePages/ManagePagesTable.tsx
clicking a link to a page in the page library should take you to the edit page for that page
> Cnft2 606/add links to edit page

- apps/modernization-ui/src/apps/page-builder/components/Concept/ConceptTable.spec.tsx
- apps/modernization-ui/src/components/FormInputs/DatePickerInput.spec.tsx
- apps/modernization-ui/src/components/FormInputs/DatePickerInput.tsx
- apps/modernization-ui/src/components/FormInputs/Input.tsx
- apps/modernization-ui/src/components/FormInputs/SelectInput.tsx
- apps/modernization-ui/src/components/selection/multi/MultiSelectInput.tsx
- apps/modernization-ui/src/pages/addPatient/components/generalInformation/generalInformation.tsx
- apps/modernization-ui/src/pages/patient/profile/addresses/AddressEntryForm.tsx
- apps/modernization-ui/src/pages/patient/profile/addresses/AddressesTable.tsx
- apps/modernization-ui/src/pages/patient/profile/administrative/AdminstrativeForm.tsx
- apps/modernization-ui/src/pages/patient/profile/ethnicity/EthnicityForm.tsx
- apps/modernization-ui/src/pages/patient/profile/generalInfo/GeneralInformationForm.tsx
- apps/modernization-ui/src/pages/patient/profile/identification/IdentificationEntryForm.tsx
- apps/modernization-ui/src/pages/patient/profile/mortality/MortalityForm.tsx
- apps/modernization-ui/src/pages/patient/profile/names/NameEntryForm.tsx
- apps/modernization-ui/src/pages/patient/profile/phoneEmail/PhoneEmailEntryForm.tsx
- apps/modernization-ui/src/pages/patient/profile/race/RaceEntryForm.tsx
- apps/modernization-ui/src/pages/patient/profile/sexBirth/SexBirthForm.tsx
- apps/modernization-ui/src/settings.scss
[CNFT1-1459](https://cdc-nbs.atlassian.net/browse/CNFT1-1459)
1. Adds required indicator to patient demographic fields.
2. Disables "Save" button on `General Patient Information`, `Sex & Birth`, and `Mortality` if form is not valid
3. Fixes header for `Add - Address` modal
Example:
[CNFT1-1459]: https://cdc-nbs.atlassian.net/browse/CNFT1-1459?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CNFT1-1459 Show red * next to required demographic fields

- apps/modernization-ui/src/apps/page-builder/components/CreateCondition/CreateCondition.scss
- apps/modernization-ui/src/apps/page-builder/components/CreateCondition/CreateCondition.tsx
- apps/modernization-ui/src/apps/page-builder/generated/models/Concept.ts
- apps/modernization-ui/src/apps/page-builder/services/conditionAPI.ts
- apps/modernization-ui/src/apps/page-builder/services/programAreaAPI.ts
- apps/modernization-ui/src/apps/page-builder/services/valueSetAPI.ts
- apps/modernization-ui/src/components/RadioGroup/RadioGroup.tsx
Here we refactor CreateCondition to use our native components and react-hook-form
> CNFT2-923 CreateCondition refactor

- apps/modernization-ui/src/apps/page-builder/components/Counter/Counter.scss
- apps/modernization-ui/src/apps/page-builder/components/Counter/Counter.tsx
- apps/modernization-ui/src/apps/page-builder/components/EditPageContent/EditPageContent.scss
- apps/modernization-ui/src/apps/page-builder/components/EditPageContent/EditPageContent.tsx
- apps/modernization-ui/src/apps/page-builder/components/EditPageTabs/EditPageTabs.tsx
- apps/modernization-ui/src/apps/page-builder/components/Question/Question.scss
- apps/modernization-ui/src/apps/page-builder/components/Question/Question.tsx
- apps/modernization-ui/src/apps/page-builder/components/Section/Section.scss
- apps/modernization-ui/src/apps/page-builder/components/Section/Section.tsx
- apps/modernization-ui/src/apps/page-builder/components/Subsection/Subsection.scss
- apps/modernization-ui/src/apps/page-builder/components/Subsection/Subsection.tsx
- apps/modernization-ui/src/apps/page-builder/generated/models/EditPageContent.ts
- apps/modernization-ui/src/apps/page-builder/generated/models/EditPageQuestion.ts
- apps/modernization-ui/src/apps/page-builder/generated/models/PageDetails.ts
- apps/modernization-ui/src/apps/page-builder/generated/models/Section.ts
- apps/modernization-ui/src/apps/page-builder/generated/models/Subsection.ts
- apps/modernization-ui/src/apps/page-builder/generated/models/SubsectionQuestion.ts
- apps/modernization-ui/src/apps/page-builder/generated/models/Tabs.ts
- apps/modernization-ui/src/apps/page-builder/pages/AddNewPage/AddNewPage.tsx
- apps/modernization-ui/src/apps/page-builder/pages/EditPage/EditPage.scss
- apps/modernization-ui/src/apps/page-builder/pages/EditPage/EditPage.tsx
- apps/modernization-ui/src/styles/_uswds.scss
Here we display sections (and subsections and partially Questions which will be completed in https://cdc-nbs.atlassian.net/browse/CNFT2-622) to the Edit Page views.
> CNFT2-606 Edit Page: Display Section

- apps/modernization-ui/src/apps/page-builder/components/AddTabs/AddTab.spec.tsx
- apps/modernization-ui/src/apps/page-builder/components/AddTabs/index.tsx
- apps/modernization-ui/src/apps/page-builder/components/EditPageTabs/EditPageTabs.tsx
- apps/modernization-ui/src/apps/page-builder/pages/QuestionLibrary/QuestionLibraryTable.tsx
- [CNFT2-613] - add tab to page
- https://cdc-nbs.atlassian.net/browse/CNFT2-613
[CNFT2-613]: https://cdc-nbs.atlassian.net/browse/CNFT2-613?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CNFT2-613] - add tab to page

- apps/modernization-ui/src/apps/page-builder/components/ConditionalCase/ConditionalCase.spec.tsx
- apps/modernization-ui/src/apps/page-builder/components/ConditionalCase/ConditionalCase.tsx
- apps/modernization-ui/src/apps/page-builder/components/CreateCondition/CreateCondition.spec.tsx
- apps/modernization-ui/src/apps/page-builder/components/CreateCondition/CreateCondition.tsx
- apps/modernization-ui/src/apps/page-builder/components/CreateQuestion/CreateQuestion.spec.tsx
- apps/modernization-ui/src/apps/page-builder/components/CreateQuestion/CreateQuestion.tsx
> Test file fix

- apps/modernization-api/src/main/java/gov/cdc/nbs/patient/profile/identification/PatientIdentificationFinder.java
- apps/modernization-api/src/test/java/gov/cdc/nbs/patient/PatientMother.java
- apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/identification/PatientProfileIdentificationSteps.java
- apps/modernization-api/src/test/resources/features/patient/PatientProfileIdentification.feature
- apps/modernization-ui/src/pages/patient/profile/identification/IdentificationsTable.tsx
- apps/modernization-ui/src/pages/patient/profile/identification/useFindPatientProfileIdentifications.ts
Resolves [CNFT1-1442](https://cdc-nbs.atlassian.net/browse/CNFT1-1442) by fixing an issue with the Patient Profile Identifications API where the total count was not resolving correctly.  
[CNFT1-1442]: https://cdc-nbs.atlassian.net/browse/CNFT1-1442?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CNFT1-1442 Identification paging

- apps/modernization-ui/src/apps/page-builder/components/EditPageContent/EditPageContent.spec.tsx
- apps/modernization-ui/src/apps/page-builder/components/EditPageContent/EditPageContent.tsx
- apps/modernization-ui/src/apps/page-builder/components/EditPageHeader/EditPageHeader.spec.tsx
- apps/modernization-ui/src/apps/page-builder/components/EditPageTabs/EditPageTabs.spec.tsx
- apps/modernization-ui/src/apps/page-builder/components/Section/Section.spec.tsx
- apps/modernization-ui/src/apps/page-builder/components/Section/Section.tsx
- apps/modernization-ui/src/apps/page-builder/components/Subsection/Subsection.spec.tsx
- apps/modernization-ui/src/apps/page-builder/components/Subsection/Subsection.tsx
- apps/modernization-ui/src/apps/page-builder/pages/EditPage/EditPage.spec.tsx
Unit tests for the Edit Page family of components.
> CNFT2-961 Edit Page unit tests

- .github/workflows/sonar.yaml
- gradle/sonar.gradle
Removes the sonar cache form the workflow. 
Removes the non-working exclusion from the `sonar.gradle`
Adds `clean` to the gradle command just in case
> Remove sonar cache 

- apps/modernization-ui/src/apps/page-builder/components/EditPageHeader/EditPageHeader.tsx
- apps/modernization-ui/src/apps/page-builder/components/SaveTemplate/SaveTemplate.spec.tsx
- apps/modernization-ui/src/apps/page-builder/components/SaveTemplate/SaveTemplate.tsx
- apps/modernization-ui/src/apps/page-builder/components/SaveTemplate/SavetTemplate.scss
- [CNFT2-960] - Save Page as Template
- https://cdc-nbs.atlassian.net/browse/CNFT2-960
[CNFT2-960]: https://cdc-nbs.atlassian.net/browse/CNFT2-960?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CNFT2-960] - Save Page as Template

- apps/modernization-api/src/test/java/gov/cdc/nbs/FindUsersSteps.java
- apps/modernization-api/src/test/java/gov/cdc/nbs/event/search/investigation/InvestigationQueryBuilderTest.java
- apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/phone/PatientProfilePhoneSteps.java
- apps/modernization-api/src/test/java/gov/cdc/nbs/support/PermissionMother.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/condition/ConditionReader.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/PageDownloader.java
Removes some unused imports. Fixes a couple of code smells
> Fix code smells

- apps/modernization-ui/src/pages/advancedSearch/components/patientSearch/PatientSearch.tsx
Resolves [CNFT1-1475](https://cdc-nbs.atlassian.net/browse/CNFT1-1482) by adding the name format validations to the Last and First name criteria for Patient Search.
[CNFT1-1475]: https://cdc-nbs.atlassian.net/browse/CNFT1-1475?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CNFT1-1475 Adds name validations to Patient Search name criteria

- .github/workflows/Build-and-deploy-modernization-api.yaml
- .github/workflows/Build-and-deploy-nbs-gateway.yaml
- apps/modernization-api/README.md
- apps/nbs-gateway/README.md
- build.gradle
- gradle/cucumber-logging.gradle
- gradle/libs.versions.toml
- gradle/sonar.gradle
Configures the gradle projects to ensure that Java 17 is used in local development.
> Project configuration

- .github/pull_request_template.md
- README.md
- documentation/Pull-Requests.md
Adds some documentation on how to create and review pull requests. Creates a pull request template with the following format:
[Jira Ticket](url)
1. Provide steps here
1.
1.
1.
> Pull request doc

- apps/modernization-ui/src/pages/patient/profile/addresses/AddressesTable.tsx
- apps/modernization-ui/src/pages/patient/profile/administrative/AdministrativeTable.tsx
- apps/modernization-ui/src/pages/patient/profile/identification/IdentificationsTable.tsx
- apps/modernization-ui/src/pages/patient/profile/names/NamesTable.tsx
- apps/modernization-ui/src/pages/patient/profile/phoneEmail/PhoneAndEmailTable.tsx
- apps/modernization-ui/src/pages/patient/profile/race/RaceTable.tsx
…le modal
[Jira Ticket](url)
1. Provide steps here
1.
1.
1.
> CNFT1-1465 asOf date set for Address Admin Iden Name PhoneEmail Race Mortality S&B

- apps/question-bank/build.gradle
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/PageController.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/PageDownloader.java
- apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/page/download/PageControllerTest.java
- apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/page/download/PageDownloaderSteps.java
- apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/page/download/PageDownloaderTest.java
- [CNFT2-607] - Print Page library PDF
- https://cdc-nbs.atlassian.net/browse/CNFT2-607
[CNFT2-607]: https://cdc-nbs.atlassian.net/browse/CNFT2-607?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CNFT2-607] - Print Page library PDF

- apps/modernization-ui/src/pages/patient/profile/ethnicity/Ethnicity.tsx
- apps/modernization-ui/src/pages/patient/profile/ethnicity/EthnicityForm.tsx
New entry for "asOf" ethnicity now defaults to current date in patient profile demographic tab.
[CNFT1-1465](https://cdc-nbs.atlassian.net/browse/CNFT1-1465)
1. Visit patient profile
2. Click demographics tab
3. Click edit ethnicity  to view the "asOf" date will default to current date
[CNFT1-1465]: https://cdc-nbs.atlassian.net/browse/CNFT1-1465?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CNFT1-1465 ethnicity Auto-Fill "As of Date" to current date for ethnicity fixed in patient profile

- .github/workflows/Build-and-deploy-page-builder-api.yaml
Commentating Helm step in page-builder workflow for automated deployments
* [Jira Ticket](https://cdc-nbs.atlassian.net/jira/software/c/projects/CNAT/boards/115?selectedIssue=CNAT-83)
1. On merge to main, pipeline should run successfully. Result in Github Actions
2. Navigate to [NEDSS-Helm](https://github.com/CDCgov/NEDSS-Helm)
3. Check if your image tag has been updated in charts/page-builder-api.values.yaml
> uncomment helm updates

- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/PageDownloader.java
Resolves code smells in the sonar scan
NA
1. Validate code smells in sonar scan
> Resolve code smells

- apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/page/download/PageControllerTest.java
- apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/page/download/PageDownloaderTest.java
Removes some unused imports
N/A
> Remove unused imports

- apps/modernization-ui/src/apps/page-builder/constant/constant.ts
- apps/modernization-ui/src/apps/page-builder/context/BusinessContext.tsx
- apps/modernization-ui/src/apps/page-builder/context/PageBuilderContext.tsx
- apps/modernization-ui/src/apps/page-builder/generated/services/PageRuleControllerService.ts
- apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/BusinessRulesLibrary.scss
- apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/BusinessRulesLibrary.tsx
- apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/BusinessRulesLibraryTable.spec.tsx
- apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/BusinessRulesLibraryTable.tsx
- apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/FilterButton/Filter.tsx
- apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/SearchBar.tsx
- apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/useBusinessRulesAPI.ts
- apps/modernization-ui/src/routes/AppRoutes.tsx
Created Business Rules Library View
* [Jira Ticket]https://cdc-nbs.atlassian.net/browse/CNFT2-959
1. URL to navigate - http://localhost:3000/page-builder/manage/business-rules-library
2. Type the above url in the browser
> [CNFT2-959] - Business Rules Library View

- apps/modernization-ui/src/apps/page-builder/pages/EditPage/EditPage.tsx
Linter error on main, added line-breaks to fix.
> fix formatting

- .github/workflows/verify-modernization-ui.yaml
Adds a pipeline to verify the `modernization-ui` by executing Jest tests.
> [Pipeline] adds pipeline to verify ui by executing tests

- apps/modernization-ui/src/apps/page-builder/components/CreateQuestion/CreateQuestion.spec.tsx
- apps/modernization-ui/src/apps/page-builder/components/CreateQuestion/CreateQuestion.tsx
- apps/modernization-ui/src/apps/page-builder/constant/constant.ts
Fixes the CreateQuestion test so that builds will succeed.
> [FIX] Failing test

- apps/modernization-ui/src/coded/race/useRaceCodedValues.ts
- apps/modernization-ui/src/pages/addPatient/useAddPatientCodedValues.ts
- apps/modernization-ui/src/providers/SearchCriteriaContext.tsx
Hide Multi-Race as a Race Option
* https://cdc-nbs.atlassian.net/browse/CNFT1-1447
In Patient-search > Race, Add-patient, Patient-profile> Demographics tab > Add Race - Should not display Multi-race as an option under race options.
> Hide Multi-Race as a Race Option

- .github/workflows/Build-and-deploy-elasticsearch.yaml
- .github/workflows/Build-and-deploy-modernization-api.yaml
- .github/workflows/Build-and-deploy-nbs-gateway.yaml
- .github/workflows/Build-and-deploy-nifi.yaml
- .github/workflows/Build-and-deploy-page-builder-api.yaml
Int1 will now be replacing the DEV environment. This updates the workflows to deploy there instead.
NA
NA
> Update deployment from dev to int1

- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/model/CreateRuleRequest.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/pagerules/PageRuleController.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/pagerules/PageRuleFinderService.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/pagerules/PageRuleFinderServiceImpl.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/pagerules/PageRuleService.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/pagerules/PageRuleServiceImpl.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/pagerules/SearchPageRuleRequest.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/pagerules/repository/WaRuleMetaDataRepository.java
- apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/pagerules/PageRuleControllerTest.java
- apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/pagerules/PageRuleServiceImplTest.java
- apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/pagerules/PageRuleSteps.java
- apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/support/RuleRequestMother.java
- apps/question-bank/src/test/resources/features/pagerule/CreatePageRule.feature
- apps/question-bank/src/test/resources/features/pagerule/DeletePageRule.feature
- apps/question-bank/src/test/resources/features/pagerule/GetAllPageRule.feature
- apps/question-bank/src/test/resources/features/pagerule/SearchPageRule.feature
- apps/question-bank/src/test/resources/features/pagerule/UpdatePageRule.feature
Develop get all business rules API and search business rule API
* [CNFT2-1040](https://cdc-nbs.atlassian.net/browse/CNFT2-1040)
* [CNFT2-1267](https://cdc-nbs.atlassian.net/browse/CNFT2-1267)
1. Import the curl command in Postman
curl --location 'http://localhost:8095/nbs/page-builder/api/v1/rules?page=0&size=10&sort=ruleDescText'
--header 'accept: /'
--header 'Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJubmRfYmF0Y2hfdG9fY2RjIiwiaXNzIjoiZ292LmNkYy5uYnMiLCJleHAiOjE2OTY4NzA0MDEsImlhdCI6MTY5Njg2ODYwMX0.Q-C5bJRRcL7SxsGr92CYeHo1hXKmJ6_hSpT5t9ajqbQ'
2. Update the bearer token
3. The getAllPageRule API fetch all business rules value from database
4. 
1. Import the curl command in Postman
curl --location --request GET …
> [CNFT2-1040] [CNFT2-1267] - Develop get all business rules API and Search business rules API

- apps/modernization-api/Dockerfile
- apps/modernization-api/build.gradle
- apps/modernization-api/src/test/java/gov/cdc/nbs/patient/PatientMother.java
- apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/address/PatientProfileAddressSteps.java
- apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/address/change/PatientProfileAddressChangeSteps.java
- apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/administrative/change/PatientAdministrativeChangeSteps.java
- apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/birth/change/PatientBirthChangeSteps.java
- apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/general/change/PatientGeneralInformationChangeSteps.java
- apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/identification/PatientProfileIdentificationSteps.java
- apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/mortality/change/PatientMortalityChangeSteps.java
- apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/names/PatientProfileNameSteps.java
- apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/names/change/PatientProfileNameChangeSteps.java
- apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/phone/PatientProfileEmailSteps.java
- apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/phone/PatientProfilePhoneSteps.java
- apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/phone/change/PatientProfilePhoneChangeSteps.java
- apps/nbs-gateway/Dockerfile
- apps/nbs-gateway/build.gradle
- apps/question-bank/Dockerfile
- apps/question-bank/build.gradle
- gradle/libs.versions.toml
First attempt to mitigate CVE's.  
Updated troublesome dependencies;
- guava
- snake yaml
- faker  
Updated Spring Boot to 2.8.17 for `modernization-api` and `page-builder`
Updated Spring Boot to 3.1.5 for `nbs-gateway`
Changed the container creation to use jlink to minimize the fluff.
Run all tests and re-build all containers
> Updates dependencies and changes how API containers are built

- apps/modernization-api/Dockerfile
- apps/nbs-gateway/Dockerfile
- apps/question-bank/Dockerfile
Changes the `Dockerfile` for the Spring Applications to work with the existing helm charts.
> fixes Dockerfiles to work with helm charts

- apps/modernization-api/src/main/java/gov/cdc/nbs/patient/profile/PatientProfileDeletableResolver.java
- apps/modernization-api/src/main/java/gov/cdc/nbs/patient/profile/PatientProfileTupleMapper.java
- apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/PatientProfileShortIdentifierResolverTest.java
- apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/PatientProfileTupleMapperTest.java
- apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/race/PatientProfileRaceSteps.java
- apps/modernization-ui/src/pages/patient/profile/summary/PatientProfileSummary.scss
- apps/modernization-ui/src/pages/patient/profile/summary/PatientProfileSummary.tsx
Changes the Patient Profile API to return the correct status display.
* [CNFT1-1546](https://cdc-nbs.atlassian.net/browse/CNFT1-1546)
1. Create a Patient
2. Delete a Patient
3. Ensure that the status displayed on the Patient Profile is `INACTIVE`
4. Search for a Superseded Patient
5. Ensure that the status displayed on the Patient Profile is `SUPERSEDED`
[CNFT1-1546]: https://cdc-nbs.atlassian.net/browse/CNFT1-1546?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CNFT1-1546] Enusres API returns the correct status display for the Patient Profile

- apps/modernization-api/Dockerfile
- apps/modernization-api/build.gradle
- apps/modernization-api/src/test/java/gov/cdc/nbs/patient/PatientMother.java
- apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/address/PatientProfileAddressSteps.java
- apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/address/change/PatientProfileAddressChangeSteps.java
- apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/administrative/change/PatientAdministrativeChangeSteps.java
- apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/birth/change/PatientBirthChangeSteps.java
- apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/general/change/PatientGeneralInformationChangeSteps.java
- apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/identification/PatientProfileIdentificationSteps.java
- apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/mortality/change/PatientMortalityChangeSteps.java
- apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/names/PatientProfileNameSteps.java
- apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/names/change/PatientProfileNameChangeSteps.java
- apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/phone/PatientProfileEmailSteps.java
- apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/phone/PatientProfilePhoneSteps.java
- apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/phone/change/PatientProfilePhoneChangeSteps.java
- apps/nbs-gateway/Dockerfile
- apps/nbs-gateway/build.gradle
- apps/question-bank/Dockerfile
- apps/question-bank/build.gradle
- gradle/libs.versions.toml
Merges the CVE mitigations into rc_20231017.
> CVE mitigation

- apps/modernization-ui/src/pages/patient/search/result/PatientResult.tsx
* [CNFT1-1504](https://cdc-nbs.atlassian.net/browse/CNFT1-1504)
1. Login, visit search page.
1. Do Person search and middle names are displayed in the person search results
1.
1.
[CNFT1-1504]: https://cdc-nbs.atlassian.net/browse/CNFT1-1504?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Change Legal Full Name to include middle name for person search results.

- apps/modernization-api/build.gradle
- gradle/libs.versions.toml
(cherry picked from commit 3aded76af123857b9492372bff3f8a08b4390da2)
Cherry picking https://github.com/CDCgov/NEDSS-Modernization/pull/681 into RC_20231017
> CVE-2023-2976 mitigation

- apps/modernization-ui/src/utils/ExportUtil.ts
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/entity/repository/WaTemplateRepository.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/PageDownloader.java
Updated the query in the template repository (Modern) so that the PDF and CSV downloads match those in Classic.
* https://cdc-nbs.atlassian.net/browse/CNFT2-1225
* https://cdc-nbs.atlassian.net/browse/CNFT2-1224
1. Create Page Library PDF and CSV documents from Classic.
2. Create the same using Modern API.
3. Both PDFs and both CSVs should match.
> Page-report report query

- apps/modernization-ui/src/apps/page-builder/components/ConditionalCase/ConditionalCase.tsx
- apps/modernization-ui/src/apps/page-builder/context/DragDropProvider.tsx
- apps/modernization-ui/src/apps/page-builder/pages/EditPage/EditPage.tsx
- apps/modernization-ui/src/apps/page-builder/pages/EditPage/ReorderModal/ReorderModal.spec.tsx
- apps/modernization-ui/src/apps/page-builder/pages/EditPage/ReorderQuestion/ReorderQuestion.spec.tsx
- apps/modernization-ui/src/apps/page-builder/pages/EditPage/ReorderSection/ReorderSection.spec.tsx
- apps/modernization-ui/src/apps/page-builder/pages/EditPage/ReorderSubsection/ReorderSubsection.spec.tsx
- apps/modernization-ui/src/apps/page-builder/pages/QuestionLibrary/useQuestionAPI.ts
- apps/modernization-ui/src/apps/page-builder/services/reorderObjectsAPI.ts
Here we integrate the reorder API to commit reordering changes to the db
> CNFT2-1416 Integrate reorder API

- apps/modernization-ui/src/apps/page-builder/components/TableMenu/TableMenu.tsx
Here we fix the search in Pages Library:
now when you clear the search terms, the page list resets
> INT1 Remove sort filter Page Library

- apps/modernization-ui/src/pages/advancedSearch/AdvancedSearch.scss
- apps/modernization-ui/src/pages/patient/profile/PatientProfile.tsx
- apps/modernization-ui/src/pages/patient/profile/summary/PatientProfileSummary.scss
Update Font-Size for the titles and tabs in Patient profile as per the design
* https://cdc-nbs.atlassian.net/browse/CNFT1-1595
* https://cdc-nbs.atlassian.net/browse/CNFT1-1596
* https://cdc-nbs.atlassian.net/browse/CNFT1-1599
In the Patient Profile page Patient title, Patient ID and Tabs(Summary, Events, Demographics) font size is changed to 1.375rem.
> updated font size as per the design

- apps/modernization-ui/src/apps/page-builder/pages/FilterModal/PageFilterModal.tsx
Minor heading changes needed (according to the FRD and Figma 2.0 Filter design).
Revise Selected Field to Select a field.
The letter v is capitalized in the word Value. Should be lowercase. 
* [CNFT2-1463](https://cdc-nbs.atlassian.net/browse/CNFT2-1463)
1. If running locally, navigate to url with extension /page-builder/manage/pages
2. Then click on the filter button, and then click add filter and check the headings are as required
[CNFT2-1463]: https://cdc-nbs.atlassian.net/browse/CNFT2-1463?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CNFT2-1463-headings-revised

- apps/modernization-ui/src/apps/page-builder/components/EditPageHeader/EditPageHeader.scss
- apps/modernization-ui/src/apps/page-builder/components/EditPageHeader/EditPageHeader.spec.tsx
- apps/modernization-ui/src/apps/page-builder/components/EditPageHeader/EditPageHeader.tsx
- apps/modernization-ui/src/apps/page-builder/components/EditPageTabs/EditPageTabs.scss
- apps/modernization-ui/src/apps/page-builder/generated/models/PagesResponse.ts
- apps/modernization-ui/src/apps/page-builder/pages/EditPage/EditPage.scss
- apps/modernization-ui/src/classic/ClassicButton.tsx
- apps/modernization-ui/src/classic/ClassicLink.tsx
- apps/modernization-ui/src/classic/ClassicModalButton.tsx
- apps/modernization-ui/src/classic/ClassicModalLink.tsx
- apps/modernization-ui/src/classic/Destination.d.ts
- apps/modernization-ui/src/classic/useRedirect.ts
- apps/modernization-ui/src/components/FormInputs/Input.tsx
- apps/modernization-ui/src/components/LinkButton/LinkButton.scss
- apps/modernization-ui/src/components/LinkButton/LinkButton.tsx
- apps/modernization-ui/src/components/LinkButton/index.ts
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/classic/redirect/outgoing/ClassicManagePageRequester.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/classic/redirect/outgoing/ClassicPreviewPageRequester.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/detail/PagesResponse.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/print/PagePrintController.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/print/PagePrintRedirector.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/template/ClassicCreateTemplatePreparer.java
- apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/page/print/PagePrintRequester.java
- apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/page/print/PagePrintSteps.java
- apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/page/template/ClassicViewPagePreparerTest.java
- apps/question-bank/src/test/resources/features/page/print/PagePrint.feature
Allows printing of a Page using the NBS 6 simplified page view.
* [CNFT2-1486](https://cdc-nbs.atlassian.net/browse/CNFT2-1486)
_Contains API and user interface changes._
1. Navigate to Page Builder
2. From the Page Library click on a Page
3. ???
4. Click `Print page`
5. A simplified view of the Page should open in a new tab 
[CNFT2-1486]: https://cdc-nbs.atlassian.net/browse/CNFT2-1486?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CNFT2-1468] Page Print

- apps/modernization-api/build.gradle
- apps/modernization-api/src/main/resources/application-development.yml
- apps/question-bank/build.gradle
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/config/QueryDSLConfig.java
- gradle/libs.versions.toml
- libs/audit/build.gradle
- libs/authentication/build.gradle
- libs/configuration-api/build.gradle
- libs/database-entities/build.gradle
- libs/event-schema/build.gradle
- libs/id-generator/build.gradle
- libs/me-api/build.gradle
- libs/options-api/build.gradle
- libs/testing/auth-cucumber/build.gradle
- libs/testing/auth/build.gradle
- libs/testing/database/build.gradle
- libs/testing/identity/build.gradle
- libs/testing/support/build.gradle
Addresses recent CVE findings on the `modernization-api` and `pagebuilder-api` related to Apache Commons Compress, and Apache Kafka.
https://github.com/CDCgov/NEDSS-Modernization/security/code-scanning/413
https://github.com/CDCgov/NEDSS-Modernization/security/code-scanning/414
https://github.com/CDCgov/NEDSS-Modernization/security/code-scanning/415
It may also resolve
https://github.com/CDCgov/NEDSS-Modernization/security/code-scanning/409
https://github.com/CDCgov/NEDSS-Modernization/security/code-scanning/410
1. Ensure that the containers build and run by executing `docker compose up -d --build`
> [CVE] Removes Blaze and updates dependencies

- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/question/QuestionController.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/question/QuestionManagementUtil.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/question/model/DisplayControlOptions.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/question/model/DisplayOption.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/question/model/DisplayTypeOptions.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/question/request/CreateCodedQuestionRequest.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/question/request/CreateDateQuestionRequest.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/question/request/CreateNumericQuestionRequest.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/question/request/CreateQuestionRequest.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/question/request/CreateTextQuestionRequest.java
- apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/question/QuestionControllerTest.java
- apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/question/QuestionManagementUtilTest.java
The UI needs to be notified of what values are valid for the displayControl field.
https://cdc-nbs.atlassian.net/browse/CNFT2-1182
> List Valid Display Types

- apps/modernization-ui/src/apps/page-builder/components/CreateQuestion/CreateDateQuestion.tsx
- apps/modernization-ui/src/apps/page-builder/components/CreateQuestion/CreateNumericQuestion.tsx
- apps/modernization-ui/src/apps/page-builder/components/CreateQuestion/CreateQuestion.scss
- apps/modernization-ui/src/apps/page-builder/components/CreateQuestion/CreateQuestion.spec.tsx
- apps/modernization-ui/src/apps/page-builder/components/CreateQuestion/CreateQuestion.tsx
- apps/modernization-ui/src/apps/page-builder/components/CreateQuestion/CreateTextQuestion.tsx
- apps/modernization-ui/src/apps/page-builder/generated/models/CreateDateQuestionRequest.ts
- apps/modernization-ui/src/apps/page-builder/generated/services/QuestionControllerService.ts
- apps/modernization-ui/src/apps/page-builder/pages/ValuesetLibrary/ValuesetLibraryTable.tsx
[CNFT2-1185](https://cdc-nbs.atlassian.net/browse/CNFT2-1185) - To sync up the backend changes for split create question API ( https://github.com/CDCgov/NEDSS-Modernization/pull/655 )
* [Jira Ticket]https://cdc-nbs.atlassian.net/browse/CNFT2-1185
1. Provide steps here
1. Click the URL - http://localhost:3000/page-builder/manage/pages
2. Click any page name on manage pages
3. Click the add question button
4. Enter the required values and click the Create and add to page button at the bottom of the Add Question page
[CNFT2-1185]: https://cdc-nbs.atlassian.net/browse/CNFT2-1185?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CNFT2-1185] - Fixing question UI for the backend changes on PR 655

- apps/modernization-ui/src/apps/page-builder/page/library/usePageLibraryProperties.ts
- apps/modernization-ui/src/generated/graphql/schema.ts
- apps/modernization-ui/src/generated/index.ts
- apps/modernization-ui/src/generated/services/ConditionOptionsService.ts
- apps/modernization-ui/src/options/condition/index.ts
- apps/modernization-ui/src/options/condition/useConditionOptionsAutocomplete.ts
- libs/options-api/src/main/java/gov/cdc/nbs/option/condition/ConditionOptionFinder.java
- libs/options-api/src/main/java/gov/cdc/nbs/option/condition/ConditionOptionsController.java
- libs/options-api/src/main/java/gov/cdc/nbs/option/condition/autocomplete/ConditionOptionAutocompleteController.java
- libs/options-api/src/main/java/gov/cdc/nbs/option/condition/autocomplete/ConditionOptionResolver.java
- libs/options-api/src/main/java/gov/cdc/nbs/option/jdbc/OptionRowMapper.java
- libs/options-api/src/main/java/gov/cdc/nbs/option/jdbc/SQLBasedOptionFinder.java
- libs/options-api/src/main/java/gov/cdc/nbs/option/jdbc/autocomplete/SQLBasedOptionResolver.java
- libs/options-api/src/test/java/gov/cdc/nbs/option/concept/ConceptOptionsVerificationSteps.java
- libs/options-api/src/test/java/gov/cdc/nbs/option/condition/ConditionMother.java
- libs/options-api/src/test/java/gov/cdc/nbs/option/condition/ConditionOptionsSteps.java
- libs/options-api/src/test/java/gov/cdc/nbs/option/condition/ConditionRequester.java
- libs/options-api/src/test/java/gov/cdc/nbs/option/condition/ConditionSteps.java
- libs/options-api/src/test/java/gov/cdc/nbs/option/condition/autocomplete/ConditionAutocompleteRequester.java
- libs/options-api/src/test/java/gov/cdc/nbs/option/condition/autocomplete/ConditionAutocompleteSteps.java
- libs/options-api/src/test/resources/features/Concepts.Autocomplete.feature
- libs/options-api/src/test/resources/features/Concepts.feature
- libs/options-api/src/test/resources/features/condition/Conditions.feature
Connects the Page library filter for Related conditions to the options API that obtains conditions from the database.  The file count is higher than 10 because the Concept Options tests were changed to reflect only concepts and not any options.
* [Jira Ticket](https://cdc-nbs.atlassian.net/browse/CNFT2-1513)
> [CNFT2-1513] Filter page library by Related conditions

- apps/modernization-api/postman/NDESS-Modernization-API.postman_collection.json
- apps/modernization-ui/src/apps/page-builder/page/library/usePageLibraryProperties.ts
- apps/modernization-ui/src/components/selection/multi/MultiSelectAutocomplete.tsx
- apps/modernization-ui/src/filters/entry/MultiValueEntryForm.tsx
- apps/modernization-ui/src/generated/index.ts
- apps/modernization-ui/src/generated/services/UserOptionsService.ts
- apps/modernization-ui/src/options/users/index.ts
- apps/modernization-ui/src/options/users/useUserOptionsAutocomplete.ts
- apps/question-bank/postman/Question Bank.postman_collection.json
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/summary/search/PageSummarySearcher.java
- libs/options-api/src/main/java/gov/cdc/nbs/option/condition/autocomplete/ConditionOptionResolver.java
- libs/options-api/src/main/java/gov/cdc/nbs/option/users/autocomplete/UserOptionAutocompleteController.java
- libs/options-api/src/main/java/gov/cdc/nbs/option/users/autocomplete/UserOptionResolver.java
- libs/options-api/src/test/java/gov/cdc/nbs/option/user/autocomplete/UserAutocompleteRequester.java
- libs/options-api/src/test/java/gov/cdc/nbs/option/user/autocomplete/UserAutocompleteSteps.java
- libs/options-api/src/test/java/gov/cdc/nbs/option/user/autocomplete/UserOptionMother.java
- libs/options-api/src/test/java/gov/cdc/nbs/option/user/autocomplete/UserOptionSteps.java
- libs/options-api/src/test/resources/features/users/UserOptions.feature
Connects the Page library filter for Last updated by to the options API that obtains conditions from the database. 
* [CNFT2-1585](https://cdc-nbs.atlassian.net/browse/CNFT2-1585)
[CNFT2-1585]: https://cdc-nbs.atlassian.net/browse/CNFT2-1585?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CNFT2-1585] selectable users

- apps/modernization-ui/src/pages/patient/profile/identification/IdentificationsTable.tsx
- apps/modernization-ui/src/pages/patient/profile/treatment/PatientTreatmentTable.spec.tsx
- apps/modernization-ui/src/pages/patient/profile/treatment/PatientTreatmentTable.tsx
- apps/modernization-ui/src/pages/patient/profile/treatment/treatment.ts
- apps/modernization-ui/src/pages/patient/profile/treatment/treatmentSorter.spec.ts
- apps/modernization-ui/src/pages/patient/profile/treatment/treatmentSorter.ts
- apps/modernization-ui/src/pages/patient/profile/treatment/treatmentTransformer.spec.ts
- apps/modernization-ui/src/pages/patient/profile/treatment/treatmentTransformer.ts
added consistency in the implementation of the patient Treatment table and fixed the actions button for the identifications table
https://cdc-nbs.atlassian.net/browse/CNFT1-1718
> Cnft1 1718 patient treatment table consistency

- apps/modernization-ui/src/apps/page-builder/components/CreateCondition/CreateCondition.scss
- apps/modernization-ui/src/apps/page-builder/components/CreateCondition/CreateCondition.tsx
- apps/modernization-ui/src/apps/page-builder/pages/AddNewPage/AddNewPage.tsx
Here we update the Create New Condition modal in Add New Page to the current designs.
[* [Jira Ticket](url)](https://cdc-nbs.atlassian.net/browse/CNFT2-1466)
1. In Pages Library, click on `Add new page`
2. Select type 'Investigation'
3. Under `Condition(s)`, select "create a new condition here"
4. Ensure the modal matches the designs on the Add new condition modal here https://www.figma.com/file/Uz9YzHbHQAubHpQTcsibA2/NBS-PageBuilder-2.0?type=design&node-id=7903-148396&mode=dev
- [x ] PR focuses on a single story
- [x ] Functions/classes/components focused on one …
> CNFT2-1466 Create New Condition modal ux update

- apps/modernization-ui/src/apps/page-builder/pages/AddNewPage/AddNewPage.scss
- apps/modernization-ui/src/apps/page-builder/pages/AddNewPage/AddNewPageFields.tsx
Here we update some of the buttons and UX on Add new page.
[CNFT2-1557](https://cdc-nbs.atlassian.net/browse/CNFT2-1557)
1. On Pages Library, select `Add new page`
2. Select "Investigation" from the Event type menu
3. Buttons and layout should match designs. https://www.figma.com/file/Uz9YzHbHQAubHpQTcsibA2/NBS-PageBuilder-2.0?type=design&node-id=1-6365&mode=dev
- [x ] Code has been fully tested to meet acceptance criteria
- [ x] Code easy to understand and modify (clarity over concise/clever)
- [ x] PRs containing TypeScript follow …
> CNFT2-1557 Revise Search and add condition title

- apps/nbs-gateway/src/main/java/gov/cdc/nbs/gateway/pagebuilder/ManagePagesRouteConfiguration.java
- apps/nbs-gateway/src/test/java/gov/cdc/nbs/gateway/pagebuilder/ManagePagesRouteConfigurationDisabledTest.java
- apps/nbs-gateway/src/test/java/gov/cdc/nbs/gateway/pagebuilder/ManagePagesRouteConfigurationTest.java
Update the route for the page library in the nbs-gateway.
N/A
> Updates route for page library

- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/entity/WaTemplate.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/entity/question/WaQuestion.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/command/PageContentCommand.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/content/question/PageQuestionController.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/content/question/PageQuestionDeleter.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/exception/DeleteQuestionException.java
- apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/page/DeleteQuestionFromPageSteps.java
- apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/page/content/question/PageQuestionDeleterTest.java
- apps/question-bank/src/test/resources/features/page/DeleteQuestionFromPage.feature
An API needs to be created that will allow removing a question from a Draft page when the question is not standard.
https://cdc-nbs.atlassian.net/browse/CNFT2-1523
> Implement feature to remove a question from the page

- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/PageDownloader.java
Page library Download to csv file, Last updated column should display date in the MM/DD/YYYY format.
https://cdc-nbs.atlassian.net/browse/CNFT2-1643
> Fix the Last Updated date format in Page Library CSV download

- apps/modernization-ui/src/apps/page-builder/page/management/edit/subsection/SubsectionHeader.tsx
- apps/modernization-ui/src/apps/page-builder/pages/QuestionLibrary/QuestionLibrary.scss
- apps/modernization-ui/src/apps/page-builder/pages/QuestionLibrary/QuestionLibrary.tsx
- apps/modernization-ui/src/apps/page-builder/pages/QuestionLibrary/QuestionLibraryTable.spec.tsx
- apps/modernization-ui/src/apps/page-builder/pages/QuestionLibrary/QuestionLibraryTable.tsx
- apps/modernization-ui/src/apps/page-builder/pages/QuestionLibrary/useQuestionAPI.ts
- apps/modernization-ui/src/components/ModalComponent/ModalComponent.tsx
- apps/modernization-ui/src/routes/AppRoutes.tsx
Developed Search Question UI
* [Jira Ticket] https://cdc-nbs.atlassian.net/browse/CNFT2-1577
> [CNFT2-1577] - Search Question

- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/filter/querydsl/DefaultQueryDSLCriteriaResolver.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/filter/querydsl/QueryDSLFilterApplier.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/PageStatus.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/PageStatusResolver.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/summary/search/PageSummaryMapper.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/summary/search/PageSummarySearcher.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/summary/search/PageSummaryTables.java
- apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/filter/querydsl/DefaultQueryDSLCriteriaResolverTest.java
- apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/page/summary/search/PageSummarySearchSteps.java
- apps/question-bank/src/test/resources/features/page/summary/search/PageSummarySearch.filtering.status.feature
Ensures that page status is filtered using derived values
* [CNFT2-1649](https://cdc-nbs.atlassian.net/browse/CNFT2-1649)
[CNFT2-1649]: https://cdc-nbs.atlassian.net/browse/CNFT2-1649?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CNFT2-1649] Ensures that page status is filtered using derived values

- apps/modernization-ui/src/apps/page-builder/components/DeleteQuestion/DeleteQuestion.scss
- apps/modernization-ui/src/apps/page-builder/components/DeleteQuestion/DeleteQuestion.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/question/Question.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/question/QuestionHeader.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/subsection/Subsection.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/subsection/SubsectionHeader.tsx
Developed Delete Question
* [Jira Ticket] https://cdc-nbs.atlassian.net/browse/CNFT2-1572
> [CNFT2_1572] - Delete Question

- apps/modernization-ui/src/apps/page-builder/page/management/edit/content/PageContent.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/section/Section.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/section/Sections.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/subsection/Subsection.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/subsection/SubsectionHeader.tsx
- apps/modernization-ui/src/apps/page-builder/pages/QuestionLibrary/QuestionLibrary.scss
- apps/modernization-ui/src/apps/page-builder/pages/QuestionLibrary/QuestionLibrary.tsx
- apps/modernization-ui/src/apps/page-builder/pages/QuestionLibrary/QuestionLibraryTable.tsx
Developed search question UI
* [Jira Ticket] https://cdc-nbs.atlassian.net/browse/CNFT2-1577
> [CNFT-1577] search question

- apps/modernization-ui/src/pages/advancedSearch/components/InvestigationResults.spec.tsx
- apps/modernization-ui/src/pages/advancedSearch/components/LabReportResults.spec.tsx
- apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/condition/create/ConditionCreatorTest.java
A few tests had a hard coded value for the current year and began failing. This PR fixes the failing tests.
NA
> Fix year specific tests

- apps/modernization-ui/src/apps/page-builder/pages/AddNewPage/AddNewPageFields.tsx
- apps/modernization-ui/src/validation/entry/dataMartNameRule.ts
Here we validate the Datamart Name field when Adding a new Page.
An error message is displayed when the name begins with a number or when special characters, excluding underscores, are used.
https://cdc-nbs.atlassian.net/browse/CNFT2-1558
> CNFT2-1558 Datamart name - numeric & special char

- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/condition/ConditionReader.java
Resolve search issue for existing condition code while searching by condition code (partial) 
https://cdc-nbs.atlassian.net/browse/CNFT2-1420
> Resolve search issue for existing condition code. 

- apps/modernization-ui/src/apps/page-builder/components/QuickConditionLookup/QuickConditionLookup.tsx
Changing the text on a button
* [Jira Ticket](https://cdc-nbs.atlassian.net/jira/software/c/projects/CNFT2/boards/99?assignee=712020%3A591f5469-427d-49e9-87dc-8b4df72a02b4&selectedIssue=CNFT2-1428)
- [x ] Functions/classes/components focused on one responsibility
- [ x] Code easy to understand and modify (clarity over concise/clever)
- [x ] PRs containing TypeScript follow the [Do's and Don'ts](https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html)
- [x ] PR does not contain hardcoded values (Uses …
> rename add condition button

- .github/workflows/Release-candidate-containers.yml
Fixes an issue where the prepare steps were not referencing the correct build outputs.
Adds Page builder to the release candidate containers workflow
* [CNFT1-1863](https://cdc-nbs.atlassian.net/browse/CNFT1-1863)
[CNFT1-1863]: https://cdc-nbs.atlassian.net/browse/CNFT1-1863?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CNFT1-1863] Release workflow includes page builder API

- apps/modernization-ui/src/apps/page-builder/components/CreateQuestion/CreateQuestion.scss
- apps/modernization-ui/src/apps/page-builder/components/CreateQuestion/CreateQuestion.tsx
- apps/modernization-ui/src/apps/page-builder/context/QuestionsContext.tsx
- apps/modernization-ui/src/apps/page-builder/context/contextData.ts
- apps/modernization-ui/src/apps/page-builder/page/management/edit/content/PageContent.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/question/Question.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/question/QuestionHeader.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/section/Section.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/section/Sections.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/subsection/Subsection.tsx
- apps/modernization-ui/src/apps/page-builder/pages/ValuesetLibrary/ValuesetLibraryTable.tsx
Developed the Edit Question
* [Jira Ticket] https://cdc-nbs.atlassian.net/browse/CNFT2-1571
> [CNFT2-1571] - Edit Question

- apps/modernization-api/build.gradle
- apps/modernization-ui/src/pages/advancedSearch/components/InvestigationResults.spec.tsx
- apps/modernization-ui/src/pages/advancedSearch/components/LabReportResults.spec.tsx
- apps/nbs-gateway/build.gradle
- apps/question-bank/build.gradle
- apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/condition/create/ConditionCreatorTest.java
- gradle/libs.versions.toml
- gradle/spring-dependency-override.gradle
Addresses the follow security scan issues by updating dependency versions for `logback`
https://github.com/CDCgov/NEDSS-Modernization/security/code-scanning/423
https://github.com/CDCgov/NEDSS-Modernization/security/code-scanning/421
https://github.com/CDCgov/NEDSS-Modernization/security/code-scanning/420
https://github.com/CDCgov/NEDSS-Modernization/security/code-scanning/419
https://github.com/CDCgov/NEDSS-Modernization/security/code-scanning/418
The outstanding [CVE-2023-4043](https://www.cve.org/CVERecord?id=CVE-2023-4043) with [parson](https://security.snyk.io/vuln/SNYK-JAVA-ORGECLIPSEPARSSON-6044728) has also been addresses.
PR #853 was included to resolve failing tests
* [CNFT1-1934](https://cdc-nbs.atlassian.net/browse/CNFT1-1934)
[CNFT1-1934]: …
> [CNFT1-1934] CVE mitigation

- apps/modernization-api/build.gradle
- apps/modernization-ui/src/pages/advancedSearch/components/InvestigationResults.spec.tsx
- apps/modernization-ui/src/pages/advancedSearch/components/LabReportResults.spec.tsx
- apps/nbs-gateway/build.gradle
- apps/question-bank/build.gradle
- apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/condition/create/ConditionCreatorTest.java
- gradle/libs.versions.toml
- gradle/spring-dependency-override.gradle
Addresses the follow security scan issues by updating dependency versions for `logback`
https://github.com/CDCgov/NEDSS-Modernization/security/code-scanning/423
https://github.com/CDCgov/NEDSS-Modernization/security/code-scanning/421
https://github.com/CDCgov/NEDSS-Modernization/security/code-scanning/420
https://github.com/CDCgov/NEDSS-Modernization/security/code-scanning/419
https://github.com/CDCgov/NEDSS-Modernization/security/code-scanning/418
The outstanding [CVE-2023-4043](https://www.cve.org/CVERecord?id=CVE-2023-4043) with [parson](https://security.snyk.io/vuln/SNYK-JAVA-ORGECLIPSEPARSSON-6044728) has also been addresses.
* [CNFT1-1934](https://cdc-nbs.atlassian.net/browse/CNFT1-1934)
[CNFT1-1934]: https://cdc-nbs.atlassian.net/browse/CNFT1-1934?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmN …
> [CNFT1-1934] CVE mitigation for security scans

- apps/modernization-ui/src/apps/page-builder/pages/AddNewPage/AddNewPage.spec.tsx
- apps/modernization-ui/src/apps/page-builder/pages/AddNewPage/AddNewPage.tsx
Updates the `Add new page` title to `Create new page`
* [CNFT2-1678](https://cdc-nbs.atlassian.net/browse/CNFT2-1678)
[CNFT2-1678]: https://cdc-nbs.atlassian.net/browse/CNFT2-1678?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Updates Add new page to be Create new page

- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/valueset/ValueSetUpdater.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/valueset/request/ValueSetUpdateRequest.java
Refactoring of the update value-set API to accept the UI(figma) input parameters.
https://cdc-nbs.atlassian.net/browse/CNFT2-1659
> Refactoring of the update value-set API

- apps/modernization-ui/src/apps/patient/add/nameFields/NameFields.spec.tsx
- apps/modernization-ui/src/apps/patient/profile/names/NameEntryForm.spec.tsx
- apps/modernization-ui/src/validation/entry/validNameRule.ts
Removing validations in the name Fields for patient profile, add patient and patient search where the name entry fields are used. Modified the spec files accordingly reflecting how certain scenarios are now valid.
* [CNFT1-1836](https://cdc-nbs.atlassian.net/browse/CNFT1-1836)
Steps to reproduce
1. Navigate to the name field in patient search, patient profile demographics names table, and the add patient name fields to test adding special characters and observing how there permitted.
[CNFT1-1836]: https://cdc-nbs.atlassian.net/browse/CNFT1-1836?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> removing validations for name field and mofifying test files accordingly

- apps/modernization-ui/src/apps/page-builder/components/CreateQuestion/CreateQuestion.scss
- apps/modernization-ui/src/apps/page-builder/components/CreateQuestion/CreateQuestion.tsx
- apps/modernization-ui/src/apps/page-builder/components/Subsection/AddQuestionModal/AddQuestionModal.tsx
- apps/modernization-ui/src/apps/page-builder/components/ToggleButton/index.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/question/QuestionContent.tsx
- apps/modernization-ui/src/apps/page-builder/pages/QuestionLibrary/QuestionLibrary.scss
- apps/modernization-ui/src/apps/page-builder/pages/QuestionLibrary/QuestionLibrary.tsx
- apps/modernization-ui/src/apps/page-builder/pages/QuestionLibrary/QuestionLibraryTable.tsx
- apps/modernization-ui/src/components/Table/RangeToggle/RangeToggle.tsx
Developed Numeric Question
* [Jira Ticket] https://cdc-nbs.atlassian.net/browse/CNFT2-1709
> [CNFT2-1709] - Numeric Question

- apps/modernization-ui/src/apps/page-builder/components/CreateQuestion/CreateDateQuestion.tsx
Developed Date Question
* [Jira Ticket] https://cdc-nbs.atlassian.net/browse/CNFT2-1710
> [CNFT2 -1710] Date Question

- apps/modernization-ui/src/apps/page-builder/condition/search/ConditionTable.spec.tsx
- apps/modernization-ui/src/apps/page-builder/condition/search/ConditionTable.tsx
- apps/modernization-ui/src/apps/page-builder/pages/AddNewPage/AddNewPage.tsx
Conditon Search table: 
1. Clear selection on new search
2. Prevent duplicate conditions being added to selection
* [CNFT2-1699](https://cdc-nbs.atlassian.net/browse/CNFT2-1699)
[CNFT2-1699]: https://cdc-nbs.atlassian.net/browse/CNFT2-1699?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CNFT2-1699 Clear selection

- apps/modernization-ui/src/apps/page-builder/page/library/table/ConditionsDisplay.spec.tsx
- apps/modernization-ui/src/apps/page-builder/page/library/table/ConditionsDisplay.tsx
- apps/modernization-ui/src/apps/page-builder/page/library/table/PageLibraryTable.tsx
- apps/modernization-ui/src/apps/page-builder/page/library/table/page-library-table.module.scss
Updates the condition display in the page library table.
* [CNFT2-1723](https://cdc-nbs.atlassian.net/browse/CNFT2-1723)
[CNFT2-1723]: https://cdc-nbs.atlassian.net/browse/CNFT2-1723?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CNFT2-1723 Condition Display

- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/summary/search/PageSummarySearcher.java
- apps/question-bank/src/test/resources/features/page/summary/search/PageSummarySearch.feature
Adds the condition Id to the searched fields for the page summary search.
* [CNFT2-1723](https://cdc-nbs.atlassian.net/browse/CNFT2-1723)
[CNFT2-1723]: https://cdc-nbs.atlassian.net/browse/CNFT2-1723?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Allow searching on condition id

- apps/modernization-ui/src/apps/page-builder/components/CreateQuestion/CreateQuestion.scss
- apps/modernization-ui/src/apps/page-builder/components/CreateQuestion/CreateQuestion.tsx
- apps/modernization-ui/src/apps/page-builder/context/QuestionsContext.tsx
- apps/modernization-ui/src/apps/page-builder/context/contextData.ts
- apps/modernization-ui/src/apps/page-builder/pages/ValuesetLibrary/SearchBar.tsx
- apps/modernization-ui/src/apps/page-builder/pages/ValuesetLibrary/ValuesetLibrary.scss
- apps/modernization-ui/src/apps/page-builder/pages/ValuesetLibrary/ValuesetLibraryTable.tsx
- apps/modernization-ui/src/components/Table/Table.tsx
Developed Create Question UI for Coded Field Type
* [Jira Ticket] https://cdc-nbs.atlassian.net/browse/CNFT2-1711
> {CNFT2-1711] - Create Coded Question

- apps/modernization-ui/src/apps/page-builder/page/library/menu/FilterDisplay.tsx
- apps/modernization-ui/src/apps/page-builder/page/library/menu/PageLibraryMenu.tsx
- apps/modernization-ui/src/apps/page-builder/page/library/menu/filter-display.module.scss
- apps/modernization-ui/src/apps/page-builder/page/library/menu/page-library-menu.module.scss
- apps/modernization-ui/src/filters/applied/AppliedFilters.tsx
- apps/modernization-ui/src/filters/asDisplayableFilter.ts
- apps/modernization-ui/src/filters/panel/FilterPanel.tsx
- apps/modernization-ui/src/filters/panel/filter-panel.module.scss
- apps/modernization-ui/src/overlay/OverlayPanel.tsx
- apps/modernization-ui/src/overlay/overlay-panel.module.scss
* [CNFT2-1724](https://cdc-nbs.atlassian.net/browse/CNFT2-1724)
[CNFT2-1724]: https://cdc-nbs.atlassian.net/browse/CNFT2-1724?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Cnft2 1724 filter display

- apps/modernization-ui/src/apps/page-builder/page/library/table/PageLibraryTable.tsx
- apps/modernization-ui/src/apps/page-builder/page/library/table/page-library-table.module.scss
Prevent text overflow by adding word-wrap break-word
* [CNFT2-1733](https://cdc-nbs.atlassian.net/browse/CNFT2-1733)
[CNFT2-1733]: https://cdc-nbs.atlassian.net/browse/CNFT2-1733?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CNFT2-1733 text overflow

- apps/modernization-ui/src/apps/page-builder/components/AddValueset/AddValueset.scss
- apps/modernization-ui/src/apps/page-builder/components/AddValueset/AddValueset.tsx
- apps/modernization-ui/src/apps/page-builder/components/Concept/Concept.scss
- apps/modernization-ui/src/apps/page-builder/components/CreateQuestion/CreateQuestion.tsx
- apps/modernization-ui/src/apps/page-builder/components/Subsection/AddQuestionModal/AddQuestionModal.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/content/PageContent.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/question/QuestionContent.tsx
- apps/modernization-ui/src/apps/page-builder/pages/ValuesetLibrary/SearchBar.tsx
- apps/modernization-ui/src/apps/page-builder/pages/ValuesetLibrary/ValuesetLibrary.scss
- apps/modernization-ui/src/apps/page-builder/pages/ValuesetLibrary/ValuesetLibrary.tsx
- apps/modernization-ui/src/apps/page-builder/pages/ValuesetLibrary/ValuesetLibraryTable.tsx
Developed Create Value set UI
* [Jira Ticket] https://cdc-nbs.atlassian.net/browse/CNFT2-1576
> [CNFT2-1576] - Create Valueset

- apps/modernization-ui/src/apps/page-builder/context/DragDropProvider.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/Edit.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/section/manage/AddSection.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/section/manage/ManageSection.spec.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/section/manage/ManageSection.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/section/manage/ManageSectionModal.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/section/manage/ManageSectionTile/ManageSectionTile.spec.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/section/manage/ManageSectionTile/ManageSectionTile.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/section/manage/ManageSectionTile/manageSectionTile.module.scss
- apps/modernization-ui/src/apps/page-builder/page/management/edit/section/manage/managesection.module.scss
- apps/modernization-ui/src/apps/page-builder/pages/EditPage/ReorderQuestion/ReorderQuestion.spec.tsx
- apps/modernization-ui/src/components/ModalComponent/ModalComponent.tsx
Here we have the ManageSection modal which will list out the Sections which can be reordered.
A slight adjustment was made to DragDropProvider
[* [Jira Ticket](url)](https://cdc-nbs.atlassian.net/browse/CNFT2-1682)
> CNFT2-1682 Edit page: Manage Section

- apps/modernization-ui/src/apps/page-builder/components/Concept/CreateConcept/CreateConcept.tsx
- apps/modernization-ui/src/apps/page-builder/components/CreateQuestion/CreateQuestion.tsx
Fix for concepts
* [Jira Ticket] https://cdc-nbs.atlassian.net/browse/CNFT2-1576
> [CNFT2-1576] - Concept_Fix

- apps/modernization-ui/src/apps/page-builder/page/management/edit/section/manage/AddSection.tsx
Validation for the section name
* [CNFT2-1662](https://cdc-nbs.atlassian.net/browse/CNFT2-1662)
[CNFT2-1662]: https://cdc-nbs.atlassian.net/browse/CNFT2-1662?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CNFT2-1662-add-section

- apps/modernization-ui/src/apps/page-builder/page/management/edit/section/SectionHeader.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/section/Sections.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/section/manage/ManageSectionTile/ManageSectionTile.tsx
Small design changes and bugs fixed
> cnft2 1601 delete section bug

- apps/modernization-ui/src/apps/page-builder/page/management/edit/content/PageContent.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/section/Section.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/section/Sections.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/section/manage/AddSection.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/section/manage/ManageSection.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/section/manage/ManageSectionModal.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/section/manage/ManageSectionTile/ManageSectionTile.spec.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/section/manage/ManageSectionTile/ManageSectionTile.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/section/manage/ManageSectionTile/manageSectionTile.module.scss
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/content/section/SectionUpdater.java
Editing sections within the edit page.
1. Edit section UI functionality
2. Small API change done
3. Small changes with how the alert was displaying for add section as well, and changing the message that was being printed out
* [CNFT2-1664](https://cdc-nbs.atlassian.net/browse/CNFT2-1664)
[CNFT2-1664]: https://cdc-nbs.atlassian.net/browse/CNFT2-1664?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Cnft2 1664 edit section

- apps/modernization-ui/src/apps/page-builder/page/management/edit/Edit.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/tabs/AddEditTab/AddEditTab.spec.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/tabs/AddEditTab/AddEditTab.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/tabs/AddEditTab/addedittab.module.scss
- apps/modernization-ui/src/apps/page-builder/page/management/edit/tabs/ManageTabs/ManageTabs.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/tabs/ManageTabs/manageTabs.module.scss
- apps/modernization-ui/src/apps/page-builder/page/management/header/PageHeader.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/header/tabs/PageTabs.spec.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/header/tabs/PageTabs.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/header/tabs/page-tabs.module.scss
- apps/modernization-ui/src/components/ModalComponent/ModalComponent.scss
Here we create the button and modal to Manage Tabs. The button appears in the tab bar in Edit mode. The modal will have other functionality in subsequent tickets. For now, you can click Add new tab to bring up the form to add. An alert pops up upon success and the page underneath refreshs the tabs.
[* [Jira Ticket](url)](https://cdc-nbs.atlassian.net/browse/CNFT2-1704)
> CNFT2-1704 Edit page: Add Tab

- apps/modernization-ui/src/apps/page-builder/page/management/edit/question/Question.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/question/QuestionContent.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/section/manage/AddSection.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/section/manage/ManageSection.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/section/manage/ManageSectionModal.tsx
1. Revise alert banners for section features
2. Fix bug with question content, that was messing with the CSS and display of the static elements on the Edit page
3. Fix header of the Edit section modal to have correct message
* [CNFT2-1664](https://cdc-nbs.atlassian.net/browse/CNFT2-1664)
[CNFT2-1664]: https://cdc-nbs.atlassian.net/browse/CNFT2-1664?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Bug fixed on section and question content displays

- apps/modernization-ui/src/apps/page-builder/components/CreateQuestion/CreateQuestion.tsx
Fixed create question issue
* [Jira Ticket] https://cdc-nbs.atlassian.net/browse/CNFT2-1571
> create question issue fixes

- apps/modernization-ui/src/apps/page-builder/page/management/edit/Edit.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/content/PageContent.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/section/Section.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/section/SectionHeader.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/section/Sections.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/section/section.module.scss
- apps/modernization-ui/src/apps/page-builder/page/management/edit/subsection/SubsectionHeader.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/subsection/manage/AddSubSection.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/subsection/manage/ManageSubsection.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/subsection/manage/ManageSubsectionTile/ManageSubsectionTile.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/subsection/manage/ManageSubsectionTile/managesubsectiontile.module.scss
- apps/modernization-ui/src/apps/page-builder/page/management/edit/subsection/manage/addsubsection.module.scss
- apps/modernization-ui/src/apps/page-builder/page/management/edit/subsection/manage/managesubsection.module.scss
- apps/modernization-ui/src/apps/page-builder/page/management/edit/subsection/manage/subsection.module.scss
As a PB user, I want to add a subsection to a page, so I can add questions to the subsection.
* [CNFT2-1663](https://cdc-nbs.atlassian.net/browse/CNFT2-1663)
[CNFT2-1663]: https://cdc-nbs.atlassian.net/browse/CNFT2-1663?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Cnft2 1663 add subsection

- apps/modernization-ui/src/apps/page-builder/page/management/edit/Edit.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/tabs/ManageTabs/ManageTabs.spec.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/tabs/ManageTabs/ManageTabs.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/tabs/ManageTabsTile/ManageTabsTile.spec.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/tabs/ManageTabsTile/ManageTabsTile.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/tabs/ManageTabsTile/manageTabsTile.module.scss
- apps/modernization-ui/src/apps/page-builder/page/management/header/PageHeader.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/header/tabs/PageTabs.spec.tsx
Here we add the functionality to edit a tab in the Manage Tabs modal. 
[* [Jira Ticket](url)](https://cdc-nbs.atlassian.net/browse/CNFT2-1705)
> CNFT2-1705 Edit page: edit tab

- apps/modernization-ui/src/apps/page-builder/components/CreateQuestion/CreateDateQuestion.tsx
- apps/modernization-ui/src/apps/page-builder/components/CreateQuestion/CreateQuestion.scss
- apps/modernization-ui/src/apps/page-builder/components/CreateQuestion/CreateQuestion.tsx
- apps/modernization-ui/src/apps/page-builder/components/CreateQuestion/CreateTextQuestion.tsx
- apps/modernization-ui/src/components/ModalComponent/ModalComponent.scss
- apps/modernization-ui/src/components/Table/Table.tsx
Fix for Date format Generic date
* [Jira Ticket] https://cdc-nbs.atlassian.net/browse/CNFT2-1571
> [CNFT2-1571] - Fix for Date format Generic date

- apps/modernization-ui/src/apps/page-builder/page/management/edit/section/Section.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/section/Sections.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/subsection/Subsection.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/subsection/SubsectionHeader.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/subsection/manage/ManageSubsection.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/subsection/manage/ManageSubsectionTile/ManageSubsectionTile.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/subsection/manage/ManageSubsectionTile/managesubsectiontile.module.scss
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/content/subsection/SubSectionDeleter.java
As a user, I want to delete a subsection when the section is not needed.
* [CNFT2-1661](https://cdc-nbs.atlassian.net/browse/CNFT2-1661)
[CNFT2-1661]: https://cdc-nbs.atlassian.net/browse/CNFT2-1661?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Cnft2 1661 delete subsection

- apps/modernization-ui/src/apps/page-builder/context/DragDropProvider.tsx
- apps/modernization-ui/src/apps/page-builder/helpers/moveObjectInArray.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/tabs/ManageTabs/ManageTabs.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/tabs/ManageTabs/manageTabs.module.scss
- apps/modernization-ui/src/apps/page-builder/page/management/edit/tabs/ManageTabsTile/manageTabsTile.module.scss
- apps/modernization-ui/src/components/ModalComponent/ModalComponent.scss
Here we enable drag drop to reorder tabs in Edit Page.
[* [Jira Ticket](url)](https://cdc-nbs.atlassian.net/browse/CNFT2-1707)
> CNFT2-1701 Edit page: Manage tab

- apps/modernization-ui/src/apps/page-builder/components/CreateQuestion/CreateCodedQuestion.tsx
- apps/modernization-ui/src/apps/page-builder/components/CreateQuestion/CreateQuestion.tsx
Edit page- Add question- Field Type (Value set)
* [Jira Ticket][https://cdc-nbs.atlassian.net/browse/CNFT2-1812]
> [CNFT2-1812] Edit page- Add question- Field Type (Value set)

- apps/modernization-ui/src/apps/page-builder/components/CreateQuestion/CreateQuestion.tsx
Edit page- Add question- Field Type (Numeric Entry)/ Field Type(Text Only)
* [Jira Ticket] [https://cdc-nbs.atlassian.net/browse/CNFT2-1813]
> [CNFT2-1813] - Edit page- Add question- Field Type (Numeric Entry)/ Field Type(Text Only)

- apps/modernization-ui/src/apps/page-builder/generated/services/TemplateControllerService.ts
- apps/modernization-ui/src/apps/page-builder/pages/AddNewPage/AddNewPage.tsx
- apps/modernization-ui/src/apps/page-builder/services/templatesAPI.ts
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/entity/repository/WaTemplateRepository.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/template/TemplateController.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/template/TemplateFinder.java
- apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/template/FindTemplateSteps.java
- apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/template/TemplateReaderTest.java
- apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/template/TemplateRequester.java
- apps/question-bank/src/test/resources/features/template/FindTemplate.feature
When selecting a template for a new page, only Investigation(INV) templates should be displayed.
* [CNFT2-1774](https://cdc-nbs.atlassian.net/browse/CNFT2-1774)
[CNFT2-1774]: https://cdc-nbs.atlassian.net/browse/CNFT2-1774?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Cnft2 1774 template drop down

- apps/modernization-ui/src/apps/page-builder/components/CreateCondition/CreateCondition.tsx
- apps/modernization-ui/src/apps/page-builder/pages/AddNewPage/AddNewPage.scss
- apps/modernization-ui/src/apps/page-builder/pages/AddNewPage/AddNewPageFields.tsx
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/condition/ConditionCreator.java
Multiple bug fixes, fixing create new page
* [CNFT2-1782](https://cdc-nbs.atlassian.net/browse/CNFT2-1782)
* [CNFT2-1783](https://cdc-nbs.atlassian.net/browse/CNFT2-1783)
* [CNFT2-1784](https://cdc-nbs.atlassian.net/browse/CNFT2-1784)
* [CNFT2-1786](https://cdc-nbs.atlassian.net/browse/CNFT2-1786)
[CNFT2-1782]: https://cdc-nbs.atlassian.net/browse/CNFT2-1782?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CNFT2-1783]: https://cdc-nbs.atlassian.net/browse/CNFT2-1783?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CNFT2-1784]: https://cdc-nbs.atlassian.net/browse/CNFT2-1784?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CNFT2-1786]: …
> create new page bug fixes

- apps/modernization-ui/src/apps/page-builder/context/DragDropProvider.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/section/Section.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/section/manage/ManageSectionTile/ManageSectionTile.spec.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/section/manage/ManageSectionTile/ManageSectionTile.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/section/manage/ManageSectionTile/manageSectionTile.module.scss
- apps/modernization-ui/src/apps/page-builder/page/management/edit/subsection/manage/ManageSubsection.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/subsection/manage/ManageSubsectionTile/ManageSubsectionTile.spec.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/subsection/manage/ManageSubsectionTile/ManageSubsectionTile.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/subsection/manage/ManageSubsectionTile/managesubsectiontile.module.scss
Here we enable reordering subsections in the ManageSubsections modal.
* [CNFT2-1683](https://cdc-nbs.atlassian.net/browse/CNFT2-1683)
[CNFT2-1683]: https://cdc-nbs.atlassian.net/browse/CNFT2-1683?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CNFT2-1683 Edit page: Manage subsection

- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/component/ContentNode.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/component/tree/ContentComponentResolver.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/component/tree/FlattenedComponent.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/component/tree/FlattenedComponentFinder.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/component/tree/FlattenedComponentMapper.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/detail/PagesResponse.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/detail/PagesResponseMapper.java
- apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/page/component/tree/ContentComponentResolverTestNode.java
- apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/page/component/tree/TreeifyTest.java
- apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/page/detail/PagesResponseMapperTest.java
Field length, Default label in report, Default RDB table name and RDB column name are not retrieving values. Upon clicking Edit Question API should be pulling the values
https://cdc-nbs.atlassian.net/browse/CNFT2-1789
> add Missing Fields for Edit Question

- apps/modernization-ui/src/apps/page-builder/components/CreateQuestion/CreateCodedQuestion.tsx
- apps/modernization-ui/src/apps/page-builder/components/CreateQuestion/CreateQuestion.tsx
Fixed the Concepts are not displaying in dropdown values
* [Jira Ticket] https://cdc-nbs.atlassian.net/browse/CNFT2-1812
> [CNFT2-1812] - Fixed the Concepts are not displaying in dropdown values

- apps/modernization-ui/src/apps/page-builder/generated/models/ValueSet.ts
- apps/modernization-ui/src/apps/page-builder/pages/ValuesetLibrary/ValuesetLibrary.tsx
- apps/modernization-ui/src/apps/page-builder/pages/ValuesetLibrary/ValuesetLibraryTable.tsx
Fixed value set issue CNFT2-1756 CNFT2-1757 CNFT2-1813
* [Jira Ticket] https://cdc-nbs.atlassian.net/browse/CNFT2-1756 https://cdc-nbs.atlassian.net/browse/CNFT2-1757  https://cdc-nbs.atlassian.net/browse/CNFT2-1813
> Fixed value set issue

- apps/modernization-ui/src/apps/page-builder/components/AddValueset/AddValueset.tsx
- apps/modernization-ui/src/apps/page-builder/components/Concept/Concept.scss
- apps/modernization-ui/src/apps/page-builder/components/Concept/Concept.tsx
- apps/modernization-ui/src/apps/page-builder/components/Concept/CreateConcept/CreateConcept.tsx
- apps/modernization-ui/src/apps/page-builder/context/QuestionsContext.tsx
- apps/modernization-ui/src/apps/page-builder/context/contextData.ts
- apps/modernization-ui/src/apps/page-builder/page/management/edit/content/PageContent.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/question/QuestionContent.tsx
Developed Edit Valueset UI screens
* [Jira Ticket] https://cdc-nbs.atlassian.net/browse/CNFT2-1578
> Edit Valueset

- apps/modernization-ui/src/apps/page-builder/components/CreateQuestion/CreateNumericQuestion.tsx
- apps/modernization-ui/src/apps/page-builder/components/CreateQuestion/CreateQuestion.tsx
- apps/modernization-ui/src/apps/page-builder/components/CreateQuestion/CreateTextQuestion.tsx
Create Question Bug fix
* [Jira Ticket] https://cdc-nbs.atlassian.net/browse/CNFT2-1849
> [CNFT2-1849] - Create Question bug fix

- apps/modernization-ui/src/apps/page-builder/page/management/edit/section/Section.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/section/manage/AddSection.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/section/manage/ManageSection.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/subsection/Subsection.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/subsection/SubsectionHeader.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/subsection/manage/AddSubSection.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/subsection/manage/ManageSubsection.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/subsection/manage/ManageSubsectionTile/ManageSubsectionTile.spec.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/subsection/manage/ManageSubsectionTile/ManageSubsectionTile.tsx
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/content/subsection/SubSectionUpdater.java
As a PB user, I want to edit a subsection on a page, so I can change the subsection name or its visibility.
* [CNFT2-1665](https://cdc-nbs.atlassian.net/browse/CNFT2-1665)
[CNFT2-1665]: https://cdc-nbs.atlassian.net/browse/CNFT2-1665?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CNFT2-1665 edit subsection

- apps/modernization-ui/src/apps/page-builder/components/AddValueset/AddValueset.tsx
- apps/modernization-ui/src/apps/page-builder/components/CreateQuestion/CreateCodedQuestion.tsx
- apps/modernization-ui/src/apps/page-builder/components/CreateQuestion/CreateQuestion.tsx
- apps/modernization-ui/src/apps/page-builder/components/CreateQuestion/CreateTextQuestion.tsx
Fixed edit and create question issue
* [Jira Ticket] https://cdc-nbs.atlassian.net/browse/CNFT2-1849
> [CNFT2-1849] - Fixed edit and create question issue

- apps/modernization-ui/src/apps/page-builder/components/CreateQuestion/CreateQuestion.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/content/PageContent.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/question/Question.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/question/QuestionContent.tsx
- apps/modernization-ui/src/apps/page-builder/pages/ValuesetLibrary/ValuesetLibraryTable.tsx
Fix for auto reflect Datamart Column name field with RDB Column name.
* [Jira Ticket] https://cdc-nbs.atlassian.net/browse/CNFT2-1882
> [CNFT2-1882] - Datamart column name field fix

- apps/modernization-ui/src/apps/page-builder/components/CreateQuestion/CreateQuestion.tsx
Fix for description field maximum of 50 character length
* [Jira Ticket]https://cdc-nbs.atlassian.net/browse/CNFT2-1844
> [CNFT2-1844] - Description Max 50 character

- apps/modernization-ui/src/apps/page-builder/components/CreateQuestion/CreateQuestion.tsx
[CNFT2-1882] [CNFT2-1844] [CNFT2-1813] - fixed length and value set bug
* [Jira Ticket]https://cdc-nbs.atlassian.net/browse/CNFT2-1813, https://cdc-nbs.atlassian.net/browse/CNFT2-1844, https://cdc-nbs.atlassian.net/browse/CNFT2-1882
[CNFT2-1882]: https://cdc-nbs.atlassian.net/browse/CNFT2-1882?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CNFT2-1844]: https://cdc-nbs.atlassian.net/browse/CNFT2-1844?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CNFT2-1813]: https://cdc-nbs.atlassian.net/browse/CNFT2-1813?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CNFT2-1882] [CNFT2-1844] [CNFT2-1813] - fixed length and value set bug

- apps/modernization-ui/src/apps/search/event/components/LabReportSearch/LabReportGeneralFields.tsx
* [CNFT1-1963](https://cdc-nbs.atlassian.net/browse/CNFT1-1963)
[CNFT1-1963]: https://cdc-nbs.atlassian.net/browse/CNFT1-1963?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> User search api autocomplete for Event Search Created by User for Lab Report

- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/component/SubSectionNode.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/component/tree/FlattenedComponent.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/component/tree/FlattenedComponentFinder.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/component/tree/FlattenedComponentMapper.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/component/tree/LayoutComponentResolver.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/detail/PagesResponse.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/detail/PagesResponseMapper.java
- apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/page/component/tree/ContentComponentResolverTestNode.java
- apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/page/component/tree/FlattenedComponentMapperTest.java
- apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/page/component/tree/TreeifyTest.java
- apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/page/detail/PagesResponseMapperTest.java
The subsection object needs to have a isGrouped key in order to change the view for grouped questions in subsections.
https://cdc-nbs.atlassian.net/browse/CNFT2-1907
> Add isGrouped key in Subsection objects

- apps/modernization-ui/src/apps/page-builder/components/CreateQuestion/CreateQuestion.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/question/Question.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/question/QuestionContent.tsx
Fixed bug in Question UI.
* [Jira Ticket] - https://cdc-nbs.atlassian.net/browse/CNFT2-1882
> [CNFT2-1882] - Question bug fix

- apps/modernization-ui/src/apps/page-builder/page/management/edit/section/Sections.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/section/manage/AddSection.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/subsection/manage/AddSubSection.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/subsection/manage/ManageSubsectionTile/ManageSubsectionTile.tsx
- apps/modernization-ui/src/validation/entry/checkEmptyRule.ts
- apps/modernization-ui/src/validation/entry/notEmptyRule.ts
Multiple bug fixes within subsection, and making the small bug fixes to section as well
* [CNFT2-1886](https://cdc-nbs.atlassian.net/browse/CNFT2-1886)
* [CNFT2-1901](https://cdc-nbs.atlassian.net/browse/CNFT2-1901)
* [CNFT2-1885](https://cdc-nbs.atlassian.net/browse/CNFT2-1885)
[CNFT2-1886]: https://cdc-nbs.atlassian.net/browse/CNFT2-1886?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CNFT2-1901]: https://cdc-nbs.atlassian.net/browse/CNFT2-1901?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CNFT2-1885]: https://cdc-nbs.atlassian.net/browse/CNFT2-1885?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Bug fixes subsection

- apps/modernization-ui/src/apps/patient/profile/Demographics.tsx
- apps/modernization-ui/src/apps/patient/profile/Events.tsx
- apps/modernization-ui/src/apps/patient/profile/PatientProfile.tsx
- apps/modernization-ui/src/apps/patient/profile/Summary.tsx
- apps/modernization-ui/src/apps/patient/profile/_profile-modal.scss
- apps/modernization-ui/src/apps/patient/profile/entry/EntryModal.tsx
- apps/modernization-ui/src/apps/patient/profile/style.scss
- apps/modernization-ui/src/components/EditableCard/EditableCard.tsx
- apps/modernization-ui/src/styles/_headers.scss
- apps/modernization-ui/src/styles/global.scss
Aria Tab Panel for Patient Profile tabs and h2 added to Entry Modal title that is only used in Patient Profile
* [CNFT1-1975](https://cdc-nbs.atlassian.net/browse/CNFT1-1975)
[CNFT1-1975]: https://cdc-nbs.atlassian.net/browse/CNFT1-1975?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CNFT1-1975 Aria Tab Panel for Patient Profile tabs and h2 added to Entry Modal title that is only used in Patient Profile

- apps/modernization-ui/src/apps/page-builder/components/DeleteQuestion/DeleteQuestion.scss
- apps/modernization-ui/src/apps/page-builder/page/management/edit/question/QuestionHeader.tsx
Clean up CSS for Delete Question component
* [Jira Ticket]  https://cdc-nbs.atlassian.net/browse/CNFT2-1931
> [CNFT2-1931] - Clean up CSS for Delete Question component

- apps/modernization-ui/src/apps/page-builder/components/Section/Section.spec.tsx
- apps/modernization-ui/src/apps/page-builder/components/Subsection/Subsection.spec.tsx
- apps/modernization-ui/src/apps/page-builder/generated/models/PagesSubSection.ts
- apps/modernization-ui/src/apps/page-builder/helpers/moveObjectInArray.spec.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/question/GroupQuestion/GroupQuestion.spec.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/question/GroupQuestion/GroupQuestion.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/question/GroupQuestion/RepeatingBlock.spec.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/question/GroupQuestion/RepeatingBlock.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/question/GroupQuestion/SubsectionDetails.spec.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/question/GroupQuestion/SubsectionDetails.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/question/GroupQuestion/group-question.module.scss
- apps/modernization-ui/src/apps/page-builder/page/management/edit/question/GroupQuestion/repeating-block.module.scss
- apps/modernization-ui/src/apps/page-builder/page/management/edit/question/GroupQuestion/subsection-details.module.scss
- apps/modernization-ui/src/apps/page-builder/page/management/edit/question/QuestionContent.spec.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/section/manage/ManageSection.spec.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/section/manage/ManageSectionTile/ManageSectionTile.spec.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/subsection/Subsection.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/subsection/SubsectionHeader.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/subsection/manage/ManageSubsectionTile/ManageSubsectionTile.spec.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/subsection/subsection.module.scss
- apps/modernization-ui/src/apps/page-builder/page/management/edit/tabs/ManageTabs/ManageTabs.spec.tsx
- apps/modernization-ui/src/apps/page-builder/pages/EditPage/ReorderSection/ReorderSection.spec.tsx
- apps/modernization-ui/src/apps/page-builder/pages/EditPage/ReorderSubsection/ReorderSubsection.spec.tsx
- apps/modernization-ui/src/components/ModalComponent/ModalComponent.scss
Here we enable the user to group a Subsections questions. Grouped question Subsections, when the flag is enabled will have a different styling.
* [CNFT2-1769](https://cdc-nbs.atlassian.net/browse/CNFT2-1769)
[CNFT2-1769]: https://cdc-nbs.atlassian.net/browse/CNFT2-1769?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CNFT2-1769 Edit page: Group questions

- apps/modernization-ui/src/apps/page-builder/context/DragDropProvider.tsx
Fixing ManageTabs reordering of tabs.
* [1947](https://cdc-nbs.atlassian.net/browse/CNFT2-1947)
> CNFT2-1947 Fix ManageTabs drag drop

- apps/modernization-ui/src/apps/page-builder/page/management/edit/subsection/manage/AddSubSection.tsx
- apps/modernization-ui/src/validation/entry/validSubsectionNameRule.ts
Fixes validation on subsection name 
* [CNFT2-1886](https://cdc-nbs.atlassian.net/browse/CNFT2-1886)
[CNFT2-1886]: https://cdc-nbs.atlassian.net/browse/CNFT2-1886?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> subsection bug fix

- apps/modernization-ui/src/components/Table/table.module.scss
- apps/modernization-ui/src/styles/_uswds.scss
The buttons in the patient profile for "Delete patient" and "Print" are not of the same height
* [CNFT1-1951](https://cdc-nbs.atlassian.net/browse/CNFT1-1951)
[CNFT1-1951]: https://cdc-nbs.atlassian.net/browse/CNFT1-1951?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix pation profile sort table row bug

- apps/modernization-api/src/test/java/gov/cdc/nbs/support/organization/OrganizationMother.java
- apps/modernization-api/src/test/java/gov/cdc/nbs/support/provider/ProviderMother.java
- libs/options-api/src/main/java/gov/cdc/nbs/option/facilities/autocomplete/FacilityOptionAutocompleteController.java
- libs/options-api/src/main/java/gov/cdc/nbs/option/facilities/autocomplete/FacilityOptionResolver.java
- libs/options-api/src/test/java/gov/cdc/nbs/option/facility/autocomplete/FacilityAutocompleteRequester.java
- libs/options-api/src/test/java/gov/cdc/nbs/option/facility/autocomplete/FacilityAutocompleteSteps.java
- libs/options-api/src/test/java/gov/cdc/nbs/option/facility/autocomplete/FacilityOptionMother.java
- libs/options-api/src/test/java/gov/cdc/nbs/option/facility/autocomplete/FacilityOptionSteps.java
- libs/options-api/src/test/java/gov/cdc/nbs/option/provider/autocomplete/ProviderOptionMother.java
- libs/options-api/src/test/java/gov/cdc/nbs/option/provider/autocomplete/ProviderOptionSteps.java
- libs/options-api/src/test/resources/features/facilities/FacilityOptions.feature
API at `nbs/api/options/facilities/search`
Facilities from `Organization [organization_uid, display_nm]`
Example URL: `http://localhost:9080/nbs/api/options/facilities/search?criteria=a&limit=15`
* [CNFT1-1883](https://cdc-nbs.atlassian.net/browse/CNFT1-1883)
[CNFT1-1883]: https://cdc-nbs.atlassian.net/browse/CNFT1-1883?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CNFT1-1883 Facility Autocompletion- API Development

- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/entity/WaRdbMetadatum.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/entity/WaTemplate.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/entity/WaUiMetadata.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/command/PageContentCommand.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/component/tree/FlattenedComponentFinder.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/content/question/PageQuestionController.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/content/question/PageQuestionDeleter.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/content/question/PageQuestionUpdater.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/content/question/request/UpdatePageQuestionRequest.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/question/QuestionMapper.java
- apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/page/UpdateQuestionFromPageSteps.java
- apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/page/content/question/PageQuestionDeleterTest.java
- apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/page/content/question/PageQuestionUpdaterTest.java
- apps/question-bank/src/test/resources/features/page/UpdateQuestionFromPage.feature
Add API for Edit Page Question
https://cdc-nbs.atlassian.net/browse/CNFT2-1850
> Add API for Edit Page Question

- apps/modernization-ui/src/apps/page-builder/components/DeleteQuestion/DeleteQuestion.scss
- apps/modernization-ui/src/apps/page-builder/components/DeleteQuestion/DeleteQuestion.tsx
Fix delete question warning alert
* [Jira Ticket] https://cdc-nbs.atlassian.net/browse/CNFT2-1931
> [CNFT2-1931] - Fix delete question warning alert

- apps/modernization-ui/src/apps/page-builder/page/management/edit/subsection/manage/ManageSubsection.tsx
Subsection alert found was saying section is updated and not subsection
> small bug fix

- apps/modernization-ui/src/apps/page-builder/page/management/preview/information/PageInformation.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/preview/information/page-information.module.scss
[CNFT2-1600] [CNFT2-1604] - Developed Page_Info and Page History
* [Jira Ticket] https://cdc-nbs.atlassian.net/browse/CNFT2-1600, https://cdc-nbs.atlassian.net/browse/CNFT2-1604
[CNFT2-1600]: https://cdc-nbs.atlassian.net/browse/CNFT2-1600?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CNFT2-1604]: https://cdc-nbs.atlassian.net/browse/CNFT2-1604?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CNFT2-1600] [CNFT2-1604] - Page_Info and Page History

- apps/modernization-ui/src/apps/page-builder/components/TargetQuestion/TargetQuestion.tsx
- apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/Add/AddBusinessRule.scss
- apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/BusinessRulesForm.tsx
Adds label to the search source question button, and also displays the question text and a close Icon to reset the question after one has been selected.
* [Jira Ticket](https://cdc-nbs.atlassian.net/jira/software/c/projects/CNFT2/boards/99?assignee=712020%3A591f5469-427d-49e9-87dc-8b4df72a02b4&selectedIssue=CNFT2-1941)
> fix source question display

- apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/BusinessRulesForm.tsx
Had two typos causing the target type field not to display at for enable and disable functions. also fixes alignment.
* [Jira Ticket](https://cdc-nbs.atlassian.net/browse/CNFT2-1925)
- [ x] PRs containing TypeScript follow the [Do's and Don'ts](https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html)
- [x ] PR does not contain hardcoded values (Uses constants)
- [ x] All …
> CNFT2-1925/fix target type display

- apps/modernization-ui/src/apps/page-builder/page/management/preview/information/PageInformation.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/preview/information/page-information.module.scss
Wordwrap and null handling with hyphen
* [Jira Ticket] https://cdc-nbs.atlassian.net/browse/CNFT2-1600
> [CNFT2-1600] - Page Info

- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/content/subsection/SubSectionGrouper.java
- apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/page/content/subsection/GroupSubsectionSteps.java
- apps/question-bank/src/test/resources/features/page/content/subsection/GroupSubsection.feature
After grouping questions in a Subsection, the API returns a success response. However, Subsection value for isGrouped does not change to true
https://cdc-nbs.atlassian.net/browse/CNFT2-2015
> Solve grouped flag issue

- apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/Add/AddBusinessRule.tsx
- apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/BusinessRulesForm.tsx
- apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/BusinessRulesLibrary.tsx
- apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/BusinessRulesLibraryTable.spec.tsx
- apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/BusinessRulesLibraryTable.tsx
Fixes various items such (mostly) as typos
* [Jira Ticket](https://cdc-nbs.atlassian.net/jira/software/c/projects/CNFT2/boards/99?assignee=712020%3A591f5469-427d-49e9-87dc-8b4df72a02b4&selectedIssue=CNFT2-1932)
- [x ] PRs containing TypeScript follow the [Do's and Don'ts](https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html)
- [x ] PR does not contain hardcoded values …
> CNFT2-1932 various fixes for business rules

- apps/modernization-api/src/main/java/gov/cdc/nbs/patient/search/AuthorizedPatientFilterAdjuster.java
- apps/modernization-api/src/test/java/gov/cdc/nbs/patient/PatientMother.java
- apps/modernization-api/src/test/java/gov/cdc/nbs/patient/PatientSteps.java
- apps/modernization-api/src/test/resources/features/patient/search/PatientSearch.feature
Fix permission check in AuthorizedPatientFilterAdjuster write specs to test searching for superseded
* [CNFT1-1929](https://cdc-nbs.atlassian.net/browse/CNFT1-1929)
[CNFT1-1929]: https://cdc-nbs.atlassian.net/browse/CNFT1-1929?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CNFT1-1929 Superseded patient search does not display

- apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/Add/AddBusinessRule.tsx
- apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/SearchBar.tsx
Removes the unused filter button from the business rules table, and also fixes a small typo from the delete dialog.
* [Jira Ticket] No Jira ticket
- [x ] Code has been fully tested to meet acceptance criteria
- [x ] Functions/classes/components focused on one responsibility
- [x ] PRs containing TypeScript follow the [Do's and Don'ts](https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html)
- [ x] PR does not contain hardcoded values (Uses constants)
- [ x] All code is covered by unit or feature tests
> Remove filter from rules page

- apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/BusinessRulesLibrary.scss
- apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/BusinessRulesLibraryTable.scss
- apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/BusinessRulesLibraryTable.spec.tsx
- apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/BusinessRulesLibraryTable.tsx
- apps/modernization-ui/src/components/Table/Table.tsx
Adds newly designed result for no items in the business rules table.
* [Jira Ticket](https://cdc-nbs.atlassian.net/jira/software/c/projects/CNFT2/boards/99?assignee=712020%3A591f5469-427d-49e9-87dc-8b4df72a02b4&selectedIssue=CNFT2-1990)
- [x ] Functions/classes/components focused on one responsibility
- [ x] PRs containing TypeScript follow the [Do's and Don'ts](https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html)
- [x ] PR does not …
> Add no data display to business rules table

- apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/BusinessRulesLibraryTable.tsx
quick fix to change text on a button
* [Jira Ticket](https://cdc-nbs.atlassian.net/jira/software/c/projects/CNFT2/boards/99?assignee=712020%3A591f5469-427d-49e9-87dc-8b4df72a02b4&selectedIssue=CNFT2-1990)
> button copy fix

- apps/modernization-api/Dockerfile
- apps/modernization-ui/Dockerfile
Copies the `modernization-ui` package-lock.json file into the Docker context when building the UI container.
> [FIX] Includes the modernization-ui package-lock.json in Docker build

- apps/modernization-ui/src/apps/page-builder/PageBuilderRouting.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/preview/PageDetails/PageDetails.scss
- apps/modernization-ui/src/apps/page-builder/page/management/preview/PageDetails/PageDetails.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/preview/PageDetails/PageDetailsField.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/preview/information/PageInformation.tsx
- apps/modernization-ui/src/components/FormInputs/Input.tsx
- apps/modernization-ui/src/components/selection/multi/MultiSelectInput.tsx
Preview Page - Page Info - View Page details and Edit
Defect Fix CNFT2-2024
* [Jira Ticket] https://cdc-nbs.atlassian.net/browse/CNFT2-1933, https://cdc-nbs.atlassian.net/browse/CNFT2-2024
> [CNFT2-1933] - Preview Page - Page Info - View Page details and Edit

- apps/modernization-ui/src/apps/page-builder/page/management/layout/PageManagementLayout.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/layout/page-management-layout.module.scss
- apps/modernization-ui/src/apps/page-builder/page/management/menu/page-management-menu.module.scss
- apps/modernization-ui/src/apps/page-builder/page/management/preview/PreviewPage.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/preview/preview-page.module.scss
- apps/modernization-ui/src/styles/_uswds.scss
Preview page buttons and header tags for Published, Published with Draft, and Initial Draft page. This includes the introduction of the trussworks Tooltip. Button functionality forthcoming
* [CNFT2-1605](https://cdc-nbs.atlassian.net/browse/CNFT2-1605)
* [CNFT2-1937](https://cdc-nbs.atlassian.net/browse/CNFT2-1937)
* [CNFT2-1938](https://cdc-nbs.atlassian.net/browse/CNFT2-1938)
[CNFT2-1605]: https://cdc-nbs.atlassian.net/browse/CNFT2-1605?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CNFT2-1937]: https://cdc-nbs.atlassian.net/browse/CNFT2-1937?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CNFT2-1938]: https://cdc-nbs.atlassian.net/browse/CNFT2-1938?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y …
> CNFT2-1605 Preview page: header

- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/PageController.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/service/PageHistoryFinder.java
- apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/page/download/PageControllerTest.java
- apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/page/service/PageHistoryFinderTest.java
Adding Pagination to Page History
https://cdc-nbs.atlassian.net/browse/CNFT2-2014
> Adding Pagination to Page History

- apps/modernization-ui/src/Information/InformationModal.tsx
- apps/modernization-ui/src/Information/index.ts
- apps/modernization-ui/src/apps/page-builder/components/AlertModal/AlertModal.scss
- apps/modernization-ui/src/apps/page-builder/components/AlertModal/AlertModal.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/preview/PageDetails/PageDetails.scss
- apps/modernization-ui/src/apps/page-builder/page/management/preview/PageDetails/PageDetails.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/preview/information/PageInformation.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/preview/information/page-information.module.scss
Bug fix on View page details page.
Removed Print Icon
Changed the button name `view page details/ edit page details` based on page status
Added Pagination
Fixed few CSS Issue
Changed the MMG to Reporting Mechanism
* [Jira Ticket] https://cdc-nbs.atlassian.net/browse/CNFT2-1933
> [CNFT2-1933] View Page Details Bug fixes

- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/valueset/CountyFinder.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/valueset/CountyMapper.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/valueset/ValueSetController.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/valueset/response/County.java
- apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/valueset/CountyFinderTest.java
- apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/valueset/CountyMapperTest.java
Need to have a custom component for the County question that will call an API to fetch the County options for a given State.
https://cdc-nbs.atlassian.net/browse/CNFT2-1994
> Creating API to fetch the County options for a given State

- apps/modernization-ui/src/apps/page-builder/page/management/preview/PageDetails/PageDetailsField.tsx
- apps/modernization-ui/src/validation/entry/dataMartNameRule.ts
Edit page details bug fixes CNFT2-2043, CNFT2-2044, CNFT2-2045, CNFT2-2046
* [Jira Ticket]https://cdc-nbs.atlassian.net/browse/CNFT2-2043, https://cdc-nbs.atlassian.net/browse/CNFT2-2044, https://cdc-nbs.atlassian.net/browse/CNFT2-2045,  https://cdc-nbs.atlassian.net/browse/CNFT2-2046
> [CNFT-2043] [CNFT-2044] [CNFT-2045] [CNFT-2046] - Edit Page Details bug fixes

- apps/modernization-ui/src/apps/page-builder/components/AddQuestion/fields/DataMartFields.tsx
- apps/modernization-ui/src/apps/page-builder/page/library/table/PageLibraryTable.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/menu/page-management-menu.module.scss
- apps/modernization-ui/src/apps/page-builder/page/management/preview/PreviewPage.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/preview/PublishPage/PublishPage.spec.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/preview/PublishPage/PublishPage.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/preview/PublishPage/publish-page.module.scss
- apps/modernization-ui/src/apps/page-builder/page/management/preview/SaveTemplate/SaveTemplate.spec.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/preview/SaveTemplate/SaveTemplate.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/preview/SaveTemplate/save-tempate.module.scss
- apps/modernization-ui/src/components/ModalComponent/ModalComponent.scss
- apps/modernization-ui/src/confirmation/ConfirmationModal.tsx
- apps/modernization-ui/src/confirmation/_ConfirmationModal.scss
- apps/modernization-ui/src/styles/_uswds.scss
Here we enable the functionality for the Preview Page header buttons
* [CNFT2-1939](https://cdc-nbs.atlassian.net/browse/CNFT2-1939)
[CNFT2-1939]: https://cdc-nbs.atlassian.net/browse/CNFT2-1939?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CNFT2-1939 Preview Page: Header

- apps/modernization-ui/src/apps/page-builder/page/management/preview/PageDetails/PageDetails.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/preview/PageDetails/PageDetailsField.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/preview/information/PageInformation.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/preview/information/page-information.module.scss
- apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/Add/AddBusinessRule.scss
- apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/BusinessRulesForm.tsx
Fix Edit Page and Business rules bugs CNFT2-1604, CNFT2-2027, CNFT2-2028, CNFT2-2046, CNFT2-2052
* [Jira Ticket] 
https://cdc-nbs.atlassian.net/browse/CNFT2-1604
https://cdc-nbs.atlassian.net/browse/CNFT2-2027
https://cdc-nbs.atlassian.net/browse/CNFT2-2028
https://cdc-nbs.atlassian.net/browse/CNFT2-2046
https://cdc-nbs.atlassian.net/browse/CNFT2-2052
> cnft2_2052 page info bug  fixes

- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/pagerules/PageRuleFinder.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/pagerules/PageRuleMapper.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/pagerules/Rule.java
- apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/pagerules/PageRuleControllerTest.java
- apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/pagerules/PageRuleMapperTest.java
Rule Response Model-Adding questionId to SourceQuestion
> Rule Response Model-Adding questionId to SourceQuestion

- apps/modernization-ui/src/apps/patient/profile/labReport/LabReportTable.tsx
- apps/modernization-ui/src/apps/patient/profile/labReport/PatientLabReport.ts
- apps/modernization-ui/src/apps/patient/profile/labReport/PatientLabReportSorter.spec.ts
- apps/modernization-ui/src/apps/patient/profile/labReport/PatientLabReportTransformer.spec.ts
- apps/modernization-ui/src/apps/patient/profile/labReport/PatientLabReportTransformer.ts
Implemented ELR as "Electronic" in patient profile events tab lab report table.
* [CNFT1-2034](https://cdc-nbs.atlassian.net/browse/CNFT1-2034)
[CNFT1-2034]: https://cdc-nbs.atlassian.net/browse/CNFT1-2034?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Added electronics indication to the lab report table

- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/detail/PageDescriptionFinder.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/detail/PageDescriptionRowMapper.java
- apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/page/detail/PageDescriptionRowMapperTest.java
Status of the page is displayed on the right-hand corner. When opening a page Published with Draft, status has to be ‘Published with Draft’, but currently this is 'Initial Draft'.
https://cdc-nbs.atlassian.net/browse/CNFT2-2035
> Updating the page API to display the Published with draft status.

- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/entity/WaRdbMetadatum.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/entity/WaUiMetadata.java
When adding a question to a page using the modernized APIs, it appears no Wa_RDB_metadata table entry is being created.
https://cdc-nbs.atlassian.net/browse/CNFT2-2018
> Creating Wa_RDB_metadata table entry while adding question to page.

- apps/modernization-ui/src/apps/page-builder/page/management/preview/PageDetails/PageDetails.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/preview/PageDetails/PageDetailsField.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/preview/information/PageInformation.tsx
Fixed Page Info bugs
* [Jira Ticket] https://cdc-nbs.atlassian.net/browse/CNFT2-2052
> [CNFT2-2052] - Page Info bug fix

- apps/modernization-ui/src/apps/page-builder/pages/AddNewPage/AddNewPage.tsx
- apps/modernization-ui/src/apps/page-builder/pages/AddNewPage/AddNewPageFields.tsx
Fixed Create Page bug [CNFT2-2085] [CNFT2-2048] [CNFT2-2047]
* [Jira Ticket] https://cdc-nbs.atlassian.net/browse/CNFT2-2047, https://cdc-nbs.atlassian.net/browse/CNFT2-2048, https://cdc-nbs.atlassian.net/browse/CNFT2-2085
[CNFT2-2085]: https://cdc-nbs.atlassian.net/browse/CNFT2-2085?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CNFT2-2048]: https://cdc-nbs.atlassian.net/browse/CNFT2-2048?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CNFT2-2047]: https://cdc-nbs.atlassian.net/browse/CNFT2-2047?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CNFT2-2085] [CNFT2-2048] [CNFT2-2047] - Create Page bug fixes

- apps/modernization-ui/src/apps/search/event/components/LabReportSearch/LabReportGeneralFields.tsx
Label fix for LabReportGeneralFields provider and facility
* [CNFT1-1495](https://cdc-nbs.atlassian.net/browse/CNFT1-1495)
[CNFT1-1495]: https://cdc-nbs.atlassian.net/browse/CNFT1-1495?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Label fix for LabReportGeneralFields provider and facility

- apps/modernization-api/src/main/java/gov/cdc/nbs/codes/CountryCodedValueFinder.java
SQL should sort by `code_desc_txt`
* [CNFT1-1838](https://cdc-nbs.atlassian.net/browse/CNFT1-1838)
[CNFT1-1838]: https://cdc-nbs.atlassian.net/browse/CNFT1-1838?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CNFT1-1838 Fix country sort order

- apps/modernization-ui/src/apps/page-builder/page/management/preview/information/PageInformation.tsx
Page Info button name bug fix
* [Jira Ticket] https://cdc-nbs.atlassian.net/browse/CNFT2-2093
> [CNFT2-2093] - Page Info button name bug fix

- apps/modernization-ui/src/apps/page-builder/page/management/preview/PreviewPage.tsx
On Preview Page, Preview, Clone and Print now open in new tabs.
Clone button does not appear on Published Pages.
* [CNFT2-2068](https://cdc-nbs.atlassian.net/browse/CNFT2-2068)
* [CNFT2-2069](https://cdc-nbs.atlassian.net/browse/CNFT2-2069)
* [CNFT2-2067](https://cdc-nbs.atlassian.net/browse/CNFT2-2067)
[CNFT2-2068]: https://cdc-nbs.atlassian.net/browse/CNFT2-2068?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CNFT2-2069]: https://cdc-nbs.atlassian.net/browse/CNFT2-2069?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CNFT2-2067]: https://cdc-nbs.atlassian.net/browse/CNFT2-2067?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CNFT2-2068 Preview page: header print

- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/pagerules/PageRuleFinder.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/pagerules/PageRuleMapper.java
- apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/pagerules/PageRuleMapperTest.java
Update the page rule search API to accept search by:
sourceQuestionLabel, sourceQuestionId, targetQuestions, ruleId
https://cdc-nbs.atlassian.net/browse/CNFT2-1999
> Update the page rule search API to match the UI needs.

- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/PageStateChanger.java
Edit the save Page Draft API response to return the id of the Draft Page.
https://cdc-nbs.atlassian.net/browse/CNFT2-2070
> Edit the Page Draft response to return the id of the Draft Page.

- apps/modernization-ui/public/icons/drag.svg
- apps/modernization-ui/src/apps/page-builder/context/DragDropProvider.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/Edit.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/reorder/ReorderModal/ReorderModal.spec.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/reorder/ReorderModal/ReorderModal.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/reorder/ReorderModal/reorder-modal.module.scss
- apps/modernization-ui/src/apps/page-builder/page/management/edit/reorder/ReorderQuestion/reorder-question.module.scss
- apps/modernization-ui/src/apps/page-builder/page/management/edit/reorder/ReorderSubsection/ReorderSubsection.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/reorder/ReorderSubsection/reorder-subsection.module.scss
- apps/modernization-ui/src/apps/page-builder/page/management/edit/reorder/ReorderTab/ReorderTab.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/reorder/ReorderTab/reorder-tab.module.scss
Here we update the Reorder modal to include Tab dropping and design updates.
* [CNFT2-2055](https://cdc-nbs.atlassian.net/browse/CNFT2-2055)
[CNFT2-2055]: https://cdc-nbs.atlassian.net/browse/CNFT2-2055?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CNFT2-2055 Reorder modal redux

- apps/modernization-ui/src/apps/page-builder/page/management/preview/tab/question/PreviewQuestion.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/preview/tab/question/preview-question.module.scss
- apps/modernization-ui/src/apps/page-builder/page/management/preview/tab/section/PreviewSection.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/preview/tab/section/PreviewSectionHeader.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/preview/tab/section/preview-section.module.scss
- apps/modernization-ui/src/apps/page-builder/page/management/preview/tab/subsection/PreviewSubsection.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/preview/tab/subsection/PreviewSubsectionHeader.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/preview/tab/subsection/preview-subsection.module.scss
Create Preview pages - Section, Subsection, Questions and Static Elements [CNFT2-1940] [CNFT2-1942] [CNFT2-1943]
*  https://cdc-nbs.atlassian.net/browse/CNFT2-1940, 
* https://cdc-nbs.atlassian.net/browse/CNFT2-1942, 
* https://cdc-nbs.atlassian.net/browse/CNFT2-1943
[CNFT2-1940]: https://cdc-nbs.atlassian.net/browse/CNFT2-1940?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CNFT2-1942]: https://cdc-nbs.atlassian.net/browse/CNFT2-1942?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CNFT2-1943]: https://cdc-nbs.atlassian.net/browse/CNFT2-1943?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CNFT2-1940] [CNFT2-1942] [CNFT2-1943] - Create Preview pages - Section, Subsection, Questions and Static Elements

- apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/BusinessRulesLibraryTable.spec.tsx
- apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/BusinessRulesLibraryTable.tsx
* [Jira Ticket](https://cdc-nbs.atlassian.net/jira/software/c/projects/CNFT2/boards/99?selectedIssue=CNFT2-2129)
- [ x] PRs containing TypeScript follow the [Do's and Don'ts](https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html)
- [ x] PR does not contain hardcoded values (Uses …
> Copy change from source/target fields > source/targetQuestion  for business rules table column headers

- apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/Add/AddBusinessRule.tsx
Quick typo fix.
* [Jira Ticket](https://cdc-nbs.atlassian.net/jira/software/c/projects/CNFT2/boards/99?selectedIssue=CNFT2-2117)
- [ x] Code easy to understand and modify (clarity over concise/clever)
- [ x] PRs containing TypeScript follow the [Do's and Don'ts](https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html)
- [x ] PR does not contain hardcoded values (Uses constants)
- [ x] All code is covered by unit or feature tests
> Unhide button typo

- apps/modernization-ui/src/apps/page-builder/page/management/header/PageHeader.tsx
Remove Page Description
* [Jira Ticket] https://cdc-nbs.atlassian.net/browse/CNFT2-2082
> [CNFT2-2082] - Remove Page Description

- apps/modernization-ui/src/apps/page-builder/page/management/layout/PageManagementLayout.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/layout/page-management-layout.module.scss
Edit Page Header fix
* [Jira Ticket] https://cdc-nbs.atlassian.net/browse/CNFT2-2115
> [CNFT2-2115] - Edit Page Header fix

- cdc-sandbox/nbs6-win-container/Dockerfile
> Update Dockerfile syntax

- apps/modernization-ui/src/apps/page-builder/page/management/preview/tab/question/PreviewQuestion.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/preview/tab/question/preview-question.module.scss
[CNFT2-2141] [CNFT2-2142] - Preview Page CSS fix
* [Jira Ticket] https://cdc-nbs.atlassian.net/browse/CNFT2-2141, https://cdc-nbs.atlassian.net/browse/CNFT2-2142
[CNFT2-2141]: https://cdc-nbs.atlassian.net/browse/CNFT2-2141?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CNFT2-2142]: https://cdc-nbs.atlassian.net/browse/CNFT2-2142?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CNFT2-2141] [CNFT2-2142] - Preview Page CSS fix

- apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/Add/AddBusinessRule.tsx
- apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/BusinessRulesForm.tsx
- apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/BusinessRulesLibraryTable.spec.tsx
- apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/BusinessRulesLibraryTable.tsx
- apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/helpers/mapLogicForDateCompare.ts
We had 1 issue where undefined values were being passed into the rules description when the function was date validation.  We also were not displaying an error message for date validation rules.
It was discussed and decided on 2/28 that we will not generate a rule description for date validation rules.  However we will auto generate an error message.  So this PR does both of those things.
And also cleans up some typo/copy change requests.
* [Jira Ticket for undefined description](https://cdc-nbs.atlassian.net/jira/software/c/projects/CNFT2/boards/99?assignee=712020%3A591f5469-427d-49e9-87dc-8b4df72a02b4&selectedIssue=CNFT2-2118)
*  [Jira Ticket for error message display](https://cdc-nbs.atlassian.net/jira/software/c/projects/CNFT2/boards/99?assignee=712020%3A591f5469-427d-49e9-87dc-8b4df72 …
> Rule description bug fixes

- apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/Add/AddBusinessRule.tsx
- apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/BusinessRulesForm.tsx
When clicking the Any source value checkbox, the Logic and Source value(s) fields should be disabled with Logic set to = and ALL Source Value(s) selected.
* [CNFT2-2010](https://cdc-nbs.atlassian.net/browse/CNFT2-2010)
[CNFT2-2010]: https://cdc-nbs.atlassian.net/browse/CNFT2-2010?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Cnft2 2010

- apps/modernization-ui/src/apps/page-builder/components/TargetQuestion/TargetQuestion.scss
- apps/modernization-ui/src/apps/page-builder/components/TargetQuestion/TargetQuestion.tsx
- apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/BusinessRulesForm.tsx
When adding a Business Rule for any function (except for Date Compare), Source Question always has to be a question with drop down list or Radio button list. No text fields/ date fields are allowed. Check in Classic for verification.
When adding a Business Rule for Date Validation function, Source Question always has to be a date field. Check in Classic for verification.
* [CNFT2-2107](https://cdc-nbs.atlassian.net/browse/CNFT2-2107)
* [CNFT2-2109](https://cdc-nbs.atlassian.net/browse/CNFT2-2109)
* [CNFT2-2119](https://cdc-nbs.atlassian.net/browse/CNFT2-2119)
[CNFT2-2107]: https://cdc-nbs.atlassian.net/browse/CNFT2-2107?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CNFT2-2109]: https://cdc-nbs.atlassian.net/browse/CNFT2-2109?atlOrigin=eyJpIjo …
> Business Rules Source/Target Questions modal

- apps/modernization-ui/src/apps/page-builder/page/management/preview/PreviewPage.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/preview/PublishPage/PublishPage.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/preview/preview-page.module.scss
- apps/modernization-ui/src/apps/page-builder/page/management/preview/tab/question/preview-question.module.scss
Add Wait indicator on Publish page
* [Jira Ticket] https://cdc-nbs.atlassian.net/browse/CNFT2-2056
> [CNFT2-2056] - Add Wait Indicator on Publish page

- apps/modernization-ui/src/apps/page-builder/components/TargetQuestion/TargetQuestion.tsx
- apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/BusinessRulesForm.tsx
Fix target question modal, to show the necessary questions and not show static elements
* [CNFT2-2119](https://cdc-nbs.atlassian.net/browse/CNFT2-2119)
[CNFT2-2119]: https://cdc-nbs.atlassian.net/browse/CNFT2-2119?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Cnft2 2119 target question

- apps/modernization-ui/src/apps/search/event/components/InvestigationSearch/InvestigationResults.tsx
- apps/modernization-ui/src/apps/search/event/components/InvestigationSearch/InvestigationSearchResult.spec.tsx
- apps/modernization-ui/src/apps/search/event/components/InvestigationSearch/InvestigationSearchResult.tsx
The url used to link to the investigation was using the Patient short id instead of the actual identifier which prevented the Patient from being resolved when returning to the patient profile.  
* [CNFT1-2095](https://cdc-nbs.atlassian.net/browse/CNFT1-2095)
[CNFT1-2095]: https://cdc-nbs.atlassian.net/browse/CNFT1-2095?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CNFT1-2095] Investigation Search returns to the modernized Patient Profile

- apps/modernization-ui/src/apps/page-builder/page/management/preview/tab/question/PreviewQuestion.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/preview/tab/question/preview-question.module.scss
Fixed Required fields doesnot show required in Preview page
* [Jira Ticket] https://cdc-nbs.atlassian.net/browse/CNFT2-2144
> [CNFT2-2144] - Fixed Required fields doesnot show required in Preview page

- apps/modernization-ui/src/apps/page-builder/page/management/preview/PreviewPage.tsx
Create New Draft
* [Jira Ticket] https://cdc-nbs.atlassian.net/browse/CNFT2-2070
> [CNFT2-2070] Create New Draft

- apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/Add/AddBusinessRule.tsx
- apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/BusinessRulesForm.tsx
- apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/BusinessRulesLibraryTable.tsx
Displays "any source value" on the rules table and rule description when any source value is selected.  Also caught a bug where the rule function was being set imporperly.
* [Jira Ticket](https://cdc-nbs.atlassian.net/jira/software/c/projects/CNFT2/boards/99?assignee=712020%3A591f5469-427d-49e9-87dc-8b4df72a02b4&selectedIssue=CNFT2-2150)
> Display any source value when selected on rules table and form.

- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/pagerules/PageRuleServiceImpl.java
Rule descriptions were not being updated. Here is a quick fix to address.
* [Jira Ticket](https://cdc-nbs.atlassian.net/jira/software/c/projects/CNFT2/boards/99?assignee=712020%3A591f5469-427d-49e9-87dc-8b4df72a02b4)
> Fix rule description update

- apps/modernization-api/src/main/java/gov/cdc/nbs/patient/profile/labreport/PatientLabReportResolver.java
- apps/modernization-api/src/main/resources/graphql/patient-lab-report.graphqls
- apps/modernization-ui/src/apps/patient/profile/labReport/LabReportTable.tsx
- apps/modernization-ui/src/apps/patient/profile/labReport/PatientLabReportTransformer.spec.ts
- apps/modernization-ui/src/apps/patient/profile/labReport/PatientLabReportTransformer.ts
- apps/modernization-ui/src/generated/gql/queries/findLabReportsForPatient.gql
- apps/modernization-ui/src/generated/gql/queries/findLabReportsForPatientCount.gql
- apps/modernization-ui/src/generated/gql/queries/index.js
- apps/modernization-ui/src/generated/graphql/schema.ts
- apps/modernization-ui/src/generated/schema.graphqls
- libs/database-entities/src/main/java/gov/cdc/nbs/repository/ObservationRepository.java
Use Spring Data JPA `countQuery` for our native query.
* [CNFT1-1860](https://cdc-nbs.atlassian.net/browse/CNFT1-1860)
[CNFT1-1860]: https://cdc-nbs.atlassian.net/browse/CNFT1-1860?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CNFT1-1860 fix pagination on lab reports

- apps/modernization-ui/src/apps/page-builder/page/management/preview/PublishPage/PublishPage.tsx
Publish button label change and Publish page version notes textfield validation
* [Jira Ticket] https://cdc-nbs.atlassian.net/browse/CNFT2-2153, https://cdc-nbs.atlassian.net/browse/CNFT2-2152
> [CNFT2-2152] [CNFT2-2153] - Publish page validation and button label change

- apps/modernization-ui/src/apps/page-builder/page/management/preview/PublishPage/PublishPage.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/preview/PublishPage/publish-page.module.scss
Publish page conditions empty validations
* [Jira Ticket] https://cdc-nbs.atlassian.net/browse/CNFT2-2162
> [CNFT2-2162] - Publish page conditions empty validations

- apps/modernization-ui/src/apps/page-builder/generated/index.ts
- apps/modernization-ui/src/apps/page-builder/generated/models/UpdatePageQuestionRequiredRequest.ts
- apps/modernization-ui/src/apps/page-builder/generated/services/PageQuestionControllerService.ts
- apps/modernization-ui/src/apps/page-builder/hooks/api/useSetPageQuestionRequired.ts
- apps/modernization-ui/src/apps/page-builder/page/management/edit/question/Question.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/question/QuestionHeader.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/subsection/Subsection.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/preview/information/PageInformation.tsx
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/entity/WaTemplate.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/entity/WaUiMetadata.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/command/PageContentCommand.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/content/question/PageQuestionController.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/content/question/PageQuestionUpdater.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/content/question/request/UpdatePageQuestionRequiredRequest.java
- apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/page/content/question/UpdatePageQuestionRequiredSteps.java
- apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/page/content/question/UpdatePageRequiredRequester.java
- apps/question-bank/src/test/resources/features/page/content/question/UpdatePageQuestionRequired.feature
The toggle button to set a question as required is not functioning. 
* [CNFT2-2164](https://cdc-nbs.atlassian.net/browse/CNFT2-2164)
[CNFT2-2164]: https://cdc-nbs.atlassian.net/browse/CNFT2-2164?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix required toggle

- apps/modernization-ui/src/apps/page-builder/page/management/preview/tab/question/PreviewQuestion.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/preview/tab/subsection/PreviewSubsection.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/preview/tab/subsection/preview-subsection.module.scss
Developed Preview Page Group Questions
* [https://cdc-nbs.atlassian.net/browse/CNFT2-2138]
> [CNFT2-2138] - Preview Page Group Questions

- apps/modernization-ui/src/apps/page-builder/components/EditValueset/CreateConcept.tsx
- apps/modernization-ui/src/apps/page-builder/components/EditValueset/EditConcept.tsx
- apps/modernization-ui/src/apps/page-builder/components/EditValueset/concept/ConceptForm.tsx
- apps/modernization-ui/src/apps/page-builder/components/EditValueset/concept/concept-form.module.scss
Adds the `Effective from` and `Effective to` inputs to the concept form.
* [CNFT2-2189](https://cdc-nbs.atlassian.net/browse/CNFT2-2189)
[CNFT2-2189]: https://cdc-nbs.atlassian.net/browse/CNFT2-2189?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Effective from - to

- apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/Add/AddBusinessRule.scss
- apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/Add/AddBusinessRule.tsx
- apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/BusinessRulesForm.tsx
[CNFT2-2120] [CNFT2-2151] [CNFT2-2163] [CNFT2-2165] - Fixed Business Rules defects
* https://cdc-nbs.atlassian.net/browse/CNFT2-2120
* https://cdc-nbs.atlassian.net/browse/CNFT2-2165
* https://cdc-nbs.atlassian.net/browse/CNFT2-2151
* https://cdc-nbs.atlassian.net/browse/CNFT2-2163
[CNFT2-2120]: https://cdc-nbs.atlassian.net/browse/CNFT2-2120?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CNFT2-2151]: https://cdc-nbs.atlassian.net/browse/CNFT2-2151?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CNFT2-2163]: https://cdc-nbs.atlassian.net/browse/CNFT2-2163?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CNFT2-2165]: …
> [CNFT2-2120] [CNFT2-2151] [CNFT2-2163] [CNFT2-2165] - Business Rules Bug Fixes

- apps/modernization-ui/src/apps/page-builder/components/TargetQuestion/TargetQuestion.tsx
- apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/Add/AddBusinessRule.tsx
- apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/BusinessRulesForm.tsx
Subsections with no Dropdown fields has to be hidden for (Enable/ Disable/Hide/ Unhide/ RequireIf).
Subsections with no Date fields has to be hidden for Date Validation.
* [CNFT2-2149](https://cdc-nbs.atlassian.net/browse/CNFT2-2149)
[CNFT2-2149]: https://cdc-nbs.atlassian.net/browse/CNFT2-2149?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Cnft2 2149 empty subsections

- apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/BusinessRulesForm.tsx
[CNFT2-2151] - Business Rules Bug Fixes.
* [Jira Ticket] https://cdc-nbs.atlassian.net/browse/CNFT2-2151
[CNFT2-2151]: https://cdc-nbs.atlassian.net/browse/CNFT2-2151?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CNFT2-2151] - Business Rules Bug Fix

- apps/modernization-ui/src/apps/search/event/components/EventSearch/EventSearch.tsx
During Event type “Investigation” and “Laboratory report” searches,  All fields will clear from the search criteria fields when the “Clear All” button is clicked.
Event search > Event type: Clear all button will clear the Event type field (and all other search criteria fields)
Event search > Collapse the dropdown options.
* [CNFT1-1683](https://cdc-nbs.atlassian.net/browse/CNFT1-1683)
[CNFT1-1683]: https://cdc-nbs.atlassian.net/browse/CNFT1-1683?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CNFT1-1683-search-clear

- apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/Add/AddBusinessRule.tsx
- apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/BusinessRulesForm.tsx
Somewhere in the process of fixing bugs/merge conflicts some changes were lost, and new bugs were introduced, mainly related to populating the description, and the sources/values and targets into their fields while editing.  Added some changes that may be overkill to fix them, but at this point we need it.
* [Jira Ticket](https://cdc-nbs.atlassian.net/jira/software/c/projects/CNFT2/boards/99?assignee=712020%3A591f5469-427d-49e9-87dc-8b4df72a02b4&selectedIssue=CNFT2-2183)
*  [Jira Ticket](https://cdc-nbs.atlassian.net/jira/software/c/projects/CNFT2/boards/99?assignee=712020%3A591f5469-427d-49e9-87dc-8b4df72a02b4&selectedIssue=CNFT2-2180)
*  [Jira Ticket](https://cdc-nbs.atlassian.net/jira/software/c/projects/CNFT2/boards/99?assignee=712020%3A591f5469-427d-49e9-87dc-8b4df72a02b4&selectedIssu …
> Various UI bugs for rules edit form.

- apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/BusinessRulesForm.tsx
Fixed defect for business rules
When clicking any source value the Add to Library button should be enabled:
When the mandatory values not applied then the Add to Library button should not be enabled:
* https://cdc-nbs.atlassian.net/browse/CNFT2-2205
* https://cdc-nbs.atlassian.net/browse/CNFT2-2207
* https://cdc-nbs.atlassian.net/browse/CNFT2-2197
> [CNFT2-2205], [CNFT2-2207], [CNFT2-2197] - Business Rules Bug Fix

- apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/BusinessRulesForm.tsx
Rule description was not updating when new sources question and values were selected.
* [Jira Ticket](https://cdc-nbs.atlassian.net/jira/software/c/projects/CNFT2/boards/99?assignee=712020%3A591f5469-427d-49e9-87dc-8b4df72a02b4&selectedIssue=CNFT2-2209)
> Update rule description when source question/values change

- apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/BusinessRulesForm.tsx
Fixed Business rules defects
* [Jira Ticket] 
* https://cdc-nbs.atlassian.net/browse/CNFT2-2205
* https://cdc-nbs.atlassian.net/browse/CNFT2-2211
* https://cdc-nbs.atlassian.net/browse/CNFT2-2214
> [CNFT2-2205] [CNFT2-2211] [CNFT2-2214] - Business Rules Bug Fix

- apps/modernization-ui/src/apps/page-builder/page/management/edit/question/GroupQuestion/GroupQuestion.tsx
Here we pre-populate the labels in Group Questions repeating block.
* [CNFT2-2212](https://cdc-nbs.atlassian.net/browse/CNFT2-2212)
[CNFT2-2212]: https://cdc-nbs.atlassian.net/browse/CNFT2-2212?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CNFT2-2212 Group Questions: Autopopulate label

- apps/modernization-ui/src/apps/page-builder/page/management/preview/tab/subsection/PreviewSubsection.tsx
- apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/BusinessRulesForm.tsx
Preview Page Fix
Business Rules Fix
* https://cdc-nbs.atlassian.net/browse/CNFT2-2214
* https://cdc-nbs.atlassian.net/browse/CNFT2-2197
* https://cdc-nbs.atlassian.net/browse/CNFT2-2215
> [CNFT2-2214] [CNFT2-2197] [CNFT2-2215] - Preview Page and Business Rules Bug Fix

- apps/modernization-api/src/main/java/gov/cdc/nbs/patient/search/PatientSearchCriteriaQueryResolver.java
- apps/modernization-api/src/test/resources/features/patient/search/PatientSearch.feature
Do a case insensitive prefix search (defaults to sensitive)
> Case insensitive identification search

- apps/modernization-ui/src/apps/page-builder/page/management/edit/reorder/ReorderQuestion/ReorderQuestion.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/reorder/ReorderQuestion/reorder-question.module.scss
- apps/modernization-ui/src/apps/page-builder/page/management/edit/reorder/ReorderSection/ReorderSection.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/reorder/ReorderSection/reorder-section.module.scss
- apps/modernization-ui/src/apps/page-builder/page/management/edit/reorder/ReorderSubsection/ReorderSubsection.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/reorder/ReorderSubsection/reorder-subsection.module.scss
- apps/modernization-ui/src/apps/page-builder/page/management/edit/reorder/ReorderTab/ReorderTab.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/reorder/ReorderTab/reorder-tab.module.scss
- apps/modernization-ui/src/apps/page-builder/page/management/edit/tabs/ManageTabsTile/ManageTabsTile.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/tabs/ManageTabsTile/manageTabsTile.module.scss
Updating the style of a dragged tile to have a border + drop shadow.
* [CNFT2-2098](https://cdc-nbs.atlassian.net/browse/CNFT2-2098)
[CNFT2-2098]: https://cdc-nbs.atlassian.net/browse/CNFT2-2098?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CNFT2-2098 Drag drop border

- apps/modernization-ui/src/apps/page-builder/page/management/edit/question/GroupQuestion/GroupQuestion.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/subsection/SubsectionHeader.tsx
Small fix so Group Questions > Repeating number defaults to 0.
* [CNFT2-2221](https://cdc-nbs.atlassian.net/browse/CNFT2-2221)
[CNFT2-2221]: https://cdc-nbs.atlassian.net/browse/CNFT2-2221?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CNFT2-2221 Group Data mart repeat number 0

- apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/Form/BusinessRulesForm.module.scss
- apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/Form/BusinessRulesForm.tsx
- apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/SourceQuestion/SourceQuestion.module.scss
- apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/SourceQuestion/SourceQuestion.tsx
- apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/TargetQuestion/TargetQuestion.module.scss
- apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/TargetQuestion/TargetQuestion.tsx
Bugs/Issues found by Brindha, mostly UI changes
> business rules bugs/issue fixed

- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/pagerules/DateCompareCommandCreator.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/pagerules/EnableDisableCommandCreator.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/pagerules/HideUnhideCommandCreator.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/pagerules/PageRuleFinder.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/pagerules/RequireIfCommandCreator.java
- apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/pagerules/DateCompareCommandCreatorTest.java
- apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/pagerules/EnableDisableCommandCreatorTest.java
- apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/pagerules/HideUnhideCommandCreatorTest.java
- apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/pagerules/RequireIfCommandCreatorTest.java
Removes an extra space in target identifier column
> Removes extra space in target identifier

- apps/modernization-ui/src/apps/page-builder/page/management/preview/tab/subsection/PreviewSubsection.tsx
Filter out questions that should not appear in repeating block
> Filter out questions that do not appear in batch from preview

- apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/Form/BusinessRulesForm.tsx
Remove number, colon from business rules fields
https://cdc-nbs.atlassian.net/browse/CNFT2-2214
https://cdc-nbs.atlassian.net/browse/CNFT2-2208
> [CNFT2-2214] Remove number from business rules fields

- apps/modernization-ui/src/apps/page-builder/page/management/preview/tab/subsection/PreviewSubsection.tsx
- apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/Form/BusinessRulesForm.tsx
Fixed business rules bug
https://cdc-nbs.atlassian.net/browse/CNFT2-2214
> [CNFT2-2214] - Fix business rules bug

- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/pagerules/PageRuleFinder.java
Improves the query performance by adding an additional clause to the `wa_ui_metadata` join
> Improve query performance

- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/PageDeletor.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/PageStateChanger.java
- apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/page/PageStateChangerTest.java
Fixes rules being removed when you create a new draft
* [CNFT2-2229](https://cdc-nbs.atlassian.net/browse/CNFT2-2229)
[CNFT2-2229]: https://cdc-nbs.atlassian.net/browse/CNFT2-2229?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix delete draft removing original questions

- apps/modernization-ui/src/apps/page-builder/page/management/edit/tabs/AddEditTab/AddEditTab.spec.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/tabs/AddEditTab/AddEditTab.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/tabs/AddEditTab/addedittab.module.scss
- apps/modernization-ui/src/apps/page-builder/page/management/edit/tabs/ManageTabs/ManageTabs.tsx
- apps/modernization-ui/src/apps/page-builder/services/tabsAPI.ts
Adding 50 char limit to new/edit Tabs.
* [CNFT2-1834](https://cdc-nbs.atlassian.net/browse/CNFT2-1834)
[CNFT2-1834]: https://cdc-nbs.atlassian.net/browse/CNFT2-1834?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CNFT2-1834 Add new tab: 50 char

- apps/modernization-ui/src/apps/search/patient/patientSearch/PatientSearch.tsx
Remove ariaLabel attribute from input element.
* [CNFT1-1894](https://cdc-nbs.atlassian.net/browse/CNFT1-1894)
[CNFT1-1894]: https://cdc-nbs.atlassian.net/browse/CNFT1-1894?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> removed improper ariaLabel on last name input

- apps/modernization-ui/src/apps/page-builder/page/management/edit/section/manage/AddSection.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/subsection/manage/AddSubSection.tsx
Add section and subsection `cancel` buttons should have outline styling.
* [CNFT2-2101](https://cdc-nbs.atlassian.net/browse/CNFT2-2101)
[CNFT2-2101]: https://cdc-nbs.atlassian.net/browse/CNFT2-2101?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Change cancel buttons to outline

- apps/modernization-ui/src/apps/page-builder/page/management/edit/content/page-content.module.scss
- apps/modernization-ui/src/apps/page-builder/page/management/edit/section/section.module.scss
Here, the action menu in Edit Page, when scrolled past the top
* [CNFT2-2102](https://cdc-nbs.atlassian.net/browse/CNFT2-2102)
[CNFT2-2102]: https://cdc-nbs.atlassian.net/browse/CNFT2-2102?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CNFT2-2102 Action menu docked

- apps/modernization-ui/src/apps/page-builder/components/EditValueset/concept/ConceptForm.tsx
- apps/modernization-ui/src/validation/date/isAfter.ts
Show error message on effectiveToTime instead of effectiveFromTime
* [CNFT2-2189](https://cdc-nbs.atlassian.net/browse/CNFT2-2189)
[CNFT2-2189]: https://cdc-nbs.atlassian.net/browse/CNFT2-2189?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Show error message on effectiveToTime instead of effectiveFromTime

- apps/modernization-ui/src/apps/page-builder/components/AddQuestion/fields/MessagingFields.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/question/GroupQuestion/SubsectionDetails.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/preview/information/page-information.module.scss
- apps/modernization-ui/src/apps/page-builder/pages/AddNewPage/AddNewPage.scss
- apps/modernization-ui/src/apps/page-builder/pages/AddNewPage/AddNewPage.tsx
- apps/modernization-ui/src/styles/global.scss
Fixed business rules defect
* https://cdc-nbs.atlassian.net/browse/CNFT2-1281
* https://cdc-nbs.atlassian.net/browse/CNFT2-2140
* https://cdc-nbs.atlassian.net/browse/CNFT2-2236
* https://cdc-nbs.atlassian.net/browse/CNFT2-2198
> [CNFT2-2236] [CNFT2-2236] [CNFT2-2236] [CNFT2-2198] - Fix business rules bug

- apps/modernization-ui/src/apps/page-builder/components/AddValueset/AddValueset.tsx
- apps/modernization-ui/src/apps/page-builder/components/EditValueset/CreateConcept.tsx
- apps/modernization-ui/src/apps/page-builder/components/EditValueset/concept/ConceptForm.tsx
1. Trigger validation on effectiveToChange to capture calendar date selection
2. Show error message when creating value set
3. Show error message when creating concept
> Calendar selection validation

- apps/modernization-api/src/test/java/gov/cdc/nbs/event/investigation/InvestigationMother.java
- libs/options-api/src/test/java/gov/cdc/nbs/option/concept/ConceptOptionSteps.java
> Remove a couple unused imports

- apps/modernization-ui/src/apps/page-builder/page/management/edit/question/QuestionContent.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/question/question-content.module.scss
- apps/modernization-ui/src/apps/page-builder/page/management/preview/tab/question/PreviewQuestion.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/preview/tab/question/preview-question.module.scss
Fixed preview and edit page search and quick lookup bug
Preview page:
Edit Page:
* [Jira Ticket] 
* https://cdc-nbs.atlassian.net/browse/CNFT2-2190
> [CNFT2-2190] - Fix preview and edit page search and quick lookup bug

- apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/Form/BusinessRulesForm.tsx
- apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/ViewBusinessRule/ViewBusinessRule.spec.tsx
- apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/ViewBusinessRule/ViewBusinessRule.tsx
- apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/helpers/errorMessageUtils.ts
Several minor bugs dealing with the formatting of the error messages for date compare rules.
* [Jira Ticket](https://cdc-nbs.atlassian.net/jira/software/c/projects/CNFT2/boards/99?assignee=712020%3A591f5469-427d-49e9-87dc-8b4df72a02b4&selectedIssue=CNFT2-2226)
* [Jira Ticket](https://cdc-nbs.atlassian.net/jira/software/c/projects/CNFT2/boards/99?assignee=712020%3A591f5469-427d-49e9-87dc-8b4df72a02b4&selectedIssue=CNFT2-2227)
* [Jira Ticket](https://cdc-nbs.atlassian.net/jira/software/c/projects/CNFT2/boards/99?assignee=712020%3A591f5469-427d-49e9-87dc-8b4df72a02b4&selectedIssue=CNFT2-2228)
* [Jira Ticket](https://cdc-nbs.atlassian.net/jira/software/c/projects/CNFT2/boards/99?assignee=712020%3A591f5469-427d-49e9-87dc-8b4df72a02b4&selectedIssue=CNFT2-2231)
- [] PR focuses on a single story
> View business rule page bugs

- apps/modernization-ui/src/apps/page-builder/page/management/preview/tab/question/PreviewQuestion.tsx
Fixed preview page bug for dynamic component render
* https://cdc-nbs.atlassian.net/browse/CNFT2-2249
> [CNFT2-2249] - Fix preview page bug

- apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/SourceQuestion/SourceQuestion.module.scss
- apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/SourceQuestion/SourceQuestion.tsx
- apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/TargetQuestion/TargetQuestion.module.scss
- apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/TargetQuestion/TargetQuestion.tsx
Now can see selected sections and subsections
* [CNFT2-2224](https://cdc-nbs.atlassian.net/browse/CNFT2-2224)
[CNFT2-2224]: https://cdc-nbs.atlassian.net/browse/CNFT2-2224?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Cnft2 2224 selected subsection

- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/PageMetaDataDownloader.java
- apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/page/download/PageMetaDataDownloaderTest.java
Following are the columns missing in Modernized Metadata file, Tab name: Comprehensive Question Metadata
question_oid:
question_oid_system_txt
nbs_ui_component_uid
code_set_group_id
version_ctrl_nbr
legacy_data_location
entry_method
https://cdc-nbs.atlassian.net/browse/CNFT2-1934
> Adding Missed Columns for Page Metadata.

- apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/Edit/EditBusinessRules.tsx
- apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/Form/BusinessRulesForm.tsx
Update button is disabled until a change has happened.
* [CNFT2-2233](https://cdc-nbs.atlassian.net/browse/CNFT2-2233)
[CNFT2-2233]: https://cdc-nbs.atlassian.net/browse/CNFT2-2233?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Cnft2 2233 update button disabled

- apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/Form/BusinessRulesForm.tsx
- apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/SourceQuestion/SourceQuestion.tsx
- apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/TargetQuestion/TargetQuestion.tsx
reset target question when source question is changed
* [CNFT2-2247](https://cdc-nbs.atlassian.net/browse/CNFT2-2247)
[CNFT2-2247]: https://cdc-nbs.atlassian.net/browse/CNFT2-2247?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CNFT2-2247-reset-target-question

- apps/modernization-ui/src/apps/page-builder/page/management/preview/information/PageInformation.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/preview/information/page-information.module.scss
- apps/modernization-ui/src/styles/_uswds.scss
Fixed history pagination bug
* [Jira Ticket] https://cdc-nbs.atlassian.net/browse/CNFT2-2248
> [CNFT2-2248] - Fix history pagination bug

- apps/modernization-ui/src/apps/page-builder/components/CreateCondition/CreateCondition.tsx
Updated create condition error message.
* [Jira Ticket] https://cdc-nbs.atlassian.net/browse/CNFT2-2255
> [CNFT2-2255] - Update create condition error message

- apps/modernization-ui/package.json
- apps/modernization-ui/src/generated/core/OpenAPI.ts
- apps/modernization-ui/src/index.tsx
restores the sed when generating the clients from modernization-api open-api docs
> restores the sed when generating the clients from modernization-api open-api docs

- apps/modernization-ui/src/apps/page-builder/page/management/preview/PublishPage/PublishPage.tsx
Fixed publish page empty condition validation
* [Jira Ticket] https://cdc-nbs.atlassian.net/browse/CNFT2-2256
> [CNFT2-2256] - Publish page empty condition validation

- apps/modernization-ui/src/apps/page-builder/components/CreateCondition/CreateCondition.tsx
Added more special characters to match with classic for Create New Condition - condition name validation
* [Jira Ticket] https://cdc-nbs.atlassian.net/browse/CNFT2-2255
> [CNFT2-2255] - Condition Name validation fix

- apps/modernization-ui/src/apps/page-builder/page/management/preview/PublishPage/PublishPage.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/preview/PublishPage/publish-page.module.scss
Here we ensure the Publish page modal footer does not have overflow on smaller screens.
* [CNFT2-2257](https://cdc-nbs.atlassian.net/browse/CNFT2-2257)
[CNFT2-2257]: https://cdc-nbs.atlassian.net/browse/CNFT2-2257?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CNFT2-2257 Publish page: modal

- apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/TargetQuestion/TargetQuestion.tsx
Here we limit the number of Business rules: target question to 10.
* [/CNFT2-2241)](https://cdc-nbs.atlassian.net/browse/CNFT2-2241)
> CNFT2-2241 Business rules: 10 max target questions

- apps/modernization-ui/src/apps/page-builder/components/AddQuestion/fields/DataMartFields.tsx
- apps/modernization-ui/src/apps/page-builder/components/CreateCondition/CreateCondition.scss
- apps/modernization-ui/src/apps/page-builder/components/CreateCondition/CreateCondition.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/preview/PreviewPage.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/preview/tab/question/PreviewQuestion.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/preview/tab/subsection/PreviewSubsection.tsx
Fixed Preview, Condition and Question defects
* https://cdc-nbs.atlassian.net/browse/CNFT2-2269
* https://cdc-nbs.atlassian.net/browse/CNFT2-2265
* https://cdc-nbs.atlassian.net/browse/CNFT2-2266
> [CNFT2-2265]  [CNFT2-2266]  [CNFT2-2269] - Preview Condition and Question defect fix

- apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/RuleSearchBar.tsx
Here we update Business rules search field:
1. Search works when user hits Enter
2. Clearing search field returns to default table view
* [CNFT2-2267](https://cdc-nbs.atlassian.net/browse/CNFT2-2267)
[CNFT2-2267]: https://cdc-nbs.atlassian.net/browse/CNFT2-2267?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CNFT2-2267 Business rules: search update

- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/pagerules/SourceQuestionFinder.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/pagerules/TargetQuestionFinder.java
Source questions not being populated in some pages. Have a possible fix, that can be confirmed once deployed
> possible fix for source question

- apps/modernization-ui/src/apps/page-builder/page/library/menu/PageLibraryMenu.tsx
- apps/modernization-ui/src/apps/page-builder/page/library/menu/page-library-menu.module.scss
- apps/modernization-ui/src/apps/page-builder/page/management/preview/PreviewPage.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/preview/preview-page.module.scss
- apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/RuleSearchBar.tsx
- apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/rule-search-bar.module.scss
- apps/modernization-ui/src/components/button/link/LinkButton.tsx
- apps/modernization-ui/src/styles/_uswds.scss
Adding tooltips to Page Library and Business Rules libraries
* [CNFT2-2268](https://cdc-nbs.atlassian.net/browse/CNFT2-2268)
[CNFT2-2268]: https://cdc-nbs.atlassian.net/browse/CNFT2-2268?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CNFT2-2268 Library icon tooltips

- apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/BusinessRulesLibrary.tsx
Business rules sort default to function field when page loads
* [Jira Ticket] https://cdc-nbs.atlassian.net/browse/CNFT2-2273
> [CNFT2-2273] - Business rules sort default to function field

- apps/modernization-ui/src/apps/page-builder/page/management/preview/PreviewPage.tsx
Changed Tooltip Text from Copy Page to Page porting
* [Jira Ticket] https://cdc-nbs.atlassian.net/browse/CNFT2-2284
> [CNFT2-2284] - Tooltip Text changes

- apps/modernization-ui/src/apps/page-builder/page/management/edit/subsection/SubsectionHeader.tsx
- apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/RuleSearchBar.tsx
Here we remove the Group Questions button if any Questions have `isPublished === true`.
Also small typo fix in Business rules search field.
* [CNFT2-2277](https://cdc-nbs.atlassian.net/browse/CNFT2-2277)
[CNFT2-2277]: https://cdc-nbs.atlassian.net/browse/CNFT2-2277?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CNFT2-2277 Grouping published questions

- apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/Form/BusinessRulesForm.tsx
- apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/TargetQuestion/TargetQuestion.tsx
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/entity/NbsConfiguration.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/content/staticelement/PageStaticCreator.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/pagerules/PageRuleFinder.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/pagerules/PageRuleMapper.java
- apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/page/content/staticelement/PageStaticCreatorTest.java
- apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/pagerules/CreatePageRuleSteps.java
- apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/pagerules/PageRuleMapperTest.java
- libs/id-generator/src/main/java/gov/cdc/nbs/id/IdGeneratorService.java
Business Rules: Target Question has to have Static elements also included. When a business rule is added, it has to appear in the Business Rules Library screen with Static elements listed with the Unique ID
https://cdc-nbs.atlassian.net/browse/CNFT2-2254
> Target Question has to have Static elements also included

- apps/modernization-ui/src/apps/patient/add/Race/RaceFields.tsx
- apps/modernization-ui/src/apps/patient/add/addressFields/AddressFields.tsx
- apps/modernization-ui/src/apps/patient/add/otherInfoFields/OtherInfoFields.tsx
Just fixes some labels to sentence case to match design.
* [Jira Ticket](https://cdc-nbs.atlassian.net/jira/software/c/projects/CNFT1/boards/112?assignee=712020%3A591f5469-427d-49e9-87dc-8b4df72a02b4&selectedIssue=CNFT1-2169)
> CNFT1-2169/Sentence-case labels on add new patient form

- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/entity/question/WaQuestionHist.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/filter/querydsl/DefaultQueryDSLCriteriaResolver.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/filter/querydsl/PageLibraryQueryDSLCriteriaResolver.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/PageMetaDataDownloader.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/component/tree/ContentComponentResolver.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/content/question/PageQuestionUpdater.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/question/QuestionMapper.java
- libs/authentication/src/main/java/gov/cdc/nbs/authentication/session/SessionAuthenticator.java
Fixes Sonar code smells introduced after upgrading to Java 21
> Fixes Sonar code smells introduced after upgrading to Java 21

- apps/modernization-ui/src/apps/search/advancedSearch/AdvancedSearch.tsx
- apps/modernization-ui/src/styles/_uswds.scss
Quick ui fix to make the pagination buttons transparent on the patient search page.
* [Jira Ticket](https://cdc-nbs.atlassian.net/jira/software/c/projects/CNFT1/boards/112?assignee=712020%3A591f5469-427d-49e9-87dc-8b4df72a02b4&selectedIssue=CNFT1-1926)
> Make pagination background transparent on search page

- apps/modernization-ui/src/routes/RedirectHome.tsx
Bug Fix
Fixing a redirection issue and using person instead of patient as it causes conflicts with an enum value using `patient`
> replacing patient with person on redirection for now

- apps/modernization-ui/src/apps/patient/add/AddPatient.tsx
- apps/modernization-ui/src/confirmation/ConfirmationModal.tsx
- apps/modernization-ui/src/success/SuccessModal.tsx
- apps/modernization-ui/src/success/index.ts
- apps/modernization-ui/src/success/successModal.module.scss
Here, upon successfully adding a patient, we replace the page with a modal where you can either view the patient or return to the Add Patient page.
* [CNFT1-2167](https://cdc-nbs.atlassian.net/browse/CNFT1-2167)
[CNFT1-2167]: https://cdc-nbs.atlassian.net/browse/CNFT1-2167?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CNFT1-2167 Add patient success modal

- testing/regression/cypress/e2e/features/page-library/pagination.feature
- testing/regression/cypress/e2e/pages/page-library/pagination.page.js
- testing/regression/cypress/step_definitions/page-library/pagination.steps.js
Added end to end test case for Page Library pagination for 20 records selection ( [CNFT2-976](https://cdc-nbs.atlassian.net/browse/CNFT2-976) )
[CNFT2-976]: https://cdc-nbs.atlassian.net/browse/CNFT2-976?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CNT-9] - E2E page library pagination for 20 records selection

- apps/modernization-ui/src/styles/_buttons.scss
- apps/modernization-ui/src/styles/_colors.scss
- apps/modernization-ui/src/styles/_uswds.scss
Updates some styling in buttons to match new design specs.
* [Jira Ticket](https://cdc-nbs.atlassian.net/jira/software/c/projects/CNFT1/boards/112?selectedIssue=CNFT1-2194)
* [Jira Ticket](https://cdc-nbs.atlassian.net/jira/software/c/projects/CNFT1/boards/112?selectedIssue=CNFT1-2196)
* [Jira Ticket](https://cdc-nbs.atlassian.net/jira/software/c/projects/CNFT1/boards/112?selectedIssue=CNFT1-2197)
> Update button styles

- apps/modernization-ui/src/apps/page-builder/components/AddQuestion/fields/BasicInformationFields.tsx
- apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/Form/BusinessRulesForm.tsx
- apps/modernization-ui/src/components/SegmentedButtons/SegmentedButtons.spec.tsx
- apps/modernization-ui/src/components/SegmentedButtons/SegmentedButtons.tsx
- apps/modernization-ui/src/components/SegmentedButtons/segmentedButtons.module.scss
- apps/modernization-ui/src/styles/_uswds.scss
Here we create a new SegmentedButtons component to align the styling with our design system.
* [CNFT1-2198](https://cdc-nbs.atlassian.net/browse/CNFT1-2198)
* [CNFT1-2199](https://cdc-nbs.atlassian.net/browse/CNFT1-2199)
* [CNFT1-2200](https://cdc-nbs.atlassian.net/browse/CNFT1-2200)
* [CNFT1-2201](https://cdc-nbs.atlassian.net/browse/CNFT1-2201)
[CNFT1-2198]: https://cdc-nbs.atlassian.net/browse/CNFT1-2198?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CNFT1-2199]: https://cdc-nbs.atlassian.net/browse/CNFT1-2199?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CNFT1-2200]: https://cdc-nbs.atlassian.net/browse/CNFT1-2200?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViL …
> CNFT1-2198 Segmented Buttons

- testing/regression/cypress/e2e/features/page-library/pagination.feature
- testing/regression/cypress/step_definitions/page-library/pagination.steps.js
Added end to end test case for Page Library pagination for 20 records selection ( [CNFT2-984](https://cdc-nbs.atlassian.net/browse/CNFT2-984) )
[CNFT2-984]: https://cdc-nbs.atlassian.net/browse/CNFT2-984?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CNT-9] - E2E page library pagination 30 row selection

- apps/modernization-ui/src/apps/page-builder/components/DeleteQuestion/DeleteQuestion.tsx
- apps/modernization-ui/src/apps/page-builder/components/TabGroup/TabGroup.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/question/QuestionHeader.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/staticelement/EditStaticElement.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/subsection/Subsection.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/subsection/SubsectionHeader.spec.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/subsection/SubsectionHeader.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/header/tabs/PageTabs.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/preview/PreviewPage.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/preview/tab/section/PreviewSection.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/preview/tab/subsection/PreviewSubsection.tsx
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/entity/WaTemplate.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/content/question/PageQuestionDeleter.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/content/question/PageQuestionUpdater.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/content/question/exception/DeletePageQuestionException.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/content/section/SectionUpdater.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/content/subsection/SubSectionUpdater.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/content/tab/TabUpdater.java
- apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/entity/WaTemplateTest.java
- apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/page/content/question/PageQuestionDeleterTest.java
- apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/page/content/question/PageQuestionUpdaterTest.java
- apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/page/content/section/SectionUpdaterTest.java
- apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/page/content/subsection/SubsectionUpdaterTest.java
- apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/page/content/tab/TabUpdaterTest.java
- gradle/libs.versions.toml
Cherry picks some bug fixes into release-7.4.0
|Severity|Bug Description|
|------|----|
|Critical | Allow ungrouping if a page is `Published with Draft`|
|Critical | Prevent deletion of question when question is source or target of a rule|
|Medium | Disable grouping when a subsection contains a static element|
|Low|Hide subsection in preview mode when visibility is `false`|
|Low|Hide tabs in preview mode when visibility is `false`|
|Low|Update confirmation message when deleting static element|
|Low|Remove `required` toggle from static element display|
> PB bug fix cherry pick

- testing/regression/cypress/e2e/features/page-library/pagination.feature
- testing/regression/cypress/step_definitions/page-library/pagination.steps.js
Added end to end test case for Page Library pagination for 50 records selection ( [CNFT2-1002](https://cdc-nbs.atlassian.net/browse/CNFT2-1002) )
[CNFT2-1002]: https://cdc-nbs.atlassian.net/browse/CNFT2-1002?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CNT-9] - E2E page library pagination 50 row selection

- testing/regression/cypress/e2e/features/page-library/pagination.feature
Added end to end test case for Page Library pagination for 100 records selection ( [CNFT2-1007](https://cdc-nbs.atlassian.net/browse/CNFT2-1007) )
[CNFT2-1007]: https://cdc-nbs.atlassian.net/browse/CNFT2-1007?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CNT-9] - E2E page library pagination 100 row selection

- apps/modernization-ui/src/styles/_uswds.scss
Updating Pagination styling to match current design system.
* [CNFT1-2224](https://cdc-nbs.atlassian.net/browse/CNFT1-2224)
[CNFT1-2224]: https://cdc-nbs.atlassian.net/browse/CNFT1-2224?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CNFT1-2224 Pagination colors

- apps/nbs-gateway/build.gradle
Updates spring-security-rsa to version 1.1.3 to resolve [CVE-2024-30172](https://security.snyk.io/vuln/SNYK-JAVA-ORGBOUNCYCASTLE-6612985)
[CNFT1-2326](https://cdc-nbs.atlassian.net/browse/CNFT1-2326)
[CNFT1-2326]: https://cdc-nbs.atlassian.net/browse/CNFT1-2326?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [FIX] CVE-2024-30172

- testing/regression/cypress/e2e/features/page-library/searchAndFilter.feature
Added end to end test case for search page contains part of the related condition ( [CNFT2-1034](https://cdc-nbs.atlassian.net/browse/CNFT2-1034) )
[CNFT2-1034]: https://cdc-nbs.atlassian.net/browse/CNFT2-1034?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CNT-14] E2E page library Search page contains part of related condition(s)

- apps/modernization-ui/src/apps/landing/About/About.tsx
- apps/modernization-ui/src/apps/landing/Layout/LoginWrapper.tsx
- apps/modernization-ui/src/apps/landing/Layout/WelcomeLayout.tsx
- apps/modernization-ui/src/apps/landing/Layout/login-wrapper.module.scss
- apps/modernization-ui/src/apps/landing/Layout/welcomeLayout.module.scss
- apps/modernization-ui/src/apps/landing/Learn/Learn.tsx
Fixing the following comments mentioned from QA Results
Welcome tab
- Welcome title should reside next to the NBS logo. Mural displays it that way. Then raise up the About and Learn more tabs so there is less real estate
- Space is needed between the words more and representative in the (Demo features guide section)
- Space is needed between the words at and [nbs@cdc.gov](mailto:nbs@cdc.gov) in the (Feedback section)
- The word Qualtrics (in Feedback section) should be removed from the sentence, “If you cannot access the…
Learn more tab
- In the Newsletter section, space is needed between the following here:[NNDSS News | CDC](https://www.cdc.gov/nndss/trc/news/index.html) .
- In the NBS community activities section, [nbs@cdc.gov](mailto:nbs@cdc.gov) should be a link
- More ways to get …
> fixing welcome pages design issues

- apps/modernization-ui/src/apps/patient/profile/summary/PatientProfileSummary.tsx
- apps/modernization-ui/src/apps/search/patient/result/PatientResult.spec.tsx
- apps/modernization-ui/src/apps/search/patient/result/PatientResult.tsx
Quick copy fix to add text "years old" on a patients age.
* [Jira Ticket](https://cdc-nbs.atlassian.net/jira/software/c/projects/CNFT1/boards/112?assignee=712020%3A591f5469-427d-49e9-87dc-8b4df72a02b4&selectedIssue=CNFT1-2166)
> Update DOB copy in patient search and profile

- testing/regression/cypress/e2e/features/page-library/searchAndFilter.feature
Added end to end test case for filter by event type using equal to operator ( [CNFT2-1074](https://cdc-nbs.atlassian.net/browse/CNFT2-1074) )
[CNFT2-1074]: https://cdc-nbs.atlassian.net/browse/CNFT2-1074?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CNT-14] - E2E page library filter by event type using equal to operator

- testing/regression/cypress/e2e/features/page-library/searchAndFilter.feature
Added end to end test case for filter by related condition using equal to operator ( [CNFT2-1093](https://cdc-nbs.atlassian.net/browse/CNFT2-1093) )
[CNFT2-1093]: https://cdc-nbs.atlassian.net/browse/CNFT2-1093?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CNT-14] - E2E page library filter by related condition using equal to operator

- testing/regression/cypress/e2e/features/page-library/searchAndFilter.feature
Added end to end test case for filter by status using equal to operator ( [CNFT2-1102](https://cdc-nbs.atlassian.net/browse/CNFT2-1102) )
[CNFT2-1102]: https://cdc-nbs.atlassian.net/browse/CNFT2-1102?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CNT-14] - Page library filter by status using equal to operator

- testing/regression/cypress/e2e/features/page-library/searchAndFilter.feature
Added end to end test case for filter last updated by using contains operator ( [CNFT2-1136](https://cdc-nbs.atlassian.net/browse/CNFT2-1136) )
[CNFT2-1136]: https://cdc-nbs.atlassian.net/browse/CNFT2-1136?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CNT-14] - Page library filter last updated by using contains operator

- apps/modernization-ui/src/apps/patient/add/NewPatientEntry.ts
- apps/modernization-ui/src/apps/patient/add/asPersonInput.spec.tsx
- apps/modernization-ui/src/apps/patient/add/asPersonInput.ts
- apps/modernization-ui/src/apps/patient/add/contactFields/ContactFields.tsx
- apps/modernization-ui/src/apps/patient/add/contactFields/contactFields.module.scss
- apps/modernization-ui/src/apps/patient/profile/Demographics.tsx
Here we enable users to change types when adding additional phone numbers.
* [CNFT1-2275](https://cdc-nbs.atlassian.net/browse/CNFT1-2275)
[CNFT1-2275]: https://cdc-nbs.atlassian.net/browse/CNFT1-2275?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Cnft1 2275 add additional phone

- apps/modernization-ui/src/apps/landing/About/About.tsx
- apps/modernization-ui/src/apps/landing/Layout/welcomeLayout.module.scss
Some minor updates to About page and Welcome layout.
* [CNFT1-2338](https://cdc-nbs.atlassian.net/browse/CNFT1-2338)
[CNFT1-2338]: https://cdc-nbs.atlassian.net/browse/CNFT1-2338?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CNFT1-2388 Login About updates

- testing/regression/cypress/e2e/features/search-investigation-general-info.feature
- testing/regression/cypress/e2e/pages/searchEvent.page.js
- testing/regression/cypress/step_definitions/searchEvent.steps.js
Verify that the application can successfully search for investigations based on a specific medical condition.
* [CNFT1-1330](https://cdc-nbs.atlassian.net/browse/CNFT1-1330)
[CNFT1-1330]: https://cdc-nbs.atlassian.net/browse/CNFT1-1330?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CNFT1-1330 Search investigation by condition

- apps/modernization-ui/src/apps/landing/Layout/login-wrapper.module.scss
- apps/modernization-ui/src/apps/landing/SignIn/SignIn.spec.tsx
- apps/modernization-ui/src/apps/landing/SignIn/SignIn.tsx
- apps/modernization-ui/src/logout/Logout.tsx
- apps/modernization-ui/src/logout/index.ts
- apps/modernization-ui/src/logout/logout.module.scss
- apps/modernization-ui/src/logout/logoutRouting.tsx
- apps/modernization-ui/src/providers/UserContext.tsx
- apps/modernization-ui/src/routes/AppRoutes.tsx
- testing/regression/cypress/e2e/features/page-library/searchAndFilter.feature
- testing/regression/cypress/e2e/pages/page-library/searchAndFilter.page.js
- testing/regression/cypress/step_definitions/page-library/searchAndFilter.steps.js
Logout screen with no header included in navbar and functionality to return to nbs button
* [CNFT1-2298](https://cdc-nbs.atlassian.net/browse/CNFT1-2298)
[CNFT1-2298]: https://cdc-nbs.atlassian.net/browse/CNFT1-2298?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Cnft1 2298 log out screen

- apps/modernization-ui/src/apps/landing/Expired/Expired.module.scss
- apps/modernization-ui/src/apps/landing/Expired/Expired.tsx
- apps/modernization-ui/src/routes/AppRoutes.tsx
Here we create the session time-out page. Page added to router.
Timeout process will be implemented in a future branch.
* [CNFT1-2299](https://cdc-nbs.atlassian.net/browse/CNFT1-2299)
[CNFT1-2299]: https://cdc-nbs.atlassian.net/browse/CNFT1-2299?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CNFT1-2299 Session timeout page

- apps/modernization-ui/src/apps/page-builder/components/AddQuestion/fields/BasicInformationFields.tsx
- apps/modernization-ui/src/components/SegmentedButtons/SegmentedButtons.tsx
- apps/modernization-ui/src/components/SegmentedButtons/segmentedButtons.module.scss
Updating Add Question segmented buttons to match current style.
* [CNFT1-2198](https://cdc-nbs.atlassian.net/browse/CNFT1-2198)
[CNFT1-2198]: https://cdc-nbs.atlassian.net/browse/CNFT1-2198?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CNFT1-2198 Segmented buttons part 2

- apps/modernization-ui/src/apps/landing/About/About.tsx
- apps/modernization-ui/src/apps/landing/Expired/Expired.module.scss
- apps/modernization-ui/src/apps/landing/Expired/Expired.tsx
- apps/modernization-ui/src/apps/landing/Layout/welcomeLayout.module.scss
- apps/modernization-ui/src/routes/AppRoutes.tsx
Here we ensure the long URLs on the Welcome pages have line-breaks.
* [CNFT1-2342](https://cdc-nbs.atlassian.net/browse/CNFT1-2342)
[CNFT1-2342]: https://cdc-nbs.atlassian.net/browse/CNFT1-2342?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Cnft1 2342 break urls

- testing/regression/cypress/e2e/features/page-library/dataElements.feature
Added end to end test case for verifying Related condition(s) column contains various conditions ( [CNFT2-967](https://cdc-nbs.atlassian.net/browse/CNFT2-967) )
[CNFT2-967]: https://cdc-nbs.atlassian.net/browse/CNFT2-967?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CNT-18] - Page library - data elements - verify related condition contain various condition

- apps/modernization-ui/src/apps/patient/profile/investigation/PatientOpenInvestigationsTable.spec.tsx
- apps/modernization-ui/src/apps/patient/profile/investigation/PatientOpenInvestigationsTable.tsx
Here we move the Investigation # to the first item in the Open patient investigations table.
* [CNFT1-2277](https://cdc-nbs.atlassian.net/browse/CNFT1-2277)
[CNFT1-2277]: https://cdc-nbs.atlassian.net/browse/CNFT1-2277?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CNFT1-2277 Open investigation table order

- apps/modernization-ui/src/apps/search/advancedSearch/AdvancedSearch.tsx
Updating no results message: when searching for event, there is no link to Add a new patient.
* [CNFT1-1764](https://cdc-nbs.atlassian.net/browse/CNFT1-1764)
[CNFT1-1764]: https://cdc-nbs.atlassian.net/browse/CNFT1-1764?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CNFT1-1764 No results message

- testing/regression/cypress/e2e/features/page-library/dataElements.feature
Added end to end test case to verify event type column contains required value ( [CNFT2-966](https://cdc-nbs.atlassian.net/browse/CNFT2-966) )
[CNFT2-966]: https://cdc-nbs.atlassian.net/browse/CNFT2-966?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CNT-18] - Page library data elements verify event type contains required value

- testing/regression/cypress/e2e/features/page-library/dataElements.feature
Added end to end test case to verify Status column contains required value ( [CNFT2-968](https://cdc-nbs.atlassian.net/browse/CNFT2-968) )
[CNFT2-968]: https://cdc-nbs.atlassian.net/browse/CNFT2-968?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CNT-18] - Page library data elements verify status column contains required value

- testing/regression/cypress/e2e/features/page-library/dataElements.feature
Added end to end test case to verify Last Updated column contains required date format value ( [CNFT2-969](https://cdc-nbs.atlassian.net/browse/CNFT2-969) )
[CNFT2-969]: https://cdc-nbs.atlassian.net/browse/CNFT2-969?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CNT-18] - Page library data elements verify last updated column contains required date format value

- testing/regression/cypress/e2e/features/page-library/dataElements.feature
Added end to end test case to verify Last Updated by column contains required value ( [CNFT2-970](https://cdc-nbs.atlassian.net/browse/CNFT2-970) )
[CNFT2-970]: https://cdc-nbs.atlassian.net/browse/CNFT2-970?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CNT-18] - Page library data elements verify last updated by column contains required value

- testing/regression/cypress/e2e/features/search-investigation-general-info.feature
- testing/regression/cypress/e2e/pages/searchEvent.page.js
- testing/regression/cypress/step_definitions/searchEvent.steps.js
To verify that the application can successfully search for patients based on a specific pregnancy test result associated with the investigation event.
* CNFT1-1333(https://cdc-nbs.atlassian.net/browse/CNFT1-1333)
> CNFT1-1333 Event Search investigation pregnancy

- apps/modernization-ui/src/components/SegmentedButtons/segmentedButtons.module.scss
Small adjustments to Segmented buttons styling.
* [CNFT1-2201](https://cdc-nbs.atlassian.net/browse/CNFT1-2201)
[CNFT1-2201]: https://cdc-nbs.atlassian.net/browse/CNFT1-2201?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CNFT1-2201 Adjust segmented buttons

- testing/regression/cypress/e2e/features/search-investigation-general-info.feature
- testing/regression/cypress/e2e/pages/searchEvent.page.js
- testing/regression/cypress/step_definitions/searchEvent.steps.js
To verify that the application can successfully search for patients based on a specific event ID type associated with the investigation event. 
* [CNFT1-1334](https://cdc-nbs.atlassian.net/browse/CNFT1-1334)
[CNFT1-1334]: https://cdc-nbs.atlassian.net/browse/CNFT1-1334?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CNFT1-1334 Search by Event ID Type

- testing/regression/cypress/e2e/features/search-investigation-general-info.feature
- testing/regression/cypress/e2e/pages/searchEvent.page.js
- testing/regression/cypress/step_definitions/searchEvent.steps.js
To verify that the application can successfully search for patients based on a specific event date type associated with the investigation event.
* [CNFT1-1335](https://cdc-nbs.atlassian.net/browse/CNFT1-1335)
[CNFT1-1335]: https://cdc-nbs.atlassian.net/browse/CNFT1-1335?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CNFT1-1335 event date search

- testing/regression/cypress/e2e/features/search-investigation-general-info.feature
- testing/regression/cypress/e2e/pages/searchEvent.page.js
- testing/regression/cypress/step_definitions/searchEvent.steps.js
To verify that the application can successfully search for patients based on the user who created the investigation event.
* [CNFT1-1336](https://cdc-nbs.atlassian.net/browse/CNFT1-1336)
[CNFT1-1336]: https://cdc-nbs.atlassian.net/browse/CNFT1-1336?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CNFT1-1336 Search event using created by

- apps/modernization-ui/src/apps/page-builder/pages/AddNewPage/AddNewPage.tsx
- testing/regression/cypress/e2e/features/create-page/pageElements.feature
- testing/regression/cypress/e2e/pages/create-page/pageElements.page.js
- testing/regression/cypress/step_definitions/create-page/pageElements.steps.js
Added end to end test case to verify create new page displays required page elements ( [CNFT2-1214](https://cdc-nbs.atlassian.net/browse/CNFT2-1214) )
[CNFT2-1214]: https://cdc-nbs.atlassian.net/browse/CNFT2-1214?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CNT-18] - Create Page - E2E to verify create new page displays required page elements

- testing/regression/cypress/e2e/features/search-investigation-general-info.feature
- testing/regression/cypress/e2e/pages/searchEvent.page.js
- testing/regression/cypress/step_definitions/searchEvent.steps.js
> Fixed conflicts the search investigation general info

- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/entity/pagerule/WaRuleMetadata.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/pagerules/DateCompareCommandCreator.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/pagerules/EnableDisableCommandCreator.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/pagerules/HideUnhideCommandCreator.java
- apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/pagerules/RequireIfCommandCreator.java
- apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/pagerules/DateCompareCommandCreatorTest.java
- apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/pagerules/EnableDisableCommandCreatorTest.java
- apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/pagerules/HideUnhideCommandCreatorTest.java
- apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/pagerules/RequireIfCommandCreatorTest.java
Updates the formatting for business rule error messages and function name to ensure alignment with Classic. Updates some tests and adds a few more to ensure proper coverage.
* [CNFT2-2302](https://cdc-nbs.atlassian.net/browse/CNFT2-2302)
[CNFT2-2302]: https://cdc-nbs.atlassian.net/browse/CNFT2-2302?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Adjust rule creation to match Classic parenthesis and formatting

- apps/modernization-ui/src/apps/page-builder/components/PagesBreadcrumb/PagesBreadcrumb.tsx
- apps/modernization-ui/src/apps/page-builder/pages/AddNewPage/AddNewPage.tsx
- testing/regression/cypress/e2e/features/create-page/pageElements.feature
- testing/regression/cypress/e2e/pages/create-page/pageElements.page.js
- testing/regression/cypress/step_definitions/create-page/pageElements.steps.js
Added end to end test case to verify (required field) Page name is editable and allows entry of text characters ( [CNFT2-1256](https://cdc-nbs.atlassian.net/browse/CNFT2-1256) )
[CNFT2-1256]: https://cdc-nbs.atlassian.net/browse/CNFT2-1256?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CNT-20] - Verify (required field) Page name is editable and allows entry of text characters

- testing/regression/cypress/e2e/features/search-investigation-general-info.feature
- testing/regression/cypress/e2e/pages/searchEvent.page.js
- testing/regression/cypress/step_definitions/searchEvent.steps.js
To verify that the application can successfully search for patients based on a specific provider/facility type associated with the investigation event.
* [CNFT1-1338](https://cdc-nbs.atlassian.net/browse/CNFT1-1338)
[CNFT1-1338]: https://cdc-nbs.atlassian.net/browse/CNFT1-1338?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CNFT1-1338 Search by Event Provider/Facility Type

- testing/regression/cypress/e2e/features/create-page/pageElements.feature
- testing/regression/cypress/e2e/pages/create-page/pageElements.page.js
- testing/regression/cypress/step_definitions/create-page/pageElements.steps.js
Added end to end test case to select an MMG to populate the field ( [CNFT2-1271](https://cdc-nbs.atlassian.net/browse/CNFT2-1271) )
[CNFT2-1271]: https://cdc-nbs.atlassian.net/browse/CNFT2-1271?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CNT-20] - E2E to Select an MMG and populate it in the field

- testing/regression/cypress/e2e/features/create-page/pageElements.feature
- testing/regression/cypress/e2e/pages/create-page/pageElements.page.js
- testing/regression/cypress/step_definitions/create-page/pageElements.steps.js
Added end to end test case to verify clicking the Cancel button on Add new page closes the page ( [CNFT2-1275](https://cdc-nbs.atlassian.net/browse/CNFT2-1275) )
[CNFT2-1275]: https://cdc-nbs.atlassian.net/browse/CNFT2-1275?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CNT-20] - Verify clicking the Cancel button on Add new page closes the page

- testing/regression/cypress/e2e/features/create-page/pageElements.feature
- testing/regression/cypress/e2e/pages/create-page/pageElements.page.js
- testing/regression/cypress/step_definitions/create-page/pageElements.steps.js
Added end to end test case to verify clicking the Page Library link on Add new page returns user to the Page Library ( [CNFT2-1277](https://cdc-nbs.atlassian.net/browse/CNFT2-1277) )
[CNFT2-1277]: https://cdc-nbs.atlassian.net/browse/CNFT2-1277?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CNT-20] - Verify clicking the Page Library link on Add new page returns user to the Page Library

- testing/regression/cypress/e2e/features/search-investigation-criteria.feature
- testing/regression/cypress/e2e/pages/searchEvent.page.js
- testing/regression/cypress/step_definitions/searchEvent.steps.js
CNFT1-1340 Event Search invesition status
* [CNFT1-1340](https://cdc-nbs.atlassian.net/browse/CNFT1-1340)
[CNFT1-1340]: https://cdc-nbs.atlassian.net/browse/CNFT1-1340?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CNFT1-1340 Event Search invesition status

- apps/modernization-ui/src/apps/search/advancedSearch/AdvancedSearch.tsx
Adding a period to the Event Search message.
* [CNFT1-1764](https://cdc-nbs.atlassian.net/browse/CNFT1-1764)
[CNFT1-1764]: https://cdc-nbs.atlassian.net/browse/CNFT1-1764?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CNFT1-1764 Event search message: add a period

- apps/modernization-ui/src/alert/alert.scss
- apps/modernization-ui/src/alert/useAlert.tsx
Ensures correct colors, padding, and font styles for the alert dialogs.
* [Jira Ticket](https://cdc-nbs.atlassian.net/jira/software/c/projects/CNFT1/boards/112?assignee=712020%3A591f5469-427d-49e9-87dc-8b4df72a02b4&selectedIssue=CNFT1-2216)
* [Jira Ticket](https://cdc-nbs.atlassian.net/jira/software/c/projects/CNFT1/boards/112?assignee=712020%3A591f5469-427d-49e9-87dc-8b4df72a02b4&selectedIssue=CNFT1-2215)
> adjust styling for alert messages

- apps/modernization-ui/src/apps/page-builder/page/library/PageLibrary.tsx
- testing/regression/cypress/e2e/features/create-page/createNewPage.feature
- testing/regression/cypress/e2e/pages/create-page/createNewPage.page.js
- testing/regression/cypress/step_definitions/create-page/createNewPage.steps.js
Added end to end test cases for these 2 scenario
[CNFT2-1213](https://cdc-nbs.atlassian.net/browse/CNFT2-1213) Access Add New Page from the Page Library
[CNFT2-1489](https://cdc-nbs.atlassian.net/browse/CNFT2-1489) Select Investigation to display additional fields
* [CNT-24](https://cdc-nbs.atlassian.net/browse/CNT-24)
[CNFT2-1213]: https://cdc-nbs.atlassian.net/browse/CNFT2-1213?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CNFT2-1489]: https://cdc-nbs.atlassian.net/browse/CNFT2-1489?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CNT-24]: https://cdc-nbs.atlassian.net/browse/CNT-24?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CNT-24] - Access Add New Page and Select Investigation to display additional fields

- testing/regression/cypress/e2e/features/create-page/createNewPage.feature
Added end to end test cases for these 2 scenario:
[CNFT2-1496](https://cdc-nbs.atlassian.net/browse/CNFT2-1496) Contact Record and clicking Create page button redirects to the classic design
[CNFT2-1499](https://cdc-nbs.atlassian.net/browse/CNFT2-1499) Interview and clicking Create page button redirects to the classic design
* [CNT-24](https://cdc-nbs.atlassian.net/browse/CNT-24)
[CNFT2-1496]: https://cdc-nbs.atlassian.net/browse/CNFT2-1496?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CNFT2-1499]: https://cdc-nbs.atlassian.net/browse/CNFT2-1499?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CNT-24]: https://cdc-nbs.atlassian.net/browse/CNT-24?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA …
> [CNT-24] - CNFT2-1496 and CNFT2-1499

- testing/regression/cypress/e2e/features/create-page/createNewPage.feature
Added end to end test cases for these 3 scenario:
[CNFT2-1502](https://cdc-nbs.atlassian.net/browse/CNFT2-1502) Lab Susceptibility and clicking Create page button redirects to the classic design
[CNFT2-1503](https://cdc-nbs.atlassian.net/browse/CNFT2-1503) Vaccination and clicking Create page button redirects to the classic design
[CNFT2-1548](https://cdc-nbs.atlassian.net/browse/CNFT2-1548) Create a page with Event Type (Investigation) and existing Template
* [CNT-24](https://cdc-nbs.atlassian.net/browse/CNT-24)
[CNFT2-1502]: https://cdc-nbs.atlassian.net/browse/CNFT2-1502?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CNFT2-1503]: https://cdc-nbs.atlassian.net/browse/CNFT2-1503?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLC …
> [CNT-24] - CNFT2-1502, CNFT2-1503 and CNFT2-1548 E2E tests

- testing/regression/cypress/e2e/features/lab-report-general-info.feature
- testing/regression/cypress/e2e/pages/searchEvent.page.js
- testing/regression/cypress/step_definitions/searchEvent.steps.js
Lab Report Search for program area and jurisdiction.
https://cdc-nbs.atlassian.net/browse/CNFT1-1346 https://cdc-nbs.atlassian.net/browse/CNFT1-1347
* [CNT-25](https://cdc-nbs.atlassian.net/browse/CNT-25)
[CNT-25]: https://cdc-nbs.atlassian.net/browse/CNT-25?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Lab Report Search, program area and jurisdiction

- apps/modernization-ui/src/apps/page-builder/pages/AddNewPage/AddNewPage.tsx
- testing/regression/cypress/e2e/pages/create-page/pageElements.page.js
Fixed the report failure for Create New Page end to end test cases.
* [CNT-24](https://cdc-nbs.atlassian.net/browse/CNT-24)
[CNT-24]: https://cdc-nbs.atlassian.net/browse/CNT-24?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CNT-24] - Create New Page Report fix

- apps/modernization-ui/src/apps/page-builder/page/library/PageLibrary.tsx
- apps/modernization-ui/src/apps/page-builder/page/library/page-library.module.scss
- apps/modernization-ui/src/apps/patient/profile/investigation/PatientInvestigation.ts
- apps/modernization-ui/src/apps/patient/profile/investigation/PatientInvestigationsTable.spec.tsx
- apps/modernization-ui/src/apps/patient/profile/investigation/PatientInvestigationsTable.tsx
Changing order of Events Investigation table to match Open Investigations tab.
* [CNFT1-2277](https://cdc-nbs.atlassian.net/browse/CNFT1-2277)
[CNFT1-2277]: https://cdc-nbs.atlassian.net/browse/CNFT1-2277?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CNFT1-2277 Update Events Investigation table

- apps/modernization-ui/src/apps/page-builder/page/management/edit/content/PageSideMenu.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/section/manage/AddSection.tsx
- testing/regression/cypress/e2e/features/create-page/createNewPage.feature
- testing/regression/cypress/e2e/features/create-page/pageElements.feature
- testing/regression/cypress/e2e/features/edit-page/addSection.feature
- testing/regression/cypress/e2e/features/page-library/dataElements.feature
- testing/regression/cypress/e2e/features/page-library/pagination.feature
- testing/regression/cypress/e2e/features/page-library/searchAndFilter.feature
- testing/regression/cypress/e2e/features/page-library/sort.feature
- testing/regression/cypress/e2e/pages/edit-page/addSection.page.js
- testing/regression/cypress/step_definitions/edit-page/addSection.steps.js
Added end to end test case for add a section ( [CNFT2-1775](https://cdc-nbs.atlassian.net/browse/CNFT2-1775) )
[CNFT2-1775]: https://cdc-nbs.atlassian.net/browse/CNFT2-1775?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CNT-26]  - Add a section e2e test case

- apps/modernization-ui/src/apps/search/advancedSearch/AdvancedSearch.spec.tsx
- apps/modernization-ui/src/apps/search/advancedSearch/AdvancedSearch.tsx
- apps/modernization-ui/src/components/ButtonActionMenu/ButtonActionMenu.spec.tsx
- apps/modernization-ui/src/components/ButtonActionMenu/ButtonActionMenu.tsx
- apps/modernization-ui/src/components/ButtonActionMenu/buttonActionMenu.module.scss
Here we create the ButtonActionMenu component.
Implemented in Advanced Search "Add new" button.
* [CNFT1-2214](https://cdc-nbs.atlassian.net/browse/CNFT1-2214)
[CNFT1-2214]: https://cdc-nbs.atlassian.net/browse/CNFT1-2214?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CNFT1-2214 ButtonActionMenu

- testing/regression/cypress/e2e/pages/page-library/searchAndFilter.page.js
> [CNT-26] - Report failure fix

- testing/regression/cypress/e2e/features/lab-report-general-info.feature
- testing/regression/cypress/e2e/pages/searchEvent.page.js
- testing/regression/cypress/step_definitions/searchEvent.steps.js
CNFT1-1346, CNFT1-1347, CNFT1-1348, CNFT1-1349, CNFT1-1350, CNFT1-1351, CNFT1-1352, CNFT1-1353, CNFT1-1354, CNFT1-1355 all for Lab Report General Information Search
* [Jira Ticket](url) https://cdc-nbs.atlassian.net/browse/CNFT1-1346 (https://cdc-nbs.atlassian.net/browse/CNFT1-1347) https://cdc-nbs.atlassian.net/browse/CNFT1-134
> Lab report tests search general date range

- testing/regression/cypress/e2e/features/edit-page/manageSection.feature
- testing/regression/cypress/e2e/pages/edit-page/manageSection.page.js
Added end to end test case to verify edit or rename an existing section ( [CNFT2-1805](https://cdc-nbs.atlassian.net/browse/CNFT2-1805) )
[CNFT2-1805]: https://cdc-nbs.atlassian.net/browse/CNFT2-1805?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CNT-26] -E2E for edit or rename an existing section

- testing/regression/cypress/e2e/features/edit-page/manageSection.feature
Added end to end test case to delete a section from Manage section without subsections and questions ( [CNFT2-1806](https://cdc-nbs.atlassian.net/browse/CNFT2-1806) )
[CNFT2-1806]: https://cdc-nbs.atlassian.net/browse/CNFT2-1806?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CNT-26] - E2E to delete a section from Manage section without subsections and questions

- apps/modernization-ui/src/apps/page-builder/components/TabGroup/tab-group.module.scss
- apps/modernization-ui/src/apps/search/advancedSearch/AdvancedSearch.tsx
Ensuring all Tab elements are consistent (not including the Welcome Page tab navigation)
* [CNFT1-2219)](https://cdc-nbs.atlassian.net/browse/CNFT1-2219)
> CNFT1-2219 Tab UI

- testing/regression/cypress/e2e/features/search-investigation-criteria.feature
- testing/regression/cypress/e2e/features/search-investigation-general-info.feature
Correct asserts for test environment
> Correct asserts for event test environment

- testing/regression/cypress/e2e/features/edit-page/manageSection.feature
Added end to end test for adding a section for manage section ( CNFT2-1809 )
> [CNT-26] - E2E test to add a section for manage section

- apps/modernization-ui/src/apps/search/advancedSearch/AdvancedSearch.spec.tsx
- apps/modernization-ui/src/components/ButtonActionMenu/ButtonActionMenu.tsx
- apps/modernization-ui/src/components/ButtonActionMenu/buttonActionMenu.module.scss
Fixing a small spacing issue with ButtonActionMenu
* [CNFT1-2214](https://cdc-nbs.atlassian.net/browse/CNFT1-2214)
[CNFT1-2214]: https://cdc-nbs.atlassian.net/browse/CNFT1-2214?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CNFT1-2214 ButtonActionMenu (1)

- testing/regression/cypress/e2e/features/profile.feature
- testing/regression/cypress/e2e/pages/search.results.page.js
Fix Add Patient and Basic Info
> Add new patient test fixes

- libs/authentication/src/main/java/gov/cdc/nbs/authentication/NbsUserDetails.java
- libs/options-api/src/test/java/gov/cdc/nbs/option/facility/autocomplete/FacilityOptionMother.java
Fixes the last two code smells found by Sonar as of 06/03/2024.
https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&id=CDCgov_NEDSS-Modernization&open=AY936DKmJNA0uynLx35-
https://sonarcloud.io/project/issues?open=AY_PuVLJUj-H8srGeoGO&id=CDCgov_NEDSS-Modernization
> [Sonar] Addresses remaining sonar smells

- apps/modernization-ui/src/components/SideNavigation/SideNavigation.scss
Updating SideNavigation styling
* [CNFT1-2218](https://cdc-nbs.atlassian.net/browse/CNFT1-2218)
[CNFT1-2218]: https://cdc-nbs.atlassian.net/browse/CNFT1-2218?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CNFT1-2218 Side nav styling

- apps/modernization-ui/src/apps/page-builder/components/AddQuestion/AddQuestion.tsx
- apps/modernization-ui/src/apps/page-builder/components/AddQuestion/fields/BasicInformationFields.tsx
- apps/modernization-ui/src/apps/page-builder/components/AddQuestion/fields/DataMartFields.tsx
- apps/modernization-ui/src/apps/page-builder/page/library/table/PageLibraryTable.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/add-question/search/QuestionSearch.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/add-question/search/table/QuestionSearchTable.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/edit-question/EditQuestionModal.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/question/QuestionHeader.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/subsection/SubsectionHeader.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/preview/PreviewPage.tsx
- apps/modernization-ui/src/components/SegmentedButtons/SegmentedButtons.tsx
- testing/regression/cypress/e2e/features/edit-page/addEditSearchDeleteQuestion.feature
- testing/regression/cypress/e2e/pages/edit-page/addEditSearchDeleteQuestion.page.js
- testing/regression/cypress/e2e/pages/edit-page/addSection.page.js
- testing/regression/cypress/e2e/pages/edit-page/deleteSection.page.js
- testing/regression/cypress/e2e/pages/edit-page/manageSection.page.js
- testing/regression/cypress/step_definitions/edit-page/addEditSearchDeleteQuestion.steps.js
Added end to end test case for create a text question ( [CNFT2-1818](https://cdc-nbs.atlassian.net/browse/CNFT2-1818) )
[CNFT2-1818]: https://cdc-nbs.atlassian.net/browse/CNFT2-1818?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CNT-30] - Create a question (Text Only)

- testing/regression/cypress/e2e/features/edit-page/addEditSearchDeleteQuestion.feature
Added end to end test case for editing a question ( [CNFT2-1820](https://cdc-nbs.atlassian.net/browse/CNFT2-1820) )
[CNFT2-1820]: https://cdc-nbs.atlassian.net/browse/CNFT2-1820?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CNT-30] - E2E for Edit new question created

- testing/regression/cypress/e2e/features/lab-report-criteria.feature
- testing/regression/cypress/e2e/pages/searchEvent.page.js
- testing/regression/cypress/step_definitions/searchEvent.steps.js
Search LabReport event by Coded Result/Organism and Resulted Test
* [CNFT1-1356][CNFT1-1357](https://cdc-nbs.atlassian.net/browse/CNFT1-1356) https://cdc-nbs.atlassian.net/browse/CNFT1-1357
[CNFT1-1356]: https://cdc-nbs.atlassian.net/browse/CNFT1-1356?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Search LabReport event by Coded Result/Organism and Resulted Test

- apps/modernization-ui/src/apps/page-builder/components/DeleteQuestion/DeleteQuestion.tsx
- apps/modernization-ui/src/confirmation/ConfirmationModal.tsx
- testing/regression/cypress/e2e/features/edit-page/addEditSearchDeleteQuestion.feature
- testing/regression/cypress/e2e/pages/edit-page/addEditSearchDeleteQuestion.page.js
- testing/regression/cypress/step_definitions/edit-page/addEditSearchDeleteQuestion.steps.js
Added end to end test case to create a question using same Unique ID (text only) ( [CNFT2-1821](https://cdc-nbs.atlassian.net/browse/CNFT2-1821) )
[CNFT2-1821]: https://cdc-nbs.atlassian.net/browse/CNFT2-1821?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CNT-30] - Create a question using same Unique ID (test only)

- testing/regression/cypress/e2e/features/edit-page/addEditSearchDeleteQuestion.feature
- testing/regression/cypress/e2e/pages/edit-page/addEditSearchDeleteQuestion.page.js
Added end to end test case to delete a question ( [CNFT2-1823](https://cdc-nbs.atlassian.net/browse/CNFT2-1823) )
* [CNT-30]](https://cdc-nbs.atlassian.net/browse/CNT-30)
[CNFT2-1823]: https://cdc-nbs.atlassian.net/browse/CNFT2-1823?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CNT-30] - E2E to delete a question

- testing/regression/cypress/e2e/features/add-patient.feature
- testing/regression/cypress/e2e/features/address.feature
- testing/regression/cypress/e2e/features/basic-info.feature
- testing/regression/cypress/e2e/features/contact.feature
- testing/regression/cypress/e2e/features/create-page/createNewPage.feature
- testing/regression/cypress/e2e/features/create-page/pageElements.feature
- testing/regression/cypress/e2e/features/edit-page/addEditSearchDeleteQuestion.feature
- testing/regression/cypress/e2e/features/edit-page/addSection.feature
- testing/regression/cypress/e2e/features/edit-page/deleteSection.feature
- testing/regression/cypress/e2e/features/edit-page/manageSection.feature
- testing/regression/cypress/e2e/features/events.feature
- testing/regression/cypress/e2e/features/id.feature
- testing/regression/cypress/e2e/features/lab-report-criteria.feature
- testing/regression/cypress/e2e/features/lab-report-general-info.feature
- testing/regression/cypress/e2e/features/page-library/dataElements.feature
- testing/regression/cypress/e2e/features/page-library/pagination.feature
- testing/regression/cypress/e2e/features/page-library/searchAndFilter.feature
- testing/regression/cypress/e2e/features/page-library/sort.feature
- testing/regression/cypress/e2e/features/patient-profile-Investigation.feature
- testing/regression/cypress/e2e/features/patient-profile-summary.feature
- testing/regression/cypress/e2e/features/profile.feature
- testing/regression/cypress/e2e/features/race.feature
- testing/regression/cypress/e2e/features/search-investigation-criteria.feature
- testing/regression/cypress/e2e/features/search-investigation-general-info.feature
- testing/regression/cypress/e2e/pages/events/add-lab-report-investigation.page.js
- testing/regression/cypress/e2e/pages/login.page.js
Multi environment login setup for cypress. Test Regression handles new and legacy login.
> multi environment login setup for cypress

- testing/regression/cypress/e2e/features/edit-page/addEditSearchDeleteQuestion.feature
Added end to end test to verify inactive question is not searchable ( [CNFT2-1835](https://cdc-nbs.atlassian.net/browse/CNFT2-1835) )
[CNFT2-1835]: https://cdc-nbs.atlassian.net/browse/CNFT2-1835?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CNT-30] - E2E to verify inactive question is not searchable

- testing/regression/cypress/e2e/features/edit-page/addEditSearchDeleteQuestion.feature
Added end to end test to create a question without a Unique ID ( [CNFT2-1847](https://cdc-nbs.atlassian.net/browse/CNFT2-1847) )
[CNFT2-1847]: https://cdc-nbs.atlassian.net/browse/CNFT2-1847?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CNT-30] - Create a question without a Unique ID

- testing/regression/cypress/e2e/features/edit-page/addEditSearchDeleteQuestion.feature
Added end to end test to create a question using Field type (Numeric) ( [CNFT2-1848](https://cdc-nbs.atlassian.net/browse/CNFT2-1848) )
[CNFT2-1848]: https://cdc-nbs.atlassian.net/browse/CNFT2-1848?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CNT-30] - E2E to create a question using Field type (Numeric)

- testing/regression/cypress/e2e/features/id.feature
Automate the regression test scripts for Patient Search : Patient Search by ID types
https://cdc-nbs.atlassian.net/browse/CNFT1-1293, https://cdc-nbs.atlassian.net/browse/CNFT1-1294, https://cdc-nbs.atlassian.net/browse/CNFT1-1295, https://cdc-nbs.atlassian.net/browse/CNFT1-1296, https://cdc-nbs.atlassian.net/browse/CNFT1-1297, https://cdc-nbs.atlassian.net/browse/CNFT1-1298, https://cdc-nbs.atlassian.net/browse/CNFT1-1299, https://cdc-nbs.atlassian.net/browse/CNFT1-1300, https://cdc-nbs.atlassian.net/browse/CNFT1-1301, https://cdc-nbs.atlassian.net/browse/CNFT1-1302, https://cdc-nbs.atlassian.net/browse/CNFT1-1303, https://cdc-nbs.atlassian.net/browse/CNFT1-1304, https://cdc-nbs.atlassian.net/browse/CNFT1-1305, https://cdc-nbs.atlassian.net/browse/CNFT1-1306, …
> Test for all select options by id search

- testing/regression/cypress/e2e/features/edit-page/addEditSearchDeleteQuestion.feature
- testing/regression/cypress/e2e/pages/create-page/pageElements.page.js
Added end to end test to create a question using Field type (Date picker) and (Valueset) [CNFT2-1853](https://cdc-nbs.atlassian.net/browse/CNFT2-1853) [CNFT2-1855](https://cdc-nbs.atlassian.net/browse/CNFT2-1855)
[CNFT2-1853]: https://cdc-nbs.atlassian.net/browse/CNFT2-1853?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CNFT2-1855]: https://cdc-nbs.atlassian.net/browse/CNFT2-1855?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CNT-30] - Create a question using Field type (Date picker) (Valueset)

- apps/modernization-ui/src/components/SideNavigation/SideNavigation.scss
Minor padding update for side nav.
* [CNFT1-2218](https://cdc-nbs.atlassian.net/browse/CNFT1-2218)
[CNFT1-2218]: https://cdc-nbs.atlassian.net/browse/CNFT1-2218?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CNFT1-2218 Side nav padding

- apps/modernization-ui/src/apps/page-builder/components/TabGroup/tab-group.module.scss
- apps/modernization-ui/src/apps/page-builder/page/management/preview/information/page-information.module.scss
Small spacing updates to Tabs
* [CNFT1-2219](https://cdc-nbs.atlassian.net/browse/CNFT1-2219)
[CNFT1-2219]: https://cdc-nbs.atlassian.net/browse/CNFT1-2219?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CNFT1-2219 Tabs UI updates

- apps/modernization-ui/src/apps/search/advancedSearch/AdvancedSearch.tsx
- apps/modernization-ui/src/components/ButtonActionMenu/buttonActionMenu.module.scss
Updating Sort by button to ButtonActionMenu
* [CNFT1-2214](https://cdc-nbs.atlassian.net/browse/CNFT1-2214)
[CNFT1-2214]: https://cdc-nbs.atlassian.net/browse/CNFT1-2214?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CNFT1-2214 ButtonActionMenu Sort by

- apps/modernization-ui/src/apps/page-builder/page/management/edit/section/SectionHeader.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/subsection/SubsectionHeader.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/subsection/manage/AddSubSection.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/subsection/manage/ManageSubsection.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/subsection/manage/ManageSubsectionTile/ManageSubsectionTile.tsx
- apps/modernization-ui/src/confirmation/ConfirmationModal.tsx
- testing/regression/cypress/e2e/features/edit-page/subsection/manageSubsection.feature
- testing/regression/cypress/e2e/pages/edit-page/subsection/manageSubsection.page.js
- testing/regression/cypress/step_definitions/edit-page/subsection/manageSubsection.steps.js
Added end to end test to manage subsections 
[CNFT2-1912](https://cdc-nbs.atlassian.net/browse/CNFT2-1912)
[CNFT2-1913](https://cdc-nbs.atlassian.net/browse/CNFT2-1913)
[CNFT2-1914](https://cdc-nbs.atlassian.net/browse/CNFT2-1914)
[CNFT2-1915](https://cdc-nbs.atlassian.net/browse/CNFT2-1915)
* [CNT-32](https://cdc-nbs.atlassian.net/browse/CNT-32)
[CNFT2-1912]: https://cdc-nbs.atlassian.net/browse/CNFT2-1912?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CNFT2-1913]: https://cdc-nbs.atlassian.net/browse/CNFT2-1913?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU …
> [CNT-32] - E2E - Manage subsection - Edit/ delete/ hide/unhide subsection

- testing/regression/cypress/e2e/features/edit-page/subsection/manageSubsection.feature
- testing/regression/cypress/e2e/pages/edit-page/subsection/manageSubsection.page.js
- testing/regression/cypress/step_definitions/edit-page/subsection/manageSubsection.steps.js
Added end to end test for adding new subsection ( [CNFT2-1916](https://cdc-nbs.atlassian.net/browse/CNFT2-1916) )
* [CNT-32](https://cdc-nbs.atlassian.net/browse/CNT-32)
[CNFT2-1916]: https://cdc-nbs.atlassian.net/browse/CNFT2-1916?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CNT-32]: https://cdc-nbs.atlassian.net/browse/CNT-32?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CNT-32] CNFT2-1916 add new subsection

- testing/regression/cypress/e2e/features/edit-page/subsection/manageSubsection.feature
- testing/regression/cypress/e2e/pages/edit-page/subsection/manageSubsection.page.js
- testing/regression/cypress/step_definitions/edit-page/subsection/manageSubsection.steps.js
Added end to end test for 6 dot icon on manage subsection( [CNFT2-1918](https://cdc-nbs.atlassian.net/browse/CNFT2-1918) )
* [CNT-32](https://cdc-nbs.atlassian.net/browse/CNT-32)
[CNFT2-1918]: https://cdc-nbs.atlassian.net/browse/CNFT2-1918?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CNT-32]: https://cdc-nbs.atlassian.net/browse/CNT-32?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CNT-32] - E2E for 6 dot icon on manage subsection

- apps/modernization-ui/src/apps/page-builder/page/management/preview/PreviewPage.tsx
- testing/regression/cypress/e2e/pages/edit-page/addEditSearchDeleteQuestion.page.js
- testing/regression/cypress/e2e/pages/edit-page/addSection.page.js
- testing/regression/cypress/e2e/pages/edit-page/deleteSection.page.js
- testing/regression/cypress/e2e/pages/edit-page/manageSection.page.js
- testing/regression/cypress/e2e/pages/edit-page/subsection/manageSubsection.page.js
> Regresion test fixes for draft mode in page builder

- testing/regression/cypress/e2e/pages/edit-page/addEditSearchDeleteQuestion.page.js
- testing/regression/cypress/e2e/pages/edit-page/manageSection.page.js
Fixed few reports failures
* [CNT-32](https://cdc-nbs.atlassian.net/browse/CNT-32)
[CNT-32]: https://cdc-nbs.atlassian.net/browse/CNT-32?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CNT-32] - Reports failure fix

- apps/modernization-ui/src/apps/page-builder/page/management/edit/Edit.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/question/GroupQuestion/Create/GroupQuestion.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/question/GroupQuestion/RepeatingBlock.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/question/GroupQuestion/SubsectionDetails.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/question/GroupQuestion/Update/UpdateGroupedQuestion.tsx
- apps/modernization-ui/src/apps/page-builder/page/management/edit/subsection/SubsectionHeader.tsx
- testing/regression/cypress/e2e/features/edit-page/grouping/groupAndUngroupQuestions.feature
- testing/regression/cypress/e2e/pages/edit-page/grouping/groupAndUngroupQuestions.page.js
- testing/regression/cypress/step_definitions/edit-page/grouping/groupAndUngroupQuestions.steps.js
Added end to end test cases for the grouping and ungrouping questions below scenario
[CNFT2-1967](https://cdc-nbs.atlassian.net/browse/CNFT2-1967) - Ungroup questions - Ungroup
[CNFT2-1987](https://cdc-nbs.atlassian.net/browse/CNFT2-1987) - Edit Group questions default view
[CNFT2-1988](https://cdc-nbs.atlassian.net/browse/CNFT2-1988) - Edit Group questions make changes and save
[CNFT2-1993](https://cdc-nbs.atlassian.net/browse/CNFT2-1993) - Group questions - end to end flow
* [CNT-34](https://cdc-nbs.atlassian.net/browse/CNT-34)
[CNFT2-1967]: https://cdc-nbs.atlassian.net/browse/CNFT2-1967?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CNFT2-1987]: https://cdc-nbs.atlassian.net/browse/CNFT2-1987?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y …
> [CNT-34] - E2E tests for Group Ungroup Questions

- testing/regression/cypress/e2e/features/edit-page/manageSection.feature
- testing/regression/cypress/e2e/features/edit-page/subsection/manageSubsection.feature
- testing/regression/cypress/e2e/pages/edit-page/manageSection.page.js
- testing/regression/cypress/e2e/pages/edit-page/subsection/manageSubsection.page.js
Fixed reports failures for Page Builder
* [CNT-34](https://cdc-nbs.atlassian.net/browse/CNT-34)
[CNT-34]: https://cdc-nbs.atlassian.net/browse/CNT-34?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CNT-34] report failure fix

- cdc-sandbox/keycloak/imports/nbs-users.json
- cdc-sandbox/keycloak/theme/nbs/login/messages/messages_en.properties
Enable T&C in the config file and make it the default.  Isolate the terms verbiage in the resource file and update that with "CDC terms..." before getting the final copy
* [CNFT1-2458](https://cdc-nbs.atlassian.net/browse/CNFT1-2458)
[CNFT1-2458]: https://cdc-nbs.atlassian.net/browse/CNFT1-2458?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CNFT1-2458 Keycloak Terms and Conditions

- apps/modernization-ui/src/apps/page-builder/condition/search/ConditionSearch.tsx
- apps/modernization-ui/src/apps/page-builder/pages/AddNewPage/AddNewPageFields.tsx
- testing/regression/cypress/e2e/features/advanced-condition-search/pagination.feature
- testing/regression/cypress/e2e/features/advanced-condition-search/rowSelection.feature
- testing/regression/cypress/e2e/features/advanced-condition-search/searchAndFilter.feature
- testing/regression/cypress/e2e/pages/advanced-condition-search/pagination.page.js
- testing/regression/cypress/e2e/pages/advanced-condition-search/rowSelection.page.js
- testing/regression/cypress/e2e/pages/advanced-condition-search/searchAndFilter.page.js
- testing/regression/cypress/step_definitions/advanced-condition-search/pagination.steps.js
- testing/regression/cypress/step_definitions/advanced-condition-search/rowSelection.steps.js
- testing/regression/cypress/step_definitions/advanced-condition-search/searchAndFilter.steps.js
Added end to end tests for Advanced condition search - Pagination, Row selection, Search and Filter
Automated CNFT2-1233, CNFT2-1236, CNFT2-1238, CNFT2-1239, CNFT2-1227, CNFT2-1228 tests
* [CNT-34](https://cdc-nbs.atlassian.net/browse/CNT-34)
[CNT-34]: https://cdc-nbs.atlassian.net/browse/CNT-34?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CNT-34] - Advanced condition search - Pagination, Row selection, Search and Filter

- testing/regression/cypress/e2e/features/advanced-condition-search/addCondition.feature
- testing/regression/cypress/e2e/features/advanced-condition-search/sorting.feature
- testing/regression/cypress/e2e/pages/advanced-condition-search/addCondition.page.js
- testing/regression/cypress/e2e/pages/advanced-condition-search/sorting.page.js
- testing/regression/cypress/step_definitions/advanced-condition-search/addCondition.steps.js
- testing/regression/cypress/step_definitions/advanced-condition-search/sorting.steps.js
Added end to end test for advanced condition search - Add Condition and Sorting
[CNFT2-1242](https://cdc-nbs.atlassian.net/browse/CNFT2-1242)
[CNFT2-1433](https://cdc-nbs.atlassian.net/browse/CNFT2-1433)
* [CNT-34](https://cdc-nbs.atlassian.net/browse/CNT-34)
[CNFT2-1242]: https://cdc-nbs.atlassian.net/browse/CNFT2-1242?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CNFT2-1433]: https://cdc-nbs.atlassian.net/browse/CNFT2-1433?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CNT-34]: https://cdc-nbs.atlassian.net/browse/CNT-34?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CNT-34] - Advanced condition search - Add Condition and Sorting

- apps/modernization-ui/src/design-system/autocomplete/index.ts
- apps/modernization-ui/src/design-system/autocomplete/multi/AutocompleteMulti.tsx
- apps/modernization-ui/src/design-system/autocomplete/single/Autocomplete.tsx
- apps/modernization-ui/src/design-system/select/multi/MultiSelect.tsx
Adds an Autocomplete component that allows selection of multiple items.
```typescript
const resolver = (criteria: string, limit?: number) =>
ConditionOptionsService.complete({
criteria: criteria,
limit: limit
}).then((response) => response);
...
<AutocompleteMulti id="conditions" name="conditions" label="Conditions" resolver={resolver} />
```
> [Design system] Autocomplete multi

- apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/page/content/staticelement/ReadOnlyCommentsSteps.java
- apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/page/summary/download/PageSummaryDownloadSteps.java
Resolves the 3 outstanding code smells
> Code smell fixes

- apps/modernization-ui/src/generated/index.ts
- apps/modernization-ui/src/generated/services/JurisdictionOptionsService.ts
- apps/modernization-ui/src/generated/services/ProgramAreaOptionsService.ts
- libs/options-api/src/main/java/gov/cdc/nbs/option/jurisdictions/autocomplete/JurisdictionOptionAutocompleteController.java
- libs/options-api/src/main/java/gov/cdc/nbs/option/jurisdictions/autocomplete/JurisdictionOptionResolver.java
- libs/options-api/src/main/java/gov/cdc/nbs/option/program/area/autocomplete/ProgramAreaOptionAutocompleteController.java
- libs/options-api/src/main/java/gov/cdc/nbs/option/program/area/autocomplete/ProgramAreaOptionResolver.java
- libs/options-api/src/test/java/gov/cdc/nbs/option/AutocompleteRequester.java
- libs/options-api/src/test/java/gov/cdc/nbs/option/jurisdiction/JurisdictionMother.java
- libs/options-api/src/test/java/gov/cdc/nbs/option/jurisdiction/JurisdictionOptionSteps.java
- libs/options-api/src/test/java/gov/cdc/nbs/option/jurisdiction/autocomplete/JurisdictionAutocompleteSteps.java
- libs/options-api/src/test/java/gov/cdc/nbs/option/program/area/ProgramAreaMother.java
- libs/options-api/src/test/java/gov/cdc/nbs/option/program/area/ProgramAreaOptionSteps.java
- libs/options-api/src/test/java/gov/cdc/nbs/option/program/area/autocomplete/ProgramAreaAutocompleteSteps.java
- libs/options-api/src/test/resources/features/jurisdictions/JurisdictionOptions.feature
- libs/options-api/src/test/resources/features/program-areas/ProgramAreaOptions.feature
- Adds the Autocomplete API for Program Areas at `nbs/api/options/program-areas/search`
- Adds the Autocomplete API for Jurisdictions at `nbs/api/options/jurisdictions/search`
> Options API Jurisdictions and Program Areas

- apps/modernization-ui/src/apps/search/patient/PatientCriteria/Contact.spec.tsx
- apps/modernization-ui/src/apps/search/patient/PatientCriteria/Contact.tsx
- apps/modernization-ui/src/apps/search/patient/PatientCriteria/PatientCriteria.tsx
- apps/modernization-ui/src/apps/search/patient/PatientCriteria/contact.module.scss
- apps/modernization-ui/src/apps/search/patient/PatientSearch.tsx
New branch to avoid conflicts
Adding Contact fields to Patient Search.
* [CNFT1-2433](https://cdc-nbs.atlassian.net/browse/CNFT1-2433)
[CNFT1-2433]: https://cdc-nbs.atlassian.net/browse/CNFT1-2433?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Cnft1 2433 patient search criteria contact

- apps/modernization-ui/src/apps/page-builder/components/AddQuestion/fields/MessagingFields.tsx
- testing/regression/cypress/e2e/features/question-library/createNewQuestion.feature
- testing/regression/cypress/e2e/features/question-library/pagination.feature
- testing/regression/cypress/e2e/features/question-library/sort.feature
- testing/regression/cypress/e2e/pages/question-library/createNewQuestion.page.js
- testing/regression/cypress/e2e/pages/question-library/pagination.page.js
- testing/regression/cypress/e2e/pages/question-library/sort.page.js
- testing/regression/cypress/step_definitions/question-library/createNewQuestion.steps.js
- testing/regression/cypress/step_definitions/question-library/pagination.steps.js
- testing/regression/cypress/step_definitions/question-library/sort.steps.js
Added end to end tests for Question Library - Create new Question, Pagination and sorting
* [CNT-35](https://cdc-nbs.atlassian.net/browse/CNT-35)
[CNT-35]: https://cdc-nbs.atlassian.net/browse/CNT-35?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CNT-35] - Questions Library - Create new question, pagination and sorting
