CDCgov/NEDSS-Modernization

patient-search/api/src/main/java/gov/cdc/nbs/service/PatientService.java
patient-search/api/src/test/java/gov/cdc/nbs/PatientSearchSteps.java
patient-search/api/src/test/java/gov/cdc/nbs/support/PersonMother.java
patient-search/api/src/test/java/gov/cdc/nbs/support/util/RandomUtil.java
patient-search/api/src/test/resources/features/PatientSearch.feature

Feature specs for testing with partial searches of the form `'string*'` using first name and/or last name and/or address and/or city.  The legacy code code did a `like 'searchstring%'` in the database.  
To achieve this we use https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html with a wildcard query `'string*'` 
NOTE: defaulting to `'*string*' `wildcard search is counterintuitive.  Ie searching for 'it' yielding 'Smith'.  If we want to support wildcard searches we can intercept wildcards in the search string and support them accordingly.  For now defaulting to matching the first characters including spaces (and also full match) with no added input text will be on parity with legacy.
```
gradlew clean -i …
```

CNPT-121 wildcard search testing

---

patient-search/api/src/main/java/gov/cdc/nbs/entity/odse/Person.java
patient-search/api/src/main/java/gov/cdc/nbs/message/KafkaMessageSerializer.java
patient-search/api/src/main/java/gov/cdc/nbs/service/KafkaRequestProducerService.java
patient-search/api/src/main/java/gov/cdc/nbs/service/PatientService.java
patient-search/api/src/test/java/gov/cdc/nbs/RedirectSteps.java
patient-search/api/src/test/java/gov/cdc/nbs/services/KafkaProducerTest.java
patient-search/api/src/test/java/gov/cdc/nbs/services/PatientUpdateTest.java

In this PR:
1. In the updates I made to get some of the redirects to work better with Kubernetes, I neglected to updated the redirect test cases. So this updates those test cases with the correct paths.
2. This also removes the `@ToString` annotation from the Person class. This broke the patient search as the toString was triggering recursively due to self referencing fields in the entity.
3. Resolves some small java warnings (unused imports, mock of deprecated method).
4. Fixes a spelling error in the `KafkaRequestProducerService`

Fix test case

---

patient-search/ui/src/pages/advancedSearch/components/LabReportResults.tsx

Demo environment is not displaying patient information for lab reports;
The issue is the UI is searching for a `personParticipation` where `typeDescTxt` = 'Patient subject', but the data does not have that field as our dev environment does. 
This PR updates the search to look for where `typeCd` = 'PATSBJ'

Update personParticipation search criteria to find subject of lab report

---

patient-search/api/src/main/java/gov/cdc/nbs/config/KafkaConfig.java
patient-search/api/src/main/resources/application.yml

When deploying to demo environment the following error was displayed:
The patient delete template was missing. This PR adds it as well as moving the config into a separate method to reduce duplicate code.

Fix boot issue with KafkaTemplate<String, PatientDeleteRequest>

---

cdc-sandbox/Dockerfile-antbuild

There was a patch release of maven `3.8` increasing the  version from `3.8.6` to `3.8.7`.  The binaries for `3.8.6` were no longer available causing the building of NBC Classic via `cdc-sandbox/build.sh` to fail.  Build arguments were introduced to reduce having to keep the version numbers the same through the script.

updates Maven 3.8.6 to 3.8.7

---

.dockerignore
.github/workflows/dockerfile-to-ecr.yaml
apps/modernization-api/Dockerfile
apps/modernization-api/README.md
apps/modernization-api/build.gradle
apps/modernization-api/src/main/resources/application.yml
apps/modernization-api/src/test/resources/application-test.yml
docker-compose.yml

Changed the `modernization-api` container to pull the `elasticsearch`, 'nbs-mssql`, and 'wildfly` configuration from Spring Config sources (i.e environment variables, java system properties).  
Reduces the build context of the `modernization-api` by excluding the `cdc-sandbox` directory.  This can be removed in the future if the gradle project is moved into a sibling folder of `cdc-sandbox`.
Reduces the size of the resulting `modernization-api` image by only including the files required to run the application.  This can further reduced if needed with a more precise base image for the application container.

Modernization-api externalized configuration

---

apps/modernization-api/build.gradle
apps/modernization-api/src/main/java/gov/cdc/nbs/service/PatientService.java
apps/modernization-api/src/test/java/gov/cdc/nbs/PatientSearchSteps.java
apps/modernization-api/src/test/java/gov/cdc/nbs/support/util/PersonUtil.java
apps/modernization-api/src/test/resources/features/PatientSearch.feature

Make the default operator `and` instead of `or` to require all the `-` and `@` separated values.  ie searching for 123-456-7890 could return phones with just 123 before (and appeared to be returning all phones when in actuality it was just phones in that area code).  This also allows searching by say area code 123 if that is the query string.
Added soundex search API capability.  Decided new analyzer wasn't needed in elasticsearch.  Legacy already has a populated soundex field.  Pass that through and key off of it in the api.  In the api require that the fname/lname searches satisfy at least one of a traditional or soundex match (logical OR ie `should`)

CNPT-948 CNPT-946 CNFT1-187 fix phone,email search,add soundex

---

apps/modernization-api/src/main/resources/graphql/user.graphqls
apps/modernization-ui/src/generated/gql/queries/findAllUsers.gql
apps/modernization-ui/src/generated/graphql/schema.ts
apps/modernization-ui/src/generated/schema.graphqls
apps/modernization-ui/src/pages/advancedSearch/components/eventSearch/GeneralSearch.tsx
apps/modernization-ui/src/pages/advancedSearch/components/eventSearch/LabGeneralSearch.tsx

When querying for Events that were created by or last updated by a user, the `nedssEntryId` needs to be used instead of the `userId`.
Successful search after update.

Use nedssEntryId instead of userId to query for created by / updated by

---

apps/modernization-api/src/main/java/gov/cdc/nbs/graphql/filter/PatientFilter.java
apps/modernization-api/src/main/java/gov/cdc/nbs/service/PatientService.java
apps/modernization-api/src/main/resources/graphql/patient.graphqls
apps/modernization-api/src/test/java/gov/cdc/nbs/PatientSearchSteps.java
apps/modernization-api/src/test/java/gov/cdc/nbs/PermissionSteps.java
apps/modernization-api/src/test/java/gov/cdc/nbs/services/PatientUpdateTest.java
apps/modernization-api/src/test/java/gov/cdc/nbs/support/PersonMother.java
apps/modernization-api/src/test/resources/features/PatientSearch.feature
apps/modernization-ui/src/generated/graphql/schema.ts
apps/modernization-ui/src/generated/schema.graphqls
apps/modernization-ui/src/pages/advancedSearch/AdvancedSearch.tsx
apps/modernization-ui/src/pages/advancedSearch/components/patientSearch/PatientSearch.spec.tsx
apps/modernization-ui/src/pages/advancedSearch/components/patientSearch/PatientSearch.tsx
apps/modernization-ui/src/pages/patientProfile/PatientProfile.tsx
apps/modernization-ui/src/pages/simpleSearch/SimpleSearch.tsx
libs/authentication/src/main/java/gov/cdc/nbs/service/UserService.java
libs/database-entities/src/main/java/gov/cdc/nbs/entity/enums/converter/RecordStatus.java

The current Patient Search API only allows a single `RecordStatus`. The new UI designs allow multi select for `RecordStatus`
This PR adds support for multiple `RecordStatus`, at least 1 is required for all queries.

Patient search/multiple record status

---

libs/database-entities/src/main/java/gov/cdc/nbs/entity/elasticsearch/ElasticsearchPerson.java
libs/database-entities/src/main/java/gov/cdc/nbs/entity/enums/converter/SuffixConverter.java
libs/database-entities/src/main/java/gov/cdc/nbs/entity/enums/converter/SuffixStringConverter.java
libs/database-entities/src/main/java/gov/cdc/nbs/entity/odse/NBSEntity.java
libs/database-entities/src/main/java/gov/cdc/nbs/patient/SuffixStringConverter.java
libs/database-entities/src/main/java/gov/cdc/nbs/patient/search/ElasticsearchSuffixConverter.java
libs/database-entities/src/test/java/gov/cdc/nbs/entity/odse/PersonTest.java
libs/database-entities/src/test/java/gov/cdc/nbs/patient/SuffixStringConverterTest.java
libs/database-entities/src/test/java/gov/cdc/nbs/patient/search/ElasticsearchSuffixConverterTest.java

There were at least two issues found that could cause an error in the `findPatientsByFilter` Query resulting in search pages being "skipped" when clicked.
- Corrects how the locator id was being set for Entity Locators Participations
- Adds a Suffix converter for Elasticseach results that will disregard unknown suffix values instead of throwing an error.
The invalid Suffix values were most likely introduce by anonymization of the data.

CNFT1 156/search pages skipping

---

apps/modernization-api/build.gradle
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/contact/ContactNamedByPatientResolver.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/contact/PatientContactsByPatientResolver.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/contact/PatientNamedByContactResolver.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/document/PatientDocument.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/document/PatientDocumentByPatientResolver.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/document/PatientDocumentFinder.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/treatment/PatientTreatmentByPatientResolver.java
apps/modernization-api/src/main/resources/graphql/patient-contact.graphqls
apps/modernization-api/src/main/resources/graphql/patient-document.graphqls
apps/modernization-api/src/main/resources/graphql/patient-treatment.graphqls
apps/modernization-api/src/test/java/gov/cdc/nbs/identity/TestIdentityModule.java
apps/modernization-api/src/test/java/gov/cdc/nbs/identity/TestUniqueIdGenerator.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/PatientProfileSteps.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/TestPatientCleaner.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/TestPatients.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/document/DocumentMother.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/document/PatientDocumentSteps.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/document/TestDocumentCleaner.java
apps/modernization-api/src/test/resources/application-test.yml
apps/modernization-api/src/test/resources/features/patient/PatientProfileDocuments.feature
apps/modernization-ui/src/generated/gql/queries/findDocumentsForPatient.gql
apps/modernization-ui/src/generated/gql/queries/index.js
apps/modernization-ui/src/generated/graphql/schema.ts
apps/modernization-ui/src/generated/schema.graphqls
libs/database-entities/src/main/java/gov/cdc/nbs/entity/odse/Act.java

Adds the GraphQL query 'findDocumentsForPatient' to return documents associated with a patient. 
```graphql
query documents($patient :ID!) {
findDocumentsForPatient(patient: $patient) {
document
receivedOn
type
sendingFacility
reportedOn
condition
event    
associatedWith {
id
local 
}
}
}
```
The caller of the query must have the FIND-PATIENT and VIEW-DOCUMENT authorities.

CNFT1 601 Patient documents graphql api

---

libs/database-entities/src/main/java/gov/cdc/nbs/entity/odse/EntityLocatorParticipation.java
libs/database-entities/src/main/java/gov/cdc/nbs/entity/odse/PostalEntityLocatorParticipation.java
libs/database-entities/src/main/java/gov/cdc/nbs/entity/odse/TeleEntityLocatorParticipation.java

Addresses were not displaying on patient search results due to the `classCd` property always being null.  Previously, entityLocatorParticipations with address would have a `classCd` with a value of `PST`.
The `EntityLocatorParticipation` was changed to use Single Table Inheritance with the `classCd` being the property that determines which implementation is returned.  When this change was made the `classCd` getter was removed.  This adds a getter for `classCd` that returns the same value used to determine the implementation.

CNFT1-721/ensures that classCd is returned to the client

---

apps/modernization-api/src/main/java/gov/cdc/nbs/patient/treatment/PatientTreatmentByPatientResolver.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/treatment/PatientTreatmentFinder.java
apps/modernization-api/src/main/resources/graphql/patient-treatment.graphqls
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/treatment/PatientTreatmentByPatientResolverTest.java
apps/modernization-ui/src/components/Table/Table.spec.tsx
apps/modernization-ui/src/components/Table/Table.tsx
apps/modernization-ui/src/generated/gql/queries/findTreatmentsForPatient.gql
apps/modernization-ui/src/generated/graphql/schema.ts
apps/modernization-ui/src/generated/schema.graphqls
apps/modernization-ui/src/pages/patientProfile/Events.tsx
apps/modernization-ui/src/pages/patientProfile/PatientProfile.tsx
apps/modernization-ui/src/patient/profile/treatment/PatientTreatmentTable.spec.tsx
apps/modernization-ui/src/patient/profile/treatment/PatientTreatmentTable.tsx
apps/modernization-ui/src/patient/profile/treatment/index.ts
gradle/libs.versions.toml

Adds pagination to the result of the `findTreatmentsForPatient` query and ensures that the provider is included on the response.
```graphql
query treatments($patient: ID!, $page: Page) {
findTreatmentsForPatient(patient: $patient, page: $page) {
content {
treatment
createdOn
provider
treatedOn
description
event
associatedWith {
id
local
condition
}
}
total
}
}
```

CNFT1 711/ api integration treatments provider entry

---

README.md
cdc-sandbox/docker-compose.yml
cdc-sandbox/proxy/providers.yml

Changes the sandbox reverse proxy to resolve the host name of the `modernization-api` and `modernization-ui` from environment variables.  This would allow routing from sandboxed reverse proxy to a locally running `modernization-api` and `modernization-ui` instance.
For example, if the `modernization-api` was started locally as follows;
```shell
./gradlew :modernization-api:bootRun --args='--server.port=9080'
```
then starting the reverse proxy by running this command from the `cdc-sandbox` folder
```shell
MODERNIZATION_API_SERVER=host.docker.internal MODERNIZATION_API_PORT=9080 docker compose up -d reverse-proxy
```
---
Details on the configuration (and how to reset to defaults) have been added to the [README](https://github.com/CDCgov/NEDSS-Modernization/tree/configurable_traefik#configur …

Allows sandbox proxy to use local ui and/or backend servers

---

apps/modernization-api/src/main/java/gov/cdc/nbs/patient/kafka/KafkaProducer.java

The property `kafkadef.topics.request.patient` was renamed to `kafkadef.topics.patient.request` the change in `KafkaProducer` may have been lost in a merge.

corrects name of request topic property

---

apps/modernization-api/src/main/java/gov/cdc/nbs/controller/EncryptionController.java
apps/modernization-api/src/main/java/gov/cdc/nbs/controller/ExportController.java
apps/modernization-api/src/main/java/gov/cdc/nbs/controller/RedirectController.java

This PR fixes some startup warnings by adding the `dataTypeClass` to `@ApiImplicitParam` annotations.
The warnings:

Add  to @ApiImplicitParam annotations

---

apps/modernization-api/src/main/java/gov/cdc/nbs/patient/document/PatientDocumentByPatientResolver.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/document/PatientDocumentFinder.java
apps/modernization-api/src/main/resources/graphql/patient-document.graphqls
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/document/PatientDocumentSteps.java
apps/modernization-ui/src/components/Table/Table.tsx
apps/modernization-ui/src/generated/gql/queries/findDocumentsForPatient.gql
apps/modernization-ui/src/generated/graphql/schema.ts
apps/modernization-ui/src/generated/schema.graphqls
apps/modernization-ui/src/pages/advancedSearch/components/eventSearch/SearchCriteria.spec.tsx
apps/modernization-ui/src/pages/patientProfile/Events.tsx
apps/modernization-ui/src/pages/patientProfile/PatientProfile.tsx
apps/modernization-ui/src/patient/profile/document/PatientDocumentSorter.spec.ts
apps/modernization-ui/src/patient/profile/document/PatientDocumentSorter.ts
apps/modernization-ui/src/patient/profile/document/PatientDocumentTable.spec.tsx
apps/modernization-ui/src/patient/profile/document/PatientDocumentTable.tsx
apps/modernization-ui/src/patient/profile/document/PatientDocumentTransformer.spec.ts
apps/modernization-ui/src/patient/profile/document/PatientDocumentTransformer.ts
apps/modernization-ui/src/patient/profile/document/PatientDocuments.ts
apps/modernization-ui/src/patient/profile/document/index.ts
apps/modernization-ui/src/sorting/Sort.ts
apps/modernization-ui/src/sorting/index.ts

Implements the features of [CNFT1-693](https://cdc-nbs.atlassian.net/browse/CNFT1-693) by displaying a patient's documents on the Patient Profile.  In a local development environment user `10023357` has many documents.
Paging was also added to the Patient Documents API
```graphql
query documents($patient: ID!, $page: Page) {
findDocumentsForPatient(patient: $patient, page: $page) {
content {
document
receivedOn
type
sendingFacility
reportedOn
condition
event
associatedWith {
id
local
}
}
total
}
}
```
Documents are paged when more then 10 results are returned.
Documents can be sorted.
[CNFT1-693]: https://cdc-nbs.atlassian.net/browse/CNFT1-693?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT1 693 documents table api

---

cdc-sandbox/Dockerfile-antbuild

When building fresh, the following error occurs when building the Wildfly container:
Change to using the maven amazoncorretto 8 docker image resolves this issue

Maven version 3.8.7 not found

---

cdc-sandbox/docker-compose.yml

When setting up the local environment, elasticsearch is using 6+ Gb of memory with no data. This change will set the default limit to 2Gb.
@szamfir, will this change affect the deployed environments?

Elasticsearch memory default

---

apps/modernization-api/README.md
apps/modernization-api/src/test/java/gov/cdc/nbs/containers/NbsElasticsearchContainer.java
apps/modernization-api/src/test/java/gov/cdc/nbs/containers/database/NbsDatabaseContainer.java
apps/modernization-api/src/test/resources/application-test.yml

Reduce elasticsearch test container memory usage. Use local test db until ECR config is resolved.
Pre-req to running tests is to build test-db image.

Use local test db image

---

apps/modernization-api/src/main/java/gov/cdc/nbs/patient/profile/vaccination/PatientVaccinationFinder.java

vaccination finder will now use parent id to include vaccinations for all child records.  The query to find all vaccinations was using the person id over the parent id.  it's still unclear as so when a new person record is created over using an existing person record.

CNFT1-747 Vaccination for patient API find by parent

---

apps/modernization-ui/src/page/index.ts
apps/modernization-ui/src/page/page.tsx
apps/modernization-ui/src/pages/patientProfile/Events.tsx
apps/modernization-ui/src/patient/profile/contact/ContactNamedByPatientTable.spec.tsx
apps/modernization-ui/src/patient/profile/contact/PatientNamedByContactTable.spec.tsx
apps/modernization-ui/src/patient/profile/contact/PatientNamedByContactTable.tsx
apps/modernization-ui/src/patient/profile/document/PatientDocumentContainer.tsx
apps/modernization-ui/src/patient/profile/document/PatientDocumentTable.spec.tsx
apps/modernization-ui/src/patient/profile/document/PatientDocumentTable.tsx
apps/modernization-ui/src/patient/profile/document/PatientProfileDocuments.spec.tsx
apps/modernization-ui/src/patient/profile/document/PatientProfileDocuments.tsx
apps/modernization-ui/src/patient/profile/document/index.ts
apps/modernization-ui/src/patient/profile/document/usePatientProfileDocumentsAPI.ts
apps/modernization-ui/src/patient/profile/treatment/PatientTreatmentTable.spec.tsx

Refactors the Patient Profile Documents components to decouple API calls from the display component.  This pattern will allow re-usability of components for Patient Profile and Patient Merge Review.
This also fixes some of the failing tests from the Patient Profile tables by making the tests less reliable on the expected HTML structure.

Refactor patient profile documents for reuse

---

apps/modernization-api/src/main/java/gov/cdc/nbs/geo/state/SimpleStateTupleMapper.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/profile/address/PatientAddressFinder.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/profile/birth/PatientBirthFinder.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/profile/mortality/PatientMortalityFinder.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/profile/summary/PatientSummaryFinder.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/profile/summary/PatientSummaryTupleMapper.java
apps/modernization-api/src/test/java/gov/cdc/nbs/geo/state/SimpleStateTupleMapperTest.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/address/PatientAddressTupleMapperTest.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/birth/PatientBirthTupleMapperTest.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/mortality/PatientMortalityTupleMapperTest.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/summary/PatientSummaryTupleMapperTest.java

Implements features of [CNFT1-809](https://cdc-nbs.atlassian.net/browse/CNFT1-809) by changing the state description returned by the Patient Profile API's from the full state name to the two character state name.
The source of the state name is changed however the data structure has not changed.  There is no changed required in the `modernization-ui` for users of the API.
[CNFT1-809]: https://cdc-nbs.atlassian.net/browse/CNFT1-809?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT1-809 changes state description from full name to two character name

---

apps/modernization-api/src/main/java/gov/cdc/nbs/geo/county/SimpleCountyTupleMapper.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/profile/address/PatientAddressFinder.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/profile/birth/PatientBirth.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/profile/birth/PatientBirthFinder.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/profile/birth/PatientBirthTupleMapper.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/profile/mortality/PatientMortality.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/profile/mortality/PatientMortalityFinder.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/profile/mortality/PatientMortalityTupleMapper.java
apps/modernization-api/src/main/resources/graphql/patient-profile.graphqls
apps/modernization-api/src/test/java/gov/cdc/nbs/geo/county/SimpleCountyTupleMapperTest.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/address/PatientAddressTupleMapperTest.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/address/PatientProfileAddressSteps.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/birth/PatientBirthTupleMapperTest.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/birth/PatientProfileBirthSteps.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/identification/PatientProfileIdentificationSteps.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/mortality/PatientMortalityTupleMapperTest.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/mortality/PatientProfileMortalitySteps.java
apps/modernization-api/src/test/resources/features/patient/PatientProfileAddress.feature
apps/modernization-api/src/test/resources/features/patient/PatientProfileBirth.feature
apps/modernization-api/src/test/resources/features/patient/PatientProfileIdentification.feature
apps/modernization-api/src/test/resources/features/patient/PatientProfileMortality.feature
apps/modernization-ui/src/components/Table/Table.spec.tsx
apps/modernization-ui/src/generated/gql/queries/findPatientProfile.gql
apps/modernization-ui/src/generated/graphql/schema.ts
apps/modernization-ui/src/generated/schema.graphqls

Adds missing fields to Birth and Mortality Demographics
Birth:
- Birth Order
- Birth County
Mortality:
- Death County
Changes the source of the county description from `code_short_desc_txt` to `code_desc_txt` so that a county name is displayed without the State abbreviation.  For example; `Iron` over `Iron, UT`
Fixes the TableComponent test to account for the sorting buttons being disabled when only one row exists.

Demographics api missed fields

---

apps/modernization-api/src/main/java/gov/cdc/nbs/patient/profile/treatment/ViewTreatmentRedirector.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/treatment/PatientProfileViewTreatmentSteps.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/treatment/PatientTreatmentSteps.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/treatment/TestTreatmentCleaner.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/treatment/TestTreatments.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/treatment/TreatmentMother.java
apps/modernization-api/src/test/resources/features/patient/profile/PatientProfileTreatment.feature
apps/modernization-ui/src/pages/patient/profile/treatment/PatientTreatmentTable.tsx
documentation/Routing.md
libs/database-entities/src/main/java/gov/cdc/nbs/entity/odse/Act.java
libs/database-entities/src/main/java/gov/cdc/nbs/entity/odse/ActRelationship.java
libs/database-entities/src/main/java/gov/cdc/nbs/entity/odse/Treatment.java
libs/database-entities/src/main/java/gov/cdc/nbs/entity/odse/TreatmentAdministered.java

Implements features of [CNFT1-856](https://cdc-nbs.atlassian.net/browse/CNFT1-856) by adding an endpoint to support viewing a Treatment from the Modernized Patient Profile.  Treatments can only be viewed from the Patient Profile.  Returning from the Classic NBS Treatment uses the redirection that is already in place for `ContextAction=ReturnToFileEvents`
*Routing will only work in a local development environment*
- Adds the endpont GET /nbs/api/profile/{patient}/treatment/{identifier} which prepares the Classic NBS Session to view a Treatment and then returns a redirect response with the url the client will navigate to  view a Treatment in Classic NBS. The identifier of the patient is added as the value of the Returning-Patient cookie.
Code was added to the `database-entities` library …

CNFT1-856/ Patient Profile Treatments Navigation

---

apps/modernization-api/src/main/java/gov/cdc/nbs/patient/profile/document/ViewDocumentRedirector.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/document/TestDocuments.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/document/PatientProfileViewDocumentSteps.java
apps/modernization-api/src/test/resources/features/patient/PatientProfileDocuments.feature
apps/modernization-ui/src/pages/patient/profile/document/PatientDocumentContainer.tsx
apps/modernization-ui/src/pages/patient/profile/document/PatientDocumentTable.spec.tsx
apps/modernization-ui/src/pages/patient/profile/document/PatientDocumentTable.tsx
apps/modernization-ui/src/pages/patient/profile/document/PatientProfileDocuments.spec.tsx
apps/modernization-ui/src/pages/patient/profile/document/PatientProfileDocuments.tsx
apps/modernization-ui/src/pages/patientProfile/Events.tsx

Implements features of [CNFT1-857](https://cdc-nbs.atlassian.net/browse/CNFT1-857) by adding an endpoint to support viewing a Document from the Modernized Patient Profile.  Documents can only be viewed from the Patient Profile.  Returning from the Classic NBS Document uses the redirection that is already in place for `ContextAction=ReturnToFileEvents`
*Routing will only work in a local development environment*
- Adds the endpont GET /nbs/api/profile/{patient}/document/{identifier} which prepares the Classic NBS Session to view a Document and then returns a redirect response with the url the client will navigate to  view a Document in Classic NBS. The identifier of the patient is added as the value of the Returning-Patient cookie.
[CNFT1-857]: …

CNFT1-857/ Patient Profile Documents Navigation

---

apps/modernization-api/src/main/java/gov/cdc/nbs/patient/create/PatientCreatedEmitter.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/create/PatientCreator.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/PatientCreateAssertions.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/create/PatientCreatedEmitterTest.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/event/PatientEventSteps.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/address/PatientProfileAddressSteps.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/identification/PatientProfileIdentificationSteps.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/names/PatientProfileNameSteps.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/phone/PatientProfileEmailSteps.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/phone/PatientProfilePhoneSteps.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/race/PatientProfileRaceSteps.java
apps/modernization-api/src/test/resources/features/patient/PatientCreate.feature
apps/patient-listener/src/test/java/gov/cdc/nbs/patientlistener/request/update/PatientUpdaterTest.java
libs/database-entities/src/main/java/gov/cdc/nbs/entity/odse/NBSEntity.java
libs/database-entities/src/main/java/gov/cdc/nbs/entity/odse/Person.java
libs/database-entities/src/test/java/gov/cdc/nbs/entity/odse/PersonTest.java
libs/event-schema/src/main/java/gov/cdc/nbs/message/enums/Deceased.java
libs/event-schema/src/main/java/gov/cdc/nbs/message/enums/Gender.java
libs/event-schema/src/main/java/gov/cdc/nbs/message/enums/Suffix.java
libs/event-schema/src/main/java/gov/cdc/nbs/message/patient/event/PatientEvent.java

Implements the features requested in [CNFT1-1032](https://cdc-nbs.atlassian.net/browse/CNFT1-1032) by emitting an event when a patient is created. The event is only emitted if Kafka is enabled on the `modernization-api`.
The emitted event will have the key set to the patient localId and the value is the Patient Created Event serialized into a JSON format.
A Patient created via the mutation
```json
{
"query": "mutation createPatient($patient:PersonInput!){createPatient(patient:$patient){id shortId}}",
"variables": {
"patient": {
"comments": "Created for Development testing",
"asOf": "2022-05-05T00:01:02Z",
"names": [
{
"use": "L",
"first": "Cory",
"last": "Wolf-Hart"
}
]
}
}
}
```
Will result in a `PatientEvent$Created` in the following format;
```json
{
"type": "PatientEvent$Created", …
```

Cnft1 1032 emit a patient create event on kafka

---

apps/modernization-api/src/main/java/gov/cdc/nbs/codes/CountryCodedValueFinder.java
apps/modernization-api/src/main/java/gov/cdc/nbs/codes/CountyCodedValueFinder.java
apps/modernization-api/src/main/java/gov/cdc/nbs/codes/DetailedRaceFinder.java
apps/modernization-api/src/main/java/gov/cdc/nbs/codes/GeneralCodedValueFinder.java
apps/modernization-api/src/main/java/gov/cdc/nbs/codes/PrimaryLanguageValueSetFinder.java
apps/modernization-api/src/main/java/gov/cdc/nbs/codes/PrimaryOccupationValueSetFinder.java
apps/modernization-api/src/main/java/gov/cdc/nbs/codes/StateCodedValueFinder.java
apps/modernization-api/src/main/resources/graphql/coded-values.graphqls

Implements the feature defined by [CNFT1-1049](https://cdc-nbs.atlassian.net/browse/CNFT1-1049) by ensuring that the Race Category names have proper noun capitalization.  Also, ordering of the value sets is now controlled by the `indent_level_nbr`
[CNFT1-1049]: https://cdc-nbs.atlassian.net/browse/CNFT1-1049?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT1-1049/ Removes standard formatting from Race list

---

.github/workflows/sonar.yaml

Removes the push trigger from the Sonar workflow.  Frequent pushes (good practice!) with many developers is causing the workflow actions to queue for long periods of time.

Removes the push trigger for sonar

---

.github/workflows/sonar.yaml

Inspired by the Quarter 2 Demo I looked into publishing the reports generated during testing by `junit`, `jacoco`, and `cucumber`.

Publishing of test report artifacts

---

apps/modernization-api/src/main/java/gov/cdc/nbs/redirect/outgoing/ClassicOutgoingLoggingHttpRequestInterceptor.java
apps/modernization-api/src/main/java/gov/cdc/nbs/redirect/outgoing/ClassicRestTemplateConfiguration.java
apps/modernization-api/src/main/resources/application.yml

Adds very basic logging to the outgoing requests to NBS Classic so that communication from `modernization-api` to NBS Class can be verified using the log.
Any request from `modernization-api` directly to NBS Classic will be logged to the `nbs.classic.outgoing` logger as ` {http-method} {path}       Response: {response-status}`.  For example;
```
2023-07-06 13:23:08.973 DEBUG 10388 --- [nio-9080-exec-9] nbs.classic.outgoing                     : GET /nbs/HomePage.do       Response: 200 OK
2023-07-06 13:23:09.094 DEBUG 10388 --- [nio-9080-exec-9] nbs.classic.outgoing                     : GET /nbs/PatientSearchResults1.do  Response: 200 OK
```
The level of the logging can be changed using the standard logging properties, the default level has been set to `DEBUG` for the meantime.
```yaml …
```

CNFT1-1094 Logging calls to NBS Classic

---

cdc-sandbox/README.md

Small addition to the README file within the cdc_sandbox, for better understanding of how to store the db restore files in the correct path.

Ab sandbox readme update

---

apps/modernization-api/src/main/java/gov/cdc/nbs/patient/PatientService.java

**Why**: A patient's current legal name should always come first in the search results
**How**: 
1) Since soundex is not available on the Person table any soundex matches on Person_name are giving a cumulative boost to that patient.  In addition there is no need to ever boost soundex results currently.  We need to ensure that one soundex or an aggregate of soundex names will never override the patient legal name or secondary names in the search ordering.
2) We also don't want a secondary aggregate set of names to override legal name.  Make the boost on primary even greater to override the boost effects of secondary (10x greater)

1164 - Remove any boost from soundex so it comes last in search results

---

apps/modernization-api/src/main/java/gov/cdc/nbs/codes/CountryCodedValueFinder.java
apps/modernization-api/src/main/java/gov/cdc/nbs/codes/CountyCodedValueFinder.java
apps/modernization-api/src/main/java/gov/cdc/nbs/codes/StateCodedValueFinder.java

Addresses [CNFT1-1180](https://cdc-nbs.atlassian.net/browse/CNFT1-1180) by removing the `StandardNameFormatter` from the county, state, and country lists.  This will allow the lists to be returned the way they are entered in the database.
[CNFT1-1180]: https://cdc-nbs.atlassian.net/browse/CNFT1-1180?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT1-1180 removes formatting from County, State, and Country lists

---

apps/modernization-ui/src/config.js
apps/modernization-ui/src/index.tsx
apps/modernization-ui/src/providers/UserContext.tsx
apps/modernization-ui/src/routes/AppRoutes.tsx
apps/modernization-ui/src/shared/header/NavBar.tsx
apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/config/WebSecurityConfig.java

1. Hide modernized login page behind config.
2. When logout is clicked, redirect to `/nbs/logOut` to match legacy

Hide new login page. Redirect to NBS logout page

---

apps/modernization-api/src/main/java/gov/cdc/nbs/patient/profile/investigation/PatientInvestigationFinder.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/profile/investigation/PatientInvestigationResolver.java
apps/modernization-api/src/main/java/gov/cdc/nbs/service/SecurityService.java
apps/modernization-api/src/test/java/gov/cdc/nbs/investigation/InvestigationMother.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/investigation/PatientInvestigationResolverTest.java
apps/modernization-api/src/test/java/gov/cdc/nbs/service/SecurityServiceTest.java

[BBJ12-3](https://cdc-nbs.atlassian.net/browse/BBJ12-3)
Investigations displayed on a patient profile do not check for user program area / jurisdictions. This was causing Classic™ to throw an error when trying to view the investigation details for an investigation the user should not have access to.
Pertusis Investigation:
After fix:
User lacks `VPD` program area:
After adding `VPD` program area to user:
[BBJ12-3]: https://cdc-nbs.atlassian.net/browse/BBJ12-3?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add `programJurisdictionOid` check to investigation query

---

apps/modernization-api/src/main/java/gov/cdc/nbs/patient/profile/birth/PatientBirthFinder.java
apps/modernization-api/src/main/resources/graphql/coded-values.graphqls
apps/modernization-api/src/main/resources/graphql/patient-profile.graphqls
apps/modernization-ui/src/generated/graphql/schema.ts
apps/modernization-ui/src/generated/schema.graphqls
apps/modernization-ui/src/pages/patient/profile/coded/ProfileCodedValue.ts
apps/modernization-ui/src/pages/patient/profile/coded/maybeDescription.ts
apps/modernization-ui/src/pages/patient/profile/coded/maybeId.ts
apps/modernization-ui/src/pages/patient/profile/identification/identification.ts

Resolved [BBJ12-23](https://cdc-nbs.atlassian.net/browse/BBJ12-23) by making the types in the patient-profile GraphQL Schema stronger.  All of the properties with coded values use the same type `PatientCodedValue` there was an `id` field that was causing the Apollo cache to return invalid values.  
For example, the Gender coded value for male would be returned as 
```json
{
"id": "M",
"description": "Male"
}
```
and the Marital Status coded value for married would be returned as 
```json
{
"id": "M",
"description": "Married"
}
```
Apollo would populate the cache with whichever value was pulled first, which seemed to be Male.
An alternate approach would be to add a property to `PatientCodedValue` that contained a more unique key.  This would have resulted in many more file changes. …

BBJ12-23 / Defines specific types to resolving frontend caching issues

---

apps/modernization-api/src/main/java/gov/cdc/nbs/patient/search/SearchablePatientConverter.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/search/SearchablePatientConverterTest.java

Resolves [BBJ12-34](https://cdc-nbs.atlassian.net/browse/BBJ12-34) by adding Identifications to the `SearchablePatietnConverter` so that changes to a patient's identifications are reflected when searching.
[BBJ12-34]: https://cdc-nbs.atlassian.net/browse/BBJ12-34?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

BBJ12-34 / ensure identifications are indexed when added to a patient

---

apps/modernization-ui/src/pages/advancedSearch/AdvancedSearch.tsx
apps/modernization-ui/src/pages/advancedSearch/components/eventSearch/EventSearch.tsx
apps/modernization-ui/src/pages/advancedSearch/components/eventSearch/GeneralSearch.tsx

The condition names are indexed into ES:
So we need to search by name not by Id for conditions. There is an ongoing effort to move away from Elasticsearch for Investigation queries so I did not update the indexing to include the Ids
Post fix:

Update to use condition name in search instead of Id

---

apps/modernization-api/src/main/java/gov/cdc/nbs/patient/profile/investigation/PatientInvestigation.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/profile/investigation/PatientInvestigationTupleMapper.java
apps/modernization-api/src/main/resources/graphql/patient-investigation.graphqls
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/investigation/PatientInvestigationTupleMapperTest.java
apps/modernization-ui/src/generated/graphql/schema.ts
apps/modernization-ui/src/generated/schema.graphqls
apps/modernization-ui/src/pages/patient/profile/investigation/PatientInvestigationTransformer.spec.ts
apps/modernization-ui/src/pages/patient/profile/investigation/PatientInvestigationTransformer.ts
apps/modernization-ui/src/pages/patient/profile/investigation/PatientInvestigationsTable.spec.tsx
apps/modernization-ui/src/pages/patient/profile/investigation/PatientOpenInvestigationsTable.spec.tsx

Resolves [BBJ12-40](https://cdc-nbs.atlassian.net/browse/BBJ12-40) by returning the Investigation started on date as a local date from the API and applies the `asLocalDate` function on the UI.  
[BBJ12-40]: https://cdc-nbs.atlassian.net/browse/BBJ12-40?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

BBJ12-40 Returns Investigation started on as a LocalDate

---

apps/modernization-api/src/main/java/gov/cdc/nbs/patient/document/PatientDocumentByPatientResolver.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/document/PatientDocumentFinder.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/document/DocumentMother.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/document/PatientDocumentSteps.java
apps/modernization-api/src/test/resources/features/patient/PatientProfileDocuments.feature
apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/page/AddQuestionToPageSteps.java
apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/support/ExceptionHolder.java

Fixes the issue outlined in [BBJ12-48](https://cdc-nbs.atlassian.net/browse/BBJ12-48) by adding the `program_area_jurisdiction` WHERE clause to the select statement for documents associated with a patient.
Classic™  documents listed for profile:
Modernized documents listed for profile:
Assigned another document a program area and jurisdiction for patient:
Classic™ documents now listed:
Modernized documents:
[BBJ12-48]: https://cdc-nbs.atlassian.net/browse/BBJ12-48?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add program_area_jurisdiction_oid where clause to document fetch

---

apps/modernization-api/src/main/java/gov/cdc/nbs/patient/PatientService.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/PatientSearchSteps.java
apps/modernization-api/src/test/java/gov/cdc/nbs/support/util/ElasticsearchPersonMapper.java
libs/database-entities/src/main/java/gov/cdc/nbs/entity/elasticsearch/ElasticsearchPerson.java

**Why**: Legal name was doing an exact match previously.  So when we searched by prefix (ie "Smi" for "Smith") the legal name was not getting boosted unless it was an exact match.  Moreover the exact match was case sensitive.  Note the legal name always had a nested name so it would still get LAST_NAME_NON_PRIMARY_BOOST but that is significantly less than LAST_NAME_PRIMARY_BOOST.  Finally legal name was set for a keyword search and should have been a text search.
**How**: Use QueryBuilders.queryStringQuery w/wildcard and downcase similar to all the nested searches. 
NOTE1: to do partial searches on legal name we need to convert the field type to text and set fielddata to true.  It was set to keyword for performance purposes (heap space) for sorting - when alphabetical sort (vs relevance) …

CNFT1-1432 CNFT1-1230 Switch legal name search to query string query

---

apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/question/QuestionCreator.java
apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/question/QuestionCreatorTest.java
apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/support/QuestionRequestMother.java

[CNFT2-728](https://cdc-nbs.atlassian.net/browse/CNFT2-728)
If the user specifies an Id when creating a 'LOCAL' question, use the specified Id.
[CNFT2-728]: https://cdc-nbs.atlassian.net/browse/CNFT2-728?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT2-728 Allow user to specify Id for LOCAL question

---

.github/workflows/Build-and-deploy-modernization-api.yaml
.github/workflows/sonar.yaml

This change is similar to the previous one that passes in secrets that are otherwise missing. This should be the last of them.
One more significant change is to solidify the intention behind this change. If sonar does not run or fails, then the container build will fail.

fix build pipeline and create dependency on sonar running first

---

apps/nbs-gateway/src/main/java/gov/cdc/nbs/gateway/patient/search/PatientSearchRouteLocatorConfiguration.java
apps/nbs-gateway/src/test/java/gov/cdc/nbs/gateway/patient/search/PatientSearchServiceLocatorConfigurationTest.java
documentation/Routing.md

Removes the routing rule that is preventing navigation to Manual Merge.
Path is exactly `/nbs/MyTaskList.do` containing the Query Parameter `ContextAction` with a value of `GlobalMP_ManualSearch` and the Query Parameter `Model1` with a value of `ManualMerge` >>
`/nbs/redirect/advancedSearch`

Removes the routing rules that prevent navigation to Manual Merge

---

apps/modernization-api/src/main/java/gov/cdc/nbs/patient/identifier/PatientIdentifierFinder.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/profile/redirect/incoming/IncomingPatientIdentifierResolver.java
apps/modernization-ui/src/pages/patient/profile/PatientProfile.tsx
apps/modernization-ui/src/pages/patient/profile/summary/PatientProfileSummary.tsx

Resolves [CNFT1-1518](https://cdc-nbs.atlassian.net/browse/CNFT1-1518) by removing the record status requirement on the `PatientIdentifierFinder`
- A `PatientIdentifier` can now be found for patients of any status.
- A Patient's status is displayed on the Patient Profile when the status is anything other than ACTIVE.
[CNFT1-1518]: https://cdc-nbs.atlassian.net/browse/CNFT1-1518?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT1-1518 Removes status criteria from PatientIdentifierFinder

---

apps/modernization-ui/src/components/FormInputs/SelectInput.tsx

Changes made to the `SelectInput` prevented the defaultValue property from being applied on the component.  In order for the defaultValue to set to a non null value a new component needs to be created.  
```
{defaultValue && <Wrapped />}
{!defaultValue && <Wrapped />}
```
This was present in the `SelectInput` previously however, it's purpose was not clear. I also tried setting the `key` value to the `defaultValue` however, that did not work.

Fixes the applying of a defaultValue to SelectInput

---

cdc-sandbox/Dockerfile-antbuild

Resolves 404 issue when pulling the ant binaries

Up ant version

---

apps/modernization-api/src/test/java/gov/cdc/nbs/patient/PatientSteps.java

Some Cucumber tests in `modernization-api` were randomly failing due to the clean-up steps happening out of order.  This ensures that patients are cleaned up last.

[FIX] Ensures that patients are cleaned up after everything else in tests

---

apps/modernization-ui/src/apps/page-builder/components/ManageTabs/ManageTabs.scss

When attempting to delete a patient from the Patient Profile a message appears in a modal if the Patient cannot be deleted.  A change to the `.usa-modal__close` style was causing an error that lead to a blank page being shown.  The cause of the error was that there was no component in the modal to focus on since the only component in the `MessageModal` that could have focus was the `X` icon in the upper right.
1. Search for a Patient associated with events
1. Go to the Patient Profile
1. Attempt to delete the Patient

[FIX] Message Modal Display

---

apps/modernization-api/src/main/java/gov/cdc/nbs/web/AddCookie.java
apps/modernization-api/src/main/java/gov/cdc/nbs/web/RemoveCookie.java

The `Return-Patient` cookie is being deleted immediately by the browser due to the `max-age` being set to `-1`.  This is causing the returning links to modernized patient profile to not resolve the patient to return to resulting in navigation to the advanced-search page.
1. Navigate to a Patient Profile
2. In the Events tab
3. Click `Add Investigation`
4. On the add Investigations screen click `Cancel`
5. The correct Patient Profile should display
This can also be tested if a Patient already linked to an Investigation by clicking the Investigation Id, and then clicking the `Return to File Summary` link in the upper right hand corner of the classic Investigation page.

[FIX] Return-Patient cookie

---

apps/modernization-api/src/main/java/gov/cdc/nbs/web/AddCookie.java
apps/modernization-api/src/main/java/gov/cdc/nbs/web/RemoveCookie.java

The `Return-Patient` cookie is being deleted immediately by the browser due to the `max-age` being set to `-1`.  This is causing the returning links to modernized patient profile to not resolve the patient to return to resulting in navigation to the advanced-search page.
1. Navigate to a Patient Profile
2. In the Events tab
3. Click `Add Investigation`
4. On the add Investigations screen click `Cancel`
5. The correct Patient Profile should display
This can also be tested if a Patient already linked to an Investigation by clicking the Investigation Id, and then clicking the `Return to File Summary` link in the upper right hand corner of the classic Investigation page.

[FIX] removes max-age

---

apps/modernization-api/src/main/java/gov/cdc/nbs/event/search/labreport/CodedResultFinder.java
apps/modernization-api/src/main/java/gov/cdc/nbs/event/search/labreport/LabResultController.java
apps/modernization-api/src/main/java/gov/cdc/nbs/event/search/labreport/LabTestController.java
apps/modernization-api/src/main/java/gov/cdc/nbs/event/search/labreport/ResultedTestFinder.java
apps/modernization-api/src/main/resources/graphql/labResult.graphqls
apps/modernization-api/src/main/resources/graphql/labTest.graphqls
apps/modernization-api/src/test/java/gov/cdc/nbs/CodedResultsSearchSteps.java
apps/modernization-api/src/test/java/gov/cdc/nbs/ResultedTestSearchSteps.java
apps/modernization-api/src/test/resources/features/CodedResultsSearch.feature
apps/modernization-api/src/test/resources/features/ResultedTestSearch.feature
apps/modernization-ui/src/generated/gql/queries/findDistinctCodedResults.gql
apps/modernization-ui/src/generated/gql/queries/findDistinctResultedTest.gql
apps/modernization-ui/src/generated/graphql/schema.ts
apps/modernization-ui/src/generated/schema.graphqls
apps/modernization-ui/src/pages/advancedSearch/components/eventSearch/EventSearch.tsx
apps/modernization-ui/src/pages/advancedSearch/components/eventSearch/labReportSearch/LabReportCriteria.tsx
libs/database-entities/src/main/java/gov/cdc/nbs/repository/LabResultRepository.java
libs/database-entities/src/main/java/gov/cdc/nbs/repository/LabTestRepository.java
libs/database-entities/src/main/java/gov/cdc/nbs/repository/LoincCodeRepository.java
libs/database-entities/src/main/java/gov/cdc/nbs/repository/SnomedCodeRepository.java

When searching for Resulted Tests in classic you are able to search on both `local` and `LOINC` codes.
When searching for Coded Results in classic, you are able to search on both `local` and `SNOMED` codes
This PR updates the APIs to search on `Lab_test`, and `LOINC_code` for Resulted Tests, `Lab_result` and `Snomed_code` for Coded Results.
* [CNFT1-1548](https://cdc-nbs.atlassian.net/browse/CNFT1-1548)
1. Log in to NBS
1. Navigate to Advanced search -> Event Search -> Event type `Laboratory report`
1. Under `Resulted Test`, search for `Acid-Fast Stain` -> Verify results
1. Under `Resulted Test`, search for `AMDINOCILLIN` -> Verify results
1. Under `Coded result`, search for `abnormal` -> Verify results
1. Under `Coded result`, search for `No growth` -> Verify results
[CNFT1-1548]: …

CNFT1-1548 search local and other

---

apps/modernization-ui/src/pages/patient/profile/summary/PatientProfileSummary.tsx

Display middle name and suffix in patient profile
https://cdc-nbs.atlassian.net/browse/CNFT1-1436
1. Navigate to Patient profile it should display first, middle, last and suffix in the name field if they are present in summary field
2. create new patient and click view Patient it should display first, middle, last and suffix in the name field if they are present in Summary field

Display middle name and suffix in patient profile

---

cdc-sandbox/docker-compose.yml
cdc-sandbox/nifi/Dockerfile
cdc-sandbox/nifi/nifi_conf/conf/login-identity-providers.xml

The foundations team requested we move the environment variables from the NiFi dockerfile and place them into the docker-compose. This prevents these default environment variables from being present in the NiFi image.
* [CNFT2-1255](https://cdc-nbs.atlassian.net/browse/CNFT2-1255)
1. Manually inspect Dockerfile, verify env vars are removed
2. Run `docker-compose up nifi --build -d` from the cdc-sandbox directory
3. Verify NiFI starts and runs without issue
[CNFT2-1255]: https://cdc-nbs.atlassian.net/browse/CNFT2-1255?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

NiFi remove default password from Dockerfile

---

apps/modernization-ui/src/pages/patient/profile/sexBirth/SexBirth.tsx

Added a DOB for display to the Sex&Birth card in the demographics tab.
CNFT1-1558
1. Login
2. Search for any patient 
3. Navigate to patient profile 
4. navigate towards demographics tab and then towards the sex&birth card and see the DOB added.

adding date of birth to the sex and birth in the demographics tab

---

apps/modernization-api/src/main/java/gov/cdc/nbs/patient/profile/PatientProfile.java
libs/database-entities/src/main/java/gov/cdc/nbs/entity/enums/RecordStatus.java

Incorrect spelling for "Superseded" in patient profile. Change "Superceded" to "Superseded". 
* [CNFT1-1546](https://cdc-nbs.atlassian.net/browse/CNFT1-1546)
1. Visit Advanced Search page
1. Click "Superseded" in the "Include records that are" section.
1. Click "Search" button.
2. Click Patient link to view patient profile and to see Superseded is spelled correctly. 
[CNFT1-1546]: https://cdc-nbs.atlassian.net/browse/CNFT1-1546?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fixed Incorrect spelling Superceded with Superseded in all variations

---

cdc-sandbox/docker-compose.yml

With the change to use the dev database container instead of a test-db, the `test-db` folder was removed. However, the docker-compose entry for `test-db` was not removed. 
This PR removes the unused `test-db` entry.
NA
1. Rebuild everything
2. Run tests
3. Verify all is working as intended

Remove test-db docker-compose

---

.github/workflows/Build-and-deploy-modernization-api.yaml
.github/workflows/sonar.yaml

Updates the trigger for the Build and Deploy modernization api work flow to trigger only for changes to the `modernization-api` or any dependencies.
Updates the trigger for the sonar workflow to not trigger for PRs that only affect the `modernization-ui` due to our Sonar only being able to scan Java projects.

Workflows Modernization

---

apps/modernization-api/src/main/java/gov/cdc/nbs/patient/search/phone/PatientSearchResultPhoneFinder.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/PatientMother.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/PatientSteps.java
apps/modernization-api/src/test/resources/features/patient/search/PatientSearch.feature

Patients that have a phone entry that does not contain a number causes an error that prevents Patient Search Results from loading.  The finder for Patient Search Result phone numbers are adjusted to exclude phone entries without a number value.
* [CNFT1-1560](https://cdc-nbs.atlassian.net/browse/CNFT1-1560)
1. Create a Patient with a name
2. View the Patient Profile
3. Navigate to the Demographics tabs
4. Add a Phone & email entry that contains either a country code or an extension.  (no phone number value)
5. Return to Patient Search
6. Search for the Patient
7. The Patient Search Results should be visible.
[CNFT1-1560]: https://cdc-nbs.atlassian.net/browse/CNFT1-1560?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-1560] fix phone number in search results

---

apps/modernization-ui/src/pages/addPatient/components/LeftBar/LeftBar.tsx

Changing the link in menuItems for Organization and Provider and changing spelling to match with the intention of the action item for clicking on the "Organization", "Provider", and "Morbidity".
Upon receiving feedback from the Design team to rename the menu items in the add patient page due to the fact that the actual "add" portion of the process of navigating to those menu items and adding in the case of "Provider" and "Organization" requires the user to search a provider and select one before actually adding a "Provider" or "Organization".
1. Login
2. Navigate to advanced search
3. Click on add new patient button after making a search
4. click on any of the menu items on the left navbar within the add patient page
5. route to NBS classic as expected.

changing menuItem names and route for link to match flow of NBS

---

apps/modernization-api/build.gradle
gradle/libs.versions.toml

Updates the Graphql dependency to use version `21.3` which does not include a shaded version of Guava that is susceptible to [CVE-2023-2976](https://nvd.nist.gov/vuln/detail/CVE-2023-2976)
* [CNFT1-1665](https://cdc-nbs.atlassian.net/browse/CNFT1-1665)
1.  Ensure that the `modernization-api` container builds by running `docker compose build modernization-api`
[CNFT1-1665]: https://cdc-nbs.atlassian.net/browse/CNFT1-1665?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-1665] Update graphql dependency to exclude guava

---

apps/modernization-ui/src/apps/page-builder/components/AlertBanner/AlertBanner.scss
apps/modernization-ui/src/apps/page-builder/components/AlertBanner/AlertBanner.tsx
apps/modernization-ui/src/apps/page-builder/pages/EditPage/EditPage.scss
apps/modernization-ui/src/apps/page-builder/pages/EditPage/EditPage.tsx

This fixes a bug, where the alert banner does not display above the Edit Page content when Page is successfully saved as Draft.

CNFT2-1284 Add Section overlap Save as Draft

---

.github/workflows/sonar.yaml
gradle/sonar.gradle

There is an issue with the ordering of the `codeCoverageReport` gradle task. It is being executed prior to the modernization-api tests which is greatly reducing the sonar code coverage metrics. 
This updates the way in which we trigger the `codeCoverageReport` task to ensure it goes last.
NA
1. Ensure build succeeds

call codeCoverageReport directly due to bad task ordering

---

apps/modernization-ui/package-lock.json
apps/modernization-ui/src/apps/page-builder/context/ConditionsContext.tsx
apps/modernization-ui/src/apps/page-builder/context/PagesContext.tsx
apps/modernization-ui/src/apps/page-builder/context/QuestionsContext.tsx
apps/modernization-ui/src/apps/page-builder/context/ValueSetContext.tsx
apps/modernization-ui/src/apps/page-builder/context/contextData.ts
apps/modernization-ui/src/apps/page-builder/generated/services/PageControllerService.ts
apps/modernization-ui/src/apps/page-builder/pages/ManagePages/ManagePages.tsx
apps/modernization-ui/src/apps/page-builder/pages/ManagePages/ManagePagesTable.spec.tsx
apps/modernization-ui/src/apps/page-builder/pages/ManagePages/ManagePagesTable.tsx
apps/modernization-ui/src/apps/page-builder/pages/ManagePages/usePageSummaryAPI.ts
apps/modernization-ui/src/apps/page-builder/services/pagesAPI.ts
apps/modernization-ui/src/components/Table/RangeToggle/RangeToggle.tsx

This PR adds error handling to the page library api requests.  It also cleans up some of the copy/paste related to the pagination contexts for each table, and cleans up some errors from using a hook inside of a hook within the RangeToggle component.
1. Use the page size toggle on any table and ensure there are no errors in the console.
2. Manually hard code something into the page search api call that will cause an error. Ensure that the page does not crash and the error is logged in the console.  We will need to add a banner or something in the future for displaying an error to the user.

add-error-handling-to-page-library

---

apps/modernization-ui/src/apps/page-builder/components/Navigation/Navigation.tsx

Corrects the copy and order of the navigation links to each page on the left side of page-builder
* [Jira Ticket](https://cdc-nbs.atlassian.net/jira/software/c/projects/CNFT2/boards/99?assignee=712020%3A591f5469-427d-49e9-87dc-8b4df72a02b4&selectedIssue=CNFT2-1328)
1. Verify the links on the left panel match the figma design (https://www.figma.com/file/Uz9YzHbHQAubHpQTcsibA2/NBS-PageBuilder-2.0?node-id=3398%3A197455&mode=dev)

Reorder Page builder left hand navigation

---

apps/modernization-ui/src/apps/page-builder/pages/AddNewPage/AddNewPage.tsx

Cancel button was missing a handler on the AddNewPage component.  Created one that will navigate back to the previous page.
* [Jira Ticket](https://cdc-nbs.atlassian.net/jira/software/c/projects/CNFT2/boards/99?assignee=712020%3A591f5469-427d-49e9-87dc-8b4df72a02b4&selectedIssue=CNFT2-1335)
1. Navigate to /page-builder/manage/pages
2. Click "Create new page" in the upper right
3. Click cancel at the bottom of the Create New Page form.
4. You should return to the previous page.

BUG/CNFT2-1335/Add New Page cancel button doesn't function

---

apps/modernization-ui/src/apps/page-builder/components/AlertBanner/AlertBanner.scss
apps/modernization-ui/src/apps/page-builder/components/AlertBanner/AlertBanner.tsx
apps/modernization-ui/src/apps/page-builder/pages/ConditionLibrary/ConditionLibrary.tsx
apps/modernization-ui/src/apps/page-builder/pages/EditPage/EditPage.tsx
apps/modernization-ui/src/apps/page-builder/pages/PageBuilder/PageBuilder.scss
apps/modernization-ui/src/apps/page-builder/pages/PageBuilder/PageBuilder.spec.tsx
apps/modernization-ui/src/apps/page-builder/pages/PageBuilder/PageBuilder.tsx
apps/modernization-ui/src/apps/page-builder/pages/PageLibrary/CustomFieldAdminBanner.scss
apps/modernization-ui/src/apps/page-builder/pages/PageLibrary/CustomFieldAdminBanner.tsx
apps/modernization-ui/src/apps/page-builder/pages/PageLibrary/PageLibrary.scss
apps/modernization-ui/src/apps/page-builder/pages/PageLibrary/PageLibrary.tsx
apps/modernization-ui/src/apps/page-builder/pages/QuestionLibrary/QuestionLibrary.tsx
apps/modernization-ui/src/apps/page-builder/pages/ValuesetLibrary/ValuesetLibrary.tsx
apps/modernization-ui/src/styles/_colors.scss

A link to the `Legacy Custom Fields Admin` page needs to be added to the Page Library
Hides the side nav in the `Edit` page
* [CNFT2-1223](https://cdc-nbs.atlassian.net/browse/CNFT2-1223)
1. Navigate to http://localhost:8080/nbs/login
2. Log in as `superuser`
3. Click System Management -> Page Management -> Manage Pages
4. Verify `Custom Fields Admin` banner is displayed
5. Click the link within the banner
6. Verify Classic™ custom fields admin screen is loaded
[CNFT2-1223]: https://cdc-nbs.atlassian.net/browse/CNFT2-1223?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT2-1223 legacy custom fields admin

---

apps/modernization-ui/src/pages/advancedSearch/AdvancedSearch.tsx

Fixing the add new button arrow color and ensuring it displays a white arrow if disabled otherwise it will display blue
NO tickets associated with this fix
1. Provide steps here
1.Navigate to advanced search
2. Make a search for anything 
3. Observe the blue arrow in the add new button in advanced search page

adding a condition to display the arrow in add new button

---

apps/modernization-ui/src/apps/page-builder/components/QuickConditionLookup/QuickConditionLookup.tsx

Quick conditions lookup modal was missing the range selector for the table page size.
* [Jira Ticket](https://cdc-nbs.atlassian.net/jira/software/c/projects/CNFT2/boards/99?assignee=712020%3A591f5469-427d-49e9-87dc-8b4df72a02b4&selectedIssue=CNFT2-1422)
1. Navigate to /page-builder/add/page
2. Click "search or add condition(s)"
3. use the page size selector at the bottom of the table and verify it functions correctly.

Add page range selector to Quick Condition table

---

.dockerignore
apps/modernization-api/Dockerfile
apps/nbs-gateway/Dockerfile
apps/question-bank/Dockerfile

Changes the base image of the Java application from `debian:12-slim` to Red Hat's `ubi9-micro`.  This will reduce the size and attack surface of the containers.  The base `.dockerignore` file was also updated to ensure that files not required for the build are not added to the build context.
1. Rebuild and run all containers with `docker compose up -d --build`
2. Ensure they work 😉

uses ubi9 as runtime base image

---

apps/modernization-ui/src/components/Table/RangeToggle/RangeToggle.scss
apps/modernization-ui/src/components/Table/RangeToggle/RangeToggle.tsx
apps/question-bank/src/main/resources/application.yml

Currently, the values available for selection in the drop-down (bottom left footer) are 10, 25, 50.
The list should be revised to provide the standard values: 10, 20, 30, 50, 100.
* [CNFT2-1334](https://cdc-nbs.atlassian.net/browse/CNFT2-1334)
1. Navigate to page: /page-builder/manage/pages
2. Scroll to the bottom of the page and check the dropdown values for the 'Showing' option
3. Verify that they are in fact: 10, 20, 30, 50, 100
[CNFT2-1334]: https://cdc-nbs.atlassian.net/browse/CNFT2-1334?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT2-1334-revise-row-selection

---

apps/modernization-ui/src/apps/page-builder/components/QuickConditionLookup/QuickConditionLookup.tsx

When accessing Search and add condition(s) modal and viewing the single sentence under the title heading, the period punctuation is missing.
You can search for existing condition(s) or create a new one
* [CNFT2-1406](https://cdc-nbs.atlassian.net/browse/CNFT2-1406)
1. Navigate to /page-builder/manage/pages and click on create a new page
2. Then navigation to the Search and add conditions link and check the punctuation on the title
[CNFT2-1406]: https://cdc-nbs.atlassian.net/browse/CNFT2-1406?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT-1406-puntuation-missing

---

apps/modernization-ui/src/apps/page-builder/generated/services/PageControllerService.ts
apps/modernization-ui/src/apps/page-builder/generated/services/PageRuleControllerService.ts
apps/modernization-ui/src/apps/page-builder/pages/PageLibrary/ManagePagesTable.spec.tsx
apps/modernization-ui/src/apps/page-builder/pages/PageLibrary/ManagePagesTable.tsx
apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/summary/search/PageSummary.java
apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/summary/search/PageSummaryMapper.java
apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/page/summary/search/PageSummaryMapperTest.java

On the Page Library in the Last Updated column, the timestamp is included with the date.
*Figma design 2.0 presents the date as mm/dd/yyyy or 10/2/2023. Time should not be included
* [CNFT2-1402](https://cdc-nbs.atlassian.net/browse/CNFT2-1402)
1. Navigate to page library and check the last updated column, and it should only show the date in the format MM/DD/YYYY
[CNFT2-1402]: https://cdc-nbs.atlassian.net/browse/CNFT2-1402?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT2-1402-updating-date-format

---

apps/modernization-ui/src/apps/page-builder/components/CreateCondition/CreateCondition.tsx

Resets the default value from NO to YES for the contact tracing field on the add new page form.
* [Jira Ticket](https://cdc-nbs.atlassian.net/jira/software/c/projects/CNFT2/boards/99?assignee=712020%3A591f5469-427d-49e9-87dc-8b4df72a02b4&selectedIssue=CNFT2-1453)
1. Navigate to page builder
2. Click create new page.
3. select investigation from the dropdown
4. on the contact tracing field, verify that YES is selected by default

CNFT2-1453/Set default value for contact tracing on add new page form

---

apps/nbs-gateway/build.gradle
apps/nbs-gateway/src/main/resources/application-development.yml
apps/nbs-gateway/src/main/resources/application.yml
docker-compose.yml

Addresses recent CVE findings on the `nbs-gateway` related to Apache Commons Compress.  This library is not used by the gateway.  The `spring-cloud-dependencies` dependency was removed in favor of specifying the `spring-cloud-starter-gateway` version directly.
https://github.com/CDCgov/NEDSS-Modernization/security/code-scanning/413
https://github.com/CDCgov/NEDSS-Modernization/security/code-scanning/414
https://github.com/CDCgov/NEDSS-Modernization/security/code-scanning/415
1. Ensure that the `nbs-gateway` container runs by executing `docker compose up -d --build nbs-gateway`

[CVE] addresses apache commons related vulnerabilities

---

apps/modernization-ui/src/apps/page-builder/components/QuickConditionLookup/QuickConditionLookup.tsx

Remove the filter button from the quick condition lookup modal
* [Jira Ticket](https://cdc-nbs.atlassian.net/jira/software/c/projects/CNFT2/boards/99?assignee=712020%3A591f5469-427d-49e9-87dc-8b4df72a02b4&selectedIssue=CNFT2-1474)
1. Verify there is no filter button on the quick condition lookup modal

Remove filter from quick condition search

---

apps/nbs-gateway/src/main/java/gov/cdc/nbs/gateway/patient/profile/events/observation/ViewObservationRouteLocatorConfiguration.java
apps/nbs-gateway/src/test/java/gov/cdc/nbs/gateway/patient/profile/events/observation/ViewObservationRouteLocatorConfigurationTest.java

Adds Patient-Action cookie when observations are navigated to from documents requiring review
* [CNFT1-1667](https://cdc-nbs.atlassian.net/browse/CNFT1-1667)
1. Build the `nbs-gateway` container using `docker compose up -d --build nbs-gateway`
2. Create a new Patient or Search for an existing Patient
3. On the Events tab of the Patient Profile click Add morbidity report
4. Fill out the required fields and click submit
5. Once you have been routed back to the Patient Profile click the Home link
6. From My Queues click Documents Requiring Review
7. Search for the Morbidity Report created for the Patient, click the Morbidity Report link
8. On the View Morbidity Report page click View File
9. Ensure that the correct Patient Profile is displayed
[CNFT1-1667]: …

[CNFT1-1667] Adds Patient-Action cookie for observations

---

.github/workflows/Release-candidate-containers.yml
.github/workflows/Release-container.yaml

An attempt at automating the creation of the individual containers that make up a release candidate for the NBS Modernization.  This workflow is meant to automate the tedious steps of building/tagging each release candidate container.
Includes the container build and helm chart update for each application that is part of the release candidate.
- NBS Gateway
- Modernization API
- Elasticsearch
- Nifi
Limits the environment selection to just TEST (test2) for now.

[Workflow] Release canidate containers build and deploymeny preparation

---

.github/workflows/Release-candidate-containers.yml

Fixes a typo in the name of the `values` to use a `-` over an `_`

Release Workflow typo fix

---

apps/modernization-ui/src/apps/page-builder/options/page/usePageNameOptionsAutocomplete.ts
apps/modernization-ui/src/apps/page-builder/page/library/usePageLibraryProperties.ts
apps/modernization-ui/src/generated/models/ConceptOptionsResponse.ts
apps/modernization-ui/src/generated/models/Option.ts
apps/modernization-ui/src/options/autocompete/ConceptAutocomplete.tsx
apps/modernization-ui/src/options/autocompete/index.ts
apps/modernization-ui/src/options/autocompete/useConceptOptionsAutocomplete.ts
apps/modernization-ui/src/options/autocompete/useSelectableAutocomplete.ts
apps/modernization-ui/src/options/concepts/useConceptOptions.ts
libs/options-api/src/main/java/gov/cdc/nbs/option/Option.java
libs/options-api/src/main/java/gov/cdc/nbs/option/concept/ConceptOptionsResponse.java

Connects the Page library filter for event names to the options API that obtains concepts from the database.  
- Refined the documentation for the `options/concepts` API so that the generated types have the correct required types.
- Standardizes how `Selectable` autocomplete is handled
* [CNFT2-1511](https://cdc-nbs.atlassian.net/browse/CNFT2-1511)
[CNFT2-1511]: https://cdc-nbs.atlassian.net/browse/CNFT2-1511?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT2-1511] Filter page library by event names

---

apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/detail/PageDescription.java
apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/detail/PageDescriptionFinder.java
apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/detail/PageDescriptionRowMapper.java
apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/detail/PagesResponse.java
apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/detail/PagesResponseMapper.java
apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/page/detail/PageDescriptionRowMapperTest.java
apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/page/detail/PagesResponseMapperTest.java
apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/page/detail/PagesResponseSteps.java
apps/question-bank/src/test/resources/features/page/components/Details.feature

Adds the Page status to the GET `/page-builder/api/v1/pages/{page}` endpoint to enable / disable functionality on the web interface based on status.
* [CNFT2-1529](https://cdc-nbs.atlassian.net/browse/CNFT2-1529)
[CNFT2-1529]: https://cdc-nbs.atlassian.net/browse/CNFT2-1529?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT2-1529] Adds status to page details API

---

apps/modernization-ui/src/apps/page-builder/pages/EditPage/EditPageHeader/EditPageHeader.tsx
apps/nbs-gateway/src/main/java/gov/cdc/nbs/gateway/pagebuilder/PageBuilderProvider.java
apps/nbs-gateway/src/main/java/gov/cdc/nbs/gateway/pagebuilder/PageBuilderService.java
apps/nbs-gateway/src/main/java/gov/cdc/nbs/gateway/pagebuilder/page/ManagePageViewPageDetailsRouteLocatorConfiguration.java
apps/nbs-gateway/src/main/java/gov/cdc/nbs/gateway/pagebuilder/page/PreviewPageViewPageLoadRouteLocatorConfiguration.java
apps/nbs-gateway/src/test/java/gov/cdc/nbs/gateway/pagebuilder/PageBuilderProviderTest.java
apps/nbs-gateway/src/test/java/gov/cdc/nbs/gateway/pagebuilder/page/ManagePageViewPageDetailsRouteLocatorConfigurationDisabledTest.java
apps/nbs-gateway/src/test/java/gov/cdc/nbs/gateway/pagebuilder/page/ManagePageViewPageDetailsRouteLocatorConfigurationTest.java
apps/nbs-gateway/src/test/java/gov/cdc/nbs/gateway/pagebuilder/page/PreviewPageViewPageLoadRouteLocatorConfigurationTest.java
apps/nbs-gateway/src/test/java/gov/cdc/nbs/gateway/pagebuilder/page/PreviewPageViewPageLoadRouteLocatorDisabledTest.java
apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/classic/ReturningPageCookie.java
apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/classic/redirect/outgoing/ClassicPageDetailsRequester.java
apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/classic/redirect/outgoing/ClassicPageRedirector.java
apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/clone/ClassicClonePagePreparer.java
apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/clone/PageCloneController.java
apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/clone/PageCloneRedirector.java
apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/page/clone/PageCloneRequester.java
apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/page/clone/PageCloneSteps.java
apps/question-bank/src/test/resources/features/page/clone/PageClone.feature

Adds routing to the NBS Gateway to support navigating to the NBS 6.0.X Page Clone from modernized Page Builder.  The clone button was added to Page Edit.
* [CNFT2-1487](https://cdc-nbs.atlassian.net/browse/CNFT2-1487)
[CNFT2-1487]: https://cdc-nbs.atlassian.net/browse/CNFT2-1487?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT2-1487] clone api

---

apps/modernization-ui/src/apps/page-builder/components/AddEditTab/AddEditTab.tsx
apps/modernization-ui/src/apps/page-builder/components/AlertBanner/AlertBanner.scss
apps/modernization-ui/src/apps/page-builder/components/AlertBanner/AlertBanner.tsx
apps/modernization-ui/src/apps/page-builder/pages/EditPage/EditPageTabs/EditPageTabs.tsx
apps/modernization-ui/src/apps/page-builder/pages/EditPage/ManageTabs/ManageTabs.scss
apps/modernization-ui/src/apps/page-builder/pages/EditPage/ManageTabs/ManageTabs.tsx
apps/modernization-ui/src/apps/page-builder/services/tabsAPI.ts
apps/modernization-ui/src/styles/_animation.scss
apps/modernization-ui/src/styles/_colors.scss
apps/modernization-ui/src/styles/_uswds.scss

Description
This is a new PR after fixing some state issues brought up in demo.
I have a separate branch that implements useReducer to manage state variables but it is still an incomplete solution at this time.
Here we add the tab delete functionality to the Manage Tabs modal.
Alert banners now can accept functions that can be attached to the optional close button.
Expiration can also be passed to AlertBanners as a prop in millisecons.
https://enquizit.slack.com/archives/D05M7CT42J1/p1701187247830789?thread_ts=1701186791.042799&cid=D05M7CT42J1
Tickets
https://cdc-nbs.atlassian.net/browse/CNFT2-1468
Steps to verify
From Page Builder Pages Library:
- Select a Page by clicking the Page name
- In the Tabs menu bar, select Manage Tabs
- Tabs with content cannot be deleted, their Delete icons …

CNFT2-1468 Manage Tabs - Delete tab in modal

---

apps/modernization-ui/src/filters/applied/AppliedFilters.spec.tsx
apps/modernization-ui/src/filters/applied/AppliedFilters.tsx
apps/modernization-ui/src/filters/asDisplayableFilter.spec.ts
apps/modernization-ui/src/filters/asDisplayableFilter.ts
apps/modernization-ui/src/filters/externalize.spec.ts
apps/modernization-ui/src/filters/externalize.ts
apps/modernization-ui/src/filters/filter.ts

Ensures that the date period filter that handles `between` filters displays the selected values correctly.
* [CNFT2-1586](https://cdc-nbs.atlassian.net/browse/CNFT2-1586)
[CNFT2-1586]: https://cdc-nbs.atlassian.net/browse/CNFT2-1586?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT2-1586] adds display for Date Period filter

---

apps/modernization-ui/src/apps/page-builder/page/library/usePageLibraryProperties.ts
apps/modernization-ui/src/filters/applied/AppliedFilters.spec.tsx
apps/modernization-ui/src/filters/asDisplayableFilter.spec.ts
apps/modernization-ui/src/filters/asDisplayableFilter.ts
apps/modernization-ui/src/filters/entry/ExactValueEntryForm.tsx
apps/modernization-ui/src/filters/entry/FilterEntry.ts
apps/modernization-ui/src/filters/entry/FilterEntryForm.tsx
apps/modernization-ui/src/filters/entry/PartialValueEntryForm.tsx
apps/modernization-ui/src/filters/externalize.spec.ts
apps/modernization-ui/src/filters/externalize.ts
apps/modernization-ui/src/filters/filter.ts
apps/modernization-ui/src/filters/operators.ts
apps/modernization-ui/src/filters/properties.ts
apps/modernization-ui/src/filters/selectables.ts

Removes the partial filter operators from `event type` and `status` on Page library.
* [CNFT2-1626](https://cdc-nbs.atlassian.net/browse/CNFT2-1626)
[CNFT2-1626]: https://cdc-nbs.atlassian.net/browse/CNFT2-1626?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT2-1626] Removes parital match operators from event-type and status

---

apps/modernization-ui/src/components/Search/Search.tsx

Updates search box in page library to stop accepting input after 50 characters.
* [CNFT2-1644](https://cdc-nbs.atlassian.net/browse/CNFT2-1644)
[CNFT2-1644]: https://cdc-nbs.atlassian.net/browse/CNFT2-1644?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Set max length of 50 for search input

---

apps/modernization-ui/src/apps/page-builder/page/library/menu/PageLibraryMenu.tsx
apps/modernization-ui/src/apps/page-builder/page/library/usePageSummarySearch.ts
apps/modernization-ui/src/page/usePage.tsx

Updates the `usePage` to set the search params on `firstPage`. Updates the `usePageSummarySearch` to reset the page to `1` when a new search is executed.
* [CNFT2-1337](https://cdc-nbs.atlassian.net/browse/CNFT2-1337)
[CNFT2-1337]: https://cdc-nbs.atlassian.net/browse/CNFT2-1337?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Reset page on search

---

apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/PageDownloader.java

There are typos for the Page Library download csv file column headers. They should be “Last Updated” and “Last Updated by”.
https://cdc-nbs.atlassian.net/browse/CNFT2-1642

Fix typos in column headers: 'Last Updated' and 'Last Updated by'.

---

apps/modernization-ui/src/filters/entry/DataRangeEntryForm.tsx
apps/modernization-ui/src/validation/date/index.ts
apps/modernization-ui/src/validation/date/isBefore.ts

Adds validation to the page library filter to prevent `From` being greater than the `To` date.
* [CNFT2-1640](https://cdc-nbs.atlassian.net/browse/CNFT2-1640)
[CNFT2-1640]: https://cdc-nbs.atlassian.net/browse/CNFT2-1640?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Validate From cannot be greater than To

---

apps/modernization-ui/src/apps/search/patient/patientSearch/PatientSearch.tsx
apps/modernization-ui/src/components/FormInputs/Input.tsx
apps/modernization-ui/src/pages/advancedSearch/AdvancedSearch.tsx

As a screen reader I need to be able to navigate to the main content of the advanced search page by tabbing directly to it. 
In this case the last name field should be focused upon skipping to main content for this page
https://cdc-nbs.atlassian.net/browse/CNFT1-1771

Cnft1 1771 508 main content advanced search

---

apps/modernization-ui/src/apps/page-builder/generated/models/PagesQuestion.ts
apps/modernization-ui/src/apps/page-builder/page/management/edit/content/PageSideMenu.tsx
apps/modernization-ui/src/apps/page-builder/page/management/edit/question/Question.tsx
apps/modernization-ui/src/apps/page-builder/page/management/edit/question/QuestionContent.tsx
apps/modernization-ui/src/apps/page-builder/page/management/edit/question/QuestionHeader.tsx
apps/modernization-ui/src/apps/page-builder/page/management/edit/question/question-content.module.scss
apps/modernization-ui/src/apps/page-builder/page/management/edit/question/question-header.module.scss
apps/modernization-ui/src/apps/page-builder/page/management/edit/question/question.module.scss
apps/modernization-ui/src/apps/page-builder/page/management/edit/subsection/Subsection.tsx
apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/component/tree/FlattenedComponentFinder.java
apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/detail/PagesResponse.java
apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/detail/PagesResponseMapper.java
apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/page/detail/PagesResponseMapperTest.java

Placeholder shell for questions on the Edit page. This will allow the development of `Edit` and `Delete`.
Temporarily adds a `displayComponent` field to the `PagesQuestion` object returned so that the UI can be aware of the selected display control. This will be changed in the future to not expose the Ids to the UI.
N/A

Edit question placeholder

---

apps/modernization-ui/src/apps/page-builder/page/library/table/PageLibraryTable.spec.tsx
apps/modernization-ui/src/apps/page-builder/page/library/table/PageLibraryTable.tsx

Updates the column name in the Page Library table from `Event name` to `Event type` to match Classic™.
* [CNFT2-1231](https://cdc-nbs.atlassian.net/browse/CNFT2-1231)
[CNFT2-1231]: https://cdc-nbs.atlassian.net/browse/CNFT2-1231?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Rename column  ->  on Page Library

---

apps/modernization-ui/src/apps/page-builder/page/library/usePageLibraryProperties.ts
apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/summary/search/PageSummaryTables.java

1. Fixes an issue where searching by a page status was failing to return results. The problem was the `case` statement that was being created was referencing the wrong column.
2. Corrects the capitalization to match the table display.
3. Corrects `Draft` to `Initial Draft` as no Page in the UI will display the status `Draft`
* [CNFT2-1649](https://cdc-nbs.atlassian.net/browse/CNFT2-1649)
These changes may also resolve [CNFT2-1654](https://cdc-nbs.atlassian.net/browse/CNFT2-1654)
[CNFT2-1649]: https://cdc-nbs.atlassian.net/browse/CNFT2-1649?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CNFT2-1654]: https://cdc-nbs.atlassian.net/browse/CNFT2-1654?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT2-1649 Published with Draft filter

---

apps/modernization-ui/src/apps/page-builder/page/library/PageLibrary.tsx
apps/modernization-ui/src/utils/ExportUtil.ts
apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/summary/download/PageSummaryDownloadController.java
apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/summary/download/PageSummaryDownloader.java

The CSV and PDF export had the wrong default sort.
* [CNFT2-1645](https://cdc-nbs.atlassian.net/browse/CNFT2-1645)
[CNFT2-1645]: https://cdc-nbs.atlassian.net/browse/CNFT2-1645?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix the default sort for export

---

apps/modernization-ui/src/apps/page-builder/page/library/PageLibrary.tsx
apps/modernization-ui/src/apps/page-builder/page/library/usePageSummarySearch.ts

In the Page Library the `keyword` search and the filters are operating independently of each other. Entering a new keyword should include the filters in the API call.
When changing the filters, the page should be reset to 1.
* [CNFT2-1649](https://cdc-nbs.atlassian.net/browse/CNFT2-1649)
[CNFT2-1649]: https://cdc-nbs.atlassian.net/browse/CNFT2-1649?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Make filter and keyword search work together

---

apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/filter/querydsl/QueryDSLMultiValueFilterApplier.java

Page Library
When filtering on `condition - not equal to`, the resulting row count is not as expected. This PR fixes this by including pages with no conditions associated with them when performing a `not equal to` search.
* [CNFT2-1653](https://cdc-nbs.atlassian.net/browse/CNFT2-1653)
[CNFT2-1653]: https://cdc-nbs.atlassian.net/browse/CNFT2-1653?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Include null in `not equals` filter

---

apps/modernization-ui/src/components/Table/Table.spec.tsx
apps/modernization-ui/src/components/Table/Table.tsx

The table component disables the sort if the current page only has 1 result. This PR changes this behavior so that sorting is enabled as long as the `total` results is > 1; 
* [CNFT2-1655](https://cdc-nbs.atlassian.net/browse/CNFT2-1655)
[CNFT2-1655]: https://cdc-nbs.atlassian.net/browse/CNFT2-1655?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Allow sort on last page if only 1 entry on page

---

apps/modernization-ui/src/apps/page-builder/pages/AddNewPage/AddNewPageFields.tsx
apps/modernization-ui/src/validation/entry/dataMartNameRule.ts

Here we piggy-back off of https://cdc-nbs.atlassian.net/browse/CNFT2-1558.
We add a `maxLength` property to the Datamart name rules we defined in CNFT2-1558.
When you Add a new page, an error will be thrown when Datamart name exceeds 21 characters.
* [Jira Ticket](url)](https://cdc-nbs.atlassian.net/browse/CNFT2-1560)

Cnft2 1560 datamart name max length

---

apps/modernization-ui/src/apps/page-builder/page/management/layout/PageManagementLayout.tsx

Here we fix a breadcrumb issue where, after creating a new page, the Pages Library breadcrumb on EditPage now works as intended, taking you to PageLibrary.
[* [Jira Ticket](url)](https://cdc-nbs.atlassian.net/browse/CNFT2-1483)

CNFT2-1483 Edit page: Page Library link

---

apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/BusinessRulesLibraryTable.scss
apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/BusinessRulesLibraryTable.tsx

Some CSS was leaking into other tables and causing the 6th column to be too small.
Before:
After: 
* [CNFT2-1696](https://cdc-nbs.atlassian.net/browse/CNFT2-1696)
[CNFT2-1696]: https://cdc-nbs.atlassian.net/browse/CNFT2-1696?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Scope column css to business rule table

---

apps/modernization-ui/src/apps/patient/profile/labReport/LabReportTable.tsx
apps/modernization-ui/src/apps/patient/profile/labReport/PatientLabReport.ts
apps/modernization-ui/src/apps/patient/profile/labReport/PatientLabReportTransformer.spec.ts
apps/modernization-ui/src/apps/patient/profile/labReport/PatientLabReportTransformer.ts

Fix date collected field is defaulting to 01/01/1970 for all Lab Reports for patients under Events tab. 
* [CNFT1-1911](https://cdc-nbs.atlassian.net/browse/CNFT1-1911)
[CNFT1-1911]: https://cdc-nbs.atlassian.net/browse/CNFT1-1911?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Patient profile lab report collected on default date set to 01/01/1970 when null during UI transformation fixed

---

apps/modernization-ui/src/apps/page-builder/components/CreateQuestion/CreateQuestion.tsx
apps/modernization-ui/src/apps/page-builder/page/management/edit/content/PageContent.tsx
apps/modernization-ui/src/apps/page-builder/page/management/edit/question/Question.tsx
apps/modernization-ui/src/apps/page-builder/page/management/edit/question/QuestionHeader.tsx
apps/modernization-ui/src/apps/page-builder/page/management/edit/section/Section.tsx
apps/modernization-ui/src/apps/page-builder/page/management/edit/section/Sections.tsx
apps/modernization-ui/src/apps/page-builder/page/management/edit/subsection/Subsection.tsx

Small bug fix when clicking the edit button on a question/static element it was only showing the edit question modal since the check was not being made.

small bug fix for edit question/static element

---

apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/entity/CodeValueGeneral.java
apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/valueset/request/AddConceptRequest.java

Create value set concept api endpoint fix on two fields that were not being set.
* [CNFT2-1574](https://cdc-nbs.atlassian.net/browse/CNFT2-1693)
[CNFT2-1574]: https://cdc-nbs.atlassian.net/browse/CNFT2-1574?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT2-1574-create-value-set-concept-api

---

apps/modernization-ui/src/apps/page-builder/condition/search/ConditionSearch.spec.tsx
apps/modernization-ui/src/apps/page-builder/condition/search/ConditionSearch.tsx

When the Condition search modal was initially opened, it was not passing the page size. This resulted in the size indicator showing `10` while the table contained `20` results.
This PR updates the initial load to include the `pageSize`.
* [CNFT2-1701](https://cdc-nbs.atlassian.net/browse/CNFT2-1701)
[CNFT2-1701]: https://cdc-nbs.atlassian.net/browse/CNFT2-1701?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Use page size for initial search

---

apps/modernization-api/src/main/java/gov/cdc/nbs/patient/profile/names/PatientNameFinder.java

Patient Profile does not display more than ten Names.  We are doing a select count/distinct on names when we should be doing a max sequence number
* [CNFT1-1795](https://cdc-nbs.atlassian.net/browse/CNFT1-1795)
[CNFT1-1795]: https://cdc-nbs.atlassian.net/browse/CNFT1-1795?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
**Before**:
**After**:

CNFT1-1795 Patient Profile Name Count

---

apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/filter/querydsl/DefaultQueryDSLCriteriaResolver.java
apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/filter/querydsl/PageLibraryQueryDSLCriteriaResolver.java
apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/filter/querydsl/QueryDSLDateFilterApplier.java
apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/filter/querydsl/QueryDSLDateRangeFilterApplier.java
apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/filter/querydsl/QueryDSLFilterApplier.java
apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/summary/search/PageSummarySearcher.java
apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/filter/querydsl/PageLibraryQueryDSLCriteriaResolverTest.java

The `condition not equal to` filter in the Page Library was not working as expected and still returned pages that were associated with the provided condition. This PR adds custom handling for this query.
* [CNFT2-1697](https://cdc-nbs.atlassian.net/browse/CNFT2-1697)
[CNFT2-1697]: https://cdc-nbs.atlassian.net/browse/CNFT2-1697?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT2-1697 condition not equal

---

apps/modernization-ui/src/apps/patient/profile/administrative/AdministrativeTable.tsx

User should not be able to delete administrative comment. 
* [CNFT1-1730](https://cdc-nbs.atlassian.net/browse/CNFT1-1730)
[CNFT1-1730]: https://cdc-nbs.atlassian.net/browse/CNFT1-1730?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Removed delete prop for detail element in Profile Admin Table preventing User from being able to delete admin comment

---

apps/modernization-ui/src/apps/page-builder/pages/AddNewPage/AddNewPage.spec.tsx
apps/modernization-ui/src/apps/page-builder/pages/AddNewPage/AddNewPageFields.tsx

The MMG field is misleading the page creation form as not all options in the selection are Message Mapping Guides. Per feedback from GDIT this would be better as `Reporting mechanism`.
Also fixes the `template` field as it was plural in the code but singular in the Figma design
* [CNFT2-1747](https://cdc-nbs.atlassian.net/browse/CNFT2-1747)
[CNFT2-1747]: https://cdc-nbs.atlassian.net/browse/CNFT2-1747?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Rename MMG -> Reporting mechanism in create page form

---

apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/valueset/ValueSetFinder.java
apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/valueset/ValueSetSearchResponseMapper.java
apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/valueset/response/ValueSetSearchResponse.java
apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/valueset/read/ValueSetFinderTest.java
apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/valueset/read/ValueSetReaderTest.java

The current API response contains (type, valueSetCode, valueSetDescription, valueSetName, valueSetStatus), this should be changed to contain extra field [codeSetGroupId]
https://cdc-nbs.atlassian.net/browse/CNFT2-1750

Adding codeSetGroupId to valueSet Search API Response

---

apps/modernization-ui/src/apps/page-builder/components/CreateCondition/CreateCondition.tsx
apps/modernization-ui/src/configuration/useConfiguration.ts
apps/modernization-ui/src/generated/index.ts
apps/modernization-ui/src/generated/models/Configuration.ts
apps/modernization-ui/src/generated/models/Properties.ts
libs/configuration-api/build.gradle
libs/configuration-api/src/main/java/gov/cdc/nbs/configuration/Configuration.java
libs/configuration-api/src/main/java/gov/cdc/nbs/configuration/ConfigurationController.java
libs/configuration-api/src/main/java/gov/cdc/nbs/configuration/Features.java
libs/configuration-api/src/main/java/gov/cdc/nbs/configuration/NbsConfigurationFinder.java
libs/configuration-api/src/main/java/gov/cdc/nbs/configuration/nbs/NbsPropertiesFinder.java
libs/configuration-api/src/main/java/gov/cdc/nbs/configuration/nbs/Properties.java
libs/configuration-api/src/main/java/gov/cdc/nbs/configuration/nbs/PropertiesMapper.java
libs/configuration-api/src/test/java/gov/cdc/nbs/configuration/ConfigurationControllerTest.java
libs/configuration-api/src/test/java/gov/cdc/nbs/configuration/nbs/PropertiesMapperTest.java

The Co-infection group drop down should be disabled on the create condition form if the selected program is not an HIV or STD program area. The HIV / STD program areas are defined in the NBS_configuration table in the database (and are STD and HIV by default). 
The configuration-api was updated to return a few properties from this table so the UI could handle the disable / enable appropriately.
* [CNFT2-1748](https://cdc-nbs.atlassian.net/browse/CNFT2-1748)
[CNFT2-1748]: https://cdc-nbs.atlassian.net/browse/CNFT2-1748?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT2-1748 disable co-infection

---

apps/modernization-ui/src/apps/search/advancedSearch/AdvancedSearch.tsx

This pr is designed to fix an issue where screen readers were not able to load the data associated with the "Results for" label when it is focused upon making a search. Now for each time there is a search made the screen reader should read the data found in the label associated with the search just made, for example: "5 Results for lastName: s" . 
Also I added an aria-label to include the totalResults found associated with the search just.
* [SSTT-1844](https://cdc-nbs.atlassian.net/browse/CNFT1-1844)

adding totalResults to the aria label and setting the data to load sooner for screen readers

---

apps/modernization-ui/src/apps/page-builder/components/Concept/Concept.tsx
apps/modernization-ui/src/apps/page-builder/components/Concept/CreateConcept/CreateConcept.spec.tsx
apps/modernization-ui/src/apps/page-builder/components/Concept/CreateConcept/CreateConcept.tsx
apps/modernization-ui/src/apps/page-builder/components/Concept/EditConcept/EditConcept.spec.tsx
apps/modernization-ui/src/apps/page-builder/components/Concept/EditConcept/EditConcept.tsx

This fixes a bug where after adding a first Value Set Concept to a Value Set, you can't add any more. The wrong value was being passed as Value Set Code which flagged a redundancy error. I've added AlertBanner messages to Creating and Editing Value Set Concepts to improve the user experience.
[* [Jira Ticket](url)](https://cdc-nbs.atlassian.net/browse/CNFT2-1773)

CNFT2-1773 Fix: Add multiple value set codes

---

apps/modernization-ui/src/apps/page-builder/components/Concept/CreateConcept/CreateConcept.tsx
apps/modernization-ui/src/apps/page-builder/components/Concept/EditConcept/EditConcept.tsx

There was a bug with the format of the effectiveToDate when creating/editing value set concept.
[* [Jira Ticket](url)](https://cdc-nbs.atlassian.net/browse/CNFT2-1773)

CNFT2-1773 Fix: Create value set concept effective date

---

apps/modernization-ui/src/apps/page-builder/page/library/menu/PageLibraryMenu.tsx
apps/modernization-ui/src/apps/page-builder/page/library/menu/page-library-menu.module.scss

CNFT2-1788 - Menu button sizes were inconsistent by a couple of px. Updated to have fixed size
CNFT2-1787 - Made the filter button toggle instead of open only
* [CNFT2-1788](https://cdc-nbs.atlassian.net/browse/CNFT2-1788)
* [CNFT2-1787](https://cdc-nbs.atlassian.net/browse/CNFT2-1787)
[CNFT2-1788]: https://cdc-nbs.atlassian.net/browse/CNFT2-1788?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CNFT2-1787]: https://cdc-nbs.atlassian.net/browse/CNFT2-1787?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix menu size, hide filter on click

---

apps/modernization-ui/src/apps/page-builder/pages/AddNewPage/AddNewPage.tsx
apps/modernization-ui/src/apps/page-builder/pages/AddNewPage/AddNewPageFields.tsx
apps/modernization-ui/src/apps/page-builder/services/pagesAPI.ts
apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/PageCreator.java
apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/PageValidator.java
apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/util/PageConstants.java
apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/page/PageValidatorTest.java
apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/page/create/PageCreatorTest.java

When creating a new page and specifying the reporting mechanism, the selected entry is not visible in the NBS Classic edit details screen. 
This was due to the create page form providing an incorrect value for the reporting mechanism, and the back-end did no validation of it.
To resolve the issue, this PR updates the frontend to provide the correct value and adds validation to the page create to verify the specified reporting mechanism exists.
* [CNFT2-1831](https://cdc-nbs.atlassian.net/browse/CNFT2-1831)
[CNFT2-1831]: https://cdc-nbs.atlassian.net/browse/CNFT2-1831?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

move page create validation to validator. add tests

---

apps/modernization-ui/src/apps/page-builder/components/CreateQuestion/CreateQuestion.scss
apps/modernization-ui/src/apps/page-builder/components/CreateQuestion/CreateQuestion.tsx
apps/modernization-ui/src/apps/page-builder/page/management/edit/question/QuestionHeader.tsx

Any toggle in Page Builder should have text on each side making it clear as to what the current setting indicates
* [CNFT2-1766](https://cdc-nbs.atlassian.net/browse/CNFT2-1766)
[CNFT2-1766]: https://cdc-nbs.atlassian.net/browse/CNFT2-1766?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add text on each side of toggles

---

apps/modernization-ui/src/apps/page-builder/components/Concept/Concept.tsx
apps/modernization-ui/src/apps/page-builder/components/Concept/CreateConcept/CreateConcept.spec.tsx
apps/modernization-ui/src/apps/page-builder/components/Concept/CreateConcept/CreateConcept.tsx
apps/modernization-ui/src/apps/page-builder/components/Concept/EditConcept/EditConcept.spec.tsx
apps/modernization-ui/src/apps/page-builder/components/Concept/EditConcept/EditConcept.tsx
apps/modernization-ui/src/apps/page-builder/components/Concept/SearchBar.tsx

Here we improve the user experience by improving the alerts when a Value set concept cannot be created/edited.
* [CNFT2-1758](https://cdc-nbs.atlassian.net/browse/CNFT2-1758)
[CNFT2-1758]: https://cdc-nbs.atlassian.net/browse/CNFT2-1758?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT2-1758 Fix: Value set concepts

---

apps/modernization-ui/src/apps/page-builder/page/management/edit/add-question/modal/AddQuestionModal.tsx
apps/modernization-ui/src/apps/page-builder/page/management/edit/add-question/search/QuestionSearch.tsx

Trigger table fetch on page content change. This prevents newly created / added questions from still appearing in the search results.
I was doing some dumb things to force the table to refresh when the modal was closed, i removed that and moved the PageProvider up a level to be able to trigger the `firstPage` call when a close action occurred. I also added a useEffect that monitors the current page content. If this content changes, a new fetch is made to refresh the table content. This prevents questions from showing up in the search that have just been added to the page.
* [CNFT2-1811](https://cdc-nbs.atlassian.net/browse/CNFT2-1811)
[CNFT2-1811]: https://cdc-nbs.atlassian.net/browse/CNFT2-1811?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Prevent added questions from displaying in search table (pt 2)

---

apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/question/QuestionController.java
apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/question/QuestionControllerHelper.java
apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/question/QuestionCreator.java
apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/question/QuestionFinder.java
apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/question/repository/WaQuestionRepository.java
apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/question/request/QuestionValidationRequest.java
apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/question/DisplayControlOptionsSteps.java
apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/question/QuestionControllerTest.java
apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/question/QuestionFinderTest.java
apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/question/ValidateQuestionSteps.java
apps/question-bank/src/test/resources/features/question/DisplayControlOptions.feature
apps/question-bank/src/test/resources/features/question/ValidateQuestion.feature

When creating a question with the same Unique ID previously used, the Create and add to page button (when clicked) is inoperable. The application should return an error message similar to "Unique ID cannot be duplicated.”
https://cdc-nbs.atlassian.net/browse/CNFT2-1815

Implement error display functionality for duplicate Unique ID

---

apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/question/QuestionFinder.java
apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/question/repository/WaQuestionRepository.java
apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/question/QuestionFinderTest.java
apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/question/ValidateQuestionSteps.java
apps/question-bank/src/test/resources/features/question/ValidateQuestion.feature

When creating a question with the same Unique Name previously used, the Create and add to page button (when clicked) is inoperable. The application should return an error message similar to "Unique Name cannot be duplicated.”
https://cdc-nbs.atlassian.net/browse/CNFT2-1842

Implement error display functionality for duplicate Unique Name

---

apps/modernization-ui/src/apps/page-builder/page/management/edit/section/manage/AddSection.tsx
apps/modernization-ui/src/apps/page-builder/page/management/edit/subsection/manage/AddSubSection.tsx
apps/modernization-ui/src/apps/page-builder/page/management/edit/tabs/AddEditTab/AddEditTab.tsx

Fixing default required toggle for add section, subsection, and tab

Bug fixes with add section, subsection, and tab

---

apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/question/QuestionFinder.java
apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/question/repository/WaQuestionRepository.java
apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/question/request/QuestionValidationRequest.java
apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/question/QuestionFinderTest.java
apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/question/ValidateQuestionSteps.java
apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/support/QuestionCommandMother.java
apps/question-bank/src/test/resources/features/question/ValidateQuestion.feature

When creating a question with the same RDB column name previously used, the Create and add to page button (when clicked) is inoperable. The application should return an error message when    duplicate RDB column name is used or duplicate Data Mart column name is used
https://cdc-nbs.atlassian.net/browse/CNFT2-1843

Implement error display functionality for duplicate rdbColumnName 

---

libs/options-api/src/main/java/gov/cdc/nbs/option/providers/autocomplete/ProviderOptionAutocompleteController.java
libs/options-api/src/main/java/gov/cdc/nbs/option/providers/autocomplete/ProviderOptionResolver.java
libs/options-api/src/test/java/gov/cdc/nbs/option/provider/autocomplete/ProviderAutocompleteRequester.java
libs/options-api/src/test/java/gov/cdc/nbs/option/provider/autocomplete/ProviderAutocompleteSteps.java
libs/options-api/src/test/java/gov/cdc/nbs/option/provider/autocomplete/ProviderOptionMother.java
libs/options-api/src/test/java/gov/cdc/nbs/option/provider/autocomplete/ProviderOptionSteps.java
libs/options-api/src/test/resources/features/providers/ProviderOptions.feature

API at `nbs/api/options/providers/search`.  Response return the Provider/Person `person_uid` as value and first_nm, last_nm as `name`.  The master record Person should contain the appropriate name.  Note our db isn't optimized for this query as we are doing a like on the concatenation of first_name last_name
* [CNFT1-1880](https://cdc-nbs.atlassian.net/browse/CNFT1-1880)
[CNFT1-1880]: https://cdc-nbs.atlassian.net/browse/CNFT1-1880?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT1-1880 Provider Autocompletion- API development

---

apps/modernization-ui/src/apps/page-builder/components/AddQuestion/QuestionForm.tsx
apps/modernization-ui/src/apps/page-builder/components/AddQuestion/fields/BasicInformationFields.tsx
apps/modernization-ui/src/apps/page-builder/components/AddQuestion/fields/CodedFields.tsx
apps/modernization-ui/src/apps/page-builder/components/AddQuestion/fields/DataMartFields.spec.tsx
apps/modernization-ui/src/apps/page-builder/components/AddQuestion/fields/DataMartFields.tsx
apps/modernization-ui/src/apps/page-builder/components/AddQuestion/fields/MessagingFields.tsx
apps/modernization-ui/src/apps/page-builder/components/AddQuestion/fields/NumericFields.tsx
apps/modernization-ui/src/apps/page-builder/components/AddQuestion/fields/QuestionSpecificFields.tsx
apps/modernization-ui/src/apps/page-builder/components/AddQuestion/fields/TextFields.tsx
apps/modernization-ui/src/apps/page-builder/components/AddQuestion/fields/UserInterfaceFields.tsx

Fixes an issue where `onChange` events were clearing the form validation status. This is done by  changing from:
```typescript
const watch = useWatch(form);
```
to
```typescript
const [uniqueId, uniqueName, questionType] = useWatch({
control: form.control,
name: ['uniqueId', 'uniqueName', 'questionType'],
exact: true
});
```
Also improves some validation messages.
NA

Fix validation loss onChange

---

apps/modernization-api/src/main/java/gov/cdc/nbs/patient/documentsrequiringreview/detail/LaboratoryReportDetailFinder.java

Replaces use of `queryForStream` with `query`.  When using this method the caller is responsible for closing the connection.  Not required to be used for this instance.

[Fix] Database connection leak issue

---

apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/pagerules/PageRuleController.java

When calling Update Page Rule API, it is not Working, as there is difference in the path variable name.

Change the page variable name to match the path variable name.

---

apps/modernization-ui/src/apps/page-builder/page/management/edit/question/GroupQuestion/GroupQuestion.tsx
apps/modernization-ui/src/apps/page-builder/page/management/layout/PageManagementLayout.tsx
apps/modernization-ui/src/apps/page-builder/page/management/layout/page-management-layout.module.scss

To accomodate the backend change of Page status, we now display the status directly in the Page Preview label.
Also snuck in a small change to the GroupQuestion form.
* [CNFT2-2064](https://cdc-nbs.atlassian.net/browse/CNFT2-2064)
* [CNFT2-1769](https://cdc-nbs.atlassian.net/browse/CNFT2-1769)
[CNFT2-2064]: https://cdc-nbs.atlassian.net/browse/CNFT2-2064?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CNFT2-1769]: https://cdc-nbs.atlassian.net/browse/CNFT2-1769?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT2-2064 Previewing label

---

apps/modernization-ui/src/apps/page-builder/components/AddQuestion/fields/MessagingFields.tsx
apps/modernization-ui/src/apps/page-builder/page/management/edit/add-question/modal/AddQuestionModal.tsx
apps/modernization-ui/src/apps/page-builder/page/management/edit/content/PageSideMenu.tsx

While prepping for the GDIT demo I noticed that the messaging fields sometimes failed to enable when toggling the radio button. This was due to the watch failing to initialize properly.
Krishna also asked to temporarily remove the reorder button until it is re-implemented.
The create question form also needs to reset its state upon successful creation of a question.
NA

Fix watch for messaging fields

---

apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/Add/AddBusinessRule.tsx

When clicking the Yes, delete button, the application is deleting the selected business rule. However, it does not return you to the Business Rules library (list).
*The same is true for Cancel. The application does not delete the selected business rule (as expected). But, it does not return you to the Business Rules library (list).
*The application returns to DRAFT mode with the other available buttons related to the page.  *See video example.
* [CNFT2-2025](https://cdc-nbs.atlassian.net/browse/CNFT2-2025)
[CNFT2-2025]: https://cdc-nbs.atlassian.net/browse/CNFT2-2025?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

cnft2-2025

---

apps/modernization-ui/src/apps/page-builder/page/management/edit/add-question/search/QuestionSearch.tsx

The page size was resetting back to 10 due to a de-rendering of the RangeToggle component. This was cause by a duplicate usePage `ready` trigger with undefined.
* [CNFT2-2103](https://cdc-nbs.atlassian.net/browse/CNFT2-2103)
[CNFT2-2103]: https://cdc-nbs.atlassian.net/browse/CNFT2-2103?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix the page size selection for question search.

---

apps/modernization-ui/src/alert/useAlert.tsx
apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/Add/AddBusinessRule.scss
apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/Add/AddBusinessRule.tsx

Simple updating the copy message when successfully adding/editing/deleting a business rule.  Had to make a change to the Alert itself to allow a node so that I could style a span with bold font.
* [Jira Ticket](https://cdc-nbs.atlassian.net/jira/software/c/projects/CNFT2/boards/99?assignee=712020%3A591f5469-427d-49e9-87dc-8b4df72a02b4&selectedIssue=CNFT2-2002)
- [x ] PR focuses on a single story
- [x ] Code has been fully tested to meet acceptance criteria
- [ x] PRs containing TypeScript follow …

update success banners for business rules

---

apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/pagerules/PageRuleFinder.java

1. The function to select the number of records to show in the library is currently not working.
2. The ability to sort text alphabetically in the Business Rules Library for columns Values and Target Fields is not available. This capability is available in Classic.
* [CNFT2-2029](https://cdc-nbs.atlassian.net/browse/CNFT2-2029)
* [CNFT2-2003](https://cdc-nbs.atlassian.net/browse/CNFT2-2003)
[CNFT2-2029]: https://cdc-nbs.atlassian.net/browse/CNFT2-2029?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CNFT2-2003]: https://cdc-nbs.atlassian.net/browse/CNFT2-2003?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

sort and total elements page fixed

---

apps/modernization-api/src/main/java/gov/cdc/nbs/codes/CountyCodedValueFinder.java
apps/modernization-api/src/main/java/gov/cdc/nbs/codes/DetailedRaceFinder.java
apps/modernization-api/src/main/java/gov/cdc/nbs/codes/GeneralCodedValueQuery.java
apps/modernization-api/src/main/java/gov/cdc/nbs/codes/PrimaryLanguageValueSetFinder.java
apps/modernization-api/src/main/java/gov/cdc/nbs/codes/PrimaryOccupationValueSetFinder.java

Fix sort criteria for county, generalcodedvalue, detailedrace, primarylanguage, primaryoccupation
`indentLevelNbr => descTxt`
* [CNFT1-1838](https://cdc-nbs.atlassian.net/browse/CNFT1-1838)
[CNFT1-1838]: https://cdc-nbs.atlassian.net/browse/CNFT1-1838?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT1-1838 fix sort criteria part 2 (more than just county)

---

apps/modernization-api/src/main/java/gov/cdc/nbs/event/search/investigation/InvestigationQueryBuilder.java
apps/modernization-api/src/main/java/gov/cdc/nbs/event/search/labreport/LabReportQueryBuilder.java
apps/modernization-api/src/test/resources/features/InvestigationSearch.feature
libs/event-schema/src/main/java/gov/cdc/nbs/message/enums/PregnancyStatus.java

The Lab Report and Investigation search queries were passing `U` instead of `UNK` for `pregnacny_ind_cd` when searching for pregnancy status.
* [CNFT1-2109](https://cdc-nbs.atlassian.net/browse/CNFT1-2109)
[CNFT1-2109]: https://cdc-nbs.atlassian.net/browse/CNFT1-2109?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-2109] Enures expected value is used when searching for pregnancy: UNKNOWN

---

apps/nbs-gateway/README.md
apps/nbs-gateway/build.gradle
apps/nbs-gateway/src/main/java/gov/cdc/nbs/gateway/RouteOrdering.java
apps/nbs-gateway/src/main/java/gov/cdc/nbs/gateway/patient/profile/PatientProfileRouteLocatorConfiguration.java
apps/nbs-gateway/src/main/java/gov/cdc/nbs/gateway/patient/profile/events/observation/ViewObservationRouteLocatorConfiguration.java
apps/nbs-gateway/src/main/resources/application.yml
apps/nbs-gateway/src/test/java/gov/cdc/nbs/gateway/RouteOrderingTest.java

The `view-observation-apply-patient-action-cookie` route was resolving before the `patient-profile` route when clicking the patient name in the Documents Requiring Review queue.  Ordering was introduced to ensure that the `view-observation-apply-patient-action-cookie` route is checked after the `patient-profile` route.
* [CNFT1-1909](https://cdc-nbs.atlassian.net/browse/CNFT1-1909)
[CNFT1-1909]: https://cdc-nbs.atlassian.net/browse/CNFT1-1909?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-1909] DRR Patient Profile Routing

---

apps/modernization-api/src/main/java/gov/cdc/nbs/event/search/labreport/SearchableLabReportConfiguration.java
apps/modernization-api/src/main/resources/application.yml
apps/modernization-api/src/main/resources/search/lab-report/lab-report.index.json

Auto-initializes the 'lab_report' Elasticsearch index on application start up if the index does not already exist. A file has been added that contains the current mappings for the index.
* [CNFT1-2067](https://cdc-nbs.atlassian.net/browse/CNFT1-2067)
[CNFT1-2067]: https://cdc-nbs.atlassian.net/browse/CNFT1-2067?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-2067] Initialize Lab Report index

---

apps/modernization-ui/src/apps/page-builder/page/management/preview/tab/subsection/PreviewSubsection.tsx

Fixed Subsection visibility when user chooses Non visible
* [Jira Ticket] https://cdc-nbs.atlassian.net/browse/CNFT2-2145

[CNFT2-2145] - Subsection is still visible when user chooses Non visible

---

apps/modernization-ui/src/apps/page-builder/components/AddQuestion/fields/CodedFields.tsx
apps/modernization-ui/src/apps/page-builder/components/AddQuestion/fields/NumericFields.tsx
apps/modernization-ui/src/apps/page-builder/components/AddQuestion/fields/QuestionSpecificFields.tsx
apps/modernization-ui/src/apps/page-builder/page/management/edit/edit-question/EditQuestionModal.tsx
apps/modernization-ui/src/apps/page-builder/page/management/edit/edit-question/form/EditPageQuestion.tsx

1. When editing a `CODED` question, hide the create new value set workflow.
2. Related units was default to `Yes` due to using `||` instead of `&&`
NA

Edit coded question fix

---

apps/modernization-ui/src/apps/search/event/components/InvestigationSearch/InvestigationResults.spec.tsx
apps/modernization-ui/src/apps/search/event/components/InvestigationSearch/InvestigationSearchResult.spec.tsx
apps/modernization-ui/src/apps/search/event/components/InvestigationSearch/InvestigationSearchResult.tsx
apps/modernization-ui/src/apps/search/event/components/LabReportSearch/LabReportResults.spec.tsx
apps/modernization-ui/src/apps/search/event/components/LabReportSearch/LabReportResults.tsx
apps/modernization-ui/src/apps/search/event/components/PatientDetails/PatientDetails.tsx
apps/modernization-ui/src/apps/search/event/components/PatientDetails/index.ts
apps/modernization-ui/src/date/InternalizeDate.ts

The url used to link to the lab report was using the Patient short id instead of the actual identifier which prevented the Patient from being resolved when returning to the patient profile.
* [CNFT1-2095](https://cdc-nbs.atlassian.net/browse/CNFT1-2095)
[CNFT1-2095]: https://cdc-nbs.atlassian.net/browse/CNFT1-2095?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-2095] Lab Report Search returns to the modernized Patient Profile

---

apps/modernization-ui/src/apps/page-builder/hooks/api/useFetchPageRules.ts
apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/Add/AddBusinessRule.tsx
apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/BusinessRulesLibrary.tsx

We've been having the issue where canceling a business rule edit would navigate back to the table with an undefined pageId.  I have not been able to reproduce this issue locally, but QA consistently has the issue.  I've added a few pageId checks that i'm hoping will fix but I won't know for sure until we merge and test on INT

fix undefined pageId when canceling rule edit form

---

apps/modernization-ui/src/apps/page-builder/page/management/edit/Edit.tsx
apps/modernization-ui/src/apps/page-builder/page/management/edit/question/GroupQuestion/GroupQuestion.spec.tsx
apps/modernization-ui/src/apps/page-builder/page/management/edit/question/QuestionContent.spec.tsx
apps/modernization-ui/src/apps/page-builder/page/management/edit/question/QuestionContent.tsx
apps/modernization-ui/src/apps/page-builder/page/management/edit/reorder/ReorderModal/ReorderModal.spec.tsx
apps/modernization-ui/src/apps/page-builder/page/management/edit/staticelement/AddStaticElement.spec.tsx
apps/modernization-ui/src/apps/page-builder/page/management/edit/staticelement/EditStaticElement.spec.tsx
apps/modernization-ui/src/apps/page-builder/page/management/header/tabs/PageTabs.spec.tsx
apps/modernization-ui/src/apps/page-builder/page/management/preview/PreviewPage.tsx
apps/modernization-ui/src/apps/page-builder/page/management/preview/PublishPage/PublishPage.spec.tsx
apps/modernization-ui/src/apps/page-builder/page/management/preview/SaveTemplate/SaveTemplate.spec.tsx
apps/modernization-ui/src/apps/page-builder/page/management/useGetPageDetails.ts
apps/modernization-ui/src/apps/page-builder/page/management/usePageManagement.tsx

After editing a value set, refresh the concepts for coded questions. 
After the value set is editing the `refresh` method is called to pull the latest changes for a page. This did not trigger the `loading` state or re-render the question components, leading to them still having the old value set concepts.
By exposing the loading state of a refresh, the components can monitor that and trigger a fetch of their concepts.
NA

Expose loading indicator for page refresh

---

apps/modernization-ui/src/apps/page-builder/components/TargetQuestion/TargetQuestion.tsx
apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/Add/AddBusinessRule.scss

Two small UI bugs within the add business rules page. One that matches the greys of disabled input fields, and to change the default of the select all checkbox within the target question modal

business rules UI bugs

---

apps/modernization-ui/src/apps/page-builder/page/management/edit/edit-question/form/EditPageQuestion.tsx
apps/modernization-ui/src/apps/page-builder/page/management/edit/staticelement/AddStaticElement.spec.tsx
apps/modernization-ui/src/apps/page-builder/page/management/edit/staticelement/AddStaticElement.tsx

If editing a question that has display control of `Readonly user entered text, number or date`, hide reporting / messaging fields.
NA

Hide reporting / messaging for readonly

---

apps/modernization-ui/src/components/NoData/NoData.scss

Changing the color for the no data indicator to meet color contrast requirements addressing a 508 compliance issue.
* [CNFT1-771](https://cdc-nbs.atlassian.net/browse/CNFT1-771)
[CNFT1-771]: https://cdc-nbs.atlassian.net/browse/CNFT1-771?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

changing the color for the no data indicator to pass color contrast

---

apps/modernization-ui/src/apps/page-builder/PageBuilderRouting.tsx
apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/BusinessRulesLibraryTable.tsx
apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/ViewBusinessRule/ViewBusinessRule.spec.tsx
apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/ViewBusinessRule/ViewBusinessRule.tsx
apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/ViewBusinessRule/view-business-rule.module.scss

When a Page is 'Published', when you select "Business rules", the "Add business rule" button is disabled.
From the table, when you select a Business rule, it takes you to a read-only display of the Rule.
* [CNFT2-2106](https://cdc-nbs.atlassian.net/browse/CNFT2-2106)
[CNFT2-2106]: https://cdc-nbs.atlassian.net/browse/CNFT2-2106?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT2-2106 Preview page header: Business rules - published

---

apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/pagerules/PageRuleFinder.java
apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/pagerules/PageRuleMapper.java
apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/pagerules/Rule.java
apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/pagerules/PageRuleControllerTest.java
apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/pagerules/PageRuleMapperTest.java
apps/question-bank/src/test/resources/features/pagerules/CreatePageRule.feature

When creating the below Business Rule, the target question, ‘Total duration of stay in the hospital (in days)’ does NOT appear in the Target Fields column with the rest of the other questions. Possibly, due to the length of the question. 
* [CNFT2-1992](https://cdc-nbs.atlassian.net/browse/CNFT2-1992)
[CNFT2-1992]: https://cdc-nbs.atlassian.net/browse/CNFT2-1992?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Cnft2 1992 value missing

---

apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/BusinessRulesLibraryTable.tsx
apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/ViewBusinessRule/ViewBusinessRule.spec.tsx
apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/ViewBusinessRule/ViewBusinessRule.tsx
apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/ViewBusinessRule/view-business-rule.module.scss

There needed to be different Business rule views based on type. 
Error messages were added and some fields that were missing from initial designs.
* [CNFT2-2192](https://cdc-nbs.atlassian.net/browse/CNFT2-2192)
[CNFT2-2192]: https://cdc-nbs.atlassian.net/browse/CNFT2-2192?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix: View Business rule

---

apps/modernization-ui/src/analytics/AnalyticsProvider.tsx
apps/modernization-ui/src/analytics/PageviewTracker.tsx
apps/modernization-ui/src/analytics/useAnalytics.ts

By default the `$pageview` event is triggered by pageLoad with SPAs pageLoad generally happens only once.  A `PageviewTracker` component was added to manually trigger a `$pageview` event when the router changes location.

Adds pageview tracker that uses the router

---

apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/helpers/mapComparatorToString.ts

We were missing the value from a switch statement.
* [Jira Ticket](https://cdc-nbs.atlassian.net/jira/software/c/projects/CNFT2/boards/99?assignee=712020%3A591f5469-427d-49e9-87dc-8b4df72a02b4)

bug fix for displaying >= in business rules table

---

apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/BusinessRulesForm.tsx
apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/BusinessRulesLibraryTable.tsx
apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/SubSectionDropdown.tsx

Originally had the logic wrong for selecting a subsection, we now are only selecting a subsection and displaying it - not all of its questions.
* [Jira Ticket](https://cdc-nbs.atlassian.net/jira/software/c/projects/CNFT2/boards/99?assignee=712020%3A591f5469-427d-49e9-87dc-8b4df72a02b4&selectedIssue=CNFT2-2148)

display subsection names for business rules

---

apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/Add/AddBusinessRule.tsx
apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/BusinessRulesForm.tsx

[CNFT2-2185] - Business Rules Bug Fixes - Disable Add to Library button when the source value is not selected
* [Jira Ticket] https://cdc-nbs.atlassian.net/browse/CNFT2-2185
[CNFT2-2185]: https://cdc-nbs.atlassian.net/browse/CNFT2-2185?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT2-2185] - Business Rules Bug Fixes

---

apps/modernization-api/src/main/java/gov/cdc/nbs/patient/search/PatientSearchCriteriaQueryResolver.java
apps/modernization-api/src/main/java/gov/cdc/nbs/search/AdjustStrings.java
apps/modernization-api/src/test/resources/features/patient/search/PatientSearch.feature

Last names are stored in the index without a hyphen.  Strip the hyphen from the search criteria and replace with a space.
* [CNFT1-2094](https://cdc-nbs.atlassian.net/browse/CNFT1-2094)
[CNFT1-2094]: https://cdc-nbs.atlassian.net/browse/CNFT1-2094?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT1-2094 fix hyphenated name search

---

libs/options-api/src/main/java/gov/cdc/nbs/option/facilities/autocomplete/FacilityOptionResolver.java
libs/options-api/src/main/java/gov/cdc/nbs/option/jdbc/autocomplete/SQLBasedOptionResolver.java
libs/options-api/src/main/java/gov/cdc/nbs/option/providers/autocomplete/ProviderOptionResolver.java
libs/options-api/src/test/resources/features/facilities/FacilityOptions.feature
libs/options-api/src/test/resources/features/providers/ProviderOptions.feature

When searching by autocomplete for `A` return `Anne Jones`, `Joe Adams`, but not `Tammy Tate`.  Add the ability to autocomplete (on exact match) of quick code.
* [CNFT1-2084](https://cdc-nbs.atlassian.net/browse/CNFT1-2084)
[CNFT1-2084]: https://cdc-nbs.atlassian.net/browse/CNFT1-2084?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT1-2084 prefix, quick code search in autocomplete for provider/facility

---

apps/modernization-ui/src/apps/page-builder/page/management/edit/reorder/ReorderQuestion/ReorderQuestion.tsx

Here we distinguish static elements in the Reorder Modal. They maintain the Question icon but have their own distinctive styling.
* [CNFT2-2143](https://cdc-nbs.atlassian.net/browse/CNFT2-2143)
[CNFT2-2143]: https://cdc-nbs.atlassian.net/browse/CNFT2-2143?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT2-2143 Reorder modal: Static elements

---

apps/modernization-ui/src/apps/page-builder/hooks/api/useDownloadPageMetadata.ts
apps/modernization-ui/src/apps/page-builder/page/management/preview/information/PageInformation.tsx

The page metadata download was corrupted when attempting to download through the auto generated API call.
* [CNFT-1934](https://cdc-nbs.atlassian.net/browse/CNFT2-1934)
|Tab | Modernized row count | Classic row count|
|---|---|---|
|Simple Question Metadata| 175 | 175 |
|Comprehensive Question Metadata| 233 | 233 |
|Vocabulary Metadata| 1003 | 1003 |
|Question With Vocabulary | 2401 | 2401|

Download metadata fix

---

apps/modernization-ui/src/apps/page-builder/components/MoreOptions/MoreOptions.tsx
apps/modernization-ui/src/apps/page-builder/page/management/edit/subsection/SubsectionHeader.tsx

Because the Subsection menu doesn't close when Ungroup Questions is selected, user needs to click an extra time to change focus to the modal. Here I ensure the menu closes so focus is restored to the modal.
* [CNFT2-2213](https://cdc-nbs.atlassian.net/browse/CNFT2-2213)
[CNFT2-2213]: https://cdc-nbs.atlassian.net/browse/CNFT2-2213?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT2-2213 Ungroup Questions: close menu

---

apps/modernization-ui/src/apps/page-builder/page/management/edit/question/question.module.scss
apps/modernization-ui/src/apps/page-builder/page/management/edit/section/section.module.scss

Fixing the gap between Question blocks in Edit Page view.
* [CNFT2-2100](https://cdc-nbs.atlassian.net/browse/CNFT2-2100)
[CNFT2-2100]: https://cdc-nbs.atlassian.net/browse/CNFT2-2100?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT2-2100 Questions gap

---

apps/modernization-api/src/main/java/gov/cdc/nbs/event/search/investigation/SearchableInvestigationConfiguration.java
apps/modernization-api/src/main/resources/application.yml
apps/modernization-api/src/main/resources/search/investigation/investigation.index.json

Auto-initializes the 'investigation' Elasticsearch index on application start up if the index does not already exist. A file has been added that contains the current mappings for the index.
* [CNFT1-2078](https://cdc-nbs.atlassian.net/browse/CNFT1-2078)
[CNFT1-2078]: https://cdc-nbs.atlassian.net/browse/CNFT1-2078?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-2078] Initialize Investigation index

---

gradle/libs.versions.toml

Updates Spring Security to 5.8.11 to resolve [CVE-2024-22257](https://spring.io/security/cve-2024-22257) and address https://github.com/CDCgov/NEDSS-Modernization/security/code-scanning/433

[CVE-2024-22257] Resolution

---

apps/modernization-ui/src/apps/page-builder/page/management/preview/tab/subsection/PreviewSubsection.tsx

When showing the headers for a grouped subsection, the label specified by the grouping should be displayed instead of the question label.

Display batch label for heading

---

apps/modernization-ui/src/apps/page-builder/page/management/edit/question/GroupQuestion/SubsectionDetails.tsx

The "Visible" Yes/No toggle was not working on Group Questions--here we fix it.
* [CNFT2-2219](https://cdc-nbs.atlassian.net/browse/CNFT2-2219)
[CNFT2-2219]: https://cdc-nbs.atlassian.net/browse/CNFT2-2219?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT2-2219 Group: No toggle

---

apps/modernization-ui/src/apps/page-builder/components/EditValueset/CreateConcept.tsx
apps/modernization-ui/src/apps/page-builder/components/EditValueset/concept/ConceptForm.tsx
apps/modernization-ui/src/validation/date/isBefore.ts

`Effective from time` was not being externalized on concept creation. Added validation to prevent `from` time being after `to` time.
* [CNFT2-2189](https://cdc-nbs.atlassian.net/browse/CNFT2-2189)
[CNFT2-2189]: https://cdc-nbs.atlassian.net/browse/CNFT2-2189?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Externalize date on concept creation

---

apps/modernization-ui/src/apps/page-builder/page/management/edit/question/GroupQuestion/SubsectionDetails.tsx
apps/modernization-ui/src/apps/page-builder/page/management/edit/section/section.module.scss

Limits the Data mart repeat number to 0-5 as indicated by the help text.
NA

Add validation to data mart repeat number to restrict to 0-5

---

apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/pagerules/PageRuleFinder.java
apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/pagerules/PageRuleMapper.java
apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/pagerules/PageRuleMapperTest.java

When Target Question has a comma, Business rule library is missing part of the question.
https://cdc-nbs.atlassian.net/browse/CNFT2-2193

Fix issue where Business rule misses part of the question If when Question contains a comma. 

---

apps/modernization-api/src/main/java/gov/cdc/nbs/patient/search/PatientFilter.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/search/PatientSearchCriteriaQueryResolver.java
apps/modernization-api/src/main/resources/graphql/patient-search.graphqls
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/search/PatientSearchCriteriaSteps.java
apps/modernization-api/src/test/resources/features/patient/search/PatientSearch.feature
apps/modernization-ui/src/generated/graphql/schema.ts
apps/modernization-ui/src/generated/schema.graphqls

Add option to backend API to disable soundex upon searching.  Add `disableSoundex` to `PatientFilter`.  For backwards compatibility it defaults to false and behaves as before and is optional.   The front end api can now use this option to disable soundex results from searches.
* [CNFT1-798](https://cdc-nbs.atlassian.net/browse/CNFT1-798)
[CNFT1-798]: https://cdc-nbs.atlassian.net/browse/CNFT1-798?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT1-798 Search Update- Update API for SoundEx for Search 1.1

---

libs/options-api/src/main/java/gov/cdc/nbs/option/facilities/autocomplete/FacilityOptionResolver.java
libs/options-api/src/main/java/gov/cdc/nbs/option/providers/autocomplete/ProviderOptionResolver.java
libs/options-api/src/test/java/gov/cdc/nbs/option/facility/autocomplete/FacilityOptionMother.java
libs/options-api/src/test/java/gov/cdc/nbs/option/facility/autocomplete/FacilityOptionSteps.java
libs/options-api/src/test/java/gov/cdc/nbs/option/provider/autocomplete/ProviderOptionMother.java
libs/options-api/src/test/java/gov/cdc/nbs/option/provider/autocomplete/ProviderOptionSteps.java
libs/options-api/src/test/resources/features/facilities/FacilityOptions.feature
libs/options-api/src/test/resources/features/providers/ProviderOptions.feature

Restricts the Providers and Facilities returned by the autocomplete API to only return manually entered items only.  This is required due to new Organizations and Facilities being added during data ingestion.

Filter electronic Providers and Facilities

---

apps/modernization-ui/src/apps/page-builder/hooks/api/useDownloadPageMetadata.ts

Fixes url for metadata download. Previously `/nbs/page-builder` was not included in the `OpenAPI.BASE`.
* [CNFT2-2263(https://cdc-nbs.atlassian.net/browse/CNFT2-2263)

Fix metadata url

---

apps/modernization-ui/src/apps/page-builder/page/management/edit/question/GroupQuestion/RepeatingBlock.tsx

Here we fix in Group questions: Repeating block, if "No" is selected in "Appears in table", it's width is not factored into the total width nor is it required to have a width.
* [CNFT2-2271](https://cdc-nbs.atlassian.net/browse/CNFT2-2271)
[CNFT2-2271]: https://cdc-nbs.atlassian.net/browse/CNFT2-2271?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT2-2271 Appearing in table

---

apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/RuleSearchBar.tsx
apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/rule-search-bar.module.scss

Here we fix the Business rules search highlight and padding. Also re-added some tooltips
* [CNFT2-2267](https://cdc-nbs.atlassian.net/browse/CNFT2-2267)
[CNFT2-2267]: https://cdc-nbs.atlassian.net/browse/CNFT2-2267?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT2-2267 Business rules search highlight

---

apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/PageDeletor.java
apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/PageUidFinder.java
apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/page/PageDeletorSteps.java
apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/page/PageDeletorTest.java
apps/question-bank/src/test/resources/features/page/PageDeletor.feature

After creating a new page, the page is in INITIAL DRAFT state. Currently, the ability to delete the Initial Draft is inoperable.
https://cdc-nbs.atlassian.net/browse/CNFT2-2258

Fix issue with deleting Initial Draft pages.

---

apps/modernization-api/src/test/java/gov/cdc/nbs/time/graphql/DateCoercingTest.java

Adds tests to verify the exceptions thrown by `DateCoercing.parseValue`

Adds exception tests to DateCoercingTest

---

apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/entity/question/CodedQuestionEntity.java
apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/entity/question/WaQuestion.java

When adding a Coded question to a page, the valueset information is being lost after the Spring boot / java upgrade. This fixes an issue where a field was re-declared in the `CodedQuestionEntity`
* [CNFT2-2272](https://cdc-nbs.atlassian.net/browse/CNFT2-2272)
[CNFT2-2272]: https://cdc-nbs.atlassian.net/browse/CNFT2-2272?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix add question value set removal

---

apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/Add/AddBusinessRules.tsx
apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/RuleSearchBar.tsx
apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/SubSectionDropdown.tsx

Here we limit target subsections in Add Business Rule to 10.
Also fixed a small tooltip typo
* [CNFT2-2241](https://cdc-nbs.atlassian.net/browse/CNFT2-2241)
* [CNFT2-2268](https://cdc-nbs.atlassian.net/browse/CNFT2-2268)
[CNFT2-2241]: https://cdc-nbs.atlassian.net/browse/CNFT2-2241?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CNFT2-2268]: https://cdc-nbs.atlassian.net/browse/CNFT2-2268?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT2-2241 Business rules: target subsection max 10

---

apps/modernization-ui/src/apps/page-builder/components/AddQuestion/fields/UserInterfaceFields.tsx

Added Display Type validation
* [Jira Ticket] https://cdc-nbs.atlassian.net/browse/CNFT2-2285

[CNFT2-2285] - Add Display Type validation

---

apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/Edit/EditBusinessRules.tsx

In edit, when source question is cleared, the target question button was not showing up
* [CNFT2-2279](https://cdc-nbs.atlassian.net/browse/CNFT2-2279)
[CNFT2-2279]: https://cdc-nbs.atlassian.net/browse/CNFT2-2279?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

bug fix for edit business rules, target question

---

apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/entity/WaNndMetadatum.java
apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/entity/WaRdbMetadata.java
apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/entity/WaUiMetadata.java
apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/exception/PageBuilderExceptionHandler.java
apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/PageCreator.java
apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/PageStateChanger.java
apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/entity/WaUiMetadataTest.java
apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/exception/PageBuilderExceptionHandlerTest.java
apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/page/state/PageStateChangeTest.java

When creating a draft, duplicate `wa_nnd_metadata` entries were being created. This changes how the clone works to not produce duplicates.

Prevent duplicate wa_nnd_metadata

---

apps/modernization-ui/src/apps/page-builder/page/management/edit/question/GroupQuestion/Update/UpdateGroupedQuestion.tsx

When editing a grouped Subsection with published questions, we want to show an alert that specifically states that there are published Questions when attempting to group again.
* [CNFT2-2277](https://cdc-nbs.atlassian.net/browse/CNFT2-2277)
[CNFT2-2277]: https://cdc-nbs.atlassian.net/browse/CNFT2-2277?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT2-2277-group-again-with-published

---

apps/modernization-ui/src/apps/page-builder/page/management/edit/subsection/SubsectionHeader.tsx
apps/modernization-ui/src/apps/page-builder/page/management/edit/subsection/subsection.module.scss
apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/BusinessRulesLibrary.tsx
apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/BusinessRulesLibraryTable.spec.tsx
apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/BusinessRulesLibraryTable.tsx

There are two methods for rendering the table rows. One for a `Published` page and one for Draft. The only difference between the two was the inclusion of `edit` in the view rule url. 
* [CNFT2-2251](https://cdc-nbs.atlassian.net/browse/CNFT2-2251)
[CNFT2-2251]: https://cdc-nbs.atlassian.net/browse/CNFT2-2251?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Cnft2 2251 published rule targets

---

db/golden/01-pii-export-odse.sql
db/golden/02-pii-export-msgoute.sql
db/golden/03-pii-restore-odse.sql
db/golden/04-pii-restore-msgoute.sql
db/golden/restore-data.sh
db/golden/runCliniDeID.sh
db/golden/tabs-msgoute.txt
db/golden/tabs-odse.txt

Completed set of scripts to DB restore using de-identified sensitive data. Also includes some important corrections for sensitive data exporting scripts.
- **03-pii-restore-odse.sql**: sp creation for restore NBS_ODSE db with anonymized sensitive data
- **04-pii-restore-msgoute.sql**: sp creation for restore NBS_ODSE db with anonymized sensitive data
- **restore-data.sh**: shell script to run restoring procedures and bulk insert data from processed CSV files
* [CNFT1-2160 Golden DB - Repopulate DB with anonymized data set](https://cdc-nbs.atlassian.net/browse/CNFT1-2160)

CNFT1-2160 Repopulate DB with anonymized data set

---

apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/content/staticelement/PageStaticCreator.java
apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/pagerules/PageRuleCreator.java
apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/page/PageDeletorTest.java
apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/page/download/PageMetaDataDownloaderTest.java
apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/pagerules/CreatePageRuleSteps.java
apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/pagerules/PageRuleCreatorTest.java
apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/pagerules/TargetSubsectionFinderTest.java
libs/me-api/src/test/java/gov/cdc/nbs/me/MeControllerTest.java
libs/options-api/src/test/java/gov/cdc/nbs/option/facility/autocomplete/FacilityOptionMother.java

1. Verifies question identifiers are provided when creating a rule. 
2. Removes some unused imports
* [CNFT2-2254](https://cdc-nbs.atlassian.net/browse/CNFT2-2254)
[CNFT2-2254]: https://cdc-nbs.atlassian.net/browse/CNFT2-2254?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Validate identifiers are provided

---

apps/modernization-ui/src/apps/page-builder/page/library/PageLibrary.tsx
testing/regression/cypress/e2e/features/page-library-sort.feature
testing/regression/cypress/e2e/pages/page-library-sort.page.js
testing/regression/cypress/step_definitions/page.library.sort.steps.js

Added end to end test case for Page Library Page name column ( [CNFT2-1012](https://cdc-nbs.atlassian.net/browse/CNFT2-1012) )
* [Jira Ticket] https://cdc-nbs.atlassian.net/browse/CNT-8
[CNFT2-1012]: https://cdc-nbs.atlassian.net/browse/CNFT2-1012?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNT-8] - E2E page library sort page name column

---

testing/regression/cypress/e2e/features/page-library-sort.feature
testing/regression/cypress/e2e/pages/page-library-sort.page.js
testing/regression/cypress/step_definitions/page.library.sort.steps.js

Added end to end test case for Page Library Event type column ( [CNFT2-1013](https://cdc-nbs.atlassian.net/browse/CNFT2-1013) )
* [Jira Ticket]  https://cdc-nbs.atlassian.net/browse/CNT-8
[CNFT2-1013]: https://cdc-nbs.atlassian.net/browse/CNFT2-1013?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNT-8] - E2E page library sort Event type column

---

testing/regression/cypress/e2e/features/page-library-sort.feature
testing/regression/cypress/e2e/pages/page-library-sort.page.js
testing/regression/cypress/step_definitions/page.library.sort.steps.js

Added end to end test case for Page Library Event type column ( [CNFT2-1016](https://cdc-nbs.atlassian.net/browse/CNFT2-1016) )
* [Jira Ticket] https://cdc-nbs.atlassian.net/browse/CNT-8
[CNFT2-1016]: https://cdc-nbs.atlassian.net/browse/CNFT2-1016?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNT-8] - E2E Page library sorting Status Column

---

testing/regression/cypress/e2e/features/page-library-sort.feature
testing/regression/cypress/e2e/pages/page-library-sort.page.js
testing/regression/cypress/step_definitions/page.library.sort.steps.js

Added end to end test case for Page Library Last Updated column ( [CNFT2-1017](https://cdc-nbs.atlassian.net/browse/CNFT2-1017) )
* [Jira Ticket] https://cdc-nbs.atlassian.net/browse/CNT-8
[CNFT2-1017]: https://cdc-nbs.atlassian.net/browse/CNFT2-1017?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNT-8] - E2E Page library sorting Last Updated Column

---

testing/regression/cypress/e2e/features/page-library/sort.feature
testing/regression/cypress/e2e/pages/page-library/sort.page.js
testing/regression/cypress/step_definitions/page-library/sort.steps.js

Added end to end test case for Page Library sorting on Last Updated by column  ( [CNFT2-1019](https://cdc-nbs.atlassian.net/browse/CNFT2-1019) )
* [Jira Ticket] https://cdc-nbs.atlassian.net/browse/CNT-8
[CNFT2-1019]: https://cdc-nbs.atlassian.net/browse/CNFT2-1019?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNT-8] - E2E page library sort last updated by column

---

apps/modernization-ui/src/apps/page-builder/page/management/edit/subsection/SubsectionHeader.spec.tsx
apps/modernization-ui/src/apps/page-builder/page/management/edit/subsection/SubsectionHeader.tsx

Allow ungrouping of subsection if page is `Published with Draft`.
Do not allow grouping / ungrouping if subsection contains a `published` question.

Display ungroup option for published with draft

---

gradle/libs.versions.toml

Updates Spring Boot to 3.2.5 to resolve [CVE-2024-22262](https://avd.aquasec.com/nvd/2024/cve-2024-22262/) which first appeared on [this scan](https://github.com/CDCgov/NEDSS-Modernization/security/code-scanning/436).

[FIX] CVE-2024-22262

---

cdc-sandbox/keycloak/imports/nbs-users.json

Enable keycloak forgot password flow inside the realm settings for nbs-users via the import file and the  `resetPasswordAllowed` attribute.  Additionally we can offer a link from any other screen outside of keycloak that goes directly to the reset password page via a link similar to the following: `http://localhost:8100/realms/nbs-users/login-actions/reset-credentials?client_id=security-admin-console&tab_id=jhNJDspklvk`
* [CNFT1-2270](https://cdc-nbs.atlassian.net/browse/CNFT1-2270)
[CNFT1-2270]: https://cdc-nbs.atlassian.net/browse/CNFT1-2270?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT1-2270 Forgot Password Key Cloak integration

---

apps/modernization-ui/src/components/Table/Table.tsx
testing/regression/cypress/e2e/features/page-library/pagination.feature
testing/regression/cypress/e2e/pages/page-library/pagination.page.js
testing/regression/cypress/step_definitions/page-library/pagination.steps.js

Added end to end test case for Page Library pagination for default value ( [CNFT2-975](https://cdc-nbs.atlassian.net/browse/CNFT2-975) )
[CNFT2-975]: https://cdc-nbs.atlassian.net/browse/CNFT2-975?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNT-9] - E2E page library pagination default value

---

testing/regression/cypress/e2e/features/page-library/pagination.feature
testing/regression/cypress/e2e/pages/page-library/pagination.page.js
testing/regression/cypress/step_definitions/page-library/pagination.steps.js

Added end to end test case for Page Library pagination after it redirect from create page still defaulted to 10 ( [CNFT2-981](https://cdc-nbs.atlassian.net/browse/CNFT2-981) )
[CNFT2-981]: https://cdc-nbs.atlassian.net/browse/CNFT2-981?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNT-9] - E2E page library pagination after redirect default to 10

---

testing/regression/cypress/e2e/features/page-library/pagination.feature

Added end to end test case for pagination with 30 rows selected and after it redirect from create page the pagination is defaulted to 10 ( [CNFT2-997](https://cdc-nbs.atlassian.net/browse/CNFT2-997) )
[CNFT2-997]: https://cdc-nbs.atlassian.net/browse/CNFT2-997?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNT-9] - E2E page library pagination 30 row defaulted after it redirect

---

apps/modernization-ui/src/apps/page-builder/components/DeleteQuestion/DeleteQuestion.tsx
apps/modernization-ui/src/apps/page-builder/components/TabGroup/TabGroup.tsx
apps/modernization-ui/src/apps/page-builder/page/management/edit/question/QuestionHeader.tsx
apps/modernization-ui/src/apps/page-builder/page/management/edit/staticelement/EditStaticElement.tsx
apps/modernization-ui/src/apps/page-builder/page/management/edit/subsection/Subsection.tsx
apps/modernization-ui/src/apps/page-builder/page/management/edit/subsection/SubsectionHeader.tsx
apps/modernization-ui/src/apps/page-builder/page/management/header/tabs/PageTabs.tsx
apps/modernization-ui/src/apps/page-builder/page/management/preview/PreviewPage.tsx
apps/modernization-ui/src/apps/page-builder/page/management/preview/tab/section/PreviewSection.tsx
apps/modernization-ui/src/apps/page-builder/page/management/preview/tab/subsection/PreviewSubsection.tsx
apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/entity/WaTemplate.java
apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/content/question/PageQuestionDeleter.java
apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/content/question/PageQuestionUpdater.java
apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/content/question/exception/DeletePageQuestionException.java
apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/content/section/SectionUpdater.java
apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/content/subsection/SubSectionUpdater.java
apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/content/tab/TabUpdater.java
apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/entity/WaTemplateTest.java
apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/page/content/question/PageQuestionDeleterTest.java
apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/page/content/question/PageQuestionUpdaterTest.java
apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/page/content/section/SectionUpdaterTest.java
apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/page/content/subsection/SubsectionUpdaterTest.java
apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/page/content/tab/TabUpdaterTest.java

Page Builder bug fixes
|Severity|Bug Description|
|------|----|
|Critical | Prevent deletion of question when question is source or target of a rule|
|Medium | Disable grouping when a subsection contains a static element|
|Low|Hide subsection in preview mode when visibility is `false`|
|Low|Hide tabs in preview mode when visibility is `false`|
|Low|Update confirmation message when deleting static element|
|Low|Remove `required` toggle from static element display|
* [CNFT2-2294](https://cdc-nbs.atlassian.net/browse/CNFT2-2294)
[CNFT2-2294]: https://cdc-nbs.atlassian.net/browse/CNFT2-2294?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PageBuilder misc bug fixes

---

testing/regression/cypress/e2e/features/page-library/pagination.feature
testing/regression/cypress/e2e/pages/page-library/pagination.page.js
testing/regression/cypress/step_definitions/page-library/pagination.steps.js

Added end to end test case for pagination with 50 rows selected and after it redirect from create page the pagination is defaulted to 10 ( [CNFT2-1006](https://cdc-nbs.atlassian.net/browse/CNFT2-1006) )
[CNFT2-1006]: https://cdc-nbs.atlassian.net/browse/CNFT2-1006?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNT-9] - E2E page library pagination 50 row defaulted after redirects

---

testing/regression/cypress/e2e/features/page-library/pagination.feature

Added end to end test case for pagination with 100 rows selected and after it redirect from create page the pagination is defaulted to 10 ( [CNFT2-1008](https://cdc-nbs.atlassian.net/browse/CNFT2-1008) )
[CNFT2-1008]: https://cdc-nbs.atlassian.net/browse/CNFT2-1008?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNT-9] - E2E page library pagination 100 row defaulted after redirects

---

testing/regression/cypress/e2e/features/page-library/pagination.feature
testing/regression/cypress/step_definitions/page-library/pagination.steps.js

Added end to end test case for pagination that retrieve next set of pages while clicking the next link ( [CNFT2-1011](https://cdc-nbs.atlassian.net/browse/CNFT2-1011) )
[CNFT2-1011]: https://cdc-nbs.atlassian.net/browse/CNFT2-1011?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNT-9] - E2E page library pagination click next page link advances to next subsequent page

---

apps/modernization-ui/src/components/Search/Search.tsx
testing/regression/cypress/e2e/features/page-library/searchAndFilter.feature
testing/regression/cypress/e2e/pages/page-library/searchAndFilter.page.js
testing/regression/cypress/step_definitions/page-library/searchAndFilter.steps.js

Added end to end test case for Search and Filter - Search for a page equal to page name ( CNFT2-1021 )

[CNT-14] - E2E page library Search and Filter equal to page name

---

apps/modernization-ui/src/apps/page-builder/page/library/menu/PageLibraryMenu.tsx
apps/modernization-ui/src/filters/entry/FilterEntryForm.tsx
apps/modernization-ui/src/filters/panel/FilterPanel.tsx
testing/regression/cypress/e2e/features/page-library/searchAndFilter.feature
testing/regression/cypress/e2e/pages/page-library/searchAndFilter.page.js
testing/regression/cypress/step_definitions/page-library/searchAndFilter.steps.js

Added end to end test case for filter by page name using contains operator ( [CNFT2-1059](https://cdc-nbs.atlassian.net/browse/CNFT2-1059) )
[CNFT2-1059]: https://cdc-nbs.atlassian.net/browse/CNFT2-1059?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNT-14] - E2E page library filter by page name using contains operator

---

testing/regression/cypress/e2e/features/page-library/searchAndFilter.feature
testing/regression/cypress/e2e/pages/page-library/searchAndFilter.page.js
testing/regression/cypress/step_definitions/page-library/searchAndFilter.steps.js

Added end to end test case for filter by page name using not equal to operator ( [CNFT2-1061](https://cdc-nbs.atlassian.net/browse/CNFT2-1061) )
[CNFT2-1061]: https://cdc-nbs.atlassian.net/browse/CNFT2-1061?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNT-14] - E2E page library filter by page name using not equal to operator

---

testing/regression/cypress/e2e/features/page-library/searchAndFilter.feature
testing/regression/cypress/e2e/pages/page-library/searchAndFilter.page.js
testing/regression/cypress/step_definitions/page-library/searchAndFilter.steps.js

Added end to end test case for filter by last updated using last 7 days date validation ( [CNFT2-1115](https://cdc-nbs.atlassian.net/browse/CNFT2-1115) )
Since the last 7 days don't have any data in page builder, so I have used MORE_THAN_30_DAYS for screenshot
Last 7 days option shows no data in page builder
[CNFT2-1115]: https://cdc-nbs.atlassian.net/browse/CNFT2-1115?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNT-14] - Page library filter by last updated using last 7 days date validation

---

apps/modernization-ui/src/apps/search/event/components/InvestigationSearch/InvestigationCriteria.tsx
apps/modernization-ui/src/apps/search/event/components/InvestigationSearch/InvestigationGeneralFields.tsx
apps/modernization-ui/src/forms/event.ts

resetField and typescript won't allow you to set the field back to it's original value (generally `undefined` or `{type: undefined}`) so use `any` with `dirty` and `revalidate` and don't propagate the event.  Note~ exception to typescript do's dont's.
* [CNFT1-2324](https://cdc-nbs.atlassian.net/browse/CNFT1-2324)
[CNFT1-2324]: https://cdc-nbs.atlassian.net/browse/CNFT1-2324?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT1-2324 API: Event Search (Investigation) UI passing an empty string for Event type ID field

---

apps/modernization-api/src/test/java/gov/cdc/nbs/patient/PatientMother.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/address/PatientProfileAddressSteps.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/address/change/PatientProfileAddressChangeSteps.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/mortality/change/PatientMortalityChangeSteps.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/phone/change/PatientProfilePhoneChangeSteps.java

Initialize `Locale` objects using static initializers instead of deprecated constructor.

Remove deprecated constructor usage

---

testing/regression/cypress/e2e/features/page-library/dataElements.feature
testing/regression/cypress/e2e/features/page-library/pagination.feature
testing/regression/cypress/e2e/features/page-library/sort.feature
testing/regression/cypress/e2e/pages/page-library/dataElements.page.js
testing/regression/cypress/step_definitions/page-library/dataElements.steps.js
testing/regression/package.json

Added end to end test case for page name appear as links in the page name column ( [CNFT2-964](https://cdc-nbs.atlassian.net/browse/CNFT2-964) ) and fixed the report not showing the page-builder artifacts
[CNFT2-964]: https://cdc-nbs.atlassian.net/browse/CNFT2-964?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNT-18] - Page library data elements page name appear as link and Reports fix

---

testing/regression/cypress/e2e/features/search-investigation-general-info.feature
testing/regression/cypress/e2e/pages/searchEvent.page.js
testing/regression/cypress/step_definitions/searchEvent.steps.js

To verify that the application can successfully search for patients based on a specific program area related to the investigation event.
CNFT1-1331 (https://cdc-nbs.atlassian.net/browse/CNFT1-1331)

CNFT1-1331 test for search event program area

---

testing/regression/cypress/e2e/features/search-investigation-general-info.feature
testing/regression/cypress/e2e/pages/searchEvent.page.js
testing/regression/cypress/step_definitions/searchEvent.steps.js

To verify that the application can successfully search for patients based on a specific jurisdiction associated with the investigation event.
* [CNFT1-1332](https://cdc-nbs.atlassian.net/browse/CNFT1-1332)
[CNFT1-1332]: https://cdc-nbs.atlassian.net/browse/CNFT1-1332?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT1-1332 test for search event investigation jursidiction

---

apps/modernization-ui/src/SkipLink/SkipLink.scss
apps/modernization-ui/src/SkipLink/SkipLinkContext.tsx
apps/modernization-ui/src/apps/landing/About/About.tsx
apps/modernization-ui/src/apps/landing/Layout/WelcomeLayout.tsx
apps/modernization-ui/src/apps/landing/Layout/login-wrapper.module.scss
apps/modernization-ui/src/apps/landing/Learn/Learn.tsx
apps/modernization-ui/src/apps/landing/SignIn/SignIn.spec.tsx
apps/modernization-ui/src/apps/landing/SignIn/SignIn.tsx

adding required header specificity for welcome page and skipLink styles 
A skip link navigation button is needed in order to navigate to the main content of the Login page.
Adding the styles used from USWDS for the skipLink button
* [CNFT1-2273](https://cdc-nbs.atlassian.net/browse/CNFT1-2273)
[CNFT1-2273]: https://cdc-nbs.atlassian.net/browse/CNFT1-2273?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

adding required header specificity for welcome page and skipLink styles

---

testing/regression/cypress/e2e/features/create-page/pageElements.feature
testing/regression/cypress/e2e/pages/create-page/pageElements.page.js
testing/regression/cypress/step_definitions/create-page/pageElements.steps.js

Added end to end test case to verify selection of a single condition in the Condition(s) drop-down box ( [CNFT2-1251](https://cdc-nbs.atlassian.net/browse/CNFT2-1251) )
[CNFT2-1251]: https://cdc-nbs.atlassian.net/browse/CNFT2-1251?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNT-18] - Verify selection of a single condition in the Condition(s) drop-down box

---

apps/modernization-ui/src/authorization/IdleTimer.tsx
apps/modernization-ui/src/authorization/ProtectedLayout.tsx

Creates the functionality to track a user's idle time, as well as a second timer that can start once a warning message is displayed.
There are several things still in question at this point mainly.
- there does not appear to be designs yet for a warning modal/page/alert?
- How long can a user be idle before the warning is displayed. (right now just set to 15 minutes)
- How long will the warning stay up? (currently set to 5 minutes)
* [Jira Ticket](https://cdc-nbs.atlassian.net/jira/software/c/projects/CNFT1/boards/112?assignee=712020%3A591f5469-427d-49e9-87dc-8b4df72a02b4&selectedIssue=CNFT1-2325)

ui Idle session timer

---

testing/regression/cypress/e2e/features/create-page/pageElements.feature
testing/regression/cypress/e2e/pages/create-page/pageElements.page.js
testing/regression/cypress/step_definitions/create-page/pageElements.steps.js

Added end to end test case to select a Template to populate the field ( [CNFT2-1260](https://cdc-nbs.atlassian.net/browse/CNFT2-1260) )
[CNFT2-1260]: https://cdc-nbs.atlassian.net/browse/CNFT2-1260?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNT-20] - Select a Template to populate the field

---

testing/regression/cypress/e2e/features/create-page/pageElements.feature
testing/regression/cypress/e2e/pages/create-page/pageElements.page.js
testing/regression/cypress/step_definitions/create-page/pageElements.steps.js

Added end to end test case to verify Event Type field displays required values (upon selection) on Add new page ( [CNFT2-1257](https://cdc-nbs.atlassian.net/browse/CNFT2-1257) )
[CNFT2-1257]: https://cdc-nbs.atlassian.net/browse/CNFT2-1257?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNT-20] - Verify Event Type field displays required values (upon selection) on Add new page

---

apps/nbs-gateway/src/main/java/gov/cdc/nbs/gateway/patient/profile/events/report/lab/DeletedLabReportLocatorConfiguration.java
apps/nbs-gateway/src/test/java/gov/cdc/nbs/gateway/patient/profile/events/report/lab/DeletedLabReportLocatorConfigurationTest.java

Adds routing to the `nbs-gateway` to handle returning to the Patient Profile after deleting a Lab Report.
* [CNFT1-2143](https://cdc-nbs.atlassian.net/browse/CNFT1-2143)
[CNFT1-2143]: https://cdc-nbs.atlassian.net/browse/CNFT1-2143?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-2143] Lab Report Delete return route

---

apps/modernization-ui/src/styles/_uswds.scss

Removing line height to correct placement of text within our .usa-button
* [CNFT-2239](https://cdc-nbs.atlassian.net/browse/CNFT1-2339)

removing line height from usa button

---

apps/modernization-ui/src/apps/search/advancedSearch/AdvancedSearch.tsx
apps/modernization-ui/src/apps/search/advancedSearch/components/OutOfTabOrder/OutOfTabOrder.spec.tsx
apps/modernization-ui/src/apps/search/advancedSearch/components/OutOfTabOrder/OutOfTabOrder.tsx
apps/modernization-ui/src/apps/search/advancedSearch/components/OutOfTabOrder/index.tsx
apps/modernization-ui/src/apps/search/patient/result/PatientResult.tsx

Creating a component to enable skipping through the tab order when wrapping the child element within the outOfTabOrder component.
Ensuring that from the Sort By dropdown we can tab directly to the first element in the search results.
Tickets
[CNFT-1980](https://cdc-nbs.atlassian.net/browse/CNFT1-1980)

creating out of tab order component

---

.github/workflows/Regression-tests.yaml
testing/regression/.gitignore
testing/regression/cypress.config.js
testing/regression/github-report.js
testing/regression/package-lock.json
testing/regression/package.json

Creates a GitHub Action to execute Cypress tests against the specified environment.
The tests will run nightly at 3am EST against the int1 environment. There is also a `workflow_dispatch` added to allow manual execution of the workflow. 
* [CNT-28](https://cdc-nbs.atlassian.net/browse/CNT-28)
[Workflow run](https://github.com/CDCgov/NEDSS-Modernization/actions/runs/9276096208)
[CNT-28]: https://cdc-nbs.atlassian.net/browse/CNT-28?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Cypress e2e action for INT1 

---

apps/modernization-ui/src/apps/page-builder/components/MoreOptions/MoreOptions.tsx
apps/modernization-ui/src/apps/page-builder/page/management/edit/section/SectionHeader.tsx
apps/modernization-ui/src/apps/page-builder/page/management/edit/subsection/SubsectionHeader.tsx
testing/regression/cypress/e2e/features/edit-page/deleteSection.feature
testing/regression/cypress/e2e/pages/edit-page/deleteSection.page.js
testing/regression/cypress/step_definitions/edit-page/deleteSection.steps.js

Added end to end test case for delete a section with subsections via edit page view ( [CNFT2-2295](https://cdc-nbs.atlassian.net/browse/CNFT2-2295) )
[CNFT2-2295]: https://cdc-nbs.atlassian.net/browse/CNFT2-2295?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNT-26] - E2E for Delete Section with subsections via edit page view

---

testing/regression/cypress/e2e/features/edit-page/deleteSection.feature
testing/regression/cypress/step_definitions/edit-page/deleteSection.steps.js

Added end to end test case for delete a section without subsection ( [CNFT2-2296](https://cdc-nbs.atlassian.net/browse/CNFT2-2296) )
[CNFT2-2296]: https://cdc-nbs.atlassian.net/browse/CNFT2-2296?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNT-26] - Delete a section without subsection

---

apps/nbs-gateway/src/main/java/gov/cdc/nbs/gateway/classic/NBSClassicService.java
apps/nbs-gateway/src/main/java/gov/cdc/nbs/gateway/classic/report/NBS6ReportCancelRouteLocatorConfiguration.java
apps/nbs-gateway/src/main/java/gov/cdc/nbs/gateway/classic/report/NBS6ReportPageRouteLocatorConfiguration.java
apps/nbs-gateway/src/main/java/gov/cdc/nbs/gateway/classic/report/NBS6ReportRunnerRouteLocatorConfiguration.java
apps/nbs-gateway/src/main/java/gov/cdc/nbs/gateway/classic/report/NBSReportCookie.java
apps/nbs-gateway/src/main/resources/application.yml
apps/nbs-gateway/src/test/java/gov/cdc/nbs/gateway/classic/report/NBS6ReportCancelRouteLocatorConfigurationTest.java
apps/nbs-gateway/src/test/java/gov/cdc/nbs/gateway/classic/report/NBS6ReportPageRouteLocatorConfigurationTest.java
apps/nbs-gateway/src/test/java/gov/cdc/nbs/gateway/classic/report/NBS6ReportRunnerRouteLocatorConfigurationTest.java

The `nbs-gateway` sets the `Referrer-Policy` to `no-referrer` which prevents the `Referer` header from being added to requests.  The NBS6 `ReportWebProcessor` relies on the value of the `Referer `header to resolve which report to run.  The `NBS-Report` cookie has been added to store which report is being run.  The value of the cookie is used to create an appropriate `Referer` header for the NBS6 `ReportWebProcessor`.
* [CNFT1-2392](https://cdc-nbs.atlassian.net/browse/CNFT1-2392)
[CNFT1-2392]: https://cdc-nbs.atlassian.net/browse/CNFT1-2392?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-2392] Adds routing that allows reports to be run in NBS6

---

apps/modernization-ui/src/apps/page-builder/page/management/edit/content/PageSideMenu.tsx
apps/modernization-ui/src/apps/page-builder/page/management/edit/section/manage/AddSection.tsx
apps/modernization-ui/src/apps/page-builder/page/management/edit/section/manage/ManageSection.tsx
apps/modernization-ui/src/apps/page-builder/page/management/edit/section/manage/ManageSectionTile/ManageSectionTile.tsx
testing/regression/cypress/e2e/features/create-page/pageElements.feature
testing/regression/cypress/e2e/features/edit-page/addSection.feature
testing/regression/cypress/e2e/features/edit-page/deleteSection.feature
testing/regression/cypress/e2e/features/edit-page/manageSection.feature
testing/regression/cypress/e2e/pages/edit-page/manageSection.page.js
testing/regression/cypress/step_definitions/edit-page/manageSection.steps.js

Added end to end test case to verify Manage sections modal displays key elements ( [CNFT2-1803](https://cdc-nbs.atlassian.net/browse/CNFT2-1803) )
[CNFT2-1803]: https://cdc-nbs.atlassian.net/browse/CNFT2-1803?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNT-26] - E2E to verify Manage sections modal displays key elements

---

apps/modernization-api/src/main/resources/application.yml
apps/nbs-gateway/src/main/java/gov/cdc/nbs/security/oidc/OIDCAuthenticationConfiguration.java

Adds `/goodbye` and `/expired` to the ignored paths of `moderniztion-api` so that they accessible without the need for authentication.
* [CNFT1-2429](https://cdc-nbs.atlassian.net/browse/CNFT1-2429)
[CNFT1-2429]: https://cdc-nbs.atlassian.net/browse/CNFT1-2429?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-2429] adds /goodbye and /expired to the ignored paths of moderniztion-api

---

testing/regression/cypress/e2e/features/edit-page/addEditSearchDeleteQuestion.feature
testing/regression/cypress/e2e/pages/edit-page/addEditSearchDeleteQuestion.page.js
testing/regression/cypress/step_definitions/edit-page/addEditSearchDeleteQuestion.steps.js

Added end to end test to verify question added to a page is not searchable ( [CNFT2-1833](https://cdc-nbs.atlassian.net/browse/CNFT2-1833) )
[CNFT2-1833]: https://cdc-nbs.atlassian.net/browse/CNFT2-1833?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNT-30] - E2E to verify question added to a page is not searchable

---

apps/nbs-gateway/src/main/java/gov/cdc/nbs/gateway/classic/NBSClassicServiceProvider.java
apps/nbs-gateway/src/main/java/gov/cdc/nbs/gateway/ui/ModernizedUIRoutes.java
apps/nbs-gateway/src/main/java/gov/cdc/nbs/security/oidc/NBS6LogoutRouteLocatorConfiguration.java
apps/nbs-gateway/src/test/java/gov/cdc/nbs/gateway/ui/ModernizedUIRoutesTest.java
apps/nbs-gateway/src/test/java/gov/cdc/nbs/security/oidc/NBS6LogoutRouteLocatorConfigurationTest.java

- Ensures that `/nbs/logout` redirects to `/logout` when OIDC is enabled.
- Ensures that `/nbs/logOut` redirects to `/goodbye`

[FIX] Updates the nbs-gateway routes to allow logout

---

libs/options-api/src/main/java/gov/cdc/nbs/option/jdbc/autocomplete/SQLBasedOptionResolver.java
libs/options-api/src/main/java/gov/cdc/nbs/option/resultedtest/autocomplete/ResultedTestOptionAutocompleteController.java
libs/options-api/src/main/java/gov/cdc/nbs/option/resultedtest/autocomplete/ResultedTestOptionResolver.java
libs/options-api/src/test/java/gov/cdc/nbs/option/resultedtest/autocomplete/ResultedTestAutocompleteRequester.java
libs/options-api/src/test/java/gov/cdc/nbs/option/resultedtest/autocomplete/ResultedTestAutocompleteSteps.java
libs/options-api/src/test/java/gov/cdc/nbs/option/resultedtest/autocomplete/ResultedTestOptionMother.java
libs/options-api/src/test/java/gov/cdc/nbs/option/resultedtest/autocomplete/ResultedTestOptionSteps.java
libs/options-api/src/test/resources/features/resultedtests/ResultedTestOptions.feature

Reuse SQLBasedOptionResolver like other autocompletes.  Union Lab_test (local) and LOINC_code resulted tests.  Search codes and values.  ResultedTestOptionMother can create arbitrary entries to test with.
* [CNFT1-2328](https://cdc-nbs.atlassian.net/browse/CNFT1-2328)
[CNFT1-2328]: https://cdc-nbs.atlassian.net/browse/CNFT1-2328?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT1-2328 Resulted test auto-complete API

---

apps/modernization-ui/src/authorization/ProtectedLayout.tsx
apps/modernization-ui/src/configuration/configuration.ts
apps/modernization-ui/src/configuration/currentConfiguration.ts
apps/modernization-ui/src/configuration/defaults.ts
apps/modernization-ui/src/configuration/useConfiguration.tsx
apps/nbs-gateway/src/main/java/gov/cdc/nbs/security/oidc/NBS6LoginRouteLocatorConfiguration.java
apps/nbs-gateway/src/main/java/gov/cdc/nbs/security/oidc/NBS6LogoutRouteLocatorConfiguration.java
apps/nbs-gateway/src/main/java/gov/cdc/nbs/security/oidc/OIDCAuthenticationConfiguration.java
apps/nbs-gateway/src/main/resources/application.yml
apps/nbs-gateway/src/test/java/gov/cdc/nbs/security/oidc/NBS6LogoutRouteLocatorConfigurationTest.java

The idle timer was routing to `/nbs/logout` since it was created before the `expired` page existed.  It seemed to work because it was hitting NBS6 unauthenticated forcing a redirect to the timeout page.  
- The settings for the warning and expiration times were added to the UI configuration
- Changes the security configuration to remove the Spring Security default logout page with confirmation.
* [CNFT1-2302](https://cdc-nbs.atlassian.net/browse/CNFT1-2302)
[CNFT1-2302]: https://cdc-nbs.atlassian.net/browse/CNFT1-2302?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-2302] timeout / expired routing

---

apps/modernization-api/src/main/java/gov/cdc/nbs/patient/search/redirect/SearchRedirectController.java
apps/modernization-api/src/main/resources/application-development.yml
apps/modernization-api/src/main/resources/application.yml
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/search/redirect/AdvancedSearchRedirectSteps.java

We need to be able to switch from simple to the new advanced search.  Feature flag the current `advanced-search` to allow it to be replaced with `search` the new advanced search and store the value in application.yml under `nbs.search.advanced-search-path`
* [CNFT1-2428](https://cdc-nbs.atlassian.net/browse/CNFT1-2428)
[CNFT1-2428]: https://cdc-nbs.atlassian.net/browse/CNFT1-2428?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT1-2428 Feature flag simple to advanced search

---

apps/modernization-api/build.gradle
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/profile/address/PatientAddressFinder.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/profile/phone/PatientPhoneFinder.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/PatientCreateAssertions.java
libs/database-entities/src/main/java/gov/cdc/nbs/entity/odse/Locator.java
libs/database-entities/src/main/java/gov/cdc/nbs/entity/odse/PostalEntityLocatorParticipation.java
libs/database-entities/src/main/java/gov/cdc/nbs/entity/odse/PostalLocator.java
libs/database-entities/src/test/java/gov/cdc/nbs/entity/odse/PersonTest.java

The `last_chg_time` was not being set when a Patient's address was updated.
* [CNFT1-2518](https://cdc-nbs.atlassian.net/browse/CNFT1-2518)
[CNFT1-2518]: https://cdc-nbs.atlassian.net/browse/CNFT1-2518?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-2518] Ensures last change time is set for Address update

---

apps/modernization-api/src/main/java/gov/cdc/nbs/event/search/LabReportFilter.java
apps/modernization-api/src/main/resources/graphql/labReport.graphqls
apps/modernization-api/src/main/resources/graphql/patient-lab-report.graphqls
apps/modernization-api/src/test/java/gov/cdc/nbs/event/search/labreport/LabReportSearchCriteriaSteps.java
apps/modernization-api/src/test/resources/features/search/lab-report/LabReportSearch.feature
apps/modernization-ui/src/generated/graphql/schema.ts
apps/modernization-ui/src/generated/schema.graphqls

Make new API backwards compatible with old by adding optional `orderingLabId` and `orderingProviderId` to `LabReportFilter`.  This allows us to use these criteria together vs previously you could only select one.
* [CNFT1-2478](https://cdc-nbs.atlassian.net/browse/CNFT1-2478)
* [CNFT1-2479](https://cdc-nbs.atlassian.net/browse/CNFT1-2479)
[CNFT1-2478]: https://cdc-nbs.atlassian.net/browse/CNFT1-2478?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CNFT1-2479]: https://cdc-nbs.atlassian.net/browse/CNFT1-2479?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT1-2478 CNFT1-2479 Lab Search API: ordering provider, facility

---

apps/modernization-api/src/main/java/gov/cdc/nbs/event/search/LabReportFilter.java
apps/modernization-api/src/main/resources/graphql/labReport.graphqls
apps/modernization-api/src/main/resources/graphql/patient-lab-report.graphqls
apps/modernization-api/src/test/java/gov/cdc/nbs/event/search/labreport/LabReportSearchCriteriaSteps.java
apps/modernization-api/src/test/resources/features/search/lab-report/LabReportSearch.feature
apps/modernization-ui/src/generated/graphql/schema.ts
apps/modernization-ui/src/generated/schema.graphqls

Make new API backwards compatible with old by adding optional `reportingLabId` to `LabReportFilter`.  This allows us to use these criteria together vs previously you could only select one.
* [CNFT1-2480](https://cdc-nbs.atlassian.net/browse/CNFT1-2480)
[CNFT1-2480]: https://cdc-nbs.atlassian.net/browse/CNFT1-2480?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT1-2480 API: Lab search API- Reporting facility

---

apps/modernization-ui/src/apps/search/laboratory-report/CriteriaFields.spec.tsx
apps/modernization-ui/src/apps/search/laboratory-report/CriteriaFields.tsx
apps/modernization-ui/src/components/Accordion/accordion.module.scss

Fixing the capitalization of the Lab report criteria, for consistency sake.
Tacked on a styling update to Accordian component.
* [CNFT1-2732](https://cdc-nbs.atlassian.net/browse/CNFT1-2732)
[CNFT1-2732]: https://cdc-nbs.atlassian.net/browse/CNFT1-2732?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT1-2732 Lab report: label

---

apps/modernization-api/src/main/java/gov/cdc/nbs/patient/profile/redirect/incoming/ModernizedPatientProfileRedirect.java
apps/modernization-api/src/main/resources/application.yml
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/redirect/incoming/ModernizedPatientProfileRedirectResolverTest.java
libs/redirect/src/main/java/gov/cdc/nbs/redirect/RedirectionConfiguration.java
libs/redirect/src/test/java/gov/cdc/nbs/redirect/RedirectControllerTest.java

Replace the legacy search paths with new search paths.  `/advanced-search` => `/search`.  Note that new advanced search will now have the path `/search`.  Also, set the feature flagged path `nbs.search.advanced-search-path`.
* [CNFT1-2440](https://cdc-nbs.atlassian.net/browse/CNFT1-2440)
[CNFT1-2440]: https://cdc-nbs.atlassian.net/browse/CNFT1-2440?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Advanced Search Go Live

---

apps/modernization-ui/src/apps/page-builder/components/AlertBanner/AlertBanner.tsx
apps/modernization-ui/src/apps/search/NoPatientInputBanner.tsx
apps/modernization-ui/src/apps/search/NoPatientResultsBanner.tsx
apps/modernization-ui/src/apps/search/layout/SearchLayout.spec.tsx
apps/modernization-ui/src/apps/search/layout/SearchLayout.tsx
apps/modernization-ui/src/apps/search/layout/result/SearchResults.tsx
apps/modernization-ui/src/apps/search/layout/result/search-results.module.scss
apps/modernization-ui/src/apps/search/layout/search-layout.module.scss
apps/modernization-ui/src/apps/search/no-patient-result-banner.module.scss
apps/modernization-ui/src/apps/search/patient/PatientSearch.tsx
apps/modernization-ui/src/apps/search/useSearch.spec.tsx
apps/modernization-ui/src/apps/search/useSearch.ts
apps/modernization-ui/src/apps/search/useSearchResultDisplay.tsx
apps/modernization-ui/src/page/usePage.tsx

As a NBS user, I want to see No results found page when search results are not found, so that its clear that no data match was found.
Figma: https://www.figma.com/design/TVilgvbjEwoYTqtQekVZwJ/NBS-7.x--%3E-Patient-Search-2.0?node-id=2524-242120&t=9cOoNI4rXV2LzxW1-4Connect your Figma account 
Acceptance Criteria
Create a new UI page to display search results when no matching records are found.
The empty results page should include a clear message indicating that no results were found for the given search criteria.
As a NBS user, I want to see No results found page when user does not enter any inputs, so that its clear that no search criteria was provided.
Figma link: https://www.figma.com/design/TVilgvbjEwoYTqtQekVZwJ/NBS-7.x--%3E-Patient-Search-2.0?node-id=2524-36173&t=9cOoNI4rXV2LzxW1-4Co …

Cnft1 2468 no results page, CNFT1 2469 no input results page

---

apps/modernization-ui/src/apps/search/investigation/InvestigationSearch.tsx
apps/modernization-ui/src/apps/search/laboratory-report/LaboratoryReportSearch.tsx
apps/modernization-ui/src/apps/search/layout/SearchLayout.spec.tsx
apps/modernization-ui/src/apps/search/layout/SearchLayout.tsx
apps/modernization-ui/src/apps/search/layout/result/SearchResults.tsx
apps/modernization-ui/src/apps/search/layout/result/header/SearchResultsHeader.tsx
apps/modernization-ui/src/apps/search/layout/result/header/terms/SearchTerms.tsx
apps/modernization-ui/src/apps/search/layout/result/header/terms/search-terms.module.scss
apps/modernization-ui/src/apps/search/patient/PatientSearch.tsx
apps/modernization-ui/src/design-system/select/multi/MultiSelect.tsx

adding chips ui and hooking up the search and form update when removing a chip with the close button
Update the search criteria in the search results section
* [CNFT1-2788](https://cdc-nbs.atlassian.net/browse/CNFT1-2788)
[CNFT1-2788]: https://cdc-nbs.atlassian.net/browse/CNFT1-2788?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

adding chips ui and hooking up the search and form update 

---

apps/modernization-ui/src/apps/search/advancedSearch/AdvancedSearch.tsx
apps/modernization-ui/src/apps/search/layout/result/header/options/list/SearchResultsListOptions.tsx
apps/modernization-ui/src/apps/search/patient/PatientSearch.tsx
apps/modernization-ui/src/components/ButtonActionMenu/ButtonActionMenu.spec.tsx
apps/modernization-ui/src/components/ButtonActionMenu/ButtonActionMenu.tsx
apps/modernization-ui/src/components/ButtonActionMenu/buttonActionMenu.module.scss

Refactoring ButtonActionMenu to accept menu content as {children} to enable more custom content, such as drag-drop tiles.
* [CNFT1-2804](https://cdc-nbs.atlassian.net/browse/CNFT1-2804)
[CNFT1-2804]: https://cdc-nbs.atlassian.net/browse/CNFT1-2804?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT1-2804 Refactor ButtonActionMenu

---

apps/nbs-gateway/Dockerfile

Resolves (hopefully) the issue of the missing ciphers in the docker container when executed locally and pointed at the foundation team sandbox 2 ALB.

Add jdk.crypto.cryptoki module to ensure cipher availability"

---

apps/modernization-ui/src/apps/landing/SignUp/SignUp.tsx
apps/modernization-ui/src/apps/landing/SignUp/useSignUp.ts

fixing url email domain name is changed correctly but clicking the email link is showing .org still
* [CNFT1-2758](https://cdc-nbs.atlassian.net/browse/CNFT1-2758)
[CNFT1-2758]: https://cdc-nbs.atlassian.net/browse/CNFT1-2758?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

adding .gov instead of .org for cdc website

---

testing/regression/cypress/e2e/hl7/elr-generate.feature
testing/regression/cypress/e2e/pages/searchEvent.page.js
testing/regression/cypress/step_definitions/hl7/generate-mark-reviewed.steps.js

Change the E2E testing from wait to Poll and Retry .
* [CNT-49](https://cdc-nbs.atlassian.net/browse/CNT-49)
[CNT-49]: https://cdc-nbs.atlassian.net/browse/CNT-49?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNT-49 E2E testing from wait to Poll and Retry

---

apps/nbs-gateway/Dockerfile

Adds the [nbs-gateway fix](https://github.com/CDCgov/NEDSS-Modernization/pull/1583) to the 7.5.0 release branch.

Add jdk.crypto.cryptoki module to ensure cipher availability" (#1583)

---

apps/modernization-api/src/main/java/gov/cdc/nbs/patient/profile/redirect/incoming/ModernizedPatientProfileRedirect.java
apps/nbs-gateway/src/main/java/gov/cdc/nbs/gateway/filter/RemoveCookieGatewayFilterFactory.java
apps/nbs-gateway/src/main/java/gov/cdc/nbs/gateway/patient/profile/events/investigation/ViewInvestigationRouteLocatorConfiguration.java
apps/nbs-gateway/src/main/java/gov/cdc/nbs/gateway/patient/profile/events/observation/ViewObservationRouteLocatorConfiguration.java
apps/nbs-gateway/src/test/java/gov/cdc/nbs/gateway/filter/RemoveCookieGatewayFilterFactoryTest.java
apps/nbs-gateway/src/test/java/gov/cdc/nbs/gateway/patient/profile/events/investigation/ViewInvestigationRouteLocatorConfigurationTest.java
apps/nbs-gateway/src/test/java/gov/cdc/nbs/gateway/patient/profile/events/observation/ViewObservationRouteLocatorConfigurationTest.java
apps/nbs-gateway/src/test/resources/application-remove-cookie-gateway-filter.yml

The `Return-Patient` cookie was not being removed when routing back to the patient profile which was causing routing to go to the previous patient as the `Return-Patient` cookie has precedence over `Patient-Action`
* [CNFT1-2807](https://cdc-nbs.atlassian.net/browse/CNFT1-2807)
[CNFT1-2807]: https://cdc-nbs.atlassian.net/browse/CNFT1-2807?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-2807] Ensures that Return-Patient cookie is removed after use

---

apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/entity/CodeValueGeneralRepository.java
apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/question/QuestionManagementUtil.java
apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/question/QuestionManagementUtilTest.java

A 500 server error is being thrown when attempting to create a new page builder question using the `SNOMED_CT_HL7` code system. This is due to there being multiple entries in the `code_value_general` with the `SNOMED_CT_HL7`  code.
This PR updates the query to specify the `code_value_general` `code_set_nm` along with the `code` to correctly select only 1 entry from the db.
*  TBD - awaiting bug creation

Code System Lookup Fix

---

apps/modernization-api/Dockerfile
apps/question-bank/Dockerfile

Add additional SSL Cipher support to modernization-api and question-bank docker containers in the same manner as it was added to the nbs-gateway here:
https://github.com/CDCgov/NEDSS-Modernization/pull/1583

Adds the cipher dependency to JRE

---

apps/modernization-ui/src/apps/patient/add/AddPatient.tsx
apps/modernization-ui/src/apps/patient/add/otherInfoFields/OtherInfoFields.tsx

Toggling `Is the patient deceased` to a value and then back to null causes an error on submission. This is due to the form value being set to an empty string: ''.
Changing this to undefined at time of submission resolves the issue.
* [CNFT1-2845](https://cdc-nbs.atlassian.net/browse/CNFT1-2845)
[CNFT1-2845]: https://cdc-nbs.atlassian.net/browse/CNFT1-2845?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Prevent submission of empty string for deceased value. Type form

---

apps/modernization-ui/src/apps/search/investigation/GeneralSearchFields.spec.tsx
apps/modernization-ui/src/apps/search/investigation/GeneralSearchFields.tsx
apps/modernization-ui/src/design-system/autocomplete/single/Autocomplete.tsx

Displays the `Event ID` field when an `Event ID type` is selected. Matching the behavior of search v1, `Event ID` is required if an `Event ID type` is selected.
* [CNFT1-2760](https://cdc-nbs.atlassian.net/browse/CNFT1-2760)
[CNFT1-2760]: https://cdc-nbs.atlassian.net/browse/CNFT1-2760?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add event id field when event id type is selected

---

apps/modernization-api/src/main/java/gov/cdc/nbs/patient/search/PatientSearchCriteriaSortResolver.java

The field to sort by is `patient` not `id`
* [CNFT1-2555](https://cdc-nbs.atlassian.net/browse/CNFT1-2555)
```"findPatientsByFilter":{"content":[{"patient":-19999759,...```
[CNFT1-2555]: https://cdc-nbs.atlassian.net/browse/CNFT1-2555?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix id sorting

---

apps/modernization-ui/src/apps/page-builder/page/management/preview/PreviewPage.tsx
apps/modernization-ui/src/apps/page-builder/page/management/preview/PublishPage/PublishPage.tsx
apps/modernization-ui/src/apps/page-builder/page/management/preview/information/PageInformation.tsx
testing/regression/cypress/e2e/features/preview-page/previewPage.feature
testing/regression/cypress/e2e/pages/preview-page/previewPage.page.js
testing/regression/cypress/step_definitions/preview-page/previewPage.steps.js

Added end to end test case for preview and publish page has View page details and edit [CNFT2-1978](https://cdc-nbs.atlassian.net/browse/CNFT2-1978)
[CNFT2-1978]: https://cdc-nbs.atlassian.net/browse/CNFT2-1978?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNT-45] - Preview and publish - View page details and edit

---

apps/modernization-ui/src/apps/search/investigation/InvestigationSearch.tsx
apps/modernization-ui/src/apps/search/investigation/result/list/InvestigationSearchResultListItem.module.scss
apps/modernization-ui/src/apps/search/investigation/result/list/InvestigationSearchResultListItem.spec.tsx
apps/modernization-ui/src/apps/search/investigation/result/list/InvestigationSearchResultListItem.tsx
apps/modernization-ui/src/apps/search/laboratory-report/result/list/LaboratoryReportSearchResultListItem.spec.tsx
apps/modernization-ui/src/apps/search/laboratory-report/result/list/LaboratoryReportSearchResultListItem.tsx
apps/modernization-ui/src/apps/search/layout/result/header/terms/search-terms.module.scss

Changes the `Link` to a `ClassicLink` in the Investigation Search Result Item component so that the user can click to navigate to the Investigation.
- Refactors the `InvestigationSearchResultListItem` to use the standardized search result components `Result`, `ResultItemGroup`, and `ResultItem`.
- Adds unit tests for `InvestigationSearchResultListItem`
* [CNFT1-2829](https://cdc-nbs.atlassian.net/browse/CNFT1-2829)
[CNFT1-2829]: https://cdc-nbs.atlassian.net/browse/CNFT1-2829?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-2829] Investigations Search Result link to investigation

---

apps/modernization-api/src/main/java/gov/cdc/nbs/event/search/InvestigationFilter.java
apps/modernization-api/src/main/resources/graphql/investigation.graphqls
apps/modernization-api/src/test/java/gov/cdc/nbs/event/search/investigation/InvestigationSearchCriteriaSteps.java
apps/modernization-api/src/test/resources/features/search/investigation/InvestigationSearch.feature
apps/modernization-ui/src/generated/graphql/schema.ts
apps/modernization-ui/src/generated/schema.graphqls

Make new API backwards compatible with old by adding optional `reportingProviderId` to `InvestigationFilter`. This allows us to use these criteria together vs previously you could only select one.
* [CNFT1-2482](https://cdc-nbs.atlassian.net/browse/CNFT1-2482)
[CNFT1-2482]: https://cdc-nbs.atlassian.net/browse/CNFT1-2482?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT1-2482 API: Investigation search Reporting provider

---

apps/modernization-ui/src/apps/landing/SignIn/SignIn.tsx
apps/modernization-ui/src/apps/landing/SignIn/signIn.module.scss

Sets the target of the "Login to NBS demo site" button to _self to ensure that the user stays in the same tab.
* [CNFT1-2599](https://cdc-nbs.atlassian.net/browse/CNFT1-2599)
[CNFT1-2599]: https://cdc-nbs.atlassian.net/browse/CNFT1-2599?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-2599] "Login to NBS demo site" link in same tab

---

apps/modernization-ui/src/apps/search/patient/add/asNewPatientEntry.spec.ts
apps/modernization-ui/src/apps/search/patient/add/asNewPatientEntry.ts

The new patient form is driven by an object, when coming from a search without an email address there was no initial email object created to make the email input show up.  The `asNewPatientEntry` function was changed to ensure that an email address is present in the array to make the input show up.
* [CNFT1-2852](https://cdc-nbs.atlassian.net/browse/CNFT1-2852)
[CNFT1-2852]: https://cdc-nbs.atlassian.net/browse/CNFT1-2852?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-2852] Ensures that the email input is present.

---

apps/modernization-ui/src/apps/search/layout/SearchLayout.tsx

Using "enter or return" key press on keyboard to trigger search in new search forms
* [CNFT1-2853](https://cdc-nbs.atlassian.net/browse/CNFT1-2853)
[CNFT1-2853]: https://cdc-nbs.atlassian.net/browse/CNFT1-2853?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

adding keypress listener triggering onSearch in search layout

---

apps/modernization-ui/src/apps/search/investigation/GeneralSearchFields.tsx
apps/modernization-ui/src/apps/search/investigation/investigationTermsResolver.spec.ts
apps/modernization-ui/src/apps/search/investigation/investigationTermsResolver.ts
apps/modernization-ui/src/apps/search/laboratory-report/GeneralFields.tsx
apps/modernization-ui/src/apps/search/laboratory-report/laboratoryReportTermsResolver.spec.ts
apps/modernization-ui/src/apps/search/laboratory-report/laboratoryReportTermsResolver.ts

Investigations - General search - Event provider - Duplicate chips displaying in search results header
Investigations: Not able to search with Event facility type
* [CNFT1-2810](https://cdc-nbs.atlassian.net/browse/CNFT1-2810)
* [CNFT1-2848](https://cdc-nbs.atlassian.net/browse/CNFT1-2848)
[CNFT1-2810]: https://cdc-nbs.atlassian.net/browse/CNFT1-2810?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CNFT1-2848]: https://cdc-nbs.atlassian.net/browse/CNFT1-2848?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

adding fixes to bug in investigation and general fields and fixing tests

---

apps/modernization-ui/src/apps/search/patient/add/asNewPatientEntry.spec.ts
apps/modernization-ui/src/apps/search/patient/add/asNewPatientEntry.ts

The new patient form is driven by an object, when coming from a search without an identification there was no initial identification object created to make the identification input show up. The `asNewPatientEntry` function was changed to ensure that an email address is present in the array to make the input show up.
* [CNFT1-2854](https://cdc-nbs.atlassian.net/browse/CNFT1-2854)
[CNFT1-2854]: https://cdc-nbs.atlassian.net/browse/CNFT1-2854?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ensures that an identification exists for a new patient

---

apps/modernization-ui/src/apps/search/useSearchResultDisplay.tsx
apps/modernization-ui/src/apps/search/useSearchSettings.ts

saving search view type- list or table”, so that its easy for data search.
Whenever user changes the preference, Save the search preference in local Browser storage. 
* [CNFT1-2556](https://cdc-nbs.atlassian.net/browse/CNFT1-2556)
[CNFT1-2556]: https://cdc-nbs.atlassian.net/browse/CNFT1-2556?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

adding localStorage.getItem(defaultSearchView) as View

---

apps/modernization-api/src/main/java/gov/cdc/nbs/patient/search/PatientSearchCriteriaQueryResolver.java
apps/modernization-api/src/test/resources/features/patient/search/PatientSearch.feature

The story was written for last name with tilde.  Behind the scenes search uses `queryString` for 5 different searches: last name, first name, city, address, email.  Tilde is a special character used in advanced searches for fuzzy searching.  We have 2 options.  We can modify the input to make sure it's valid for special searches or switch to `simpleQueryString` (suggested by @adamloup-enquizit ) which is more forgiving with special characters.  This is the easiest path to fix this and we fix all the instances where it is used (5 total).  The test cases simply prove the searches don't blow up with a tilde (as they did previously) but are somewhat undefined (meaning sometimes they return matches searching with tildes and sometimes they don't depending on if the advanced search is …

CNFT1-2736 Fix search with special characters

---

apps/modernization-ui/src/components/selection/multi/MultiSelectInput.scss
apps/modernization-ui/src/components/selection/multi/MultiSelectInput.tsx
apps/modernization-ui/src/design-system/autocomplete/multi/AutocompleteMulti.tsx
apps/modernization-ui/src/design-system/checkbox/Checkbox.tsx
apps/modernization-ui/src/design-system/checkbox/checkbox.module.scss
apps/modernization-ui/src/design-system/select/multi/MultiSelect.tsx
apps/modernization-ui/src/design-system/select/multi/design.ts
apps/modernization-ui/src/design-system/select/multi/index.ts
apps/modernization-ui/src/design-system/select/multi/theme.ts

I'm not sure what the bug was referring to however, I've fixed the styling issue with options that have long names and ensure that the input box expands correctly in compact mode.
* [CNFT1-2875](https://cdc-nbs.atlassian.net/browse/CNFT1-2875)
[CNFT1-2875]: https://cdc-nbs.atlassian.net/browse/CNFT1-2875?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-2875] multi-select styles

---

apps/modernization-api/src/main/java/gov/cdc/nbs/patient/search/PatientSearchCriteriaQueryResolver.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/search/PatientSearchCriteriaSteps.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/search/PatientSearchVerificationSteps.java
apps/modernization-api/src/test/resources/features/patient/search/PatientSearch.feature
apps/modernization-api/src/test/resources/features/search/redirect/SimpleSearchRedirect.feature

adding empty string logic into applyPatientIdentifierCriteria.
* [CNFT1-2861](https://cdc-nbs.atlassian.net/browse/CNFT1-2861)
[CNFT1-2861]: https://cdc-nbs.atlassian.net/browse/CNFT1-2861?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

adding empty string logic into applyPatientIdentifierCriteria

---

apps/modernization-api/src/main/java/gov/cdc/nbs/search/redirect/simple/SimplePatientSearchCriteriaMerger.java
apps/modernization-api/src/main/java/gov/cdc/nbs/search/redirect/simple/SimplePatientSearchCriteriaResolver.java
apps/modernization-api/src/test/java/gov/cdc/nbs/search/redirect/simple/SimplePatientSearchCriteriaMergerTest.java
libs/options-api/src/main/java/gov/cdc/nbs/option/Option.java

Fixes the name ordering of searches from the home page.  A.K.A. This is why you don't skip the last 5% coverage.
* [CNFT1-2813](https://cdc-nbs.atlassian.net/browse/CNFT1-2813)
[CNFT1-2813]: https://cdc-nbs.atlassian.net/browse/CNFT1-2813?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-2813] ensures name ordering for home page search

---

README.md
apps/modernization-api/README.md
apps/question-bank/README.md
cdc-sandbox/build_classic.sh
cdc-sandbox/build_modernized.sh
cdc-sandbox/doc/build.md

Newer version of docker no longer supports `docker-compose` as this was deprecated in the migration to Go.
https://docs.docker.com/compose/migrate/

Fix docker-compose -> docker compose

---

libs/options-api/src/main/java/gov/cdc/nbs/option/providers/autocomplete/ProviderOptionResolver.java

Parenthesis were missing from the criteria that excludes electronic providers that was causing patients to be load in the provider list.
* [CNFT1-2892](https://cdc-nbs.atlassian.net/browse/CNFT1-2892)
[CNFT1-2892]: https://cdc-nbs.atlassian.net/browse/CNFT1-2892?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-2892] fixes criteria to exclude patients from providers list

---

apps/modernization-ui/src/apps/search/laboratory-report/LaboratoryReportSearch.tsx
apps/modernization-ui/src/apps/search/laboratory-report/result/index.ts
apps/modernization-ui/src/apps/search/laboratory-report/result/laboratoryReportResult.spec.tsx
apps/modernization-ui/src/apps/search/laboratory-report/result/laboratoryReportResult.tsx
apps/modernization-ui/src/apps/search/laboratory-report/result/list/LaboratoryReportSearchResultListItem.tsx
apps/modernization-ui/src/apps/search/laboratory-report/result/table/LaboratoryReportSearchResultsTable.spec.tsx
apps/modernization-ui/src/apps/search/laboratory-report/result/table/LaboratoryReportSearchResultsTable.tsx
apps/modernization-ui/src/apps/search/laboratory-report/result/table/index.ts

Adds Laboratory Report Search results table view.  
_Note:_ The duplicate associated investigation is coming from the API
* [CNFT1-2851](https://cdc-nbs.atlassian.net/browse/CNFT1-2851)
[CNFT1-2851]: https://cdc-nbs.atlassian.net/browse/CNFT1-2851?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-2851] Laboratory report search results table view

---

apps/modernization-ui/src/apps/search/layout/result/list/result-item.module.scss
apps/modernization-ui/src/apps/search/patient/result/list/PatientSearchResultListItem.module.scss

Search result list view headings should be base-darkest.
* [CNFT1-2888](https://cdc-nbs.atlassian.net/browse/CNFT1-2888)
[CNFT1-2888]: https://cdc-nbs.atlassian.net/browse/CNFT1-2888?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT1-2888 List view headings color

---

apps/modernization-ui/src/design-system/table/data-table.module.scss
apps/modernization-ui/src/design-system/table/header.module.scss

Bug to fix the column width for legal name so it doesn't keep changing when filtered or sorted.
* [CNFT1-2867](https://cdc-nbs.atlassian.net/browse/CNFT1-2867)
[CNFT1-2867]: https://cdc-nbs.atlassian.net/browse/CNFT1-2867?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Cnft1 2867 column width

---

apps/modernization-ui/src/apps/search/layout/result/SearchResults.tsx
apps/modernization-ui/src/apps/search/layout/result/header/options/search-results-options.module.scss
apps/modernization-ui/src/apps/search/layout/result/header/search-results-header.module.scss
apps/modernization-ui/src/apps/search/layout/result/header/terms/SearchTerms.tsx
apps/modernization-ui/src/apps/search/layout/result/header/terms/search-terms.module.scss
apps/modernization-ui/src/apps/search/layout/result/search-results.module.scss
apps/modernization-ui/src/design-system/chips/chip.module.scss

Fixing chips issue in search pages using useRef and use state to control height dynamically 
* [CNFT1-2925](https://cdc-nbs.atlassian.net/browse/CNFT1-2925)
[CNFT1-2925]: https://cdc-nbs.atlassian.net/browse/CNFT1-2925?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fixing search terms chips exceeding height spilling over results 

---

apps/modernization-ui/src/design-system/table/data-table.module.scss
apps/modernization-ui/src/styles/_colors.scss

Applies alternating background colors for the active sort column.
* [CNFT1-2940](https://cdc-nbs.atlassian.net/browse/CNFT1-2940)
[CNFT1-2940]: https://cdc-nbs.atlassian.net/browse/CNFT1-2940?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-2940] Alternating colors for the active sort column

---

apps/modernization-ui/src/components/button/Button.module.scss
apps/modernization-ui/src/components/button/Button.tsx
apps/modernization-ui/src/design-system/table/DataTableRow.tsx
apps/modernization-ui/src/design-system/table/HeightConstrained.tsx
apps/modernization-ui/src/design-system/table/height-constrained.module.scss

3 bugs with View more/less button:
1. Aligned button to the left
2. Changed it to a link and not a button
3. Also changed the aria label to have for example: 'view more address' or 'view more phone' or 'view less address'
* [CNFT1-2955](https://cdc-nbs.atlassian.net/browse/CNFT1-2955)
* [CNFT1-2953](https://cdc-nbs.atlassian.net/browse/CNFT1-2953)
[CNFT1-2955]: https://cdc-nbs.atlassian.net/browse/CNFT1-2955?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CNFT1-2953]: https://cdc-nbs.atlassian.net/browse/CNFT1-2953?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

view more/less button bugs fixed

---

apps/modernization-ui/src/generated/index.ts
apps/modernization-ui/src/generated/services/CodedResultOptionsService.ts
gradle/libs.versions.toml
libs/options-api/src/main/java/gov/cdc/nbs/option/coded/result/autocomplete/CodedResultOptionAutocompleteController.java
libs/options-api/src/main/java/gov/cdc/nbs/option/coded/result/autocomplete/CodedResultOptionResolver.java
libs/options-api/src/test/java/gov/cdc/nbs/option/coded/result/CodedResultOptionMother.java
libs/options-api/src/test/java/gov/cdc/nbs/option/coded/result/CodedResultOptionSteps.java
libs/options-api/src/test/java/gov/cdc/nbs/option/coded/result/autocomplete/CodedResultAutocompleteRequester.java
libs/options-api/src/test/java/gov/cdc/nbs/option/coded/result/autocomplete/CodedResultAutocompleteSteps.java
libs/options-api/src/test/resources/features/coded-result/CodedResultOptions.feature

Adds the `/nbs/api/options/coded-result/search` endpoint that allows autocompletion of Local and SNOMED coded results.  
- The `CodedResultOptionsService.codedResultAutocomplete` client has been generated. 
* [CNFT1-2943](https://cdc-nbs.atlassian.net/browse/CNFT1-2943)
[CNFT1-2943]: https://cdc-nbs.atlassian.net/browse/CNFT1-2943?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-2943] coded results autocomplete api

---

cdc-sandbox/keycloak/theme/nbs/login/login.ftl

Corrects the password reset email address to be `nbs@cdc.gov` in the keycloak login theme.

[FIX] Corrects the password reset email address

---

apps/modernization-ui/src/apps/search/layout/SearchLayout.tsx
apps/modernization-ui/src/apps/search/layout/search-layout.module.scss
apps/modernization-ui/src/design-system/collapsible-panel/CollapsiblePanel.tsx
apps/modernization-ui/src/design-system/collapsible-panel/collapsible-panel.module.scss

Makes the `CollapsiblePanel` slide to the left and give up previously occupied space.
* [CNFT1-2470](https://cdc-nbs.atlassian.net/browse/CNFT1-2470)
[CNFT1-2470]: https://cdc-nbs.atlassian.net/browse/CNFT1-2470?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-2470] Actually collapsible criteria

---

.github/workflows/Build-and-deploy-modernization-api.yaml
.github/workflows/Build-and-deploy-page-builder-api.yaml
.github/workflows/sonar.yaml

The sonar workflow runs all tests regardless of the api being updated. Due to this, the `PARAMETER_SECRET` is in fact required for the pagebuilder workflow.
1. Resets params to required in sonar since they are actually required for each container
2. Adds `PARAMETER_SECRET` to page builder workflow

Pagebuilder workflow fix

---

.gitignore
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/search/PatientSearchCriteriaSortResolver.java
apps/modernization-api/src/test/java/gov/cdc/nbs/RunCucumber.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/search/PatientSearchSortingSteps.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/search/PatientSearchVerificationSteps.java
apps/modernization-api/src/test/resources/features/patient/search/PatientSearch.sorting.feature

The recent changes to sorting broke a few of the sorting options on Patient Search. 
- Add support for sorting by `patientid` and `legalname` in Patient Search to match Investigation and Laboratory Search.
- Makes the `local` profile active for tests.

[FIX] Patient sorting

---

apps/modernization-ui/src/apps/patient/profile/sexBirth/BirthAndGenderEntryFields.tsx
apps/modernization-ui/src/location/useCountyCodedValues.ts

Changing the `state` value of the `Sex & birth` form was causing an error triggering a redirection. There was also an issue with the county value persisting when deselecting the state. 
* [CNFT1-2980](https://cdc-nbs.atlassian.net/browse/CNFT1-2980)
[CNFT1-2980]: https://cdc-nbs.atlassian.net/browse/CNFT1-2980?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Clear county when state value is cleared. Hook error fix

---

apps/modernization-ui/src/apps/search/investigation/result/table/InvestigationSearchResultsTable.spec.tsx
apps/modernization-ui/src/apps/search/investigation/result/table/InvestigationSearchResultsTable.tsx

Changes the investigation start date value from `addTime` to `startedOn` so that the displayed results would match the chosen sort.
* [CNFT1-2973](https://cdc-nbs.atlassian.net/browse/CNFT1-2973)
[CNFT1-2973]: https://cdc-nbs.atlassian.net/browse/CNFT1-2973?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-2973] Investigation add time to started on

---

apps/modernization-api/src/main/java/gov/cdc/nbs/event/search/labreport/ElasticsearchLabReportSearchResolver.java
apps/modernization-api/src/main/java/gov/cdc/nbs/event/search/labreport/LabReportSearchResult.java
apps/modernization-api/src/main/java/gov/cdc/nbs/event/search/labreport/LabReportSearchResultConverter.java
apps/modernization-api/src/main/java/gov/cdc/nbs/event/search/labreport/LabTestSummaryFinder.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/documentsrequiringreview/detail/LabTestSummaryRowMapper.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/documentsrequiringreview/detail/LaboratoryReportDetailRowMapper.java
apps/modernization-api/src/main/resources/graphql/lab-report-search.graphqls
apps/modernization-api/src/test/java/gov/cdc/nbs/event/search/labreport/LabReportSearchResultConverterTest.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/documentsrequiringreview/detail/LabTestSummaryRowMapperTest.java
apps/modernization-ui/src/apps/search/event/components/LabReportSearch/LabReportResults.spec.tsx
apps/modernization-ui/src/apps/search/laboratory-report/result/laboratoryReportResult.spec.tsx
apps/modernization-ui/src/apps/search/laboratory-report/result/list/LaboratoryReportSearchResultListItem.spec.tsx
apps/modernization-ui/src/apps/search/laboratory-report/result/table/LaboratoryReportSearchResultsTable.spec.tsx
apps/modernization-ui/src/generated/gql/queries/findLabReportsByFilter.gql
apps/modernization-ui/src/generated/graphql/schema.ts
apps/modernization-ui/src/generated/schema.graphqls

Create a `LabTestSummaryFinder` that finds resulted tests by observation_uid.  Do db lookup when converting the lab report results from elasticsearch and place the db fetched resulted tests into the labTestSummary field. Make old `LabTestSummaryRowMapper` implement `RowMapper<LabTestSummary>`.  Switch old calls from `map` to `mapRow`
* [CNFT1-2945](https://cdc-nbs.atlassian.net/browse/CNFT1-2945)
[CNFT1-2945]: https://cdc-nbs.atlassian.net/browse/CNFT1-2945?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
```
{
"data": {
"findLabReportsByFilter": {
"content": [
{
"relevance": 1.0,
"id": "10055288",
"jurisdictionCd": 130006,
"localId": "OBS10002000GA01",
"addTime": "2024-03-01",
"personParticipations": [
{
"birthTime": "1990-01-01",
"currSexCd": …
```

CNFT1-2928 API: Update Lab Search API to include Resulted Test Data

---

apps/modernization-ui/src/apps/search/patient/result/list/PatientSearchResultListItem.spec.tsx
apps/modernization-ui/src/apps/search/patient/result/list/PatientSearchResultListItem.tsx

adding no data indicator on ui for when id types no data displayed on the list view for patient search 
* [CNFT1-3051](https://cdc-nbs.atlassian.net/browse/CNFT1-3051)
[CNFT1-3051]: https://cdc-nbs.atlassian.net/browse/CNFT1-3051?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

adding no data indicator on ui for when id types no data

---

apps/modernization-ui/src/apps/dedup-config/DataElementsConfiguration/DataElementsConfiguration.tsx
apps/modernization-ui/src/apps/dedup-config/DataElementsConfiguration/DataElementsTable.tsx
apps/modernization-ui/src/apps/dedup-config/DataElementsConfiguration/data-elements-configuration.module.scss
apps/modernization-ui/src/apps/dedup-config/DataElementsConfiguration/data-elements-table.module.scss
apps/modernization-ui/src/components/Entry/EntryWrapper.tsx
apps/modernization-ui/src/components/Entry/HorizontalEntryWrapper.tsx
apps/modernization-ui/src/components/Entry/VerticalEntryWrapper.tsx
apps/modernization-ui/src/components/Entry/entry-wrapper.module.scss
apps/modernization-ui/src/components/Entry/vertical-entry-wrapper.module.scss
apps/modernization-ui/src/components/FormInputs/Input.tsx
apps/modernization-ui/src/design-system/table/DataTable.tsx
apps/modernization-ui/src/design-system/table/DataTableRow.tsx

Error handling with tooltips and highlighting in Data Element rows
* [CNFT2-2767](https://cdc-nbs.atlassian.net/browse/CNFT2-2767)
[CNFT2-2767]: https://cdc-nbs.atlassian.net/browse/CNFT2-2767?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT2-2767 Error tooltips

---

apps/modernization-api/src/main/java/gov/cdc/nbs/patient/profile/NewPatient.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/profile/PatientCreateController.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/profile/phone/change/PatientPhoneChangeService.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/PatientCreateSteps.java
apps/modernization-api/src/test/resources/features/patient/profile/PatientProfileCreate.feature

Build on https://github.com/CDCgov/NEDSS-Modernization/pull/1660 and expand the requestbody to include Phones (and emails). Use the existing service to add phones once the patient is created.
* [CNFT1-2770](https://cdc-nbs.atlassian.net/browse/CNFT1-2770)
[CNFT1-2770]: https://cdc-nbs.atlassian.net/browse/CNFT1-2770?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT1-2770 API: Create Extended patient data entry form for Phone/email

---

.github/workflows/sonar.yaml

Resolves deprecation by bumping the version of `upload-artifact` to `v4`

Bump upload-artifact to v4

---

apps/modernization-ui/src/apps/dedup-config/DataElementsConfiguration/DataElementsConfiguration.tsx

save data elements

---

apps/modernization-ui/src/apps/search/laboratory-report/result/ResultedTestDisplay.tsx

"Reference from" phrase is now displaying in bold
* [CNFT1-3073](https://cdc-nbs.atlassian.net/browse/CNFT1-3073)
[CNFT1-3073]: https://cdc-nbs.atlassian.net/browse/CNFT1-3073?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

reference from bug

---

apps/modernization-api/src/main/java/gov/cdc/nbs/patient/profile/NewPatient.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/profile/PatientCreateController.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/profile/identification/change/NewPatientIdentificationInput.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/profile/identification/change/PatientIdentificationChangeService.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/profile/race/change/PatientRaceChangeService.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/PatientCreateSteps.java
apps/modernization-api/src/test/resources/features/patient/profile/PatientProfileCreate.feature

Build on https://github.com/CDCgov/NEDSS-Modernization/pull/1660 and expand the requestbody to include Races. Use the existing service to add races once the patient is created.
* [CNFT1-2774](https://cdc-nbs.atlassian.net/browse/CNFT1-2774)
[CNFT1-2774]: https://cdc-nbs.atlassian.net/browse/CNFT1-2774?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT1-2774 API: Create Extended patient data entry for Race, Identification

---

apps/modernization-ui/src/apps/search/useSearchCriteria.ts
apps/modernization-ui/src/apps/search/useSearchResults.ts
apps/modernization-ui/src/apps/search/useSearchResultsFormAdapter.ts

This is an attempt to fix an issue encountered in the INT1 environment that I am unable to recreate locally.  When trying to recreate the issue I noticed that when searching from the home page the URL is reset after the search has completed.  This did not prevent the results from showing up locally. 
* [CNFT1-3074](https://cdc-nbs.atlassian.net/browse/CNFT1-3074)
[CNFT1-3074]: https://cdc-nbs.atlassian.net/browse/CNFT1-3074?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-3074] Fixes interaction between useSearchCriteria and useSearchResults to prevent double searches

---

apps/modernization-ui/src/apps/dedup-config/PatientMatchConfiguration/PassConfiguration/PassConfigurationListItem.module.scss
apps/modernization-ui/src/apps/dedup-config/PatientMatchConfiguration/PassConfiguration/PassConfigurationListItem.tsx
apps/modernization-ui/src/apps/dedup-config/PatientMatchConfiguration/PatientMatchConfigurationPage/PatientMatchConfigurationPage.tsx

Drag drop reorder of Pass config.
Removed descriptions as per Henry Tavarez.
* [CNFT2-2776](https://cdc-nbs.atlassian.net/browse/CNFT2-2776)
[CNFT2-2776]: https://cdc-nbs.atlassian.net/browse/CNFT2-2776?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT2-2776 Pass config drag drop reorder

---

testing/regression/cypress/e2e/pages/edit-page/addEditSearchDeleteQuestion.page.js
testing/regression/cypress/e2e/pages/preview-page/previewPage.page.js
testing/regression/cypress/step_definitions/preview-page/previewPage.steps.js

[CNT-57] - E2E test cases failure fix

---

apps/modernization-ui/src/apps/search/layout/navigation/search-navigation.module.scss
apps/modernization-ui/src/components/ButtonActionMenu/buttonActionMenu.module.scss

The panel that appears when clicking `Add new` after performing a patient search was appearing behind the search results display. This was probably due to some global styles being removed.
The designs also were not easily inspected and no example exists within the design system. A best effort was made to match the image

Fix panel appearing behind results

---

apps/modernization-api/src/main/java/gov/cdc/nbs/patient/profile/create/NewPatient.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/profile/create/PatientCreationService.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/profile/mortality/MortalityDemographic.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/profile/mortality/MortalityDemographicPatientCommandMapper.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/create/PatientCreateEntrySteps.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/mortality/MortalityDemographicEntrySteps.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/mortality/MortalityDemographicSupportConfiguration.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/mortality/PatientProfileCreateMortalitySteps.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/mortality/PatientProfileMortalityRequester.java
apps/modernization-api/src/test/resources/features/patient/profile/create/ExtendedPatientCreation.mortality.feature

Build on `PatientCreationService` update mortality demographics if present
* [CNFT1-2780](https://cdc-nbs.atlassian.net/browse/CNFT1-2780)
[CNFT1-2780]: https://cdc-nbs.atlassian.net/browse/CNFT1-2780?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT1-2780 API: Create Extended patient data entry form for Mortality

---

apps/modernization-ui/src/design-system/entry/multi-value/RepeatingBlock.tsx

Changing repeatingBlock useForm mode to onSubmit to remove inline validation 
* [CNFT1-3183](https://cdc-nbs.atlassian.net/browse/CNFT1-3183)
[CNFT1-3183]: https://cdc-nbs.atlassian.net/browse/CNFT1-3183?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-3183]changing mode of repeatingBlock

---

apps/modernization-ui/src/apps/search/layout/SearchLayout.spec.tsx
apps/modernization-ui/src/apps/search/useSearchInteraction.tsx
apps/modernization-ui/src/apps/search/useSearchResults.spec.tsx
apps/modernization-ui/src/apps/search/useSearchResults.ts

When a new search is performed or the sorting is change, the pagination is now reset to the first page.
* [CNFT1-3243](https://cdc-nbs.atlassian.net/browse/CNFT1-3243)
[CNFT1-3243]: https://cdc-nbs.atlassian.net/browse/CNFT1-3243?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-3243] Reset paginiation on new search

---

apps/modernization-ui/src/apps/patient/add/extended/inputs/address/AddressRepeatingBlock.spec.tsx
apps/modernization-ui/src/apps/patient/data/address/AddressEntryFields.spec.tsx
apps/modernization-ui/src/apps/patient/data/address/AddressEntryFields.tsx

See attached images observing the button enabled after correct format added
Census Tract should be in numeric XXXX or XXXX.xx format where XXXX is the basic tract and xx is the suffix. XXXX ranges from 0001 to 9999. The suffix is limited to a range between .01 and .98.
Must not allow nonNumeric input
examples of button disabled for invalid format
* [CNFT1-3196](https://cdc-nbs.atlassian.net/browse/CNFT1-3196)
[CNFT1-3196]: https://cdc-nbs.atlassian.net/browse/CNFT1-3196?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Cnft1 3196 census tract validation

---

apps/modernization-api/src/main/java/gov/cdc/nbs/patient/profile/create/NewPatient.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/profile/general/GeneralInformationDemographic.java

Updates the request for the `/nbs/api/profile` API to allow dates in the `MM/DD/YYYY` format to match the rest of the dates in the request.  Also, removes the need to specify empty arrays for the multi valued fields.

[FIX] Making the add patient api request a little more flexible

---

apps/modernization-ui/src/apps/patient/add/extended/AddPatientExtendedForm.tsx
apps/modernization-ui/src/apps/patient/add/extended/inputs/name/NameRepeatingBlock.spec.tsx
apps/modernization-ui/src/apps/patient/add/extended/inputs/race/RaceRepeatingBlock.spec.tsx
apps/modernization-ui/src/apps/patient/add/extended/inputs/race/RaceRepeatingBlock.tsx
apps/modernization-ui/src/apps/patient/data/race/RaceEntryFields.spec.tsx
apps/modernization-ui/src/apps/patient/data/race/RaceEntryFields.tsx
apps/modernization-ui/src/apps/patient/data/race/entry.ts
apps/modernization-ui/src/apps/patient/data/race/index.ts
apps/modernization-ui/src/design-system/entry/multi-value/RepeatingBlock.spec.tsx
apps/modernization-ui/src/design-system/entry/multi-value/RepeatingBlock.tsx
apps/modernization-ui/src/design-system/entry/multi-value/index.ts
apps/modernization-ui/src/design-system/entry/multi-value/useMultiValueEntryState.ts

In preparation for Race validations, changes were made to `RepeatingBlock` that allow values to be passed in.  This allows the `RepeatingBlock` component values to be initialized from the form using the `Controller`.
```typescript
<Controller
control={control}
name="races"
render={({ field: { onChange, value, name } }) => (
<RaceRepeatingBlock
id={name}
values={value}
isDirty={(isDirty) => setSubFormState({ race: isDirty })}
onChange={onChange}
/>
)}
/>
```
* [CNFT1-3230](https://cdc-nbs.atlassian.net/browse/CNFT1-3230)
[CNFT1-3230]: https://cdc-nbs.atlassian.net/browse/CNFT1-3230?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-3230] extended add race validation (part 1)

---

apps/modernization-ui/src/apps/patient/add/extended/AddPatientExtendedForm.spec.tsx
apps/modernization-ui/src/apps/patient/add/extended/AddPatientExtendedForm.tsx
apps/modernization-ui/src/apps/patient/add/extended/add-patient-extended-form.module.scss
apps/modernization-ui/src/apps/patient/add/extended/inputs/address/AddressRepeatingBlock.spec.tsx
apps/modernization-ui/src/apps/patient/add/extended/inputs/address/AddressRepeatingBlock.tsx
apps/modernization-ui/src/apps/patient/add/extended/inputs/identification/IdentificationRepeatingBlock.spec.tsx
apps/modernization-ui/src/apps/patient/add/extended/inputs/identification/IdentificationRepeatingBlock.tsx
apps/modernization-ui/src/apps/patient/add/extended/inputs/name/NameRepeatingBlock.spec.tsx
apps/modernization-ui/src/apps/patient/add/extended/inputs/name/NameRepeatingBlock.tsx
apps/modernization-ui/src/apps/patient/add/extended/inputs/phone/PhoneAndEmailRepeatingBlock.spec.tsx
apps/modernization-ui/src/apps/patient/add/extended/inputs/phone/PhoneAndEmailRepeatingBlock.tsx
apps/modernization-ui/src/apps/patient/add/extended/inputs/race/RaceRepeatingBlock.tsx
apps/modernization-ui/src/apps/patient/add/extended/nav/AddPatientExtendedNav.tsx
apps/modernization-ui/src/apps/patient/add/extended/useAddExtendedPatient.ts
apps/modernization-ui/src/design-system/entry/multi-value/RepeatingBlock.module.scss
apps/modernization-ui/src/design-system/entry/multi-value/RepeatingBlock.spec.tsx
apps/modernization-ui/src/design-system/entry/multi-value/RepeatingBlock.tsx
apps/modernization-ui/src/design-system/inPageNavigation/InPageNavigation.tsx
apps/modernization-ui/src/design-system/inPageNavigation/useInPageNavigation.ts

Displays repeating block validation errors within banner at the top of the repeating block. Validations are triggered onSubmit.
* [CNFT1-3181](https://cdc-nbs.atlassian.net/browse/CNFT1-3181)
[CNFT1-3181]: https://cdc-nbs.atlassian.net/browse/CNFT1-3181?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Cnft1 3181 repeating block error banner

---

apps/modernization-ui/src/apps/patient/add/extended/api.ts
apps/modernization-ui/src/apps/patient/add/extended/entry.ts
apps/modernization-ui/src/apps/patient/add/extended/inputs/race/DetailedRaceDisplay.tsx
apps/modernization-ui/src/apps/patient/add/extended/inputs/race/RaceEntryView.spec.tsx
apps/modernization-ui/src/apps/patient/add/extended/inputs/race/RaceEntryView.tsx
apps/modernization-ui/src/apps/patient/add/extended/inputs/race/RaceRepeatingBlock.spec.tsx
apps/modernization-ui/src/apps/patient/add/extended/inputs/race/RaceRepeatingBlock.tsx
apps/modernization-ui/src/apps/patient/add/extended/inputs/race/categoryValidator.spec.ts
apps/modernization-ui/src/apps/patient/add/extended/inputs/race/categoryValidator.ts
apps/modernization-ui/src/apps/patient/add/extended/transformer.spec.ts
apps/modernization-ui/src/apps/patient/data/api.ts
apps/modernization-ui/src/apps/patient/data/entry.ts
apps/modernization-ui/src/apps/patient/data/race/RaceEntryFields.spec.tsx
apps/modernization-ui/src/apps/patient/data/race/RaceEntryFields.tsx
apps/modernization-ui/src/apps/patient/data/race/api.ts
apps/modernization-ui/src/apps/patient/data/race/asRace.spec.ts
apps/modernization-ui/src/apps/patient/data/race/asRace.ts
apps/modernization-ui/src/apps/patient/data/race/entry.ts
apps/modernization-ui/src/options/race/useRaceCategoryOptions.ts
apps/modernization-ui/src/utils/index.ts
apps/modernization-ui/src/utils/predicate/allOf.spec.ts
apps/modernization-ui/src/utils/predicate/allOf.ts
apps/modernization-ui/src/utils/predicate/index.ts
apps/modernization-ui/src/utils/predicate/predicate.ts

Adds validation to the Patient add extended that prevents a user from adding a Patient with duplicate race categories.  
- Adds `useRaceCategoryOptions` hook to encapsulate the look-up of race categories
- Adds `RaceCategoryValidator` type to unable defining how the category's are validated
- Adds an implementation of the `RaceCategoryValidator` to validate races within a repeating block
* [CNFT1-3230](https://cdc-nbs.atlassian.net/browse/CNFT1-3230)
[CNFT1-3230]: https://cdc-nbs.atlassian.net/browse/CNFT1-3230?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-3230] Patient Extended Add race demographics validation

---

apps/modernization-api/postman/NDESS-Modernization-API.postman_collection.json
apps/modernization-api/src/main/java/gov/cdc/nbs/address/Address.java
apps/modernization-api/src/main/java/gov/cdc/nbs/address/AddressRowMapper.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/profile/summary/address/PatientSummaryAddressFinder.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/profile/summary/address/PatientSummaryHomeAddressFinder.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/search/address/PatientSearchResultAddressFinder.java
apps/modernization-api/src/main/resources/graphql/patient-search.graphqls
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/PatientMother.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/address/PatientProfileAddressSteps.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/search/PatientSearchRequester.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/search/PatientSearchVerificationSteps.java
apps/modernization-api/src/test/java/gov/cdc/nbs/support/concept/address/AddressTypeSteps.java
apps/modernization-api/src/test/java/gov/cdc/nbs/support/concept/address/AddressUseSteps.java
apps/modernization-api/src/test/resources/features/patient/search/PatientSearch.address.feature
apps/modernization-ui/src/generated/gql/queries/findPatientsByFilter.gql
apps/modernization-ui/src/generated/graphql/schema.ts
apps/modernization-ui/src/generated/schema.graphqls

Updates the finder that resolves patient addresses in search results to include the address type.  
- The client graphql schema was regenerated to reflect the changes 
- The Postman collection was updated to include address type and use in the Patient Search request.
Issuing the request 
```graphql
query search($filter: PersonFilter!, $page: SortablePage, $share: String) {
findPatientsByFilter(filter: $filter, page: $page, share: $share) {
content {
patient
shortId
legalName {
first
middle
last
suffix
}
addresses {
type
use
address
city
county
zipcode
state
}
}
total
page
size
}
}
```
Will return the address type and use when the patient has an address.
```json
{
"data": {
"findPatientsByFilter": {
"content": [
{
"patient": 10055284,
"shortId": 91001,
"legalName": {
"first": "Katherine", …
```

[CNFT1-3282] Include address type in patient search results

---

apps/modernization-ui/src/apps/search/patient/result/list/PatientSearchResultListItem.tsx
apps/modernization-ui/src/apps/search/patient/result/patientSearchResult.spec.tsx
apps/modernization-ui/src/apps/search/patient/result/patientSearchResult.tsx
apps/modernization-ui/src/apps/search/patient/result/table/PatientSearchResultTable.tsx

Adding Patient ID as the first column in the Patient search results - Table view.
Adds hyperlink to Patient ID which routes to patient profile 
* [CNFT1-3290](https://cdc-nbs.atlassian.net/browse/CNFT1-3290)
[CNFT1-3290]: https://cdc-nbs.atlassian.net/browse/CNFT1-3290?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1]-passing display type with name and id for profileLink to change table view for firstColumn

---

apps/modernization-ui/src/design-system/entry/multi-value/RepeatingBlock.spec.tsx
apps/modernization-ui/src/design-system/entry/multi-value/RepeatingBlock.tsx

Internal form state is retaining some values when `reset` is called. Calling `form.reset` first and then performing a table update seems to resolve the issue.
* [CNFT1-3365](https://cdc-nbs.atlassian.net/browse/CNFT1-3365)
[CNFT1-3365]: https://cdc-nbs.atlassian.net/browse/CNFT1-3365?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix form retaining value

---

apps/modernization-ui/src/apps/search/patient/result/table/PatientSearchResultTable.tsx
apps/modernization-ui/src/design-system/table/preferences/ColumnPreferencesPanel.tsx

On Patient Search, made these changes:
- moved Patient ID as first column
- make columns draggable: Legal name, Date of Birth, Current sex
- remove drag icon for locked columns (this is universal change for all column preferences)
* [Jira Ticket](https://cdc-nbs.atlassian.net/browse/CNFT1-3280)

CNFT1-3280: Patient Search table reorder columns and lock only Patient ID column

---

apps/modernization-api/src/main/java/gov/cdc/nbs/patient/search/name/PatientSearchResultLegalNameFinder.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/search/name/PatientSearchResultName.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/search/name/PatientSearchResultNameMapper.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/search/name/PatientSearchResultOtherNamesFinder.java
apps/modernization-api/src/main/resources/graphql/patient-search.graphqls
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/names/PatientNameDemographicSteps.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/search/PatientSearchRequester.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/search/PatientSearchVerificationSteps.java
apps/modernization-api/src/test/resources/features/patient/search/PatientSearch.feature
apps/modernization-api/src/test/resources/features/patient/search/PatientSearch.sorting.feature
apps/modernization-api/src/test/resources/features/search/investigation/InvestigationSearch.sorting.feature
apps/modernization-api/src/test/resources/features/search/lab-report/LabReportSearch.sorting.feature
apps/modernization-ui/src/generated/gql/queries/findPatientsByFilter.gql
apps/modernization-ui/src/generated/graphql/schema.ts
apps/modernization-ui/src/generated/schema.graphqls

Updates the finder that resolves patient names in search results to include the name type.  
- The client graphql schema was regenerated to reflect the changes 
Issuing the request 
```graphql
query search($filter: PersonFilter!, $page: SortablePage, $share: String) {
findPatientsByFilter(filter: $filter, page: $page, share: $share) {
content {
patient
shortId
names {
type
first
last
}
}
total
page
size
}
}
```
Will return the name type and use when the patient has a names.
```json
{
"data": {
"findPatientsByFilter": {
"content": [
{
"patient": 10055284,
"shortId": 91001,
"names": [
{
"type": "Alias Name",
"first": "Kitty",
"last": null
},
{
"type": "Legal",
"first": "Katherine",
"last": "Pryde"
}
]
}
],
"total": 1,
"page": 0,
"size": 5
}
}
}
```
* …

[CNFT1-3278] name type in search results

---

apps/modernization-api/src/main/java/gov/cdc/nbs/patient/search/PatientSearchCriteriaFilterResolver.java
apps/modernization-api/src/test/resources/features/patient/search/PatientSearch.feature

Removes the functionality of an "Unknown" gender search returning both patients with "Unknown" genders as well as patients without a gender specified.  When a search is performed with criteria specifying a gender of "Unknown" only patients with a gender of "Unknown" will be returned.
* [CNFT1-3350](https://cdc-nbs.atlassian.net/browse/CNFT1-3350)
[CNFT1-3350]: https://cdc-nbs.atlassian.net/browse/CNFT1-3350?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-3350] Searches for Unknown gender returns only patients with an unknown gender

---

apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/entity/Codeset.java
apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/entity/WaNndMetadatum.java
apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/entity/WaTemplate.java
apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/entity/condition/ConditionCode.java
apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/entity/condition/LdfPageSet.java
apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/entity/question/WaQuestion.java
apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/entity/question/WaQuestionHist.java
apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/filter/querydsl/QueryDSLFilterApplier.java
apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/content/question/request/UpdatePageQuestionRequest.java
apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/content/reorder/models/ReorderablePage.java
libs/authentication/src/main/java/gov/cdc/nbs/authentication/entity/AuthPermSet.java
libs/database-entities/src/main/java/gov/cdc/nbs/entity/odse/NBSEntity.java
libs/database-entities/src/main/java/gov/cdc/nbs/entity/odse/Person.java
libs/database-entities/src/main/java/gov/cdc/nbs/entity/odse/PersonEthnicGroup.java
libs/database-entities/src/main/java/gov/cdc/nbs/entity/odse/PostalEntityLocatorParticipation.java
libs/database-entities/src/main/java/gov/cdc/nbs/patient/PatientEntityLocatorHistoryListener.java
libs/database-entities/src/main/java/gov/cdc/nbs/patient/PatientEthnicityHistoryListener.java
libs/database-entities/src/main/java/gov/cdc/nbs/patient/PatientIdentificationHistoryListener.java
libs/database-entities/src/main/java/gov/cdc/nbs/patient/PatientNameHistoryListener.java
libs/database-entities/src/main/java/gov/cdc/nbs/patient/PatientPhoneLocatorHistoryListener.java
libs/database-entities/src/main/java/gov/cdc/nbs/patient/PatientPostalLocatorHistoryListener.java
libs/database-entities/src/main/java/gov/cdc/nbs/patient/PatientRaceHistoryListener.java

Sonar's new rule `javaarchitecture:S7027` is not great. It flags the following scenarios I consider false positives:
1. Bi-directional mappings in `@Entity`s
2. Static variable references
3. Sealed interfaces using `permits`
4. `@EntityListeners`
This PR suppresses several of these.

Suppresses several instances of javaarchitecture:S7027

---

apps/modernization-ui/src/apps/patient/add/extended/AddPatientExtended.tsx
apps/modernization-ui/src/apps/patient/add/extended/add-patient-extended.module.scss
apps/modernization-ui/src/apps/patient/add/extended/entry.ts
apps/modernization-ui/src/apps/patient/add/extended/useAddPatientExtendedDefaults.ts
apps/modernization-ui/src/navigation/index.ts
apps/modernization-ui/src/navigation/useNavigationBlock.spec.ts
apps/modernization-ui/src/navigation/useNavigationBlock.ts

Adds finer control over when navigation blocking is applied to ensure that the cancel modal does not appear after a patient has been created.
* [CNFT1-3369](https://cdc-nbs.atlassian.net/browse/CNFT1-3369)
[CNFT1-3369]: https://cdc-nbs.atlassian.net/browse/CNFT1-3369?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-3369] Prevents the cancel modal from appearing after a patient is created

---

apps/modernization-ui/src/address/display/displayAddress.spec.tsx
apps/modernization-ui/src/apps/search/patient/result/list/PatientSearchResultListItem.tsx
apps/modernization-ui/src/apps/search/patient/result/patientSearchResult.spec.tsx
apps/modernization-ui/src/apps/search/patient/result/patientSearchResult.tsx
apps/modernization-ui/src/apps/search/patient/result/table/PatientSearchResultTable.tsx
apps/modernization-ui/src/name/displayName.ts
apps/modernization-ui/src/name/displayNameElement.spec.tsx
apps/modernization-ui/src/name/displayNameElement.tsx
apps/modernization-ui/src/name/index.ts
apps/modernization-ui/src/name/nameUtils.spec.ts
apps/modernization-ui/src/name/nameUtils.ts
apps/modernization-ui/src/name/types.ts

Implement the header for other names in search for list and table.
* [Jira Ticket](https://cdc-nbs.atlassian.net/browse/CNFT1-3287)

CNFT1-3287: Other names header for search

---

apps/modernization-ui/src/apps/patient/add/extended/add-patient-extended-form.module.scss
apps/modernization-ui/src/apps/patient/data/general/GeneralInformationEntryFields.tsx
apps/modernization-ui/src/apps/patient/data/general/asGeneral.ts
apps/modernization-ui/src/design-system/input/index.ts
apps/modernization-ui/src/design-system/input/numeric/NumericInput.spec.tsx
apps/modernization-ui/src/design-system/input/numeric/NumericInput.tsx
apps/modernization-ui/src/design-system/input/numeric/index.ts

Prevents the entry of non-muerica characters by adding a `NumericInput` component. The "Number of adults in residence" and "Number of children in residence" from the General information section now use this component.
* [CNFT1-3372](https://cdc-nbs.atlassian.net/browse/CNFT1-3372)
[CNFT1-3372]: https://cdc-nbs.atlassian.net/browse/CNFT1-3372?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-3372] Numeric values only

---

apps/modernization-ui/src/apps/search/patient/result/list/PatientSearchResultListItem.spec.tsx
apps/modernization-ui/src/apps/search/patient/result/patientSearchResult.spec.tsx
apps/modernization-ui/src/apps/search/patient/result/patientSearchResult.tsx
apps/modernization-ui/src/name/displayNameElement.spec.tsx
apps/modernization-ui/src/name/displayNameElement.tsx

apps/modernization-ui/src/apps/search/patient/result/patientSearchResult.tsx
names now display as Last, First:  `displayNameElement(result.legalName, 'fullLastFirst')}`

Quick fix for a bug introduced in refactoring / merge conflict resolution

---

apps/modernization-ui/src/name/displayName.spec.ts
apps/modernization-ui/src/name/displayName.ts

Adding dash for when there is no first or last name
* [CNFT1-3339](https://cdc-nbs.atlassian.net/browse/CNFT1-3339)
[CNFT1-3339]: https://cdc-nbs.atlassian.net/browse/CNFT1-3339?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-3339]-adding dash for first last names and tests

---

apps/modernization-ui/src/apps/patient/add/PatientCreatedPanel.tsx
apps/modernization-ui/src/apps/patient/add/api.ts
apps/modernization-ui/src/apps/patient/add/basic/entry.ts
apps/modernization-ui/src/apps/patient/add/extended/AddPatientExtended.tsx
apps/modernization-ui/src/apps/patient/add/extended/creator.ts
apps/modernization-ui/src/apps/patient/add/extended/transformer.ts
apps/modernization-ui/src/apps/patient/add/extended/useAddExtendedPatient.spec.ts
apps/modernization-ui/src/apps/patient/add/extended/useAddExtendedPatient.ts
apps/modernization-ui/src/apps/patient/add/extended/useAddExtendedPatientInteraction.tsx
apps/modernization-ui/src/apps/patient/data/entry.ts
apps/modernization-ui/src/utils/index.ts
apps/modernization-ui/src/utils/mapping/index.ts
apps/modernization-ui/src/utils/mapping/mapping.ts
apps/modernization-ui/src/utils/mapping/maybeMap.ts
apps/modernization-ui/src/utils/mapping/maybeMapAll.ts

Adds short form patient data entry object and refactors/ moves around some files to allow both add pages to use the same hook for patient creation in the near future.
- `mapping`, `maybeMap`, and `maybeMapAll` have been moved to the `utils` folder
- The `Transformer` and `Creator` types were moved to the `add` folder
- The `Transformer` function was made generic
These changes will make more sense with the New patient short form API integration story.
* [CNFT1-3406](https://cdc-nbs.atlassian.net/browse/CNFT1-3406)
[CNFT1-3406]: https://cdc-nbs.atlassian.net/browse/CNFT1-3406?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-3406] adds short form patient data entry object

---

apps/modernization-ui/src/apps/patient/add/NewPatientEntry.ts
apps/modernization-ui/src/apps/patient/add/extended/asExtendedNewPatientEntry.ts
apps/modernization-ui/src/apps/patient/add/extended/inputs/phone/PhoneAndEmailRepeatingBlock.tsx

Label for the type columns in the phone section required a change so it should type/use and not just type. And small bug was fixed where it was adding empty email addresses when the data transfer was happening.
* [CNFT1-3407](https://cdc-nbs.atlassian.net/browse/CNFT1-3407)
[CNFT1-3407]: https://cdc-nbs.atlassian.net/browse/CNFT1-3407?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Label for phone section, type

---

apps/modernization-ui/src/apps/patient/profile/PatientProfile.tsx
apps/modernization-ui/src/apps/patient/profile/delete/DeletePatient.spec.tsx
apps/modernization-ui/src/apps/patient/profile/delete/DeletePatient.tsx

1.  Delete patient modal, message displays a “,“ at the end of message. Replace “, “ with a  “.“
2. When there is no name for a patient, then the modal is displayed as:  Patient Id Number followed by ",," -> Solution: When there is no patient name then the message is displayed as “Patient ID, --,--. “
3. When there is no last name/ first name for a patient, then the modal is displayed as: "FirstName, " or "LastName," -> Solution: When there is no patient name - last name/ first name then the message is displayed as “Patient ID, test,--. “/ “Patient ID, --,test. “
4. When patient name is updated in Patient profile, Its not reflecting when deleting a patient:
Patient name was updated from “test,--” to “Something,--” but the modal is still displayed as: "test,--" -> Solution: When there is a …

[CNFT1-3423]: correcting content for delete modal in patient profile

---

apps/modernization-ui/src/apps/patient/add/basic/entry.ts
apps/modernization-ui/src/apps/patient/add/basic/transformer.spec.ts
apps/modernization-ui/src/apps/patient/add/basic/transformer.ts
apps/modernization-ui/src/apps/patient/add/basic/useAddBasicPatient.ts
apps/modernization-ui/src/apps/patient/add/creator.ts
apps/modernization-ui/src/apps/patient/add/extended/AddPatientExtended.tsx
apps/modernization-ui/src/apps/patient/add/extended/useAddExtendedPatient.spec.ts
apps/modernization-ui/src/apps/patient/add/extended/useAddExtendedPatient.ts
apps/modernization-ui/src/apps/patient/add/extended/useAddExtendedPatientInteraction.tsx
apps/modernization-ui/src/apps/patient/add/index.ts
apps/modernization-ui/src/apps/patient/add/useAddPatient.spec.ts
apps/modernization-ui/src/apps/patient/add/useAddPatient.ts
apps/modernization-ui/src/options/address/types.ts
apps/modernization-ui/src/options/address/uses.ts
apps/modernization-ui/src/options/name/types.ts
apps/modernization-ui/src/options/phone/types.ts
apps/modernization-ui/src/options/phone/uses.ts
apps/modernization-ui/src/utils/isEmpty.ts

Adds the `useAddBasicPatient` hook to allow adding a patient with the patient create API using a `BasicNewPatientEntry`.  The API interaction was extracted from `useAddExtendedPatient`into `useAddPatient` so that it could be used by both `useAddBasicPatient` and `useAddExtendedPatient`.  The extra validation for pending input remains in `useAddExtendedPatient`.  
- a `transformer` function was introduced to map a `BasicNewPatientEntry` to a `NewPatient` to send as a request to the patient create API
- The `creator` function was moved up to the `add` folder to be used by both `basic` and `extended`
* [CNFT1-3408](https://cdc-nbs.atlassian.net/browse/CNFT1-3408)
[CNFT1-3408]: https://cdc-nbs.atlassian.net/browse/CNFT1-3408?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjo …

[CNFT1-3408] basic add patient api integration

---

apps/modernization-ui/src/apps/patient/profile/summary/PatientProfileSummary.tsx
apps/modernization-ui/src/apps/search/patient/result/patientSearchResult.spec.tsx
apps/modernization-ui/src/apps/search/patient/result/patientSearchResult.tsx

Adding No data on search and 3 dashes for no name entries on patient profile.
* [CNFT1-3423](https://cdc-nbs.atlassian.net/browse/CNFT1-3423)
[CNFT1-3423]: https://cdc-nbs.atlassian.net/browse/CNFT1-3423?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-3423]: Adding no data and three patient profile dashes update.

---

apps/modernization-ui/src/apps/patient/add/NewPatientEntry.ts
apps/modernization-ui/src/apps/patient/add/asPersonInput.ts
apps/modernization-ui/src/apps/patient/add/basic/transformer.ts
apps/modernization-ui/src/apps/patient/add/extended/asExtendedNewPatientEntry.ts
apps/modernization-ui/src/apps/patient/data/entry.ts
apps/modernization-ui/src/apps/patient/data/identification/asIdentification.ts
apps/modernization-ui/src/options/selectable.ts

Removes the empty values `Selectable` objects that were being created when a user transitions from basic patient entry to extended patient entry.

[FIX] removes empty valued selectables

---

apps/modernization-api/src/main/java/gov/cdc/nbs/patient/search/phone/PatientSearchResultDetailedPhoneFinder.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/search/phone/PatientSearchResultPhoneMapper.java
apps/modernization-ui/src/apps/search/patient/result/patientSearchResult.tsx

Update "use" label for phone numbers in the API to match NBS 6. Display common labels like "Home", "Cell", "Work"
* [Jira Ticket](https://cdc-nbs.atlassian.net/browse/CNFT1-3429)

CNFT1-3429: Phone number header label in search

---

apps/modernization-api/src/main/java/gov/cdc/nbs/patient/search/PatientDemographicQueryResolver.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/search/PatientFilter.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/search/PatientNameDemographicQueryResolver.java
apps/modernization-api/src/main/java/gov/cdc/nbs/search/criteria/name/NameCriteria.java
apps/modernization-api/src/main/java/gov/cdc/nbs/search/criteria/text/TextCriteria.java
apps/modernization-api/src/main/java/gov/cdc/nbs/search/criteria/text/TextCriteriaNestedQueryResolver.java
apps/modernization-api/src/main/resources/graphql/patient-search.graphqls
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/search/PatientSearchCriteriaSteps.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/search/PatientSearchEventIdSteps.java
apps/modernization-api/src/test/resources/features/patient/search/PatientSearch.last-name-operator.feature
apps/modernization-ui/src/generated/graphql/schema.ts
apps/modernization-ui/src/generated/schema.graphqls

Add new field `name` with a patient name type `input PatientNameCriteria {
last: TextCriteria
}` that is a generic type of 
`input TextCriteria {
equals: String
not: String
startsWith:String
contains: String
soundsLike: String
}`.
If that field is populated diverge from old code (for backwards compatibility) and call the new searches wrt each operator.
* [CNFT1-3312](https://cdc-nbs.atlassian.net/browse/CNFT1-3312)
[CNFT1-3312]: https://cdc-nbs.atlassian.net/browse/CNFT1-3312?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT1-3312 API: Update API to handle Operators for Last Name

---

apps/modernization-ui/src/apps/search/patient/add/useAddPatientFromSearch.ts

Disables the navigation to `/patient/add` from patient search until the page is more complete.  A new story will be created to restore this functionality.

[FIX] disables navigation to /patient/add

---

apps/modernization-ui/src/design-system/entry/multi-value/RepeatingBlock.tsx
apps/modernization-ui/src/design-system/select/single/SingleSelect.spec.tsx
apps/modernization-ui/src/design-system/select/single/SingleSelect.tsx

changing reValidate to onBlur to fix an issue where the repeating blocks inline validations were not being removed after they were corrected on blur
* [CNFT1-3446](https://cdc-nbs.atlassian.net/browse/CNFT1-3446)
[CNFT1-3446]: https://cdc-nbs.atlassian.net/browse/CNFT1-3446?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-3446]: changing reValidate to onBlur

---

apps/modernization-api/src/main/java/gov/cdc/nbs/search/redirect/simple/SimplePatientSearchCriteria.java
apps/modernization-api/src/main/java/gov/cdc/nbs/search/redirect/simple/SimplePatientSearchCriteriaResolver.java
apps/modernization-api/src/main/java/gov/cdc/nbs/search/redirect/simple/SimplePatientSearchNameCriteria.java
apps/modernization-api/src/main/java/gov/cdc/nbs/search/redirect/simple/SimpleSearchRedirectionController.java
apps/modernization-api/src/test/java/gov/cdc/nbs/search/redirect/simple/SimplePatientSearchCriteriaResolverTest.java
apps/modernization-api/src/test/java/gov/cdc/nbs/search/redirect/simple/SimpleSearchRedirectSteps.java
apps/modernization-api/src/test/resources/features/search/redirect/SimpleSearchRedirect.feature
apps/modernization-ui/src/apps/search/patient/PatientCriteria/BasicInformation.tsx
apps/modernization-ui/src/apps/search/patient/add/asNewPatientEntry.spec.ts
apps/modernization-ui/src/apps/search/patient/add/asNewPatientEntry.ts
apps/modernization-ui/src/apps/search/patient/criteria.ts
apps/modernization-ui/src/apps/search/patient/patientTermsResolver.spec.ts
apps/modernization-ui/src/apps/search/patient/patientTermsResolver.ts
apps/modernization-ui/src/apps/search/patient/transformer.spec.ts
apps/modernization-ui/src/apps/search/patient/transformer.ts

Adds operator support to the Home page search for "Last name" and "First name".  By default the value entered into the "Last name" or "First name" fields will result in a starts with search for the respective field.  If the value starts with `%` it will results in a contains search for the respective field.
- A "Last name" with the value "bri" results in patients with a last name that starts with "bri"
- A "Last name" with the value "%bri" results in patients with a last name that contains "bri"
- A "First name" with the value "aro" results in patients with a last name that starts with "aro"
- A "First name" with the value "%aro" results in patients with a last name that contains "aro"
* [CNFT1-3208](https://cdc-nbs.atlassian.net/browse/CNFT1-3208)
[CNFT1-3208]: …

[CNFT1-3208] Home page name searching contains support

---

apps/modernization-api/src/main/java/gov/cdc/nbs/patient/profile/summary/PatientSummaryFinder.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/profile/summary/address/PatientSummaryAddressFinder.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/search/address/PatientSearchResultAddressFinder.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/search/indexing/address/SearchablePatientAddressFinder.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/search/phone/PatientSearchResultDetailedPhoneFinder.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/search/phone/PatientSearchResultPhoneFinder.java
apps/modernization-ui/src/apps/patient/profile/summary/PatientProfileSummary.tsx

The queries seem to only have a problem with  null values.  They are happy to return codes that don't exist.  So check for null in the conditionals and return blanks for the interface fields that are non-null.  In the case of 'TELE' have the null condition default to a phone (vs an email)
* [CNFT1-3421](https://cdc-nbs.atlassian.net/browse/CNFT1-3421)
[CNFT1-3421]: https://cdc-nbs.atlassian.net/browse/CNFT1-3421?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT1-3421 API: Loosen cd,use_cd fields for Search to enable HL7 ingestion without error

---

apps/modernization-ui/src/apps/search/patient/result/list/PatientSearchResultListItem.spec.tsx
apps/modernization-ui/src/apps/search/patient/result/list/PatientSearchResultListItem.tsx
apps/modernization-ui/src/apps/search/patient/result/patientSearchResult.tsx
apps/modernization-ui/src/apps/search/patient/result/table/PatientSearchResultTable.tsx

Includes [Cnft1 3018 UI update search results table view to display details of page age ](https://github.com/CDCgov/NEDSS-Modernization/pull/2026) changes and updates the list view as well.
https://cdc-nbs.atlassian.net/browse/CNFT1-3444

Cnft1 3444 UI update search results list view to display details of page age

---

apps/modernization-ui/src/apps/patient/add/extended/AddPatientExtendedForm.spec.tsx
apps/modernization-ui/src/apps/patient/data/administrative/AdministrativeEntryFields.spec.tsx
apps/modernization-ui/src/apps/patient/data/administrative/AdministrativeEntryFields.tsx

UI: New patient- Extended: Administrative: "Information as of date" field name has to be updated to "Information as of"
* [CNFT1-3522](https://cdc-nbs.atlassian.net/browse/CNFT1-3522)
[CNFT1-3522]: https://cdc-nbs.atlassian.net/browse/CNFT1-3522?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT1-3522: updating label to just Information as of

---

apps/modernization-api/src/main/java/gov/cdc/nbs/patient/search/PatientDemographicQueryResolver.java
apps/modernization-api/src/test/resources/features/patient/search/PatientSearch.feature

Switch to wildcard search instead of prefix search
* [CNFT1-3538](https://cdc-nbs.atlassian.net/browse/CNFT1-3538)
[CNFT1-3538]: https://cdc-nbs.atlassian.net/browse/CNFT1-3538?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT1-3538 API: Patient search: ID Type search uses "Contains"

---

apps/modernization-ui/src/apps/patient/add/extended/inputs/race/categoryValidator.spec.ts
apps/modernization-ui/src/apps/patient/data/address/AddressEntryFields.spec.tsx
apps/modernization-ui/src/apps/patient/data/address/AddressEntryFields.tsx
apps/modernization-ui/src/apps/patient/data/identification/IdentificationEntryFields.spec.tsx
apps/modernization-ui/src/apps/patient/data/identification/IdentificationEntryFields.tsx
apps/modernization-ui/src/apps/patient/data/name/NameEntryFields.spec.tsx
apps/modernization-ui/src/apps/patient/data/name/NameEntryFields.tsx
apps/modernization-ui/src/apps/patient/data/phoneEmail/PhoneEmailEntryFields.spec.tsx
apps/modernization-ui/src/apps/patient/data/phoneEmail/PhoneEmailEntryFields.tsx
apps/modernization-ui/src/apps/patient/data/race/RaceEntryFields.spec.tsx
apps/modernization-ui/src/apps/patient/data/race/RaceEntryFields.tsx
apps/modernization-ui/src/apps/patient/data/race/categoryRequiredValidator.spec.ts
apps/modernization-ui/src/apps/patient/data/race/categoryRequiredValidator.ts
apps/modernization-ui/src/validation/entry/index.ts
apps/modernization-ui/src/validation/entry/maxLengthRule.ts
apps/modernization-ui/src/validation/entry/validEmailRule.ts
apps/modernization-ui/src/validation/entry/validateExtendedNameRule.ts
apps/modernization-ui/src/validation/entry/validateRequiredRule.ts

Repeating block - has to display the field labels and the associated validation message.
* [CNFT1-3522](https://cdc-nbs.atlassian.net/browse/CNFT1-3522)
[CNFT1-3522]: https://cdc-nbs.atlassian.net/browse/CNFT1-3522?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT13512-Repeating-bloc-error-messages]: adding changes to validate rule files for entry fields

---

apps/modernization-api/src/main/java/gov/cdc/nbs/patient/search/SearchablePatient.java
apps/modernization-api/src/main/java/gov/cdc/nbs/search/WildCards.java
apps/modernization-api/src/main/java/gov/cdc/nbs/search/WithoutHyphensJsonSerializer.java
apps/modernization-api/src/main/java/gov/cdc/nbs/search/criteria/text/TextCriteriaNestedQueryResolver.java
apps/modernization-api/src/test/java/gov/cdc/nbs/search/WithoutHyphensJsonSerializerTest.java
apps/modernization-api/src/test/resources/features/patient/search/PatientSearch.last-name-operator.feature

Fixes multi name last name searches with and without hyphens
* [CNFT1-3520](https://cdc-nbs.atlassian.net/browse/CNFT1-3520)
[CNFT1-3520]: https://cdc-nbs.atlassian.net/browse/CNFT1-3520?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT1-3520 Fix last name indexing to retain spaces and convert hyphens to spaces

---

apps/modernization-ui/src/apps/search/patient/PatientCriteria/BasicInformation.spec.tsx
apps/modernization-ui/src/apps/search/patient/PatientCriteria/BasicInformation.tsx
apps/modernization-ui/src/apps/search/patient/patientTermsResolver.spec.ts
apps/modernization-ui/src/apps/search/patient/patientTermsResolver.ts
apps/modernization-ui/src/apps/search/terms/fromSelectable.ts
apps/modernization-ui/src/apps/search/terms/fromValue.ts
apps/modernization-ui/src/apps/search/terms/removeTerm.spec.ts
apps/modernization-ui/src/apps/search/terms/removeTerm.ts
apps/modernization-ui/src/apps/search/terms/terms.ts
apps/modernization-ui/src/apps/search/useSearchResults.spec.tsx
apps/modernization-ui/src/components/Entry/vertical-entry-wrapper.module.scss
apps/modernization-ui/src/utils/index.ts
apps/modernization-ui/src/utils/text.spec.ts
apps/modernization-ui/src/utils/text.ts
apps/modernization-ui/src/utils/util.spec.ts
apps/modernization-ui/src/utils/util.ts

- Implement splitting of patient ID for chips
- Add help text for patient ID field
- Fixes issue with chips for name (first and last) and location (street and city), nested properties were not being respected and thus these items weren't being removed when X was clicked
* [Jira Ticket](https://cdc-nbs.atlassian.net/browse/CNFT1-3557)

CNFT1-3557: Chips for multiple patient IDs

---

apps/modernization-api/src/main/java/gov/cdc/nbs/search/criteria/text/TextCriteriaNestedQueryResolver.java

Currently the "not equals" Elasticsearch only works when ALL elements in the array (for name or location) don't match. This fix changes it to ANY logic, so that if at least one element doesn't match the search term, it filters out the whole item. This brings it inline with NBS 6.
For example, consider a person with 2 names, "John Lee" and "Jet Li". Currently a not equals "Lee" query was returning John Lee anyway because the second last name of "Li" failed the not equals check. This also fixes not equals for first name, address, and city.
* [Jira Ticket](https://cdc-nbs.atlassian.net/browse/CNFT1-3559)

CNFT1-3559: Update query to filter out any in an array with not equals

---

apps/modernization-api/src/main/java/gov/cdc/nbs/search/criteria/text/TextCriteriaNestedQueryResolver.java

Fixes the tokenization problems with street addresses so that "123 Happy St" must match exactly. This includes similar behavior for name and city.
* [Jira Ticket](https://cdc-nbs.atlassian.net/browse/CNFT1-3560)

CNFT1-3560: Equals operator enhance strictness in exact matches

---

apps/modernization-ui/src/apps/patient/add/contactFields/ContactFields.tsx

limits the Extension field to 8 numeric characters with mask and regex pattern. 8 digits in short form only for now, extended form is a different story. 
* [Jira Ticket](https://cdc-nbs.atlassian.net/browse/CNFT1-3562)

Add character limit 8 num chars to the Extension field in add patient short form.

---

apps/modernization-ui/src/date/today.ts
apps/modernization-ui/src/design-system/date/clock.ts
apps/modernization-ui/src/design-system/date/occursInThePast.spec.ts
apps/modernization-ui/src/design-system/date/occursInThePast.ts
apps/modernization-ui/src/design-system/date/validateDateEntry.spec.ts
apps/modernization-ui/src/design-system/date/validateDateEntry.ts

Fixes the validation for future dates to only do the check when a `DateEntry` has a `month` and a `year` value.  The validation for only the `year` value happens before this validation is called.
- Adds a `now` function to be able to mock the current date in tests to prevent unexpected failures.
- Changes the validation message for years to closer match NBS6
* [CNFT1-3583](https://cdc-nbs.atlassian.net/browse/CNFT1-3583)
[CNFT1-3583]: https://cdc-nbs.atlassian.net/browse/CNFT1-3583?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-3583] Date equals criteria validations fix

---

apps/modernization-ui/src/components/Entry/entry-wrapper.module.scss

adding a bit more padding left on error class to compensate for border left padding 
* [CNFT1-3513](https://cdc-nbs.atlassian.net/browse/CNFT1-3513)
[CNFT1-3513]: https://cdc-nbs.atlassian.net/browse/CNFT1-3513?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-3513-inline-validation-shifting-fields-fix]

---

apps/modernization-ui/src/apps/search/terms/removeTerm.spec.ts
apps/modernization-ui/src/apps/search/terms/removeTerm.ts

When certain entries in the form object are present but there is no form element for them, set a null value in the form object to clear it. This fixes a bug with removing term when form element is not on the form.
* [Jira Ticket](https://cdc-nbs.atlassian.net/browse/CNFT1-3549)

CNFT1-3549: Clear form value in addition to resetting field

---

apps/modernization-ui/src/apps/patient/add/AddPatient.tsx
apps/modernization-ui/src/apps/patient/add/NewPatientEntry.ts
apps/modernization-ui/src/apps/patient/add/addressFields/AddressFields.tsx
apps/modernization-ui/src/apps/patient/add/usePreFilled.ts
apps/modernization-ui/src/design-system/select/single/SingleSelect.spec.tsx
apps/modernization-ui/src/design-system/select/single/SingleSelect.tsx

The value for the state was being converted from a `Selectable` to a `string` during address verification which caused the value to be excluded when making the request to add the patient.  Even though address verification was turned off the pass-through function was where the `Selectable` to `string` conversion was happening.
- Removed the code from `usePrefilled` that supported Advanced Search which greatly simplifies it
- Removed the Trussworks Select element from `SingleSelect` as it was only a wrapper for a `<select>` with the USWDS styling.
* [CNFT1-3581](https://cdc-nbs.atlassian.net/browse/CNFT1-3581)
[CNFT1-3581]: https://cdc-nbs.atlassian.net/browse/CNFT1-3581?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-3581] Ensure a patient's state is saved from New Patient

---

apps/modernization-ui/src/apps/search/patient/result/table/PatientSearchResultTable.tsx
apps/modernization-ui/src/apps/search/patient/result/table/patient-search-result-table.module.scss
apps/modernization-ui/src/design-system/table/DataTable.spec.tsx
apps/modernization-ui/src/design-system/table/DataTable.tsx
apps/modernization-ui/src/design-system/table/data-table.module.scss

Implement patient search column sizing for table view based on the Figma style guide, specifically minimizing the size of Patient ID column. Allow specifying a class name for columns + unit tests for DataTable.
* [Jira Ticket](https://cdc-nbs.atlassian.net/browse/CNFT1-3413)

CNFT1-3413: Implement sizing of columns for patient search

---

apps/modernization-api/src/main/java/gov/cdc/nbs/patient/search/email/PatientSearchResultEmailFinder.java

Fixes blank search results with error:
```
The field at path '/findPatientsByFilter/content[11]/emails[0]' was declared as a non null type, but the code involved in retrieving data has wrongly returned a null value.
```
Notes: could fetch just non null values but figured it was beneficial to see if blanks and nulls are being inserted into the db erroneously.
* [CNFT1-3538](https://cdc-nbs.atlassian.net/browse/CNFT1-3538)
[CNFT1-3538]: https://cdc-nbs.atlassian.net/browse/CNFT1-3538?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Convert null emails to blanks

---

apps/modernization-ui/src/apps/patient/data/mortality/MortalityEntryFields.tsx
apps/modernization-ui/src/apps/patient/data/sexAndBirth/SexAndBirthEntryFields.tsx

The errors were not being passed to the "Date of death" field for display in the "Mortality" section and the "Date of birth" field in the "Sex and birth" section within "New patient - extended"
* [CNFT1-3627](https://cdc-nbs.atlassian.net/browse/CNFT1-3627)
[CNFT1-3627]: https://cdc-nbs.atlassian.net/browse/CNFT1-3627?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-3627] Ensures that the error messages for date of birth validations

---

apps/modernization-ui/src/system/return-message/ReturnMessage.spec.tsx
apps/modernization-ui/src/system/return-message/ReturnMessage.tsx
apps/nbs-gateway/build.gradle
apps/nbs-gateway/src/main/resources/application-development.yml

Changes the "Return to NBS" link to go to `/nbs/login` to ensure that a user is logged in to NBS6.
* [CNFT1-3634](https://cdc-nbs.atlassian.net/browse/CNFT1-3634)
[CNFT1-3634]: https://cdc-nbs.atlassian.net/browse/CNFT1-3634?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-3634] Return link location

---

apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/entity/CodeSetGroupMetadatum.java
apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/entity/Codeset.java
apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/filter/querydsl/QueryDSLFilterApplier.java
apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/content/reorder/models/ReorderablePage.java
apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/content/reorder/models/SimplePageMapper.java
apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/support/condition/ConditionMother.java
apps/question-bank/src/test/java/gov/cdc/nbs/questionbank/support/valueset/ValueSetMother.java
libs/authentication/src/main/java/gov/cdc/nbs/authentication/entity/AuthBusObjRt.java
libs/authentication/src/main/java/gov/cdc/nbs/authentication/entity/AuthBusOpRt.java
libs/database-entities/src/main/java/gov/cdc/nbs/entity/odse/EntityId.java
libs/database-entities/src/main/java/gov/cdc/nbs/entity/odse/EntityLocatorParticipation.java
libs/database-entities/src/main/java/gov/cdc/nbs/entity/odse/PersonEthnicGroup.java
libs/database-entities/src/main/java/gov/cdc/nbs/entity/odse/PersonName.java
libs/database-entities/src/main/java/gov/cdc/nbs/entity/odse/PersonRace.java
libs/database-entities/src/main/java/gov/cdc/nbs/entity/odse/PostalEntityLocatorParticipation.java
libs/database-entities/src/main/java/gov/cdc/nbs/entity/odse/TeleEntityLocatorParticipation.java
libs/database-entities/src/main/java/gov/cdc/nbs/patient/PatientEntityLocatorHistoryListener.java
libs/database-entities/src/main/java/gov/cdc/nbs/patient/PatientEthnicityHistoryListener.java
libs/database-entities/src/main/java/gov/cdc/nbs/patient/PatientIdentificationHistoryListener.java
libs/database-entities/src/main/java/gov/cdc/nbs/patient/PatientNameHistoryListener.java
libs/database-entities/src/main/java/gov/cdc/nbs/patient/PatientPhoneLocatorHistoryListener.java
libs/database-entities/src/main/java/gov/cdc/nbs/patient/PatientPostalLocatorHistoryListener.java
libs/database-entities/src/main/java/gov/cdc/nbs/patient/PatientRaceHistoryListener.java

Resolves a few outstanding code smells found from Sonar scans.

SonarQube code smell resolution

---

apps/modernization-ui/src/apps/search/layout/result/header/terms/SearchTerms.spec.tsx
apps/modernization-ui/src/apps/search/layout/result/header/terms/SearchTerms.tsx
apps/modernization-ui/src/utils/text.spec.ts
apps/modernization-ui/src/utils/text.ts

Pluralize "results" for text and aria-label. Create `pluralize()` function for use across the app in other places.
* [Jira Ticket](https://cdc-nbs.atlassian.net/browse/CNFT1-3610)

CNFT1-3610: Search results pluralize fix

---

apps/modernization-ui/src/components/selection/multi/MultiSelectInput.scss

Height of the multi-select drop-down box should match the Race field so set min height to 2.5 rem
* [CNFT1-3638](https://cdc-nbs.atlassian.net/browse/CNFT1-3638)
[CNFT1-3638]: https://cdc-nbs.atlassian.net/browse/CNFT1-3638?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-3638]: fixing height for race field

---

apps/modernization-ui/src/address/suggestion/AddressSuggestionInput.tsx
apps/modernization-ui/src/apps/patient/add/extended/add-patient-extended-form.module.scss
apps/modernization-ui/src/apps/patient/data/address/AddressEntryFields.tsx
apps/modernization-ui/src/apps/patient/data/ethnicity/EthnicityEntryFields.tsx
apps/modernization-ui/src/apps/patient/data/general/GeneralInformationEntryFields.tsx
apps/modernization-ui/src/apps/patient/data/identification/IdentificationEntryFields.tsx
apps/modernization-ui/src/apps/patient/data/mortality/MortalityEntryFields.tsx
apps/modernization-ui/src/apps/patient/data/name/NameEntryFields.tsx
apps/modernization-ui/src/apps/patient/data/phoneEmail/PhoneEmailEntryFields.tsx
apps/modernization-ui/src/apps/patient/data/race/RaceEntryFields.tsx
apps/modernization-ui/src/apps/patient/data/sexAndBirth/SexAndBirthEntryFields.tsx

All extended form inputs are now compact
* [CNFT1-3623](https://cdc-nbs.atlassian.net/browse/CNFT1-3623)
[CNFT1-3623]: https://cdc-nbs.atlassian.net/browse/CNFT1-3623?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

all extended made into compact

---

apps/modernization-api/src/main/java/gov/cdc/nbs/codes/PrimaryLanguageValueSetFinder.java
apps/modernization-api/src/main/resources/application-development.yml

Add `nbs.primary-language` with default of English to application.yml.  Fetch rows from db.  Pluck out primary language and added it to front of list
* [CNFT1-3612](https://cdc-nbs.atlassian.net/browse/CNFT1-3612)
[CNFT1-3612]: https://cdc-nbs.atlassian.net/browse/CNFT1-3612?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT1-3612 API: New patient- Extended: General patient information: Primary Language: English

---

apps/modernization-ui/src/address/suggestion/AddressSuggestionInput.tsx
apps/modernization-ui/src/apps/patient/add/addressFields/AddressFields.tsx
apps/modernization-ui/src/apps/patient/add/basic/address/BasicAddressFields.tsx
apps/modernization-ui/src/apps/patient/add/basic/phoneEmail/BasicPhoneEmailFields.tsx
apps/modernization-ui/src/apps/patient/data/address/AddressEntryFields.tsx
apps/modernization-ui/src/apps/patient/profile/addresses/AddressEntryFields.tsx

Removes some duplicate properties that were introduced when a PR was merged.  It also changes `AddressSuggestionInput` to use the `TextInputField`.

[FIX] removes duplicate props

---

apps/modernization-ui/src/apps/patient/add/extended/AddPatientExtendedForm.spec.tsx
apps/modernization-ui/src/apps/patient/add/extended/AddPatientExtendedForm.tsx

Change _data has been entered in X section_ to _data have been entered in X section_ as per this issue: 
https://cdc-nbs.atlassian.net/browse/CNFT1-3616
* [Jira Ticket](https://cdc-nbs.atlassian.net/browse/CNFT1-3616)

change Data has been entered to Data have been entered in repeating block section

---

apps/modernization-ui/src/design-system/date/validateDate.spec.ts
apps/modernization-ui/src/design-system/date/validateDateEntry.spec.ts

Changes the `validateDate` and `validateDateEntry` tests to not rely on the current date.

[FIX] Strengthen date tests

---

apps/modernization-ui/src/apps/search/layout/result/list/ResultItem.tsx
apps/modernization-ui/src/apps/search/layout/result/list/result-item.module.scss

aligning resultItems using horizontal class to fix the Data in the list view, that are currently not in the same line as the label. 
* [CNFT1-2964](https://cdc-nbs.atlassian.net/browse/CNFT1-2964)
[CNFT1-2964]: https://cdc-nbs.atlassian.net/browse/CNFT1-2964?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

 [CNFT1-2964]: aligning resultItems using horizontal class 

---

apps/modernization-ui/src/styles/_uswds.scss

When you select a date field, a blue border appears around it, but the calendar icon to the right of it overlaps with the blue border. Moved the icon over 4px to the right to account for the focus border that appears.
* [Jira Ticket](https://cdc-nbs.atlassian.net/browse/CNFT1-3621)

Add a margin right of 4px on the input text box component in the date picker to accommodate 4px focus border

---

apps/nbs-gateway/build.gradle
apps/nbs-gateway/src/main/java/gov/cdc/nbs/gateway/patient/profile/PatientProfileRouteLocatorConfiguration.java
apps/nbs-gateway/src/test/java/gov/cdc/nbs/gateway/patient/profile/PatientProfileRouteLocatorConfigurationTest.java

The route locator for direct requests for a patient profile was including any URL that contained the parameter `MPRUid`.  This was causing event links from the "Documents Requiring Security Assignment" queue to route to the modernized patient profile over the event.
The rule was changed to correctly require a "ContextAction" of `ViewFile` or `FileSummary` along with a parameter of `uid` or `MPRUid`.
* [CNFT1-3656](https://cdc-nbs.atlassian.net/browse/CNFT1-3656)
[CNFT1-3656]: https://cdc-nbs.atlassian.net/browse/CNFT1-3656?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-3656] Fixes direct patient routing rules

---

apps/modernization-api/src/main/java/gov/cdc/nbs/patient/search/PatientDemographicQueryResolver.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/search/PatientFilter.java
apps/modernization-api/src/main/resources/graphql/patient-search.graphqls
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/search/PatientSearchCriteriaSteps.java
apps/modernization-api/src/test/resources/features/patient/search/PatientSearch.feature
apps/modernization-ui/src/generated/graphql/schema.ts
apps/modernization-ui/src/generated/schema.graphqls

Make the new `idFilter` field a should (wildcard) query on `local_id`.  The existing id searches are exact match term queries on `local_id`
* [CNFT1-3464](https://cdc-nbs.atlassian.net/browse/CNFT1-3464)
[CNFT1-3464]: https://cdc-nbs.atlassian.net/browse/CNFT1-3464?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT1-3464 Search API: Add filters for Patient ID

---

apps/modernization-ui/src/design-system/input/text/MaskedTextInput.tsx
apps/modernization-ui/src/design-system/input/text/TextInput.spec.tsx
apps/modernization-ui/src/design-system/input/text/TextInput.tsx

Replace keyup with change as keyup doesn't capture paste events consistently. It also causes a delay so non-masked chars briefly appear.
This is primarily to fix the mask on phone and country code fields.
* [Jira Ticket](https://cdc-nbs.atlassian.net/browse/CNFT1-3651)

CNFT1-3651: Fix MaskedTextInput to apply mask on change events

---

apps/modernization-ui/src/apps/patient/add/AddPatient.tsx
apps/modernization-ui/src/apps/patient/add/basic/AddPatientBasic.tsx
apps/modernization-ui/src/apps/patient/add/extended/AddPatientExtended.tsx

When the API call to add a patient takes a while there is no indication to the user that the patient is being created.  The "Save" button remains enabled allowing a user to create multiple patients with the same demographics.  
The "Save" button was changed to be disabled while the API is being called on the "New patient" and "New patient - extended" pages to prevent multi-submission.
* [CNFT1-3666](https://cdc-nbs.atlassian.net/browse/CNFT1-3666)
[CNFT1-3666]: https://cdc-nbs.atlassian.net/browse/CNFT1-3666?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CNFT1-3666]: https://cdc-nbs.atlassian.net/browse/CNFT1-3666?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-3666] Patient add feedback

---

apps/modernization-ui/src/apps/patient/add/basic/asBasicNewPatientEntry.spec.ts
apps/modernization-ui/src/apps/patient/add/basic/asBasicNewPatientEntry.ts
apps/modernization-ui/src/apps/search/patient/add/asNewPatientEntry.spec.ts
apps/modernization-ui/src/apps/search/patient/add/asNewPatientEntry.ts
apps/modernization-ui/src/design-system/date/entry.ts
apps/modernization-ui/src/design-system/date/index.ts

Adds support for converting patient searches that include a full date equals criteria of the date of birth to the value of "Date of birth" on the  "New patient" page.
This is replicating the feature added for the new version of "New patient" that was added with [CNFT1-3652](https://cdc-nbs.atlassian.net/browse/CNFT1-3652)
* [MU-13](https://cdc-nbs.atlassian.net/browse/MU-13)
[CNFT1-3652]: https://cdc-nbs.atlassian.net/browse/CNFT1-3652?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MU-13]: https://cdc-nbs.atlassian.net/browse/MU-13?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MU-13] Ensures that date of birth is pre-populated from search when adding a patient

---

apps/modernization-api/src/main/java/gov/cdc/nbs/patient/search/PatientDemographicQueryResolver.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/search/PatientFilter.java
apps/modernization-api/src/main/java/gov/cdc/nbs/search/criteria/text/TextCriteria.java
apps/modernization-api/src/main/java/gov/cdc/nbs/search/criteria/text/TextCriteriaNestedQueryResolver.java
apps/modernization-api/src/main/resources/graphql/patient-search.graphqls
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/search/PatientSearchCriteriaSteps.java
apps/modernization-api/src/test/resources/features/patient/search/PatientSearch.feature
apps/modernization-ui/src/generated/graphql/schema.ts
apps/modernization-ui/src/generated/schema.graphqls

Add name to the filter.  Have the name filter do an elasticsearch should on both nested fields (first and last name)
* [CNFT1-3465](https://cdc-nbs.atlassian.net/browse/CNFT1-3465)
[CNFT1-3465]: https://cdc-nbs.atlassian.net/browse/CNFT1-3465?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT1-3465 Search API: Add filters for Patient Name

---

apps/modernization-api/src/main/java/gov/cdc/nbs/patient/create/BasicPatientCreator.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/profile/create/PatientCreationService.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/profile/names/change/PatientNameChangeService.java
apps/modernization-api/src/main/java/gov/cdc/nbs/soundex/ApacheSoundexResolver.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/PatientMother.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/create/PatientCreatedEmitterTest.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/names/change/PatientNameChangeServiceTest.java
libs/database-entities/src/main/java/gov/cdc/nbs/entity/odse/Person.java
libs/database-entities/src/main/java/gov/cdc/nbs/entity/odse/PersonName.java
libs/database-entities/src/main/java/gov/cdc/nbs/patient/demographic/name/SoundexResolver.java
libs/database-entities/src/test/java/gov/cdc/nbs/entity/odse/PersonNameTest.java
libs/database-entities/src/test/java/gov/cdc/nbs/entity/odse/PersonTest.java
libs/database-entities/src/test/java/gov/cdc/nbs/patient/demographic/name/PatientLegalNameResolverTest.java

The corresponding soundex values are now populated when a Patient name is added or updated from the `modernization-api`.
- The `first_nm_sndx` column of the `Person_Name` table is populated with the encoded value of the "First name"
- The `last_nm_sndx` column of the `Person_Name` table is populated with the encoded value of the "Last name"
- The `last_nm2_sndx` column of the `Person_Name` table is populated with the encoded value of the "Second last name"
* [CNFT1-3682](https://cdc-nbs.atlassian.net/browse/CNFT1-3682)
[CNFT1-3682]: https://cdc-nbs.atlassian.net/browse/CNFT1-3682?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-3682] populate soundex values for names

---

apps/modernization-ui/src/apps/patient/add/extended/inputs/race/DetailedRaceDisplay.tsx
apps/modernization-ui/src/apps/patient/add/extended/inputs/race/RaceRepeatingBlock.tsx

Convert Race repeating block table blank value to use dashes.
* [Jira Ticket](https://cdc-nbs.atlassian.net/browse/CNFT1-3678)

CNFT1-3678: New patient extended - Race repeating block blank value to dashes

---

apps/modernization-ui/src/apps/patient/add/basic/AddPatientBasic.tsx
apps/modernization-ui/src/apps/patient/add/useBasicExtendedTransition/useBasicExtendedTransition.tsx

Navigating back to the search page was not behaving as expected. When going from search -> basic -> extended -> basic -> search the search results were not persisting.
* [CNFT1-3679](https://cdc-nbs.atlassian.net/browse/CNFT1-3679)
[CNFT1-3679]: https://cdc-nbs.atlassian.net/browse/CNFT1-3679?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

cancel button bug

---

apps/modernization-api/src/main/java/gov/cdc/nbs/patient/search/PatientFilter.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/search/PatientSearchCriteriaFilterResolver.java
apps/modernization-api/src/main/resources/graphql/patient-search.graphqls
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/search/PatientSearchCriteriaSteps.java
apps/modernization-api/src/test/resources/features/patient/search/PatientSearch.feature
apps/modernization-ui/src/generated/graphql/schema.ts
apps/modernization-ui/src/generated/schema.graphqls

Combine the existing term query for gender with sex filter.  Derive the implied sex by parsing the text (ie m is Male).
1) if the filter matches the old term query nothing to be done
2) if the filter does not match the old term query add a non-existent term query to return no results found. We could also bubble this up to the top to return no results but not worth the effort to optimize a rare condition.
3) if there is no old term query just use the implied sex as the term query
* [CNFT1-3467](https://cdc-nbs.atlassian.net/browse/CNFT1-3467)
[CNFT1-3467]: https://cdc-nbs.atlassian.net/browse/CNFT1-3467?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT1-3467 Search API: Add filters for sex

---

apps/modernization-ui/src/design-system/entry/multi-value/RepeatingBlock.module.scss
apps/modernization-ui/src/design-system/table/data-table.module.scss

Removed the flag to always hide scrollbar, and instead added padding to the right of the data table to prevent the scrollbar from appearing when not needed. 
Padding right by 6px is needed to keep the table from trying to expand into the entirety of the container element, and then the margins of the table contents (buttons + text) **plus** border styling then pushing the table to be slightly larger than the width of the container element (making the scrollbar appear even when the table contents are not overflowing). 
* [Jira Ticket](https://cdc-nbs.atlassian.net/browse/CNFT1-3615)

Cnft1 3615 UI new patient extended all repeating blocks horizontal scroll bar

---

testing/regression/cypress/e2e/features/nbs-classic/patient.feature
testing/regression/cypress/e2e/pages/nbs-classic/patient.page.js
testing/regression/cypress/step_definitions/nbs-classic/patient.steps.js

Added end to end test for invalid future date in "information as of date" field.
* [CNT-126](https://cdc-nbs.atlassian.net/browse/CNT-126)
[CNT-126]: https://cdc-nbs.atlassian.net/browse/CNT-126?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNT-126] - E2E - Invalid future date in "information as of date"

---

testing/regression/cypress/e2e/features/patient-extended-form/patient.feature
testing/regression/cypress/e2e/pages/patient-extended-form/patient.page.js
testing/regression/cypress/step_definitions/patient-extended-form/patient.steps.js

Added end to end test for valid address  on patient extended form.
* [CNT-136](https://cdc-nbs.atlassian.net/browse/CNT-136)
[CNT-136]: https://cdc-nbs.atlassian.net/browse/CNT-136?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNT-136] -E2E - Valid Address Input

---

apps/modernization-ui/src/design-system/entry/multi-value/RepeatingBlock.module.scss

Remove the padding at the end of the Table.
AC: User should not be seeing any space after the table in the repeating block.
* [Jira Ticket](https://cdc-nbs.atlassian.net/browse/CNFT1-3680)

Remove padding bottom from repeating block

---

apps/modernization-ui/src/apps/patient/add/basic/AddPatientBasic.tsx

The default short add patient form was not correctly displaying the default country code. The short add patient form now auto populates with US as default country. 
* [Jira Ticket](https://cdc-nbs.atlassian.net/browse/CNFT1-3718)

defaultValues on AddPatientBasic form initialization set to include the US as the default country.

---

apps/modernization-api/src/main/java/gov/cdc/nbs/patient/search/PatientDemographicQueryResolver.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/search/PatientFilter.java
apps/modernization-api/src/main/resources/graphql/patient-search.graphqls
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/search/PatientSearchCriteriaSteps.java
apps/modernization-api/src/test/resources/features/patient/search/PatientSearch.feature
apps/modernization-ui/src/generated/graphql/schema.ts
apps/modernization-ui/src/generated/schema.graphqls

Leverage contains code in the TextCriteria for an elasticsearch filter query on `entity_id.rootExtensionTxt`. Strip special characters.
* [CNFT1-3470](https://cdc-nbs.atlassian.net/browse/CNFT1-3470)
[CNFT1-3470]: https://cdc-nbs.atlassian.net/browse/CNFT1-3470?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT1-3470 Search API: Add filters for Identification

---

apps/modernization-api/src/main/java/gov/cdc/nbs/patient/profile/investigation/notification/NotificationStatus.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/profile/investigation/notification/NotificationStatusController.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/profile/investigation/notification/NotificationStatusResolver.java
apps/modernization-api/src/test/java/gov/cdc/nbs/event/investigation/InvestigationNotificationMother.java
apps/modernization-api/src/test/java/gov/cdc/nbs/event/investigation/InvestigationNotificationSteps.java
apps/modernization-api/src/test/java/gov/cdc/nbs/event/investigation/NotificationTransportStatusRequester.java
apps/modernization-api/src/test/resources/features/patient/profile/event/notification/PatientProfile.notification.status.feature

Adds a notification status api that returns the status from the NBS_MSGOUTE.TransportQ_out table for the specified notification.
This is to support the request to have a true end-to-end automated test that:
1. Ingests ELR
2. Triggers pre-configured WDS rule to generate a notification
3. Verify Investigation and notification are created via UI
4. Verify Notification is picked up and moved into `TransportQ_out` table with status of `queued` to await pickup by PHINMS
* [CNT-149](https://cdc-nbs.atlassian.net/browse/CNT-149)
[CNT-149]: https://cdc-nbs.atlassian.net/browse/CNT-149?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Adds notification transport status API

---

apps/modernization-api/src/main/java/gov/cdc/nbs/patient/profile/investigation/notification/NotificationStatusController.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/profile/investigation/notification/NotificationStatusResolver.java
apps/modernization-api/src/test/java/gov/cdc/nbs/event/investigation/InvestigationNotificationSteps.java
apps/modernization-api/src/test/java/gov/cdc/nbs/event/investigation/NotificationTransportStatusRequester.java

Updates the notification transport status API to use the Investigation Uid instead of the Notification Local Id.
Updated API:
`/nbs/api/investigations/{id}/notifications`
Example:
`/nbs/api/investigations/10034124/notifications`
* [CNT-149](https://cdc-nbs.atlassian.net/browse/CNT-149)
[CNT-149]: https://cdc-nbs.atlassian.net/browse/CNT-149?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Notification status api by investigation Uid

---

apps/modernization-api/src/main/java/gov/cdc/nbs/patient/profile/investigation/notification/NotificationStatusResolver.java
apps/modernization-api/src/test/java/gov/cdc/nbs/event/investigation/InvestigationNotificationMother.java
apps/modernization-api/src/test/java/gov/cdc/nbs/event/investigation/InvestigationNotificationSteps.java
apps/modernization-api/src/test/resources/features/patient/profile/event/notification/PatientProfile.notification.status.feature

Transport status change to pull from `CN_Transportq_out` instead of `Transportq_out`. 
Still uses investigation uid.
* [CNT-149](https://cdc-nbs.atlassian.net/browse/CNT-149)
[CNT-149]: https://cdc-nbs.atlassian.net/browse/CNT-149?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Change to CN_Transportq_out table

---

apps/modernization-api/src/main/java/gov/cdc/nbs/patient/search/email/PatientSearchResultEmailFinder.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/search/phone/PatientSearchResultDetailedPhoneFinder.java

Email addresses from Phone & Email entries that do not have a "Type" of "Email Address" are now included in patient search results.
* [CNFT1-3805](https://cdc-nbs.atlassian.net/browse/CNFT1-3805)
[CNFT1-3805]: https://cdc-nbs.atlassian.net/browse/CNFT1-3805?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-3805] non email type addresess in search results

---

apps/modernization-ui/src/components/ButtonActionMenu/ButtonActionMenu.spec.tsx
apps/modernization-ui/src/components/ButtonActionMenu/ButtonActionMenu.tsx
apps/modernization-ui/src/components/ButtonActionMenu/buttonActionMenu.module.scss

Change ButtonActionMenu default label position to left side.
Fix `<span>` element margin spacing so it looks correct for both sides.
* [Jira Ticket](https://cdc-nbs.atlassian.net/browse/CNFT1-3818)

CNFT1-3818: ButtonActionMenu: make left side label the default (see image)

---

apps/modernization-ui/src/design-system/filter/useFilter.spec.tsx
apps/modernization-ui/src/design-system/filter/useFilter.tsx
apps/modernization-ui/src/design-system/input/text/TextInput.tsx
apps/modernization-ui/src/design-system/input/text/text-input.module.scss
apps/modernization-ui/src/design-system/table/Header.tsx
apps/modernization-ui/src/design-system/table/header/filter/HeaderFilterField.spec.tsx
apps/modernization-ui/src/design-system/table/header/filter/HeaderFilterField.tsx

Ensures that filter values that have not been applied are cleared when "Reset sort/filters" is clicked.
* [CNFT1-3804](https://cdc-nbs.atlassian.net/browse/CNFT1-3804)
[CNFT1-3804]: https://cdc-nbs.atlassian.net/browse/CNFT1-3804?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CNFT1-3804]: https://cdc-nbs.atlassian.net/browse/CNFT1-3804?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-3804] Reset clears inactive filters

---

apps/modernization-ui/src/apps/patient/add/basic/identification/BasicIdentificationRepeatingBlock.spec.tsx
apps/modernization-ui/src/apps/patient/add/basic/identification/BasicIdentificationRepeatingBlock.tsx
apps/modernization-ui/src/apps/patient/add/extended/inputs/address/AddressRepeatingBlock.spec.tsx
apps/modernization-ui/src/apps/patient/add/extended/inputs/identification/IdentificationRepeatingBlock.spec.tsx
apps/modernization-ui/src/apps/patient/add/extended/inputs/identification/IdentificationRepeatingBlock.tsx
apps/modernization-ui/src/apps/patient/add/extended/inputs/name/NameRepeatingBlock.spec.tsx
apps/modernization-ui/src/apps/patient/add/extended/inputs/name/NameRepeatingBlock.tsx
apps/modernization-ui/src/apps/patient/add/extended/inputs/phone/PhoneAndEmailRepeatingBlock.spec.tsx
apps/modernization-ui/src/apps/patient/add/extended/inputs/phone/PhoneAndEmailRepeatingBlock.tsx
apps/modernization-ui/src/design-system/entry/multi-value/RepeatingBlock.module.scss
apps/modernization-ui/src/design-system/entry/multi-value/RepeatingBlock.spec.tsx
apps/modernization-ui/src/design-system/entry/multi-value/RepeatingBlock.tsx
apps/modernization-ui/src/design-system/entry/multi-value/useMultiValueEntryState.ts

Adds a "Clear" button to repeating blocks when adding a new value.
Adds a "Cancel" button to repeating blocks when editing an existing value.
Existing unit tests for repeating block components were updated to accommodate the presence of multiple buttons.
* [CNFT1-3712](https://cdc-nbs.atlassian.net/browse/CNFT1-3712)
[CNFT1-3712]: https://cdc-nbs.atlassian.net/browse/CNFT1-3712?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-3712] Repeating block clear and cancel

---

apps/modernization-api/src/main/java/gov/cdc/nbs/patient/profile/investigation/notification/NotificationStatus.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/profile/investigation/notification/NotificationStatusResolver.java
apps/modernization-api/src/test/java/gov/cdc/nbs/event/investigation/InvestigationNotificationMother.java
apps/modernization-api/src/test/java/gov/cdc/nbs/event/investigation/InvestigationNotificationSteps.java
apps/modernization-api/src/test/resources/features/patient/profile/event/notification/PatientProfile.notification.status.feature

Adds the notification local id to the transport status response to allow verification of `NETSS_TransportQ_out` status in simulated "on prem" database.
Unfortunately, when data is copied over to the database, only the Transport tables are copied. This removes the ability to query using the public_health_case_uid, so the notification local id is needed.
https://cdc-nbs.atlassian.net/wiki/spaces/NM/pages/1247051777/Data+Sync+Service+for+NNDSS+data+-+Montana
NA

Return notification local id with status

---

apps/modernization-ui/src/design-system/date/picker/date-picker.module.scss

This pr is made to correct the spacing and sizes for the date picker icon and input field 
Here you can see the date picker along side the input with no margin 
This is the figma design
Here you can also see the calendar icon's bkg is highlighted grey, and the unselected input has a transparent calendar icon bkg. The width of the icon button is contains the datepicker icon in this case.
Please reference https://www.figma.com/design/lU5zi29qGeVt3cGxoRIU3V/NBS-Design-System-2.0?node-id=11397-79323&m=dev
* [CNFT1-3776](https://cdc-nbs.atlassian.net/browse/CNFT1-3776)
[CNFT1-3776]: https://cdc-nbs.atlassian.net/browse/CNFT1-3776?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-3776]: removing margin on input near date-picker and correcting width for sizing on button width

---

apps/modernization-api/src/main/java/gov/cdc/nbs/patient/search/PatientDemographicQueryResolver.java
apps/modernization-api/src/test/resources/features/patient/search/PatientSearch.feature

Convert '@' to space so the string is tokenized properly during query string search
* [CNFT1-3799](https://cdc-nbs.atlassian.net/browse/CNFT1-3799)
[CNFT1-3799]: https://cdc-nbs.atlassian.net/browse/CNFT1-3799?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT1-3799 Fix search api email filter that contains '@'

---

.github/workflows/sonar.yaml

Resolves "Error: This request has been automatically failed because it uses a deprecated version of `actions/cache: v1`. Please update your workflow to use v3/v4 of actions/cache to avoid interruptions. Learn more: https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/#actions-cache-v1-v2-and-actions-toolkit-cache-package-closing-down"

[Actions] Upgrades Cache Gradle packages step to actions/cache@v4

---

apps/modernization-api/src/main/java/gov/cdc/nbs/patient/search/email/PatientSearchResultEmailFinder.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/PatientMother.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/phone/PatientEmailDemographicSteps.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/phone/PatientProfileEmailSteps.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/search/PatientSearchVerificationSteps.java
apps/modernization-api/src/test/resources/features/patient/search/PatientSearch.email.feature
apps/modernization-api/src/test/resources/features/patient/search/PatientSearch.feature

Ensures that the email addresses within the patient search results are ordered by as of date descending.
With the email addresses from the Phone and Email patient demographics
the email addresses within the patient search results are order by as of date in both the table view
and the list view
```cucumber
Scenario: Patient Search Results contain email addresses ordered by as of date
Given the patient has the Beeper - Home email address of "email-three@ema.il" as of 05/13/1997
And the patient has the Email Address - Home email address of "email-one@ema.il" as of 11/07/2023
And the patient has the Email Address - Primary Work Place email address of "email-two@ema.il" as of 07/11/2023
And patients are available for search
And I would like to search for a patient using a local ID
When I …
```

[CNFT1-3811] Defines ordering of emails in patient search resutls

---

apps/modernization-ui/src/design-system/field/HorizontalField.tsx
apps/modernization-ui/src/design-system/field/horizontal-field.module.scss
apps/modernization-ui/src/design-system/field/inline-message.module.scss
apps/modernization-ui/src/design-system/select/single/SingleSelect.tsx

Updated the CSS to make error message display more responsive according to the images below.
Add more support for warning (also see images).
Error messages float on the right side
Error message display above the field

CNFT1-3795: New patient extended: responsive error message display

---

apps/modernization-ui/src/design-system/field/HorizontalField.tsx
apps/modernization-ui/src/design-system/field/horizontal-field.module.scss

Moves the warning and error message below the input and select fields when screen size < 1280px
* [Jira Ticket](https://cdc-nbs.atlassian.net/browse/CNFT1-3879)

CNFT1-3879: Move error message below input fields

---

apps/modernization-ui/src/apps/patient/add/basic/add-patient-basic-form.module.scss
apps/modernization-ui/src/apps/patient/add/extended/add-patient-extended-form.module.scss
apps/modernization-ui/src/design-system/field/field.module.scss
apps/modernization-ui/src/design-system/field/horizontal-field.module.scss
apps/modernization-ui/src/design-system/field/inline-message.module.scss
apps/modernization-ui/src/design-system/field/vertical-field.module.scss
apps/modernization-ui/src/styles/_components.scss

Adjust the styles for left / right fields so that longer error messages do not cause inputs to shrink.  The field component styles were consolidated to allow the label, component, and messages to be aligned.
* [CNFT1-3877](https://cdc-nbs.atlassian.net/browse/CNFT1-3877)
[CNFT1-3877]: https://cdc-nbs.atlassian.net/browse/CNFT1-3877?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-3877] Left / right long error message stlyes

---

apps/modernization-ui/src/components/ButtonActionMenu/buttonActionMenu.module.scss

Fix the margin/padding around button so that both text and icon have equivalent 20px spacing for both left and right modes.
* [Jira Ticket](https://cdc-nbs.atlassian.net/browse/CNFT1-3852)

CNFT1-3852: Fix padding around Add New button

---

apps/modernization-ui/src/design-system/card/card.module.scss

Update the padding of the Header Components from 24 to 16px 
* [CNFT1-3882](https://cdc-nbs.atlassian.net/browse/CNFT1-3882)
[CNFT1-3882]: https://cdc-nbs.atlassian.net/browse/CNFT1-3882?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-3882]: card padding change

---

apps/modernization-ui/src/apps/search/patient/PatientSearchActions.tsx
apps/modernization-ui/src/libs/permission/Permitted.spec.tsx
apps/modernization-ui/src/libs/permission/Permitted.tsx

Implement permissions around the "add new patient" and "add new lab report" menu. When either is not permitted, show the single button instead of menu button.
Updated the `<Permitted>` component to expand its capabilities:
* Support multiple permissions
* Ability to include and exclude specific permissions

CNFT1-3865: New patient button - add permissions

---

apps/modernization-ui/src/apps/search/patient/result/table/PatientSearchResultTable.tsx

Let’s use the numeric sort icons for DOB as tt’s conflicting with the first requirement that says to use numeric for number and date fields.
* [CNFT1-3880](https://cdc-nbs.atlassian.net/browse/CNFT1-3880)
[CNFT1-3880]: https://cdc-nbs.atlassian.net/browse/CNFT1-3880?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT1-3880 adding dob numeric sort icon instead of generic

---

apps/modernization-ui/src/design-system/field/Field.tsx
apps/modernization-ui/src/design-system/field/HorizontalField.tsx
apps/modernization-ui/src/design-system/field/VerticalField.tsx
apps/modernization-ui/src/design-system/field/field.module.scss
apps/modernization-ui/src/design-system/input/text/TextInput.tsx
apps/modernization-ui/src/design-system/input/text/TextInputField.tsx
apps/modernization-ui/src/design-system/input/text/text-input.module.scss
apps/modernization-ui/src/design-system/table/Header.tsx
apps/modernization-ui/src/design-system/table/header/filter/HeaderFilterField.tsx
apps/modernization-ui/src/design-system/table/header/filter/header-filter-field.module.scss

Removes the extra padding on filter inputs by removing the `TextInputField` from the header that was adding padding from the label.
Before
After
The `label` property should be _required_ on the `Field`, `HorizontalField`, and `VerticalField` components.  Since this is a specialized component it needs to apply the sizing to the `TextInput` component. 
* [CNFT1-3866](https://cdc-nbs.atlassian.net/browse/CNFT1-3866)
[CNFT1-3866]: https://cdc-nbs.atlassian.net/browse/CNFT1-3866?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[FIX/ CNFT1-3866] HeaderFilterField uses TextInput

---

apps/modernization-ui/src/styles/_colors.scss
apps/modernization-ui/src/styles/global.scss

asterisk is using the wrong color: Should be using error/dark which is #B51D09
* [CNFT1-3889](https://cdc-nbs.atlassian.net/browse/CNFT1-3889)
[CNFT1-3889]: https://cdc-nbs.atlassian.net/browse/CNFT1-3889?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-3889] using correct error dark on asterisk

---

apps/modernization-ui/src/design-system/sorting/preferences/useSortingPreferences.spec.tsx
apps/modernization-ui/src/design-system/sorting/preferences/useSortingPreferences.tsx

Fix preference state to address an issue where sorting preference is not persisting through the table and list view when switching
* [CNFT1-3862](https://cdc-nbs.atlassian.net/browse/CNFT1-3862)
[CNFT1-3862]: https://cdc-nbs.atlassian.net/browse/CNFT1-3862?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

adding or instead of and to reducecers sync case ensuring state updates accurately

---

apps/modernization-api/src/main/java/gov/cdc/nbs/patient/search/PatientSearchCriteriaSortResolver.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/search/SearchablePatient.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/search/indexing/SearchablePatientResolver.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/search/indexing/SearchablePatientRowMapper.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/search/indexing/address/SearchablePatientAddressFinder.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/search/indexing/address/SearchablePatientAddressRowMapper.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/search/indexing/name/SearchablePatientNameFinder.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/search/indexing/name/SearchablePatientNameRowMapper.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/search/indexing/address/SearchablePatientDocumentAddressRowMapperTest.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/search/indexing/name/SearchablePatientNameRowMapperTest.java

In nifi we make all sort fields upper case so that elastic does a case insensitive sort.  Update the incremental indexer by doing a `toUpperCase` on sort fields in java.
* [CNFT1-3905](https://cdc-nbs.atlassian.net/browse/CNFT1-3905)
* [CNFT1-3907](https://cdc-nbs.atlassian.net/browse/CNFT1-3907)
* [CNFT1-3910](https://cdc-nbs.atlassian.net/browse/CNFT1-3910)
* [CNFT1-3908](https://cdc-nbs.atlassian.net/browse/CNFT1-3908)
* [CNFT1-3914](https://cdc-nbs.atlassian.net/browse/CNFT1-3914)
* [CNFT1-3915](https://cdc-nbs.atlassian.net/browse/CNFT1-3915)
[CNFT1-3905]: https://cdc-nbs.atlassian.net/browse/CNFT1-3905?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CNFT1-3910]: https://cdc-nbs.atlassian.net/browse/CNFT1-3910?atlOrigin=eyJpIjoiNWRkNTljNzY …

CNFT1-3905, 3907, 3910, 3908, 3914, 3915 Fix search api sort fixes-nulls last, case insensitive

---

apps/modernization-ui/src/apps/patient/add/extended/AddPatientExtendedForm.spec.tsx
apps/modernization-ui/src/design-system/card/Card.spec.tsx
apps/modernization-ui/src/design-system/card/Card.tsx
apps/modernization-ui/src/design-system/card/card.module.scss

This PR introduces an optional subtext prop to the Card component. When provided, the subtext will be rendered directly below the card's title. If no subtext is passed, the component will function as it did previously, without rendering the subtext section.
Additionally, there are some changes to the `border-radius` etc. but it is propagated only when subtext is included.
Use case for this change:
Mactching Criteria Pages like~
Added unit tests to verify that:
Subtext only renders when the subtext prop is provided.
The component's existing behavior is not affected when the subtext prop is omitted.

Add SubText to Card Component

---

apps/modernization-ui/src/design-system/button/Button.spec.tsx
apps/modernization-ui/src/design-system/button/Button.tsx
apps/modernization-ui/src/styles/_buttons.scss

1. Adds `secondary` prop to design system's `Button` component. This prop will be replacing `outline` in the future.
2. Adds styling for when both `secondary` and `destructive` is specified.
Standard
Outline
Secondary
Destructive
Outline Destructive
Secondary Destructive

Add support for secondary and secondary destructive

---

apps/modernization-ui/src/styles/_buttons.scss

Previous PR https://github.com/CDCgov/NEDSS-Modernization/pull/2357, erroneously removed `!important` from some styling. 
This "worked" locally due to the the re-ordering of stylesheet imports.
NA

Important things

---

apps/modernization-ui/src/design-system/card/Card.tsx
apps/modernization-ui/src/design-system/card/card.module.scss

Subtext was showing up on the left, issue showed up due to addition of `<div>`.
none

Fix Card Alignment

---

apps/modernization-ui/src/apps/patient/data/general/GeneralInformationEntryFields.tsx
apps/modernization-ui/src/design-system/input/numeric/Numeric.tsx

**Number of adults in residence** and **Number of children in residence**
adding conditional check that prevents users from entering more digits than allowed by the max prop. If the input's text length would exceed the specified maximum which is 99999
also added max validation to handle when a value greater than 99999 is entered. We should only be preventing typing when a value has a format. as per https://github.com/CDCgov/NEDSS-Modernization/pull/2380#pullrequestreview-2699943338
* [CNFT1-3892](https://cdc-nbs.atlassian.net/browse/CNFT1-3892)
[CNFT1-3892]: https://cdc-nbs.atlassian.net/browse/CNFT1-3892?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-3892]: Changing input type to text to allow maxLength to work

---

apps/modernization-ui/src/design-system/entry/multi-value/RepeatingBlock.module.scss

Removing repeating styles already on card component to fix padding on cards to be 1 rem
* [CNFT1-3882](https://cdc-nbs.atlassian.net/browse/CNFT1-3882)
[CNFT1-3882]: https://cdc-nbs.atlassian.net/browse/CNFT1-3882?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-3882]: fixing padding on repeating blocks

---

apps/modernization-ui/src/design-system/radio/radio.module.scss

Update padding around radio button from 1.5rem to 1.75rem on small size and default. 
* [Jira Ticket](https://cdc-nbs.atlassian.net/browse/CNFT1-3924)

CNFT1-3924 Update padding around radio button from 1.5rem to 1.75rem

---

apps/modernization-ui/src/apps/deduplication/api/useDataElements.tsx
apps/modernization-ui/src/apps/deduplication/api/useMatchConfiguration.ts
apps/modernization-ui/src/apps/deduplication/data-elements/DataElementConfig.tsx
apps/modernization-ui/src/apps/deduplication/data-elements/form/DataElementRow/DataElementRow.spec.tsx
apps/modernization-ui/src/apps/deduplication/data-elements/form/DataElementRow/DataElementRow.tsx
apps/modernization-ui/src/apps/deduplication/data-elements/form/DataElementsForm/DataElementsForm.tsx
apps/modernization-ui/src/config.js
apps/modernization-ui/src/setupProxy.js

1. Updates the deduplication api calls to use the new url (`/nbs/api/deduplication`)
3. Removes extra `AlertProvider` from data element configuration page
4. Remove extra API call from `DataElementRow` component
* [CND-234](https://cdc-nbs.atlassian.net/browse/CND-234)
[CND-234]: https://cdc-nbs.atlassian.net/browse/CND-234?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CND-234 fix deduplication url

---

apps/modernization-ui/src/apps/search/criteria/SearchCriteria.tsx
apps/modernization-ui/src/apps/search/criteria/search-criteria.module.scss
apps/modernization-ui/src/apps/search/patient/PatientCriteria/Address.tsx
apps/modernization-ui/src/apps/search/patient/PatientCriteria/BasicInformation.tsx
apps/modernization-ui/src/apps/search/patient/PatientCriteria/Contact.tsx
apps/modernization-ui/src/apps/search/patient/PatientCriteria/Id.tsx
apps/modernization-ui/src/apps/search/patient/PatientCriteria/RaceEthnicity.tsx

Add small sizing support to the `SearchCriteria` component.
When `small` the gap between fields is `0.5rem`
When `medium` or `large` the gap between fields in `1rem`
* [CNFT1-3969](https://cdc-nbs.atlassian.net/browse/CNFT1-3969)
[CNFT1-3969]: https://cdc-nbs.atlassian.net/browse/CNFT1-3969?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-3969] Small sizing for search criteria

---

apps/modernization-ui/src/apps/patient/add/basic/asBasicNewPatientEntry.spec.ts
apps/modernization-ui/src/apps/patient/add/basic/asBasicNewPatientEntry.ts
apps/modernization-ui/src/apps/search/patient/PatientCriteria/BasicInformation.tsx
apps/modernization-ui/src/apps/search/patient/PatientCriteria/searchableGenders.ts
apps/modernization-ui/src/apps/search/patient/add/useAddPatientFromSearch.ts

Adds "No value" as an option for searching gender values.
- Added more unit tests for `asBasicNewPatientEntry`
* [CNFT1-3897](https://cdc-nbs.atlassian.net/browse/CNFT1-3897)
[CNFT1-3897]: https://cdc-nbs.atlassian.net/browse/CNFT1-3897?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-3897] "No value" available as a search option

---

apps/modernization-ui/src/design-system/filter/useFilter.tsx

Using pendingFilter instead of just filter on clear when updating filter, because this will allow for the user to be in a state of continues filters being set before actually applying the filter. 
* [CNFT1-3950](https://cdc-nbs.atlassian.net/browse/CNFT1-3950)
[CNFT1-3950]: https://cdc-nbs.atlassian.net/browse/CNFT1-3950?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT1-3950-multiple-filters using pendingFilter instead of filter on clear

---

apps/modernization-ui/src/design-system/input/text/criteria/TextCriteriaField.tsx
apps/modernization-ui/src/design-system/input/text/criteria/operator/OperatorSelect.tsx

An aria-label can be added to the select component using the label to construct a meaningful message.  For example, “{label} search operator“
Fixed scanned Axe Dev tool on Patient Search
Previous Scan before fix
* [CNFT1-3974](https://cdc-nbs.atlassian.net/browse/CNFT1-3974)
[CNFT1-3974]: https://cdc-nbs.atlassian.net/browse/CNFT1-3974?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-3974]: Added aria label to the operator select or select component

---

apps/modernization-ui/src/apps/deduplication/configuration/match-configuration/notification-cards/notification-card.module.scss
apps/modernization-ui/src/apps/deduplication/configuration/match-configuration/pass-configuration/pass-form/blocking-criteria/attribute/BlockingCriteriaAttribute.tsx
apps/modernization-ui/src/apps/deduplication/configuration/match-configuration/pass-configuration/pass-form/blocking-criteria/attribute/blocking-criteria-attribute.module.scss
apps/modernization-ui/src/apps/deduplication/configuration/match-configuration/pass-configuration/pass-form/matching-criteria/attribute/MatchingCriteriaAttribute.tsx
apps/modernization-ui/src/apps/deduplication/configuration/match-configuration/pass-configuration/pass-form/matching-criteria/attribute/matching-criteria-attribute.module.scss
apps/modernization-ui/src/apps/deduplication/configuration/match-configuration/pass-configuration/pass-form/save-modal/SavePassModal.tsx
apps/modernization-ui/src/apps/deduplication/configuration/match-configuration/pass-configuration/pass-list/PassList.tsx
apps/modernization-ui/src/apps/deduplication/configuration/match-configuration/pass-configuration/pass-list/pass-entry/pass-entry.module.scss
apps/modernization-ui/src/apps/deduplication/configuration/match-configuration/pass-configuration/pass-list/pass-list.module.scss
apps/modernization-ui/src/apps/deduplication/data-elements/form/DataElementRow/DataElementRow.tsx
apps/modernization-ui/src/apps/deduplication/data-elements/form/DataElementsForm/DataElementsForm.module.scss
apps/modernization-ui/src/apps/deduplication/data-elements/form/DataElementsForm/DataElementsForm.tsx
apps/modernization-ui/src/design-system/richTooltip/useRichTooltip.ts

Addresses findings from design review
Findings addressed
1. Data elements form should extend to end of table (width)
2. Add `.` to end of data elements info 
3. Fix padding on data element table cell
4. Fix sizing of info Icons on data elements configuration page
5. Fix width of Pass selection panel
6. Pass names should only be blue when selected
7. Add pass button should have disabled styling when adding a new pass
8. Provide a default name for new pass based on selected blocking attributes
9. Fix gap between attribute and info for blocking and matching criteria display
10. Fix Lower bound / Upper bound info icon alignment
* [CND-262](https://cdc-nbs.atlassian.net/browse/CND-262)
[CND-262]: https://cdc-nbs.atlassian.net/browse/CND-262?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5 …

Deduplication configuration - design review

---

apps/modernization-ui/src/design-system/filter/useFilter.tsx

The original implementation had a limitation: clicking on X or removing the text manually on any filter would call updateFilter(withoutProperty(id)(pendingFilter)), which would remove that property from pendingFilter, set filter to match the modified pendingFilter
with the changes this is solved by separating applied filters (filter state) and pending filters (pendingFilter state) and only applying the appropriate state based on where the filter exists because basically before the clear used updateFilter which would set both filter and pendingFilter to the same value. 
Attaching screen recording to show expected behavior given the scenario of having applied filter on one field and entering text in other fields but then removing the text(without having applied filter) will not apply filter …

distinguishing between when filter for a id is applied or pending

---

apps/modernization-ui/src/design-system/entry/multi-value/RepeatingBlock.module.scss
apps/modernization-ui/src/design-system/entry/multi-value/RepeatingBlock.spec.tsx
apps/modernization-ui/src/design-system/entry/multi-value/RepeatingBlock.tsx

- Fix all buttons to have aria-description attribute with reasonable description.
- Add Axe unit test to test for accessibility issues.
- Fix empty header accessibility issue.
* [Jira Ticket](https://cdc-nbs.atlassian.net/browse/CNFT1-3990)

CNFT1-3990: RepeatingBlock buttons fix aria descriptions

---

apps/modernization-ui/src/design-system/table/header/filter/HeaderFilterField.tsx

When user removes the filter condition **within the filter column** using backspace or delete the filter has to be removed. 
The previous change removed the filter condition on the patient search panel when text in the input box was cleared. 
* [Jira Ticket](https://cdc-nbs.atlassian.net/browse/CNFT1-3936)

CNFT1-3936 When the user removes the address filter condition by removing inputted text, the filter has to be removed.

---

apps/modernization-ui/src/apps/deduplication/data-elements/form/DataElementsForm/DataElementsForm.module.scss

Removes unnecessary `max-width` on data elements table.
* [CND-262](https://cdc-nbs.atlassian.net/browse/CND-262)
[CND-262]: https://cdc-nbs.atlassian.net/browse/CND-262?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Remove max width

---

apps/modernization-ui/src/design-system/date/picker/DatePicker.stories.tsx
apps/modernization-ui/src/design-system/date/picker/DatePicker.tsx
apps/modernization-ui/src/design-system/date/picker/DatePickerInput.stories.tsx
apps/modernization-ui/src/design-system/date/picker/date-picker.module.scss

Re-arranges the initialization of the `DatePicker` to prevent the "fangs" from appearing in a local dev server due to double initialization.

[FIX]  DatePicker artifacts in dev mode.

---

apps/modernization-ui/src/design-system/entry/multi-value/RepeatingBlock.spec.tsx
apps/modernization-ui/src/design-system/entry/multi-value/RepeatingBlock.tsx
libs/configuration-api/src/main/java/gov/cdc/nbs/configuration/features/patient/PatientFeaturesConfiguration.java

adding aria role of button and fixing tests to match amount of  getAllByRole('button') expected (buttons) count for in the repeating block spec file
**ARIA label has to be updated for the Repeating block table -icons:**
> View
> Edit
> Delete
* [CNFT1-3992](https://cdc-nbs.atlassian.net/browse/CNFT1-3992)
[CNFT1-3992]: https://cdc-nbs.atlassian.net/browse/CNFT1-3992?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CNFT1-3992-aria-role-button

---

apps/modernization-ui/src/design-system/date/criteria/range/DateRangeField.tsx

Fix CNFT1-3903 issue by providing an object with undefined fields if there is no between value instead of an undefined object. See https://cdc-nbs.atlassian.net/browse/CNFT1-3903?focusedCommentId=31253 video for more info.
* [Jira Ticket](https://cdc-nbs.atlassian.net/browse/CNFT1-3903)

Fix for CNFT1-3903 related issue in some cases the error would not clear when switching between exact date and date range

---

apps/modernization-ui/src/apps/patient/add/basic/asNewExtendedPatientEntry.spec.ts
apps/modernization-ui/src/apps/search/patient/PatientCriteria/searchableGenders.ts
apps/modernization-ui/src/components/selection/multi/MultiSelectInput.spec.tsx
apps/modernization-ui/src/components/selection/multi/MultiSelectInput.tsx
apps/modernization-ui/src/design-system/select/single/Select.tsx
apps/modernization-ui/src/design-system/select/single/SingleSelect.spec.tsx
apps/modernization-ui/src/design-system/select/single/SingleSelect.stories.tsx
apps/modernization-ui/src/options/selectable.ts

Changes the label for the "No value" searchable gender to "---" with an aria-label of "Null or blank values".
* [CNFT1-4030](https://cdc-nbs.atlassian.net/browse/CNFT1-4030)
[CNFT1-4030]: https://cdc-nbs.atlassian.net/browse/CNFT1-4030?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-4030] Searchable gender no value label

---

apps/modernization-ui/src/apps/patient/add/basic/AddPatientBasic.tsx
apps/modernization-ui/src/apps/patient/add/basic/useAddPatientBasicDefaults.ts
apps/modernization-ui/src/design-system/input/text/MaskedTextInput.spec.tsx
apps/modernization-ui/src/design-system/input/text/MaskedTextInput.tsx
apps/modernization-ui/src/design-system/input/text/MaskedTextInputField.spec.tsx
apps/modernization-ui/src/design-system/input/text/MaskedTextInputField.stories.tsx
apps/modernization-ui/src/design-system/input/text/MaskedTextInputField.tsx

When the "New patient" page was setting defaulted values from search criteria or values stored when transitioning from "New patient" to "New patient - extended" as the default values of the form.  This was causing cleared values to return in the masked input field because it was also not handling value changes external to the component.
* [CNFT1-4009](https://cdc-nbs.atlassian.net/browse/CNFT1-4009)
[CNFT1-4009]: https://cdc-nbs.atlassian.net/browse/CNFT1-4009?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-4009] Unclearable values in New patient

---

apps/modernization-ui/src/apps/search/layout/result/header/terms/SearchTerms.tsx

Removing the results count focus when a search is made to not be visible and only be visible for SR 
The first tabable element available after a search is made should be the chips
Problem 
Fix
* [CNFT1-4005](https://cdc-nbs.atlassian.net/browse/CNFT1-4005)
[CNFT1-4005]: https://cdc-nbs.atlassian.net/browse/CNFT1-4005?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-4005]removing results count focus upon search and correcting tab order

---

apps/modernization-ui/src/design-system/chips/chip.module.scss

**Centering icon** 
Previously it was elevated next to the label within the chip like so
* [CNFT1-4101](https://cdc-nbs.atlassian.net/browse/CNFT1-4101)
[CNFT1-4101]: https://cdc-nbs.atlassian.net/browse/CNFT1-4101?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-4101]: centering x icon in chips

---

apps/modernization-ui/src/apps/patient/add/PatientCreatedPanel.tsx
apps/modernization-ui/src/apps/search/patient/PatientSearchActions.tsx
apps/modernization-ui/src/apps/search/patient/result/none/NoPatientResults.tsx
apps/modernization-ui/src/libs/permission/Permitted.spec.tsx
apps/modernization-ui/src/libs/permission/Permitted.tsx
apps/modernization-ui/src/libs/permission/index.ts
apps/modernization-ui/src/libs/permission/permits.spec.ts
apps/modernization-ui/src/libs/permission/permits.ts
apps/modernization-ui/src/libs/permission/permitsAll.spec.ts
apps/modernization-ui/src/libs/permission/permitsAll.ts
apps/modernization-ui/src/libs/permission/permitsAny.spec.ts
apps/modernization-ui/src/libs/permission/permitsAny.ts
apps/modernization-ui/src/libs/permission/usePermissions.ts
apps/modernization-ui/src/utils/predicate/allOf.spec.ts
apps/modernization-ui/src/utils/predicate/allOf.ts
apps/modernization-ui/src/utils/predicate/anyOf.spec.ts
apps/modernization-ui/src/utils/predicate/anyOf.ts
apps/modernization-ui/src/utils/predicate/both.ts
apps/modernization-ui/src/utils/predicate/either.ts
apps/modernization-ui/src/utils/predicate/equals.spec.ts
apps/modernization-ui/src/utils/predicate/equals.ts
apps/modernization-ui/src/utils/predicate/equalsIgnoreCase.spec.ts
apps/modernization-ui/src/utils/predicate/equalsIgnoreCase.ts
apps/modernization-ui/src/utils/predicate/index.ts
apps/modernization-ui/src/utils/predicate/not.spec.ts
apps/modernization-ui/src/utils/predicate/not.ts

Changes the API of the `Permitted` component to accept a `string` or a `Predicate<string[]>`.  This simplifies the most common use case of a single permission being required to view a component.  
```react
<Permitted permission="protected">
<div>Protected</div>
</Permitted>
```
is equivalent to 
```react
<Permitted permission={permits("protected")}>
<div>Protected</div>
</Permitted>
```
A few predicates have been added to replace the existing functionality of the `includes`, `excludes` and `mode` properties.
Requiring all permissions to be present changes from 
```react
<Permitted include=["A", "B", "C"]>
<div>Protected</div>
</Permitted>
```
to 
```react
<Permitted permission={permitsAll("A", "B", "C")}>
<div>Protected</div>
</Permitted>
```
Requiring any permissions to be present …

[FIX] Permitted

---

apps/modernization-ui/src/apps/patient/add/basic/AddPatientBasic.tsx
apps/modernization-ui/src/design-system/entry/navigation-guard/NavigationGuard.tsx
apps/modernization-ui/src/design-system/entry/navigation-guard/index.ts
apps/modernization-ui/src/navigation/useNavigationBlock.ts

Introduces a `NavigationGuard` component to encapsulate prompting the user when attempting to navigate away from a form that contains pending data.

[Refactor] Navigation guard

---

apps/modernization-api/src/main/java/gov/cdc/nbs/patient/file/demographics/summary/PatientDemographicsSummaryEmailFinder.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/file/demographics/summary/PatientDemographicsSummaryPhoneFinder.java
apps/modernization-api/src/test/resources/features/patient/file/demographics/PatientFile.demographics-summary.feature

Fixes an issue where the most recent phone number was not included in the response when there was an email address for the same date.  This is due to the emails and phone numbers being stored in the same tables with the same participation `class_cd`.
The `I can view the patient's most recent phone number in the summarized demographics` feature test was updated to include this scenario.
The same issue occurred with the most recent email
* [CNFT1-4062](https://cdc-nbs.atlassian.net/browse/CNFT1-4062)
[CNFT1-4062]: https://cdc-nbs.atlassian.net/browse/CNFT1-4062?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[FIX] Patient Demographic Summary Endpoint most recent phone

---

apps/modernization-ui/src/apps/deduplication/DeduplicationRouting.tsx
apps/modernization-ui/src/apps/deduplication/api/useMergeDetails.ts
apps/modernization-ui/src/apps/deduplication/patient-merge/details/MergeDetails.module.scss
apps/modernization-ui/src/apps/deduplication/patient-merge/details/MergeDetails.spec.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/details/MergeDetails.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-review/MergeReview.spec.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-review/MergeReview.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-review/merge-review.module.scss
apps/modernization-ui/src/apps/deduplication/patient-merge/landing/MergeLanding.spec.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/landing/matches-requiring-review-table/MatchesRequiringReviewTable.tsx

Adds the initial shell for the `Patient merge details` page located at `/deduplication/merge/:patientId`
* [CND-307](https://cdc-nbs.atlassian.net/browse/CND-307)
[CND-307]: https://cdc-nbs.atlassian.net/browse/CND-307?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add patient merge details page

---

apps/modernization-ui/src/SkipLink/SkipLink.tsx
apps/modernization-ui/src/SkipLink/index.ts
apps/modernization-ui/src/apps/patient/add/basic/AddPatientBasic.tsx
apps/modernization-ui/src/apps/patient/add/extended/AddPatientExtended.tsx
apps/modernization-ui/src/apps/search/layout/result/header/terms/SearchTerms.tsx
apps/modernization-ui/src/apps/search/patient/PatientCriteria/BasicInformation.tsx

I want a simple SkipLink component that I can add to my content sections, so that I can easily implement accessible navigation without repeating effect hooks and cleanup logic across many components.
- Acceptance Criteria
- When there is no search results on the search page the last name operator should be focused upon using the skip link 
- With the results on the search page the user should be redirected or focused to the results count
- In the add patient the skip link should focus the information as of field when used.
- In the add  add extended patient the skip link should focus the information as of field when used.
* [CNFT1-4153](https://cdc-nbs.atlassian.net/browse/CNFT1-4153)
[CNFT1-4153]: https://cdc-nbs.atlassian.net/browse/CNFT1-4153?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMD …

Cnft1 4153 skiplink component

---

apps/modernization-ui/src/apps/deduplication/configuration/match-configuration/pass-configuration/pass-form/PassForm.tsx
apps/modernization-ui/src/apps/deduplication/configuration/match-configuration/pass-configuration/pass-form/matching-bounds/MatchingBounds.spec.tsx
apps/modernization-ui/src/apps/deduplication/configuration/match-configuration/pass-configuration/pass-form/matching-bounds/MatchingBounds.tsx

Bug:
In order to save the matching criteria configuration the First name element needs to be removed from active pass configurations. User is unable to Save pass configuration when deleting First name from an active pass configuration. 
Steps to Reproduce: 
Select DateofBirth_Identifier_Sex pass configuration.
Delete the First name matching criteria. 
Click Save pass configuration. 
Update Pass title, description or leave it as it and observe. 
Actual Results: Save button is disabled on the Save pass configuration modal. 
Before:
After:
* [Bug](https://cdc-nbs.atlassian.net/browse/CND-264?focusedCommentId=31807)

Update MatchingBounds validation

---

apps/modernization-api/src/main/java/gov/cdc/nbs/patient/file/demographics/summary/PatientDemographicsSummaryRaceFinder.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/PatientMother.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/file/demographics/summary/PatientDemographicsSummaryVerificationSteps.java
apps/modernization-api/src/test/resources/features/patient/file/demographics/PatientFile.demographics-summary.feature

The query to obtain the races of a patient was including the category of the detailed races also.
Enhanced the feature tests to include this scenario
```cucumber
Scenario: I can view the patient's races in the summarized demographics
Given the patient's race is Unknown as of 07/24/1974
And the patient's race is Asian as of 11/05/2022
And the patient race of Asian includes Japanese
And the patient race of Asian includes Burmese
And the patient's race is Other as of 08/17/2000
When I view the demographics summary of the patient
Then the 1st race in the demographics summary of the patient is "Asian"
And the 2nd race in the demographics summary of the patient is "Other"
And the 3rd race in the demographics summary of the patient is "Unknown"
```
* …

[CNFT1-4176] Ensures that a race only appears once

---

apps/modernization-ui/src/apps/search/layout/SearchLayout.tsx
apps/modernization-ui/src/apps/search/layout/patientSearchHeader/PatientSearchHeader.tsx
apps/modernization-ui/src/apps/search/layout/search-layout.module.scss

As a visual user and screen reader navigating through the patient search page when there are results on the screen for both table view and list view I would like to be able to tab towards the Add new patient button after navigating through the search results.
Ensure the Add new patient button is located as the last element within the DOM tree structure to allow users to tab naturally towards it after having navigated through out the search results. 
* [CNFT1-4141](https://cdc-nbs.atlassian.net/browse/CNFT1-4141)
[CNFT1-4141]: https://cdc-nbs.atlassian.net/browse/CNFT1-4141?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-4141]: adding action button to search layout as the last element of the Dom

---

apps/modernization-ui/src/apps/patient/add/extended/AddPatientExtended.spec.tsx
apps/modernization-ui/src/apps/patient/add/layout/AddPatientLayout.tsx
apps/modernization-ui/src/apps/patient/add/layout/add-patient-layout.module.scss
apps/modernization-ui/src/design-system/inPageNavigation/InPageNavigation.module.scss
apps/modernization-ui/src/design-system/inPageNavigation/InPageNavigation.tsx

https://github.com/user-attachments/assets/9cd90f6b-564e-439d-903b-1e963121211c
As a visual user and screen reader navigating through the Add patient form when the user finishes navigating through the form I would like to be able to tab towards the Add extended data button.
Ensure the Add extended data button is located as the last element within the DOM tree structure to allow users to tab naturally towards it after having navigated through out the form.
This pr will also fix the extended data entry form's desired tab order as the action buttons in the header need to also be the final elements on the page
* [CNFT1-4140](https://cdc-nbs.atlassian.net/browse/CNFT1-4140)
[CNFT1-4140]: https://cdc-nbs.atlassian.net/browse/CNFT1-4140?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZj …

Cnft1 4140 add patient actions buttons update

---

apps/modernization-ui/src/design-system/modal/Modal.tsx

The modal wrapper element was being placed next to the button component causing the parent flex container to insert another gap.
* [CNFT1-4225](https://cdc-nbs.atlassian.net/browse/CNFT1-4225)
[CNFT1-4225]: https://cdc-nbs.atlassian.net/browse/CNFT1-4225?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-4225] Patient file delete button padding

---

apps/modernization-api/src/main/java/gov/cdc/nbs/patient/file/summary/drr/morbidity/MorbidityReportRequiringReviewResolver.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/file/summary/drr/morbidity/MorbidityReportTreatmentFinder.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/file/summary/drr/morbidity/MorbidityTreatment.java

The finder used to resolve treatments for a morbidity report was streaming results from the database and not closing the connection.  The finder was changed to use a `ResultExtractor` instead of grouping via a `Stream`

[FIX] Change morbidity treatment finder to use map extractor

---

apps/modernization-api/src/main/java/gov/cdc/nbs/patient/profile/investigation/AddInvestigationRedirector.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/profile/redirect/outgoing/ClassicPatientProfileRedirector.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/profile/investigation/PatientProfileViewInvestigationSteps.java
apps/modernization-api/src/test/resources/features/patient/profile/event/investigation/PatientProfileInvestigation.feature

Changes the `ClassicPatientProfileRedirector` to always return a "Temporary Redirect" status over "Created" so that the browser can handle the redirects.

[FIX] all patient profile redirects are now 307

---

apps/modernization-ui/src/design-system/data-display/ValueView.tsx
apps/modernization-ui/src/design-system/data-display/value-view.module.scss
apps/modernization-ui/src/design-system/entry/multi-value/RepeatingBlock.module.scss
apps/modernization-ui/src/design-system/entry/multi-value/RepeatingBlock.stories.tsx
apps/modernization-ui/src/design-system/entry/multi-value/RepeatingBlock.tsx

Center aligned the view mode
Added some booleans to be able to choose either a readonly, viewable, and editable modes
* [CNFT1-4209](https://cdc-nbs.atlassian.net/browse/CNFT1-4209)
[CNFT1-4209]: https://cdc-nbs.atlassian.net/browse/CNFT1-4209?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Cnft1 4209 repeating block

---

apps/modernization-ui/src/apps/landing/Expired/Expired.tsx
apps/modernization-ui/src/authorization/IdleTimer.tsx

We don't want to call fetch keep alive upon every timeout reset
Follow up to https://github.com/CDCgov/NEDSS-Modernization/pull/2672

throttle keep alive and call logout upon expired page

---

apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-preview/components/administrative-comments/AdministrativeComments.module.scss
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-preview/components/mortality/PreviewMortality.spec.tsx
apps/modernization-ui/src/apps/deduplication/patient-merge/details/merge-preview/components/mortality/PreviewMortality.tsx

Bugs 🐞:
1. Date of Death - timestamp is being added/timestamp is not required
2. Admin Comments don't wrap when a large paragraph is typed in
* [CND-328](https://cdc-nbs.atlassian.net/browse/CND-328?focusedCommentId=33164)
[CND-328]: https://cdc-nbs.atlassian.net/browse/CND-328?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix styling in AdminComments and style date of death

---

apps/modernization-ui/src/design-system/select/single/Select.tsx

Select dropdown arrow key navigation was broken on Windows due to React remounting the component (which caused it to lose focus) on the select element when the key prop changed 
so I removed the unnecessary `key={value?.value ?? ''}` This prevents react from treating it as a new instance and keeps the focus as well when navigating using the down arrow key
* [CNFT1-4239]([CNFT1-4239](https://cdc-nbs.atlassian.net/browse/CNFT1-4239))
[CNFT1-4239]: https://cdc-nbs.atlassian.net/browse/CNFT1-4239?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CNFT1-4239]: https://cdc-nbs.atlassian.net/browse/CNFT1-4239?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-4239]fix: remove key prop from Select to fix Windows dropdown arrow navigation

---

apps/modernization-ui/src/apps/patient/file/events/labReports/LabReportsCard.tsx
apps/modernization-ui/src/apps/patient/file/summary/documentRequiringReview/PatientDocumentRequiringReview.tsx
apps/modernization-ui/src/apps/patient/file/summary/openInvestigations/OpenInvestigationsCard.tsx
apps/modernization-ui/src/design-system/table/header/ColumnHeader.tsx
apps/modernization-ui/src/design-system/table/header/column.ts
apps/modernization-ui/src/design-system/table/sortable/SortableDataTable.stories.tsx

The default sorting icons are now the alpha sorting icons.
* [CNFT1-4258](https://cdc-nbs.atlassian.net/browse/CNFT1-4258)
[CNFT1-4258]: https://cdc-nbs.atlassian.net/browse/CNFT1-4258?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-4258] DataTable sort icons

---

apps/modernization-ui/src/design-system/modal/Modal.tsx
apps/modernization-ui/src/design-system/modal/modal.module.scss

Updates the `Modal` component to use the updated styles for the header and footer.
* [CNFT1-4202](https://cdc-nbs.atlassian.net/browse/CNFT1-4202)
[CNFT1-4202]: https://cdc-nbs.atlassian.net/browse/CNFT1-4202?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-4202] Modal styles

---

apps/modernization-ui/src/apps/deduplication/DeduplicationRouting.tsx
apps/modernization-ui/src/libs/permission/permissions.ts
apps/modernization-ui/src/routes/RedirectHome.tsx

If the user lacks the merge patient permission, they should not be able to access the deduplication configuration or patient merge screens.
* [CND-362](https://cdc-nbs.atlassian.net/browse/CND-362?atlOrigin=eyJpIjoiZDAwNTE0NmEzOWMzNDBhYWJhYzUwZjliMTUzZTNhZjAiLCJwIjoiaiJ9)
[CND-362]: https://cdc-nbs.atlassian.net/browse/CND-362?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Dedupe Permissions

---

apps/modernization-api/src/main/java/gov/cdc/nbs/patient/events/tests/ResultedTestResolver.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/events/tests/ResultedTestRowMapper.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/file/events/report/laboratory/PatientLabReportsFinder.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/file/events/report/laboratory/PatientLabReportsRowMapper.java
apps/modernization-api/src/test/java/gov/cdc/nbs/event/report/lab/LabReportMother.java
apps/modernization-api/src/test/java/gov/cdc/nbs/event/report/lab/LabReportOrderedTestSteps.java
apps/modernization-api/src/test/java/gov/cdc/nbs/event/report/lab/MaterialMother.java
apps/modernization-api/src/test/java/gov/cdc/nbs/event/report/lab/SpecimenSteps.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/events/tests/ResultedTestRowMapperTest.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/file/events/reports/laboratory/PatientFileLaboratoryReportVerificationSteps.java
apps/modernization-api/src/test/resources/features/patient/file/events/PatientFile.laboratory-report.feature

The name of a resulted test on an ELR are not likely to use the DEFAULT code system, when this happens the API will fall back to the descriptions that are populated along side the coded values.
- Feature test steps were added to allow testing of specimen source and specimen site.
* [CNFT1-4305](https://cdc-nbs.atlassian.net/browse/CNFT1-4305)
[CNFT1-4305]: https://cdc-nbs.atlassian.net/browse/CNFT1-4305?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-4305] Adds fallback to desc values for resulted tests

---

apps/modernization-ui/src/apps/search/patient/result/list/PatientSearchResultListItem.spec.tsx

Fixes a fragile test that performed a date calculation without mocking `now()`.

[FIX] Mocks now for date sensitive test

---

apps/modernization-api/src/main/java/gov/cdc/nbs/patient/file/demographics/address/PatientAddressDemographicFinder.java

The value for "Census tract" was being pulled from the incorrect field `census_track_cd`, it has been changed to `census_tract`
* [CNFT1-4326](https://cdc-nbs.atlassian.net/browse/CNFT1-4326)
[CNFT1-4326]: https://cdc-nbs.atlassian.net/browse/CNFT1-4326?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-4326] Patient file > Demographics > Address census tract

---

apps/modernization-ui/src/design-system/entry/multi-value/view/DetailView.tsx
apps/modernization-ui/src/design-system/entry/multi-value/view/detail-view.module.scss
apps/modernization-ui/src/libs/patient/demographics/address/AddressDemographicView.tsx
apps/modernization-ui/src/libs/patient/demographics/administrative/AdministrativeInformationCard.tsx
apps/modernization-ui/src/libs/patient/demographics/administrative/administrative-information-card.module.scss

Restricts comment fields to have a max character length of around 75 characters.  In detail views the comments are displayed under the label when it reaches the max character per line threshold.
* [CNFT1-4323](https://cdc-nbs.atlassian.net/browse/CNFT1-4323)
[CNFT1-4323]: https://cdc-nbs.atlassian.net/browse/CNFT1-4323?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-4323] Handling displaying of longer text fields

---

apps/modernization-ui/src/apps/search/layout/result/header/options/table/SearchResultsTableOptions.tsx
apps/modernization-ui/src/design-system/card/table/TableCard.tsx
apps/modernization-ui/src/design-system/checkbox/checkbox.module.scss
apps/modernization-ui/src/design-system/panel/closable/ClosablePanel.tsx
apps/modernization-ui/src/design-system/panel/closable/closable-panel.module.scss
apps/modernization-ui/src/design-system/table/preferences/ColumnPreferencesPanel.tsx
apps/modernization-ui/src/design-system/table/preferences/column-preference-action.module.scss
apps/modernization-ui/src/design-system/table/preferences/column-preference-panel.module.scss
apps/modernization-ui/src/styles/_tooltip.scss

Updates the sizing of the Column Preferences to match the newer designs.
* [CNFT1-4288](https://cdc-nbs.atlassian.net/browse/CNFT1-4288)
[CNFT1-4288]: https://cdc-nbs.atlassian.net/browse/CNFT1-4288?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-4288] Column preferences sizing

---

apps/modernization-ui/src/design-system/hint/hint.module.scss
apps/modernization-ui/src/design-system/tooltip/tooltip-message.module.scss

Ensures that the `Hint`, and `Tooltip` components do not take up space when not visible.

[FIX] no height for non-visible Hint

---

apps/modernization-ui/src/apps/patient/file/events/PatientFileEvents.tsx
apps/modernization-ui/src/apps/patient/file/events/events.ts
apps/modernization-ui/src/apps/patient/file/events/reports/morbidity/PatientFileMorbidityReportsCard.tsx
apps/modernization-ui/src/apps/patient/file/events/reports/morbidity/index.ts
apps/modernization-ui/src/apps/patient/file/events/reports/morbidity/morbidity-report.ts
apps/modernization-ui/src/apps/patient/file/events/reports/morbidity/morbidity-reports.module.scss
apps/modernization-ui/src/apps/patient/file/events/reports/morbidity/patientMorbidityReports.ts
apps/modernization-ui/src/apps/patient/file/events/reports/morbidity/transformer.ts
apps/modernization-ui/src/libs/api/index.ts
apps/modernization-ui/src/libs/api/maybeJson.ts
apps/modernization-ui/src/libs/events/reports/morbidity/TreatmentList.spec.tsx
apps/modernization-ui/src/libs/events/reports/morbidity/TreatmentList.tsx
apps/modernization-ui/src/libs/events/reports/morbidity/index.ts
apps/modernization-ui/src/libs/events/reports/morbidity/treatment-list.module.scss

Adds the "Morbidity reports" card to the Patient file.
* [CNFT1-4175](https://cdc-nbs.atlassian.net/browse/CNFT1-4175)
* [CNFT1-4181](https://cdc-nbs.atlassian.net/browse/CNFT1-4181)
* [CNFT1-4046](https://cdc-nbs.atlassian.net/browse/CNFT1-4046)
* 
[CNFT1-4175]: https://cdc-nbs.atlassian.net/browse/CNFT1-4175?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CNFT1-4181]: https://cdc-nbs.atlassian.net/browse/CNFT1-4181?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CNFT1-4046]: https://cdc-nbs.atlassian.net/browse/CNFT1-4046?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-4175] Patient FIle: Morbidity Report card

---

apps/modernization-ui/src/apps/patient/file/summary/PatientFileSummary.tsx
apps/modernization-ui/src/apps/patient/file/summary/mergeHistory/PatientMergeHistory.module.scss

The usage of `Guarded` redirected the Patient File page to Home. 
Another bug: Merge History first column was too small

Remove Guarded, replace w/ FeatureToggle

---

apps/modernization-ui/src/design-system/table/header/ColumnHeader.tsx
apps/modernization-ui/src/shared/header/NavBar.module.scss
apps/modernization-ui/src/shared/header/NavBar.tsx

Logout button should have the space and enter keys functioning. So in this pr the prev anchor tag is now a button element.
Before changes
After changes (should be visibly the same)
small demo https://github.com/user-attachments/assets/bf37d67c-c620-4228-b721-711e95ef7e29
* [CNFT1-4356](https://cdc-nbs.atlassian.net/browse/CNFT1-4356)
[CNFT1-4356]: https://cdc-nbs.atlassian.net/browse/CNFT1-4356?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-4356]: adding button element and styles

---

apps/modernization-ui/src/design-system/card/Card.tsx
apps/modernization-ui/src/design-system/card/card-header.module.scss
apps/modernization-ui/src/design-system/card/card.module.scss

The border in `CardHeader` is still present when the card is in collapsed state. 
* [CND-405](https://cdc-nbs.atlassian.net/browse/CND-405?atlOrigin=eyJpIjoiYTRhNTIzZjFiNzMxNDJkNjkzZmQxMDA4ZGU0MTc4MWMiLCJwIjoiaiJ9)
https://github.com/user-attachments/assets/de4113e6-5cc3-4901-a276-7f5215ef0c6a
[CND-405]: https://cdc-nbs.atlassian.net/browse/CND-405?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix border in Card

---

apps/modernization-ui/src/libs/permission/permissions.ts
apps/modernization-ui/src/shared/header/NavBar.spec.tsx
apps/modernization-ui/src/shared/header/NavBar.tsx

Bug 🐞: When viewing the modernized page, the NavBar shows links to pages that the user does not have permissions to. 
This fix is a part of a [bug](https://cdc-nbs.atlassian.net/browse/CND-378?atlOrigin=eyJpIjoiMDE3NDkyNzk3NTFlNDI0Y2I1YjhkYTkyZTNjMjY0OGQiLCJwIjoiaiJ9) found while viewing System Management page through an MSA user. 
* [CND-378](https://cdc-nbs.atlassian.net/browse/CND-378?atlOrigin=eyJpIjoiMDE3NDkyNzk3NTFlNDI0Y2I1YjhkYTkyZTNjMjY0OGQiLCJwIjoiaiJ9)
MSA user system management screen with the right NavBar:
[CND-378]: https://cdc-nbs.atlassian.net/browse/CND-378?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add Permissions for NavBar

---

apps/modernization-ui/src/apps/patient/data/administrative/AdministrativeEntryFields.spec.tsx
apps/modernization-ui/src/apps/patient/data/administrative/AdministrativeEntryFields.tsx
apps/modernization-ui/src/apps/patient/data/ethnicity/EthnicityEntryFields.spec.tsx
apps/modernization-ui/src/apps/patient/data/ethnicity/EthnicityEntryFields.tsx
apps/modernization-ui/src/apps/patient/data/general/GeneralInformationEntryFields.spec.tsx
apps/modernization-ui/src/apps/patient/data/general/GeneralInformationEntryFields.tsx
apps/modernization-ui/src/apps/patient/data/mortality/MortalityEntryFields.spec.tsx
apps/modernization-ui/src/apps/patient/data/mortality/MortalityEntryFields.tsx
apps/modernization-ui/src/apps/patient/data/race/RaceEntryFields.spec.tsx
apps/modernization-ui/src/apps/patient/data/race/RaceEntryFields.tsx
apps/modernization-ui/src/apps/patient/data/sexAndBirth/SexAndBirthEntryFields.spec.tsx
apps/modernization-ui/src/apps/patient/data/sexAndBirth/SexAndBirthEntryFields.tsx

Adds aria-description attributes to all "information as of" date fields to improve accessibility. These fields are pre-populated with today's date by default, but users may need to change them if the information is from a different date.
* [CNFT1-4399](https://cdc-nbs.atlassian.net/browse/CNFT1-4399)
[CNFT1-4399]: https://cdc-nbs.atlassian.net/browse/CNFT1-4399?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix: adding aria-description to all information as of date fields

---

apps/modernization-ui/src/apps/patient/data/address/AddressEntryFields.spec.tsx
apps/modernization-ui/src/apps/patient/data/address/AddressEntryFields.tsx
apps/modernization-ui/src/apps/patient/data/identification/IdentificationEntryFields.spec.tsx
apps/modernization-ui/src/apps/patient/data/identification/IdentificationEntryFields.tsx
apps/modernization-ui/src/apps/patient/data/name/NameEntryFields.spec.tsx
apps/modernization-ui/src/apps/patient/data/name/NameEntryFields.tsx
apps/modernization-ui/src/apps/patient/data/phoneEmail/PhoneEmailEntryFields.spec.tsx
apps/modernization-ui/src/apps/patient/data/phoneEmail/PhoneEmailEntryFields.tsx

Adds aria-description attributes to all remaining "as of" date fields across patient data entry forms to improve screen reader accessibility. These fields are pre-populated with today's date, and the description helps users understand they can modify the date if the information is from a different day.
* [CNFT1-4399](https://cdc-nbs.atlassian.net/browse/CNFT1-4399)
[CNFT1-4399]: https://cdc-nbs.atlassian.net/browse/CNFT1-4399?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-4399]-fix: adding aria description to as of date fields

---

apps/modernization-ui/src/apps/patient/file/edit/PatientFileEdit.tsx
apps/modernization-ui/src/apps/patient/file/edit/useEditPatient.ts
apps/modernization-ui/src/components/selection/multi/MultiSelectInput.scss
apps/modernization-ui/src/design-system/card/Card.tsx
apps/modernization-ui/src/design-system/card/table/TableCard.spec.tsx
apps/modernization-ui/src/design-system/entry/pending/PendingEntryAlert.tsx
apps/modernization-ui/src/design-system/entry/pending/index.ts
apps/modernization-ui/src/design-system/entry/pending/pending.ts
apps/modernization-ui/src/design-system/entry/pending/usePendingFormEntry.ts
apps/modernization-ui/src/libs/patient/demographics/PatientDemographicsForm.tsx
apps/modernization-ui/src/libs/patient/demographics/address/AddressDemographicCard.tsx
apps/modernization-ui/src/libs/patient/demographics/address/edit/EditAddressDemographicsCard.tsx
apps/modernization-ui/src/libs/patient/demographics/demographics.ts
apps/modernization-ui/src/libs/patient/demographics/identification/edit/EditIdentificationDemographicsCard.tsx
apps/modernization-ui/src/libs/patient/demographics/index.ts
apps/modernization-ui/src/libs/patient/demographics/name/edit/EditNameDemographicsCard.tsx
apps/modernization-ui/src/libs/patient/demographics/phoneEmail/edit/EditPhoneEmailDemographicsCard.tsx
apps/modernization-ui/src/libs/patient/demographics/race/RaceDemographicCard.tsx
apps/modernization-ui/src/libs/patient/demographics/race/RaceDemographicRepeatingBlock.tsx
apps/modernization-ui/src/libs/patient/demographics/race/edit/EditRaceDemographicsCard.tsx
apps/modernization-ui/src/libs/patient/demographics/transformer.spec.ts
apps/modernization-ui/src/libs/patient/demographics/transformer.ts
apps/modernization-ui/src/styles/global.scss

Adds page level validations to Patient file edit to alert a user to any pending entry within repeating blocks.
- Adds the `usePendingFormEntry` hook for tracking the state of entry within one or more `RepeatingBlock` components.
- Adds the `PendingEntryAlert` component to display validation messages for pending entry.
* [CNFT1-4112](https://cdc-nbs.atlassian.net/browse/CNFT1-4112)
[CNFT1-4112]: https://cdc-nbs.atlassian.net/browse/CNFT1-4112?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-4112] Patient file edit > page level validations

---

apps/modernization-api/src/main/java/gov/cdc/nbs/patient/file/events/record/birth/redirect/SubmitBirthRecordRedirector.java
apps/modernization-api/src/test/java/gov/cdc/nbs/patient/file/events/record/birth/PatientFileAddBirthRecordSteps.java
apps/modernization-api/src/test/resources/features/patient/file/events/PatientFile.birth-record.redirect.feature

Adds the `nbs/api/patient/{patient}/records/birth/add` endpoint to prepare the NBS session to accept a redirection to add a birth record.
```cucumber
Scenario: A birth record is added from the Patient file
Given I can "ADD" any "BirthRecord"
When a birth record is added from the Patient file
Then NBS is prepared to add a birth record
And I am redirected to Classic NBS to add a birth record
Scenario: A birth record is added from the Patient file without required permissions
When a birth record is added from the Patient file
Then I am not allowed due to insufficient permissions
```
* [CNFT1-4396](https://cdc-nbs.atlassian.net/browse/CNFT1-4396)
[CNFT1-4396]: https://cdc-nbs.atlassian.net/browse/CNFT1-4396?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU …

[CNFT1-4396] Patient file birth record add redirect

---

apps/modernization-ui/src/apps/patient/file/edit/PatientFileEdit.tsx

Adjusts the "Save" button to be disabled when there are no changes to the Patient file demographics.
* [CNFT1-4112](https://cdc-nbs.atlassian.net/browse/CNFT1-4112)
[CNFT1-4112]: https://cdc-nbs.atlassian.net/browse/CNFT1-4112?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-4112] Patient file edit > Save button state

---

apps/modernization-api/src/main/java/gov/cdc/nbs/patient/file/events/contact/PatientFileContactNamedByPatientFinder.java
apps/modernization-api/src/main/java/gov/cdc/nbs/patient/file/events/contact/PatientFilePatientNamedByContactFinder.java
apps/modernization-ui/src/apps/patient/file/events/contacts/ContactsCard.tsx
apps/modernization-ui/src/apps/patient/file/events/contacts/contacts-card.module.scss
apps/modernization-ui/src/design-system/table/data-table.module.scss
apps/modernization-ui/src/libs/events/investigations/associated/Associations.tsx
apps/modernization-ui/src/libs/patient/demographics/sections.ts
apps/modernization-ui/src/utils/exists.spec.ts
apps/modernization-ui/src/utils/exists.ts
apps/modernization-ui/src/utils/mapping/maybeMap.spec.ts

Adds handling of an empty "Contacts named by patient" or "Patient named by contact" card.
The "Date named" value will now default to the `add_time` to handle Contact Records on STI investigations.
* [CNFT1-4054](https://cdc-nbs.atlassian.net/browse/CNFT1-4054)
[CNFT1-4054]: https://cdc-nbs.atlassian.net/browse/CNFT1-4054?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-4054] Patient file Contact record empty display

---

apps/modernization-ui/src/apps/patient/file/edit/PatientFileEdit.tsx
apps/modernization-ui/src/apps/search/patient/result/displayProfileLegalName.tsx
apps/modernization-ui/src/date/age/ageResolver.ts
apps/modernization-ui/src/libs/patient/PatientDescriptor.tsx
apps/modernization-ui/src/libs/supplying/defaultTo.spec.ts
apps/modernization-ui/src/libs/supplying/defaultTo.ts

Refactors the `defaultTo` method from a `<T>(fallback?: T | Supplier<T>, value?: T)` signature to `<T>(fallback: T | Supplier<T>) =>  (value?: T) => ` to allow more expressive uses of the function.  This means that `defaultTo(today, asOf)` can now be expressed as `const orElseToday = defaultTo(today)` making it easier to understand the intention.

[Refactor] defaultTo

---

apps/modernization-ui/src/apps/patient/file/edit/evaluated.spec.ts
apps/modernization-ui/src/apps/patient/file/edit/evaluated.ts

There was an assumption that "Administrative Information" would always be present for a patient.  The `evaluated` function now does not assume that `administrative` exists.
* [CNFT1-4418](https://cdc-nbs.atlassian.net/browse/CNFT1-4418)
[CNFT1-4418]: https://cdc-nbs.atlassian.net/browse/CNFT1-4418?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-4418] Prevent error when evaluating administrative

---

apps/modernization-ui/src/design-system/field/value/value-field.module.scss

Adds overflow handling to `ValueField` to prevent clipping of long values.
* [CNFT1-4096](https://cdc-nbs.atlassian.net/browse/CNFT1-4096)
* [CNFT1-4097](https://cdc-nbs.atlassian.net/browse/CNFT1-4097)
[CNFT1-4096]: https://cdc-nbs.atlassian.net/browse/CNFT1-4096?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CNFT1-4097]: https://cdc-nbs.atlassian.net/browse/CNFT1-4097?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-4096] Adds overflow wrapping to the value field value

---

apps/modernization-ui/src/design-system/input/text/TextArea.spec.tsx
apps/modernization-ui/src/design-system/input/text/TextArea.tsx
apps/modernization-ui/src/design-system/input/text/index.ts
apps/modernization-ui/src/libs/patient/demographics/administrative/edit/AdministrativeInformationFields.tsx

Resolves an issue where pressing backspace on the last character of a `TextArea` would revert to the previous value.  The state value was removed to work more like `TextInput`.

[FIX] TextArea null handling

---

apps/modernization-ui/src/libs/patient/demographics/address/edit/AddressDemographicFields.tsx
apps/modernization-ui/src/libs/patient/demographics/mortality/edit/MortalityDemographicFields.tsx
apps/modernization-ui/src/libs/patient/demographics/sex-birth/edit/SexBirthDemographicFields.tsx

Fixes the county selection in the Edit patient Address repeating block. 
- [CNFT1-4097](https://cdc-nbs.atlassian.net/browse/CNFT1-4097)
[CNFT1-4097]: https://cdc-nbs.atlassian.net/browse/CNFT1-4097?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update state - county handling in address repeating block

---

apps/modernization-ui/src/apps/patient/file/PatientFileHeader.spec.tsx
apps/modernization-ui/src/apps/patient/file/PatientFileView.tsx
apps/modernization-ui/src/apps/patient/file/edit/GuardedPatientFileEdit.tsx
apps/modernization-ui/src/apps/patient/file/patient.ts

Ensures that the "Edit" and "Delete" buttons on Patient file are only displayed for `ACTIVE` patients.
* [CNFT1-4425](https://cdc-nbs.atlassian.net/browse/CNFT1-4425)
[CNFT1-4425]: https://cdc-nbs.atlassian.net/browse/CNFT1-4425?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CNFT1-4425] Only active patients should have edit and delete options

---

apps/modernization-ui/src/libs/api/index.ts
apps/modernization-ui/src/libs/api/request.ts
apps/modernization-ui/src/libs/classic/ClassicModalButton.tsx
apps/modernization-ui/src/libs/classic/useClassicModal.ts

Adds support for delete actions within a `ClassicModal`.  NBS relies on a form action being performed in order to execute the delete for events displayed within a `ClassicModal`.  The `action` is now invoked if specified by the page being displayed.

[FIX] Handling deletes from classic modal
